- packages/amis-editor-core/src/component/Editor.tsx
- packages/amis-editor-core/src/component/Panel/DialogList.tsx
- packages/amis-editor-core/src/component/Panel/Outline.tsx
- packages/amis-editor-core/src/component/SubEditor.tsx
- packages/amis-editor-core/src/manager.ts
- packages/amis-editor-core/src/store/editor.ts
- packages/amis-editor-core/src/util.ts
- packages/amis-editor/src/renderer/event-control/DialogActionPanel.tsx
- packages/amis-editor/src/renderer/event-control/helper.tsx
> fix: 修复弹窗中的弹窗编辑器中出现重复的问题

- packages/amis-editor-core/scss/_rightPanel.scss
- packages/amis-ui/scss/components/form/_form.scss
- packages/amis-ui/scss/components/form/_selection.scss
- packages/amis/src/renderers/Chart.tsx
> style(amis): 样式细节优化，避免异常溢出和换行展示

- packages/amis-editor-core/src/manager.ts
- packages/amis-editor-core/src/store/editor.ts
- packages/amis-editor-core/src/util.ts
- packages/amis-editor/src/renderer/event-control/DialogActionPanel.tsx
- packages/amis-editor/src/renderer/event-control/action-config-dialog.tsx
- packages/amis-editor/src/renderer/event-control/index.tsx
> fix: 修复弹窗中引用弹窗自己的编辑器逻辑问题

- packages/amis-core/src/actions/AjaxAction.ts
- packages/amis/__tests__/event-action/__snapshots__/ajax.test.tsx.snap
- packages/amis/__tests__/event-action/ajax.test.tsx
> fix:发送请求动作的sendOn配置不生效

- packages/amis-editor-core/src/util.ts
> Fix editor 0422

- packages/amis-editor/examples/component/Doc.tsx
- packages/amis-editor/src/renderer/event-control/DialogActionPanel.tsx
> fix: 修复弹窗编辑嵌套异常问题

- packages/amis-ui/src/components/table/Cell.tsx
- packages/amis-ui/src/components/table/Row.tsx
- packages/amis-ui/src/components/table/index.tsx
- packages/amis/src/renderers/CRUD2.tsx
- packages/amis/src/renderers/Operation.tsx
- packages/amis/src/renderers/Table2/index.tsx
> feat: 补充CRUD2 testid

- packages/amis-ui/src/components/icons.tsx
- packages/amis-ui/src/components/table/Head.tsx
- packages/amis-ui/src/components/table/HeadCellDropDown.tsx
- packages/amis-ui/src/components/table/HeadCellFilter.tsx
- packages/amis-ui/src/components/table/HeadCellSort.tsx
- packages/amis-ui/src/components/table/index.tsx
- packages/amis/src/renderers/Table2/HeadCellSearchDropdown.tsx
- packages/amis/src/renderers/Table2/index.tsx
> feat: CRUD2 head 操作支持testid

- packages/amis-core/src/store/modal.ts
- packages/amis/src/renderers/Dialog.tsx
- packages/amis/src/renderers/Drawer.tsx
> fix: revert #9941 修复弹窗下有多个 form 时数据混乱问题

- packages/amis-editor-core/scss/_outline.scss
- packages/amis-editor-core/src/util.ts
- packages/amis-editor/src/renderer/event-control/DialogActionPanel.tsx
> fix: 修复编辑内嵌弹窗中内嵌弹窗失效的问题

- packages/amis/src/renderers/CRUD.tsx
- packages/amis/src/renderers/CRUD2.tsx
- packages/amis/src/renderers/Cards.tsx
- packages/amis/src/renderers/List.tsx
- packages/amis/src/renderers/Table/index.tsx
- packages/amis/src/renderers/Table2/index.tsx
> fix:刷新crud未执行却刷新service的问题

- packages/amis-editor-core/src/store/editor.ts
- packages/amis-editor-core/src/util.ts
- packages/amis-editor/src/renderer/event-control/DialogActionPanel.tsx
> fix: 修复弹窗修改无法删除属性的问题

- .github/workflows/gh-pages.yml
- .github/workflows/pr-test.yml
> chore: 更新 github workflow，拆分粒度方便定位问题

- packages/amis-core/src/utils/stripNumber.ts
- packages/amis-ui/src/components/Range.tsx
- packages/amis/__tests__/event-action/renderers/form/range.test.tsx
> fix(amis): 修复InputRange不能拖拽到负值的问题和精度失效问题

- packages/amis-editor-core/src/util.ts
> fix: 修复 inputArray 在编辑器中渲染错误的问题

- packages/amis-editor/src/renderer/ValidationControl.tsx
> fix(editor): 修复校验规则修改后面板不更新问题

- packages/amis-core/src/renderers/Form.tsx
> fix: 修复 crud 中 filter 开启 submitOnChnage 后无法分页问题

- packages/amis-editor-core/src/component/Editor.tsx
> fix: 修复编辑器右击菜单后报错

- packages/amis-editor/src/renderer/event-control/index.tsx
> style:更新动作面板的编辑icon

- packages/amis-editor/src/plugin/CRUD2/BaseCRUD.tsx
- packages/amis-editor/src/plugin/Each.tsx
- packages/amis-editor/src/plugin/TableCell2.tsx
- packages/amis-editor/src/plugin/Tabs.tsx
- packages/amis-editor/src/renderer/FeatureControl.tsx
- packages/amis-ui/src/components/table/Head.tsx
- packages/amis-ui/src/components/table/util.ts
- packages/amis/src/renderers/CRUD2.tsx
- packages/amis/src/renderers/Table2/index.tsx
> 修复crud2等细节报错问题

- packages/amis/package.json
- packages/office-viewer/package.json
- packages/office-viewer/src/excel/render/Consts.ts
> chore: 减小 Excel 默认单元格的 padding 大小

- packages/amis/src/renderers/Form/InputTable.tsx
> fix:inputTable删除行动作没有触发change事件 Close #10060

- packages/amis/__tests__/event-action/renderers/form/range.test.tsx
> fix(amis): 修正range.test.tsx用例

- packages/amis/__tests__/renderers/Form/inputTable.test.tsx
- packages/amis/src/renderers/Form/InputTable.tsx
> fix: 修复 inputTable 在分页情况切换数据表单项不更新的问题

- packages/amis-ui/src/components/Range.tsx
- packages/amis/__tests__/event-action/renderers/form/__snapshots__/range.test.tsx.snap
- packages/amis/__tests__/event-action/renderers/form/range.test.tsx
> fix(amis): 注释掉range.test.tsx中的滑动change case

- packages/amis-editor/src/renderer/style-control/FlexLayout.tsx
- packages/amis-ui/src/components/table/index.tsx
- packages/amis/src/renderers/Cards.tsx
> 修复flex编辑warning及列表组件移动端样式

- packages/amis-editor-core/src/store/editor.ts
- packages/amis-editor/src/renderer/event-control/DialogActionPanel.tsx
> fix: 修复 #10102 引发的旧版事件弹窗更新出现配置丢失的问题

- package.json
- packages/amis-ui/package.json
> fix: 调整amis-ui依赖

- packages/amis/src/renderers/CRUD2.tsx
> fix: 修复 #10134 引发的 CRUD2 中单元格中通用动作不执行问题

- packages/amis-editor-core/src/store/node.ts
- packages/amis-ui/scss/components/form/_date.scss
> style: 优化InputDatetimeRange组件面板样式

- packages/amis-core/src/store/formItem.ts
> fix: 修复select下拉组件的自动补全功能回显bug Close: #9989

- packages/amis/src/renderers/Form/NestedSelect.tsx
> fix: 级联选择器-修复开启多选时，每次选择二级及以上的选项，都会自动收起的问题

- packages/amis-core/src/actions/PrintAction.ts
> fix: 修复 word 打印失效问题

- packages/amis-core/src/Scoped.tsx
- packages/amis-core/src/actions/CmptAction.ts
- packages/amis-editor/src/plugin/Form/Group.tsx
- packages/amis/src/renderers/CRUD.tsx
- packages/amis/src/renderers/Cards.tsx
- packages/amis/src/renderers/List.tsx
- packages/amis/src/renderers/Table/index.tsx
> fix: 修复通用动作 reload 无法传递事件数据问题 Close: #10164

- packages/amis-editor-core/src/component/Panel/AMisCodeEditor.tsx
- packages/amis-editor-core/src/component/Panel/CodeEditorPanel.tsx
- packages/amis-editor-core/src/manager.ts
> fix: 修复schema编辑复制组件时样式冲突问题

- packages/amis-editor/src/plugin/Layout/FlexPluginBase.tsx
- packages/amis-editor/src/renderer/style-control/FlexLayout.tsx
- packages/amis-editor/src/tpl/layout.tsx
> fix: 修复flex纵向自定义比例显示重叠问题

- amis.code-workspace
- examples/components/App.tsx
- packages/amis-editor-core/scss/_bcn.scss
- packages/amis-editor-core/scss/editor.scss
- packages/amis-editor-core/src/component/Preview.tsx
- packages/amis-editor-core/src/store/node.ts
- packages/amis-editor/src/plugin/Dialog.tsx
- packages/amis-editor/src/plugin/Drawer.tsx
> chore: 调整编辑器样式解决点选被挡住问题

- docs/zh-CN/components/number.md
- packages/amis/__tests__/renderers/Form/number.test.tsx
- packages/amis/src/renderers/Number.tsx
> fix: number 组件使用和 input-number 一样的四舍五入精度策略 Closes #10112

- packages/amis-ui/src/components/MultilineText.tsx
> fix: 修复 multiLineText 组件无限更新问题

- packages/amis-editor/src/renderer/event-control/helper.tsx
> fix：组件变量赋值可视化展示问题

- packages/amis-core/src/renderers/Item.tsx
- packages/amis-editor-core/src/component/Preview.tsx
- packages/amis-editor-core/src/manager.ts
- packages/amis-editor-core/src/util.ts
- packages/amis-editor/src/plugin/Form/Form.tsx
> 初始时获取第一个region

- packages/amis-editor/src/plugin/Form/InputSignature.tsx
> feat(editor): 签名面板更名手写签

- packages/amis/src/renderers/Form/InputTable.tsx
> fix: 修复 InputTable 组件 add 事件参数上下文错误问题。Closes #10224

- packages/amis-core/src/utils/style-helper.ts
- packages/amis/src/renderers/Card.tsx
> fix: 修复 card 组件渲染异常 Close: #10229

- packages/amis/src/renderers/CRUD.tsx
- packages/amis/src/renderers/Form/Picker.tsx
- packages/amis/src/renderers/Table/AutoFilterForm.tsx
- packages/amis/src/renderers/Table/index.tsx
> chore: crud 即便不同步地址栏也回显地址栏参数 Close: #9788

- packages/amis/src/renderers/Form/ListSelect.tsx
> feat: list-select 支持 label 用变量 Close: #9807

- packages/amis/src/renderers/Form/InputTable.tsx
> chore: revert #5791 解决数据合并混乱问题 Close: #9828

- packages/amis/src/renderers/Table/AutoFilterForm.tsx
> chore: crud 的自动过滤器的重置按钮行为改成 clear-and-submit Close: #10028

- packages/amis-core/src/renderers/Form.tsx
> fix: 修复 combo 中通过 visibleOn 新出来的字段默认值没有起作用的问题 Close: #9947

- packages/amis-core/__tests__/condition.test.ts
- packages/amis-core/src/actions/Action.ts
- packages/amis-core/src/actions/AjaxAction.ts
- packages/amis-core/src/actions/SwitchAction.ts
- packages/amis-core/src/utils/filter-schema.ts
- packages/amis-core/src/utils/renderer-event.ts
- packages/amis-core/src/utils/resolveCondition.ts
- packages/amis-core/src/utils/tpl.ts
- packages/amis/src/renderers/CRUD.tsx
- packages/amis/src/renderers/Cards.tsx
- packages/amis/src/renderers/Form/Combo.tsx
- packages/amis/src/renderers/Form/InputTable.tsx
- packages/amis/src/renderers/List.tsx
- packages/amis/src/renderers/Table/index.tsx
- packages/amis/src/renderers/Table2/index.tsx
- packages/amis/src/renderers/Wizard.tsx
> feat: xxxOn 支持自定义条件

- packages/amis-editor/src/index.tsx
> fix: 导出校验相关函数

- packages/amis-editor/src/renderer/ValidationControl.tsx
> feat: 支持配置面板内其他组件更新校验项时校验信息自动刷新

- packages/amis-editor/src/renderer/ValidationControl.tsx
> 修复内置校验可关闭的问题

- packages/amis/src/renderers/DateRange.tsx
> fix: 修复daterange识别日期错误问题

- packages/amis-editor/src/plugin/Cards.tsx
- packages/amis-editor/src/plugin/Each.tsx
- packages/amis-editor/src/plugin/Form/Combo.tsx
- packages/amis-editor/src/plugin/Form/InputArray.tsx
- packages/amis-editor/src/plugin/Form/InputSubForm.tsx
- packages/amis-editor/src/plugin/Form/InputTable.tsx
- packages/amis-editor/src/plugin/Form/Static.tsx
- packages/amis-editor/src/plugin/List.tsx
- packages/amis-editor/src/plugin/List2.tsx
- packages/amis-editor/src/plugin/Table.tsx
- packages/amis-editor/src/plugin/Table2.tsx
> fix: 修复编辑器模拟数据逻辑导致的组件无限刷新问题

- packages/amis-editor/src/index.tsx
- packages/amis-editor/src/renderer/StatusControl.tsx
> fix: 优化状态中条件设置的判断逻辑

- docs/zh-CN/components/color.md
- packages/amis-core/src/SchemaRenderer.tsx
- packages/amis-ui/src/components/ColorPicker.tsx
- packages/amis/src/renderers/Form/InputColor.tsx
> feat: inputColor 支持配置弹层选择器

- packages/amis-editor-core/src/layout/flex.ts
- packages/amis-editor-core/src/manager.ts
- packages/amis-editor-core/src/util.ts
> feat: flex模式点选添加组件逻辑优化

- packages/amis/src/renderers/CRUD2.tsx
> feat: 补充crud2 外层testid

- packages/amis-ui/package.json
> upgrade react-pdf to 8.0.2

- packages/amis-editor-core/src/index.ts
- packages/amis-editor-core/src/plugin/Unknown.tsx
> feat: 导出部分基础插件

- package.json
> chore: 升级amis-publish版本

- packages/amis/src/renderers/Form/Combo.tsx
> feat: combo tabMode 增加testid

- packages/amis-ui/src/components/PdfViewer.tsx
> fix: pdfjs-dist 加载问题

- packages/amis/package.json
- packages/office-viewer/package.json
- packages/office-viewer/rollup.config.js
> fix: 修复 office-viewer 的 esm 没有 external echarts 问题

- packages/amis-editor/src/plugin/ColumnToggler.tsx
- packages/amis-ui/src/components/table/util.ts
> 补充columnToggle对齐配置 & 修复table2多个固定列问题

- packages/amis-editor-core/scss/control/_event-action.scss
- packages/amis-editor/src/renderer/event-control/helper.tsx
> fix:修复动作配置中combo样式问题

- packages/amis-ui/scss/components/form/_form.scss
> style: 修复form flex模式样式异常问题

- packages/amis/src/renderers/Form/ChainedSelect.tsx
> fix: 修复 Chained-Select 清除数据后还有逗号问题 Closes #10116

- packages/amis/src/renderers/Action.tsx
> fix: 修复接口及表单报错依然执行倒计时问题 Closes #10264

- docs/zh-CN/concepts/data-mapping.md
> docs: 修复文档中过滤器 join 连接符描述错误问题

- packages/amis-editor-core/src/component/Breadcrumb.tsx
- packages/amis-editor-core/src/plugin/BasicToolbar.tsx
> fix(editor): 修复部分场景下获取不到region的情况

- fis-conf.js
> fix: amis sdk 编译

- packages/amis-editor-core/src/store/editor.ts
> chore: 弹窗配置纠错 Close: #10269

- packages/amis/src/renderers/IFrame.tsx
> fix: 修复 iframe 事件响应重复的问题 Close: #10196

- packages/amis-ui/src/components/ContextMenu.tsx
> feat: contextMenu支持阻止关闭钩子

- packages/amis-ui/src/components/ContextMenu.tsx
> fix: 修复contextMenu阻止关闭时event.preventDefault()导致的各种功能失效

- packages/amis-editor-core/scss/editor.scss
- packages/amis-editor-core/src/component/IFramePreview.tsx
- packages/amis-ui/scss/components/_cascader.scss
- packages/amis-ui/scss/components/_result-box.scss
- packages/amis-ui/scss/components/form/_form.scss
- packages/amis-ui/scss/components/form/_select.scss
- packages/amis-ui/src/components/ResultBox.tsx
> fix: 表单移动端样式优化 & 编辑器移动端预览样式优化

- packages/amis-core/src/types.ts
- packages/amis-core/src/utils/DataScope.ts
- packages/amis-editor-core/scss/control/_tpl-formula-control.scss
- packages/amis-editor-core/src/plugin.ts
- packages/amis-editor-core/src/util.ts
- packages/amis-editor/src/renderer/FormulaControl.tsx
- packages/amis-editor/src/renderer/TplFormulaControl.tsx
- packages/amis-editor/src/renderer/textarea-formula/TextareaFormulaControl.tsx
- packages/amis-ui/src/components/index.tsx
> feat: 公式支持快捷变量

- packages/amis-editor/src/renderer/OptionControl.tsx
> chore(amis-editor): 选项类型数据源控件支持外部扩展

- packages/amis-editor-core/scss/control/_formula-control.scss
- packages/amis-editor-core/src/util.ts
- packages/amis-editor/src/renderer/FormulaControl.tsx
- packages/amis-editor/src/renderer/TplFormulaControl.tsx
- packages/amis-editor/src/renderer/textarea-formula/TextareaFormulaControl.tsx
- packages/amis-ui/src/components/formula/VariableList.tsx
> feat: 公式快捷变量支持子表

- packages/amis-core/src/store/formItem.ts
> fix: 修复select等options组件在source切换后无数据且multiple时空值不符合预期的问题

- packages/amis/src/renderers/Form/NestedSelect.tsx
> feat: NestedSelect 支持testid

- packages/amis-editor/src/plugin/CRUD.tsx
- packages/amis/src/renderers/Table/ColGroup.tsx
> fix: 修复 table 分页后列可能对不齐的问题

- packages/amis-editor/src/plugin/Form/Form.tsx
> fix(amis-editor): 修复form查看场景时修改配置面板丢失信息的问题

- docs/zh-CN/concepts/event-action.md
> fix:修复事件动作文档中错误说明

- packages/amis-editor-core/src/util.ts
- packages/amis-editor/src/renderer/FormulaControl.tsx
- packages/amis-editor/src/renderer/TplFormulaControl.tsx
- packages/amis-editor/src/renderer/textarea-formula/TextareaFormulaControl.tsx
- packages/amis-editor/src/renderer/textarea-formula/plugin.tsx
- packages/amis-ui/src/components/formula/Editor.tsx
> feat: 公式高亮模式变更

- packages/amis-editor-core/scss/control/_formula-control.scss
- packages/amis-editor-core/scss/control/_tpl-formula-control.scss
- packages/amis-editor-core/src/util.ts
- packages/amis-editor/src/renderer/FormulaControl.tsx
- packages/amis-editor/src/renderer/textarea-formula/FormulaPicker.tsx
- packages/amis-ui/scss/components/_formula.scss
- packages/amis-ui/src/components/formula/Editor.tsx
- packages/amis-ui/src/components/formula/VariableList.tsx
> feat: 公式变量展示调整

- packages/amis-core/src/utils/style-helper.ts
> fix: 修复id不为string类型时,自定义样式报错

- packages/amis-editor/src/renderer/FormulaControl.tsx
- packages/amis/src/renderers/Form/InputNumber.tsx
> fix(amis-editor): 数值精度调整默认值不跟随变化的问题

- packages/amis-editor-core/src/util.ts
- packages/amis-editor/src/renderer/FormulaControl.tsx
- packages/amis-editor/src/renderer/TplFormulaControl.tsx
- packages/amis-editor/src/renderer/textarea-formula/FormulaPicker.tsx
- packages/amis-editor/src/renderer/textarea-formula/TextareaFormulaControl.tsx
- packages/amis-ui/src/components/formula/Editor.tsx
> feat: 表达式变量展示优化

- packages/amis-editor/src/plugin/Form/InputTable.tsx
> fix(amis-editor): input-table关闭mock数据的功能

- packages/amis-editor/src/renderer/OptionControl.tsx
> fix(editor): 修复editor批量添加option异常问题

- packages/amis-core/src/renderers/Item.tsx
- packages/amis-editor/src/renderer/SwitchMoreControl.tsx
- packages/amis-editor/src/tpl/remark.tsx
- packages/amis-ui/scss/components/form/_form.scss
> style: 优化form flex模式下样式问题

- packages/amis-editor-core/src/util.ts
- packages/amis-editor/src/renderer/FormulaControl.tsx
- packages/amis/src/renderers/Form/InputNumber.tsx
> feat: FormulaControl 快捷变量点击改为替换

- packages/amis/src/renderers/Form/Picker.tsx
> fix: picker 不自定义 pickerSchema 时 labelField 配置无效问题修复

- packages/amis-ui/scss/components/form/_textarea.scss
> style: 修复textarea counter遮挡底边框的问题

- packages/amis-editor-core/src/util.ts
> fix: 公式变量过滤问题

- packages/amis-editor/src/renderer/ConditionFormulaControl.tsx
- packages/amis-editor/src/renderer/StatusControl.tsx
- packages/amis-editor/src/renderer/ValidationControl.tsx
> fix: 条件表达式获取不到上下文数据

- packages/amis-core/src/renderers/wrapControl.tsx
- packages/amis-editor/src/renderer/OptionControl.tsx
> fix(amis-editor): 修复 select 静态选项 popOver 编辑无效问题 Close: #10427

- packages/amis-ui/scss/components/_input-box.scss
- packages/amis-ui/src/components/condition-builder/Value.tsx
> style: 条件组合样式优化

- packages/amis/src/renderers/Form/InputTable.tsx
> fix: 优化 inputTable state 更新逻辑,减少多余重新渲染

- packages/amis-editor-core/scss/control/_option-control.scss
- packages/amis-editor/src/renderer/OptionControl.tsx
> feat(editor): optionControl支持配置customEdit

- packages/amis-editor-core/src/util.ts
> fix: 快捷变量层级

- packages/amis/src/renderers/Form/InputTable.tsx
> fix: input-table未下发static、删除逻辑优化

- packages/amis/src/renderers/Form/InputTable.tsx
> fix: 修复table中form item static不生效问题

- packages/amis-ui/src/components/Tree.tsx
> fix: TreeSelector 报错

- packages/amis-editor-core/src/util.ts
- packages/amis-editor/src/renderer/FormulaControl.tsx
- packages/amis-editor/src/renderer/TplFormulaControl.tsx
- packages/amis-editor/src/renderer/textarea-formula/TextareaFormulaControl.tsx
> fix: 快捷变量展示模式

- packages/amis/src/renderers/Dialog.tsx
- packages/amis/src/renderers/Drawer.tsx
> fix: 修复弹窗中表单内再弹窗新弹窗按钮不可点问题

- packages/amis-editor-core/scss/control/_tpl-formula-control.scss
> fix: formula Button style

- packages/amis-editor-core/scss/control/_tpl-formula-control.scss
- packages/amis-ui/src/components/formula/VariableList.tsx
> fix: varliableItem value 空选择问题

- packages/amis/src/renderers/Words.tsx
> fix: 修复 words 显示复杂对象时报错问题

- packages/amis-editor-core/src/component/factory.tsx
- packages/amis-editor/src/plugin/Form/Item.tsx
> chore: 调整表单项默认值变更逻辑支持值格式是数组的情况

- packages/amis/src/renderers/Table2/index.tsx
> chore: table2 单元格渲染逻辑优化

- packages/amis-editor/src/renderer/FormulaControl.tsx
> fix: formulaControl 高亮时机问题

- packages/amis-core/src/renderers/Item.tsx
> fix: 修复form flex模式下description位置不对问题

- docs/zh-CN/components/form/input-table.md
- packages/amis-ui/scss/components/_table.scss
- packages/amis/src/renderers/Form/InputTable.tsx
> feat: input-table 的复制功能支持配置复制数据映射

- packages/amis-editor/src/renderer/OptionControl.tsx
> feat(editor): optionControl批量添加支持配置customEdit

- packages/amis-core/src/SchemaRenderer.tsx
- packages/amis-core/src/renderers/Form.tsx
- packages/amis/src/renderers/Form/Combo.tsx
- packages/amis/src/renderers/Form/InputTable.tsx
- packages/amis/src/renderers/QuickEdit.tsx
- packages/amis/src/renderers/Table/Cell.tsx
- packages/amis/src/renderers/Table/TableCell.tsx
> fix: input-table 修复 input-table 内部有公式时展示值与表单项值不一致问题

- packages/amis-core/src/utils/helper.ts
- packages/amis-editor-core/src/util.ts
- packages/amis-editor/src/renderer/ConditionFormulaControl.tsx
- packages/amis-editor/src/renderer/ValidationControl.tsx
> fix: 条件表达式在input-table列上不生效、条件表达式变量去除子表及内部变量

- packages/amis-formula/__tests__/evalute.test.ts
- packages/amis-formula/src/evalutor.ts
> fix: 修复 fx 的 replace 方法可能死循环的问题

- packages/amis-editor-core/scss/control/_badge-control.scss
- packages/amis-editor/src/renderer/BadgeControl.tsx
- packages/amis/src/renderers/Grid.tsx
> crud2角标修复 & 分栏容器外观支持修复

- packages/amis-ui/src/components/ChainedDropdownSelection.tsx
- packages/amis-ui/src/components/DropDownSelection.tsx
- packages/amis-ui/src/components/GroupedSelection.tsx
- packages/amis-ui/src/components/Selection.tsx
- packages/amis-ui/src/components/condition-builder/Expression.tsx
- packages/amis-ui/src/components/condition-builder/Field.tsx
- packages/amis-ui/src/components/condition-builder/Func.tsx
- packages/amis-ui/src/components/condition-builder/Group.tsx
- packages/amis-ui/src/components/condition-builder/GroupOrItem.tsx
- packages/amis-ui/src/components/condition-builder/InputSwitch.tsx
- packages/amis-ui/src/components/condition-builder/Item.tsx
- packages/amis-ui/src/components/condition-builder/Value.tsx
- packages/amis-ui/src/components/condition-builder/index.tsx
> feat: conditionBuilder 支持testid

- packages/amis-editor/src/plugin/CRUD2/BaseCRUD.tsx
- packages/amis-editor/src/renderer/event-control/helper.tsx
> feat:动作配置面板reload动作支持选择crud2

- packages/amis-editor-core/scss/editor.scss
> style: 编辑器 crud 的批量操作 右侧面板样式优化

- packages/amis/src/renderers/CRUD2.tsx
> fix: 修复query同步后人员选择无法清除问题

- packages/amis-editor-core/src/util.ts
- packages/amis-ui/scss/components/form/_tree.scss
> fix: 条件表达式中去除系统变量，input-tree中icon图片大小设置

- packages/amis/src/renderers/Table2/index.tsx
> fix: 修复弹窗中crud2刷新后按钮不可点击问题

- packages/amis-editor/src/renderer/ValidationItem.tsx
> fix: 校验输入框删除内容时输入内容闪烁

- packages/amis-editor-core/src/plugin/BasicToolbar.tsx
> fix(editor): 修复容器类组件右键菜单缺少功能问题

- docs/zh-CN/start/getting-started.md
- examples/components/SchemaRender.jsx
- examples/embed.tsx
- examples/loadPdfjsWorker.ts
- fis-conf.js
- packages/amis-core/src/env.tsx
- packages/amis-core/src/utils/helper.ts
- packages/amis-ui/src/components/PdfViewer.tsx
- packages/amis/build.sh
- packages/amis/src/renderers/PdfViewer.tsx
> feat: pdfWokerJs 修改为env引入

- packages/amis-ui/src/components/GroupedSelection.tsx
> fix: 删除多余的console

- examples/components/SchemaRender.jsx
- fis-conf.js
> fix: 修复 gh-pages 报错 close #10592

- packages/amis-core/src/components/PopOver.tsx
- packages/amis-ui/src/components/DatePicker.tsx
> feat: popover testid

- packages/amis/src/renderers/CRUD.tsx
> feat: CRUD 支持 testid

- packages/amis-editor/src/plugin/Form/InputDate.tsx
- packages/amis-editor/src/plugin/Form/InputDateRange.tsx
- packages/amis-editor/src/renderer/ValidationControl.tsx
- packages/amis-editor/src/renderer/ValidationItem.tsx
- packages/amis-editor/src/tpl/validations.tsx
> feat: 配置面板-规则项支持自定义schema

- packages/amis-editor/src/renderer/ValidationItem.tsx
> fix: 配置面板-未配置自定义schema的校验规则丢失默认schema

- packages/amis-editor-core/src/component/Panel/CodeEditorPanel.tsx
- packages/amis-editor-core/src/manager.ts
- packages/amis-editor-core/src/util.ts
- packages/amis-ui/scss/components/_table.scss
- packages/amis-ui/scss/components/_table2.scss
- packages/amis/src/renderers/Table2/index.tsx
> table样式优化 & schema复制重新生成id策略调整

- docs/zh-CN/components/table.md
- packages/amis-editor/src/plugin/Others/TableCell.tsx
- packages/amis/src/renderers/Table/TableBody.tsx
- packages/amis/src/renderers/Table/TableCell.tsx
- packages/amis/src/renderers/Table/index.tsx
> feat: crud 列支持配置对齐方式&表头对齐方案&垂直对齐方式

- packages/amis-editor-core/src/component/factory.tsx
> fix: variableList 显示问题

- packages/amis-core/src/utils/helper.ts
- packages/amis/src/renderers/Tpl.tsx
> fix: 修复tpl值为NaN时页面卡死问题

- packages/amis-editor/src/plugin/Form/InputRange.tsx
- packages/amis-editor/src/renderer/InputRangeValueControl.tsx
> feat(amis-editor): inputRange支持设置小数

- packages/amis-core/src/utils/helper.ts
> fix: 修复 form 的 canAccessSuperData false 无效问题

- packages/amis-editor/src/renderer/event-control/DialogActionPanel.tsx
> fix: 修复弹窗编辑通过弹窗编辑进去的子弹窗编辑,修改后无法保存上的问题

- .github/workflows/codeql-analysis.yml
- .github/workflows/gh-pages.yml
- .github/workflows/pr-test.yml
> chore: Update to the latest version

- .github/labeler.yml
> chore: 增加大小写不敏感匹配

- packages/amis/src/renderers/Form/InputTable.tsx
> fix: 修复 inputTable 表单项校验问题 Close: #9680

- packages/amis-core/src/utils/helper.ts
> fix: 修复 #9981 引发的 crud 中数值变化 diff 不准确的问题 Close: #10270

- packages/amis-ui/scss/components/form/_input-group.scss
> style: 调整 inputGroup 样式 Close: #10593

- packages/amis-core/src/types.ts
- packages/amis-core/src/utils/DataScope.ts
- packages/amis-editor-core/scss/control/_tpl-formula-control.scss
- packages/amis-editor-core/src/plugin.ts
- packages/amis-editor-core/src/util.ts
- packages/amis-editor/src/renderer/FormulaControl.tsx
> feat: dataSchema 增加 rawType 细化类型

- package.json
> chore: 升级i18n版本,固定@babel/generator版本到7.24.7

- packages/amis-ui/scss/components/form/_number.scss
- packages/amis-ui/src/components/NumberInput.tsx
- packages/amis/src/renderers/Form/InputNumber.tsx
> feat:调整数字框组件只读属性的样式

- packages/amis-ui/src/components/NumberInput.tsx
- packages/amis/__tests__/renderers/Form/number.test.tsx
- packages/amis/src/renderers/Form/InputNumber.tsx
> feat: 数字框组件新增属性showPercent

- packages/amis-editor/src/renderer/event-control/helper.tsx
> fix: 人员组件事件动作问题

- packages/amis-editor-core/src/util.ts
> feat: 快捷变量过滤掉布尔类型

- packages/amis-core/src/renderers/Form.tsx
- packages/amis-editor/src/plugin/Form/Form.tsx
- packages/amis-editor/src/plugin/Form/Select.tsx
- packages/amis-editor/src/plugin/Form/Textarea.tsx
- packages/amis-editor/src/plugin/Table2.tsx
- packages/amis-editor/src/tpl/common.tsx
- packages/amis-theme-editor-helper/src/renderers/Border.tsx
- packages/amis-theme-editor-helper/src/renderers/PaddingAndMargin.tsx
- packages/amis-ui/scss/components/form/_form.scss
- packages/amis/src/renderers/Form/Select.tsx
- packages/amis/src/renderers/Table2/index.tsx
> fix: 修复外观的一些问题

- packages/amis-editor-core/src/util.ts
> feat: 快捷变量过滤掉布尔类型 (#10679)

- packages/amis-editor/src/tpl/style.tsx
- packages/amis-theme-editor-helper/src/renderers/Shadow.tsx
> fix: 修复theme:base className带短横线问题

- packages/amis-core/src/actions/CmptAction.ts
> feat: 增加自定义表单项校验方案

- docs/zh-CN/components/form/select.md
> add noResultsText to doc

- packages/amis/src/renderers/Form/IconSelect.tsx
> fix: 修复iconSelect组件不能正常展示图标问题

- packages/amis-editor-core/scss/editor.scss
- packages/amis-editor-core/src/component/FormConfigWrapper.tsx
- packages/amis-editor-core/src/component/Panel/Outline.tsx
- packages/amis-editor-core/src/component/factory.tsx
- packages/amis-editor-core/src/plugin/BasicToolbar.tsx
- packages/amis-editor-core/src/store/editor.ts
- packages/amis-editor-core/src/store/node.ts
- packages/amis-editor-core/src/util.ts
> feat: editor-core支持8738formSchema处理

- packages/amis/src/renderers/Container.tsx
- packages/amis/src/renderers/Table/HeadCellSearchDropdown.tsx
- packages/amis/src/renderers/Table/index.tsx
- packages/amis/src/renderers/Wizard.tsx
> feat: container wizard 组件 testid

- packages/amis-ui/scss/components/_table2.scss
- packages/amis/src/renderers/Table2/index.tsx
> fix: 修复crud2行角标显示问题

- packages/amis-ui/src/components/ConfirmBox.tsx
- packages/amis-ui/src/components/PickerContainer.tsx
> feat: pickerContainer 补充testid

- packages/amis-theme-editor-helper/src/renderers/PaddingAndMargin.tsx
> fix: 修复padding组件选择问题

- packages/amis-ui/src/components/menu/SubMenu.tsx
- packages/amis/__tests__/renderers/__snapshots__/Nav.test.tsx.snap
> fix: 修复nav组件横向模式下,父级无法点击问题

- packages/amis-editor-core/src/plugin/DataDebug.tsx
> fix:修复编辑器toolbar debug按钮丢失问题

- packages/amis-editor/src/renderer/event-control/helper.tsx
> 修复#10041，赋值事件，args.value值为object时初始化加载不显示的bug

- packages/amis-editor-core/scss/_outline.scss
- packages/amis-editor-core/scss/editor.scss
- packages/amis-editor-core/src/component/NodeWrapper.tsx
- packages/amis-editor-core/src/component/Panel/Outline.tsx
- packages/amis-editor-core/src/component/Preview.tsx
- packages/amis-editor-core/src/component/RegionHLBox.tsx
- packages/amis-editor-core/src/dnd/default.ts
- packages/amis-editor-core/src/dnd/index.ts
- packages/amis-editor-core/src/store/editor.ts
- packages/amis-editor-core/src/store/node.ts
1. 优化大纲，使得更紧凑，同时高亮 hover 区域优化
2. 优化拖拽，改成通过功能键切换拖拽容器，或者拖到左侧大纲切换。
3. 优化拖拽过程中的大纲视图，区域更好拖入
> chore: 优化编辑器大纲样式, 优化拖拽交互

- packages/amis-ui/scss/components/form/_combo.scss
- packages/amis/src/renderers/Form/Combo.tsx
> chore: 优化 combo tabs 模式新增成员直接打开对应 tab 减少操作步骤

- packages/amis-core/src/utils/debug.tsx
> fix:debug容错，避免阻塞

- packages/amis/src/renderers/Form/InputTable.tsx
修复issue#10758  inputTable在嵌套模式下删除逻辑存在问题
> fix: inputTable在嵌套模式下删除逻辑存在问题 Close #10758 

- packages/amis-ui/scss/components/form/_user-select.scss
- packages/amis-ui/src/components/UserTabSelect.tsx
- packages/amis/src/renderers/Form/UserSelect.tsx
> fix: 人员选择展示问题

- package.json
> chore: 升级i18n插件版本,优化console打印的颜色

- packages/amis-ui/src/components/DatePicker.tsx
- packages/amis/__tests__/renderers/Form/datetime.test.tsx
> fix: 修复时间选择器默认选择当前时间问题

- packages/amis-ui/src/components/UserSelect.tsx
> fix: 修复users-select 懒加载问题

- packages/amis-core/__tests__/utils/visitedCache.test.ts
- packages/amis-core/src/utils/isPureVariable.ts
- packages/amis-core/src/utils/memoryParse.ts
- packages/amis-core/src/utils/visitedCache.ts
- packages/amis-formula/src/index.ts
添加一个缓存类，综合考虑访问次数与新旧顺序，按照设定容量的百分比释放缓存
> feat: 添加表达式解析缓存逻辑 

- packages/amis/src/renderers/Table/ItemActionsWrapper.tsx
> fix: 修复 itemActdions 位置错误当表格内容太宽滚动到右侧时

- packages/amis-core/src/store/formItem.ts
> fix: 数值 0 在选项中不应该被认为是空值

- packages/amis-ui/scss/components/_image-gallery.scss
- packages/amis-ui/src/components/ImageGallery.tsx
> feat: imageGallery 图片超出时支持左右滚动 Close: #10756

- packages/amis-ui/src/components/menu/SubMenu.tsx
- packages/amis/__tests__/renderers/__snapshots__/Nav.test.tsx.snap
> fix: 仅横向导航需要加href

- docs/zh-CN/components/form/formitem.md
- packages/amis-core/src/renderers/Item.tsx
- packages/amis-core/src/store/formItem.ts
- packages/amis-ui/src/components/TabsTransferPicker.tsx
- packages/amis-ui/src/components/TransferPicker.tsx
- packages/amis-ui/src/components/formula/Input.tsx
- packages/amis/src/renderers/Form/Select.tsx
> chore: 调整自动填充参照录入逻辑支持默认点选,state 换成 store,优化写入对象时保留原始对象其他字段逻辑

- packages/amis-core/src/utils/helper.ts
- packages/amis/src/renderers/QuickEdit.tsx
> fix: 修复 input-table accessSuperData 模式,行数据无对应字段问题 Close: #10782

- packages/amis-editor-core/src/component/Preview.tsx
> fix(editor): 修复初次进入编辑器未选中body

- packages/amis-core/src/actions/DialogAction.ts
- packages/amis/src/renderers/Dialog.tsx
- packages/amis/src/renderers/Drawer.tsx
> fix: 修复事件动作场景弹窗关闭马上又打开时的缺陷 Close: #10304

- packages/amis-ui/scss/_variables.scss
> fix: issue#10775 防止popover被modal遮盖

- packages/amis-core/src/utils/object.ts
- packages/amis/__tests__/renderers/Form/inputTable.test.tsx
- packages/amis/src/renderers/Form/InputTable.tsx
The doAction function in the InputTable component lacks logic
关联issue👉：https://github.com/baidu/amis/issues/10792
> Fix add item logic for InputTable when using addAction

- packages/amis-ui/scss/components/form/_date.scss
> style: 日期时间组件不限制最小宽度

- packages/amis-editor/src/plugin/Form/InputNumber.tsx
- packages/amis-editor/src/plugin/Form/InputTable.tsx
- packages/amis-editor/src/plugin/Form/InputText.tsx
- packages/amis-editor/src/plugin/Form/Radios.tsx
- packages/amis-editor/src/plugin/Form/Select.tsx
- packages/amis-editor/src/renderer/StatusControl.tsx
- packages/amis/src/index.tsx
> feat: 默认放开自定义条件

- packages/amis/src/renderers/Form/InputTable.tsx
> style: inputTable 移动端操作栏不固定列

- packages/amis-editor/src/renderer/event-control/index.tsx
> fix:动作面板删除动作后配置丢失问题

- packages/amis/src/renderers/Form/Select.tsx
> fix:下拉框focus报错

- packages/amis-core/src/SchemaRenderer.tsx
- packages/amis-core/src/utils/helper.ts
- packages/amis/src/renderers/Form/Group.tsx
> fix: 修复 group 中成员隐藏状态通过事件动作无法控制的问题 Close: #10794

- packages/amis-core/src/WithStore.tsx
> fix: 修复 service 配置了 data 数据映射,在上层数据更新后丢失的问题

- packages/amis-core/src/store/table.ts
- packages/amis/src/renderers/Table/TableBody.tsx
> style: 修复 table的affixRow总结行在fixed模式下样式错乱问题 Close: #10810

- packages/amis/src/types.ts
> feat: 优化payload声明

- packages/amis-ui/scss/components/form/_user-select.scss
> fix: users-select mobile style

- packages/amis/src/renderers/Form/Combo.tsx
> chore: combo single 和 multiple 模式统一传参

- packages/amis/src/renderers/Form/NestedSelect.tsx
> fix: 修复级联选择器数据源异常label为数组时页面崩溃的问题

- packages/amis/src/renderers/OfficeViewer.tsx
> fix: 修复 OfficeViewer 示例中无法渲染上传文件问题

- packages/amis-editor-core/src/component/Panel/Outline.tsx
> fix: 修复 outline 容器释放拖拽无效的问题

- docs/zh-CN/components/button.md
- docs/zh-CN/components/crud.md
- docs/zh-CN/components/form/condition-builder.md
> fix some words's spelling errors

- packages/amis/src/renderers/Form/InputTag.tsx
> fix: issue#10507 复制带分隔符的文本到inputTag，max属性和去重会失效

- packages/amis-ui/scss/components/form/_rich-text.scss
> fix: rich-text loading 位置

- packages/amis-ui/scss/components/_collapse.scss
> fix: 折叠器（collapse）箭头显示异常 Close: #10564

- packages/amis-ui/scss/components/form/_selection.scss
- packages/amis-ui/src/components/DropDownSelection.tsx
> style:condition下拉框样式细节优化,避免内容过多导致超长

- packages/amis-ui/scss/components/form/_selection.scss
- packages/amis-ui/src/components/DropDownSelection.tsx
> style:condition下拉框样式细节优化,避免内容过多导致超长 (#10864)

- packages/office-viewer/src/util/saxes.ts
> chore: update saxes.ts

- packages/amis-ui/scss/components/form/_form.scss
> style: form label强制折行

- docs/zh-CN/start/getting-started.md
chore: fix spelling errors
CND --> CDN
> docs: fix spelling errors

- docs/zh-CN/components/table2.md
#10701  之前为 table2 新增了一个事件，但是没有补充文档，在这里补齐
> 补充 table2 事件文档

- examples/mod.js
- fis-conf.js
- scripts/embed-packager.js
> feat: jssdk 支持 qiankun, wujie 微前端框架作为子应用加载

- packages/amis-ui/src/components/ImageGallery.tsx
> fix: 修复图片放大功能右键也会触发图片移动的问题

- packages/amis/src/renderers/Form/InputNumber.tsx
> style: 修复table 中放置带单位的 inputNumber 弹出被挡住问题

- packages/amis/src/renderers/Words.tsx
> fix: 设置intag时，label 为对象时渲染异常

- packages/amis-editor-core/src/component/base/SchemaForm.tsx
- packages/amis/src/renderers/Form/Select.tsx
> fix: 配置面板首次变更无效

- packages/amis-core/src/utils/labelToString.ts
> fix: label为布尔时，显示错误

- docs/zh-CN/concepts/datascope-and-datachain.md
- packages/amis-core/src/WithStore.tsx
- packages/amis-core/src/renderers/Form.tsx
- packages/amis-core/src/renderers/Item.tsx
- packages/amis-core/src/renderers/wrapControl.tsx
- packages/amis-core/src/store/form.ts
- packages/amis-core/src/store/iRenderer.ts
- packages/amis-core/src/store/service.ts
- packages/amis-core/src/types.ts
- packages/amis-editor-core/src/plugin.ts
- packages/amis-editor-core/src/store/editor.ts
- packages/amis-editor-core/src/util.ts
- packages/amis-editor/src/plugin/Dialog.tsx
- packages/amis-editor/src/renderer/FormulaControl.tsx
- packages/amis-editor/src/renderer/StatusControl.tsx
- packages/amis-editor/src/renderer/event-control/DialogActionPanel.tsx
- packages/amis-editor/src/renderer/event-control/index.tsx
- packages/amis-editor/src/tpl/common.tsx
- packages/amis/__tests__/renderers/CRUDfilter.test.tsx
- packages/amis/src/renderers/Service.tsx
- packages/amis/src/types.ts
> feat: 隐藏数据中添加 __changeReason 字段并补充文档说明

- packages/amis-editor-core/src/manager.ts
- packages/amis-editor-core/src/store/node.ts
> feat: 组件id重复后,重新赋值

- packages/amis-editor-core/src/component/Panel/DialogList.tsx
> fix: 修复弹框复制id重复问题

- packages/amis-editor-core/scss/editor.scss
- packages/amis-editor-core/src/component/SubEditor.tsx
> feat: 编辑器只读模式的subEditor支持返回

- packages/amis-core/src/factory.tsx
- packages/amis/src/minimal.ts
> fix: 修复渲染改成异步后部分面板匹配错误问题

- packages/amis-editor-core/src/manager.ts
- packages/amis-editor-core/src/store/node.ts
> Revert "feat: 组件id重复后,重新赋值"

- packages/amis-core/src/renderers/Form.tsx
- packages/amis-core/src/store/form.ts
- packages/amis-editor-core/src/component/Panel/RightPanels.tsx
- packages/amis-editor-core/src/component/base/SchemaForm.tsx
- packages/amis-editor-core/src/component/factory.tsx
- packages/amis-editor-core/src/plugin.ts
> feat: 编辑器只读模式下编辑后还原数据

- packages/amis-core/rollup.config.js
- packages/amis-core/src/index.tsx
- packages/amis-editor-core/rollup.config.js
- packages/amis-editor-core/src/index.ts
- packages/amis-editor/rollup.config.js
- packages/amis-editor/src/index.tsx
- packages/amis-editor/src/validator.tsx
- packages/amis-formula/rollup.config.js
- packages/amis-theme-editor-helper/rollup.config.js
- packages/amis-ui/rollup.config.js
- packages/amis/rollup.config.js
> fix: 修复 amis-editor 校验面板没有翻译的问题

- packages/amis-core/src/renderers/Form.tsx
- packages/amis/__tests__/renderers/Form/inputTable.test.tsx
> chore: form 下发 onFlushForm 方便自定义组件拿取最新数据

- examples/style.scss
- packages/amis-ui/scss/_components.scss
- packages/amis-ui/scss/_mixins.scss
- packages/amis-ui/scss/_properties.scss
- packages/amis-ui/scss/_variables.scss
- packages/amis-ui/scss/components/_array-input.scss
- packages/amis-ui/scss/components/_input-box.scss
- packages/amis-ui/scss/components/_json-schema-editor.scss
- packages/amis-ui/scss/components/_result-box.scss
- packages/amis-ui/scss/components/_tag.scss
- packages/amis-ui/scss/components/_toast.scss
- packages/amis-ui/scss/components/form/_image.scss
- packages/amis-ui/scss/components/form/_list.scss
- packages/amis-ui/scss/components/form/_picker.scss
- packages/amis-ui/scss/components/form/_select.scss
- packages/amis-ui/scss/components/form/_textarea.scss
- packages/amis-ui/scss/components/form/_tree-select.scss
> fix: fix scss deprecation warning

- packages/amis-editor-core/src/manager.ts
> fix: 修复编辑器中crud2 id自动修改问题

- packages/amis-theme-editor-helper/src/systemTheme/component.ts
- packages/amis-ui/scss/_components.scss
> style: 调整表格行上下内边距

- packages/amis-core/src/factory.tsx
- packages/amis/src/renderers/Page.tsx
> fix: 修复类继承 observer 过的类无法使用 super.render 的问题

- packages/amis-editor-core/scss/editor.scss
- packages/amis-editor-core/src/component/Editor.tsx
- packages/amis-editor-core/src/component/Preview.tsx
- packages/amis-ui/scss/components/_mobile-dev-tool.scss
- packages/amis-ui/src/components/MobileDevTool.tsx
> feat: 移动端预览增加自定义尺寸功能

- packages/amis-ui/src/components/schema-editor/Array.tsx
- packages/amis-ui/src/components/schema-editor/Common.tsx
- packages/amis-ui/src/components/schema-editor/Item.tsx
- packages/amis-ui/src/components/schema-editor/Object.tsx
- packages/amis-ui/src/components/schema-editor/index.tsx
> chore: 解决递归依赖

- packages/amis-editor-core/scss/editor.scss
- packages/amis-ui/src/components/MobileDevTool.tsx
> style(amis-editor):优化移动端尺寸控制器样式

- packages/amis-ui/src/components/MobileDevTool.tsx
> chore: 优化移动端尺寸选择器自适应逻辑

- packages/amis-ui/src/components/CalendarMobile.tsx
> fix: 修复时间范围组件移动端结束时间的时间戳不是23:59:59问题

- packages/amis-editor/src/plugin/CRUD2/BaseCRUD.tsx
- packages/amis-editor/src/renderer/crud2-control/CRUDFiltersControl.tsx
- packages/amis-ui/scss/components/_table.scss
- packages/amis/src/renderers/CRUD2.tsx
> fix: 修复crud2翻页及搜索重置不生效问题

- packages/amis-ui/scss/components/_pull-refresh.scss
- packages/amis-ui/src/components/PullRefresh.tsx
- packages/amis-ui/src/hooks/index.ts
- packages/amis-ui/src/hooks/use-on-screen.ts
- packages/amis-ui/src/locale/de-DE.ts
- packages/amis-ui/src/locale/en-US.ts
- packages/amis-ui/src/locale/zh-CN.ts
- packages/amis/__tests__/renderers/Form/conditionBuilder.test.tsx
- packages/amis/src/renderers/CRUD2.tsx
> feat: crud2支持配置移动端展示为卡片或自定义schema,支持上拉加载

- packages/amis-ui/scss/components/_pull-refresh.scss
- packages/amis-ui/src/components/PullRefresh.tsx
- packages/amis-ui/src/hooks/index.ts
- packages/amis-ui/src/hooks/use-on-screen.ts
- packages/amis-ui/src/locale/de-DE.ts
- packages/amis-ui/src/locale/en-US.ts
- packages/amis-ui/src/locale/zh-CN.ts
- packages/amis/__tests__/renderers/Form/conditionBuilder.test.tsx
- packages/amis/src/renderers/CRUD2.tsx
> feat: crud2支持配置移动端展示为卡片或自定义schema,支持上滑加载更多

- packages/amis/src/renderers/Tpl.tsx
> fix: 修复 tpl 渲染时序问题导致的渲染错误

- packages/amis-editor/src/plugin/Form/NestedSelect.tsx
- packages/amis/src/renderers/Form/NestedSelect.tsx
> feat: 级联选择器支持新版外观配置

- packages/amis/src/renderers/CRUD.tsx
> fix: 修复 #10126 引发的模型页面编辑器不可拖拽问题

- packages/amis-ui/scss/components/_card.scss
> fix: 修复移动端卡片内静态表单项样式问题

- packages/amis-ui/scss/components/_card.scss
> fix: 修复卡片内静态表单项样式问题

- packages/amis-theme-editor-helper/rollup.config.js
> fix: 修复重复定义fs模块

- packages/amis-core/__tests__/renderers/wrapControl.test.tsx
- packages/amis-core/src/renderers/wrapControl.tsx
> feat: FormItem支持从类的默认属性中获取表单项的name属性，以便初始化全局状态formItem  Closes #10998

- packages/amis-core/src/locale.tsx
- packages/amis-core/src/theme.tsx
- packages/amis-ui/src/components/DiffEditor.tsx
- packages/amis-ui/src/components/Editor.tsx
- packages/amis-ui/src/components/index.tsx
- packages/amis/src/renderers/Form/DiffEditor.tsx
> fix: DiffEditor 分装成ui 组件，解决可能不显示最新值的问题

- packages/amis-core/src/renderers/Item.tsx
> fix: 去掉不可填充自己的设定

- packages/amis-ui/scss/_properties.scss
- packages/amis-ui/scss/components/_crud2.scss
- packages/amis-ui/scss/components/_modal.scss
- packages/amis-ui/scss/components/_panel.scss
- packages/amis-ui/scss/components/_pull-refresh.scss
- packages/amis-ui/scss/components/form/_form.scss
- packages/amis-ui/src/components/Card.tsx
- packages/amis/src/renderers/CRUD2.tsx
- packages/amis/src/renderers/Panel.tsx
> feat: 美化crud2移动端的卡片样式,支持查询表单折叠

- packages/amis-ui/scss/components/_crud2.scss
- packages/amis-ui/scss/components/form/_form.scss
- packages/amis/src/renderers/Panel.tsx
> feat: 优化crud2移动端样式

- packages/amis-ui/scss/components/_crud2.scss
> fix: crud2 filter为空时去掉marginBottom

- packages/amis-editor-core/src/util.ts
> fix: 修复顶层数据不是对象在公式中被过滤掉的问题 Close: #11035

- packages/amis-core/src/envOverwrite.ts
- packages/amis-editor-core/src/component/Editor.tsx
- packages/amis-editor-core/src/component/IFramePreview.tsx
- packages/amis-editor-core/src/component/Panel/CodeEditorPanel.tsx
- packages/amis-editor-core/src/component/Panel/RightPanels.tsx
- packages/amis-editor-core/src/component/Preview.tsx
- packages/amis-editor-core/src/manager.ts
- packages/amis-editor-core/src/store/editor.ts
- packages/amis-editor-core/src/util.ts
> feat:编辑器移动端支持单独编辑

- packages/amis-editor-core/src/component/Editor.tsx
> chore: 删除无用代码

- packages/amis-editor-core/src/component/Editor.tsx
- packages/amis-editor-core/src/component/ModalForm.tsx
- packages/amis-editor-core/src/plugin.ts
- packages/amis-editor-core/src/store/editor.ts
> feat: Editor 支持插件弹出面板

- packages/amis-ui/src/components/ResultBox.tsx
- packages/amis/__tests__/renderers/Form/__snapshots__/inputTag.test.tsx.snap
- packages/amis/__tests__/renderers/Form/__snapshots__/nestedSelect.test.tsx.snap
- packages/amis/__tests__/renderers/Form/__snapshots__/select.test.tsx.snap
- packages/amis/__tests__/renderers/Form/__snapshots__/tabsTransferPicker.test.tsx.snap
> feat: resultBox item项支持点击事件

- docs/zh-CN/concepts/event-action.md
- packages/amis-core/src/Scoped.tsx
- packages/amis-core/src/actions/CmptAction.ts
- packages/amis-core/src/renderers/Form.tsx
- packages/amis-core/src/utils/api.ts
- packages/amis-editor/src/renderer/event-control/helper.tsx
- packages/amis/src/renderers/App.tsx
- packages/amis/src/renderers/CRUD.tsx
- packages/amis/src/renderers/CRUD2.tsx
- packages/amis/src/renderers/Chart.tsx
- packages/amis/src/renderers/Page.tsx
- packages/amis/src/renderers/Service.tsx
- packages/amis/src/renderers/Wizard.tsx
> chore: reload 动作改成等待完成(原来不等待只发送指令), 同时支持获取 service 结果

- packages/amis-core/src/actions/ToastAction.ts
- packages/amis-ui/scss/components/_toast.scss
- vite.config.ts
> fix: 事件动作触发Toast移动端样式失效问题

- packages/amis-ui/src/components/DiffEditor.tsx
> fix: 修复 diffEditor disabled 状态不更新的问题

- packages/amis/src/renderers/Tabs.tsx
> fix: tabs activeKey 失效

- examples/mod.js
- fis-conf.js
- scripts/embed-packager.js
> fix: 修复 sdk 在单页中存在多个版本时渲染异常的问题

- packages/amis-ui/src/components/DiffEditor.tsx
- packages/amis/src/renderers/Form/DiffEditor.tsx
> fix: DiffEditor 抽成组件后onChange异常问题

- packages/amis-editor/src/plugin/CollapseGroup.tsx
- packages/amis-ui/scss/components/_collapse-group.scss
- packages/amis-ui/scss/components/_collapse.scss
- packages/amis-ui/src/components/Collapse.tsx
- packages/amis/__tests__/renderers/Form/__snapshots__/fieldSet.test.tsx.snap
> feat: 折叠面板，无标题时显示折叠箭头。组件存在于表单中，面板新增切换展示方式按钮

- packages/amis-core/src/utils/validations.ts
> fix：表单项值非string时，部分校验规则一直生效

- docs/zh-CN/components/page.md
- packages/amis-editor/src/plugin/Page.tsx
- packages/amis-ui/scss/components/_page.scss
- packages/amis/__tests__/renderers/__snapshots__/Page.test.tsx.snap
- packages/amis/src/renderers/Page.tsx
> feat: page侧栏支持左右位置

- packages/amis-theme-editor-helper/src/renderers/ColorPicker.tsx
- packages/amis-theme-editor-helper/src/style/_color-picker.scss
> chore: 优化外观颜色选择器交互

- docs/zh-CN/components/form/options.md
> feat: 补充下拉框选项禁用的说明文档

- packages/amis-ui/scss/components/_crud2.scss
- packages/amis/src/renderers/CRUD2.tsx
> feat: crud2 移动端卡片模式支持固定新增按钮以及顶部搜索

- packages/amis-core/src/SchemaRenderer.tsx
- packages/amis-core/src/utils/animations.ts
- packages/amis-editor/src/tpl/style.tsx
> chore: 优化动画配置

- packages/amis-editor/src/plugin/Form/Checkbox.tsx
- packages/amis-editor/src/plugin/Form/Radios.tsx
- packages/amis-editor/src/renderer/style-control/helper.tsx
- packages/amis-ui/scss/components/form/_form.scss
- packages/amis/src/renderers/Form/Checkbox.tsx
- packages/amis/src/renderers/Form/Checkboxes.tsx
- packages/amis/src/renderers/Form/Radios.tsx
> feat: checkbox\radios支持外观配置

- examples/doc.css
- packages/amis-ui/scss/components/_anchor-nav.scss
- packages/amis-ui/src/components/AnchorNav.tsx
- packages/amis/__tests__/renderers/AnchorNav.test.tsx
- packages/amis/__tests__/renderers/__snapshots__/AnchorNav.test.tsx.snap
> feat: 锚点导航调整为sticky布局

- docs/zh-CN/components/crud.md
- packages/amis/src/renderers/CRUD.tsx
> fix:补充crud批量操作中事件动作数据

- packages/amis-core/src/Root.tsx
- packages/amis-core/src/SchemaRenderer.tsx
- packages/amis-core/src/StatusScoped.tsx
- packages/amis-core/src/env.tsx
- packages/amis-core/src/index.tsx
- packages/amis-core/src/types.ts
- packages/amis-core/src/utils/api.ts
- packages/amis/src/renderers/Nav.tsx
- packages/amis/src/renderers/Service.tsx
> feat: 渲染器包裹支持外层自定义

- packages/amis-editor-core/scss/editor.scss
- packages/amis-editor-core/scss/style-control/_single-theme-css-code.scss
- packages/amis-editor/src/index.tsx
- packages/amis-editor/src/plugin/Page.tsx
- packages/amis-editor/src/renderer/style-control/SingleThemeCssCode.tsx
- packages/amis-editor/src/tpl/style.tsx
> feat: 自定义样式扩展

- docs/zh-CN/components/tabs.md
- packages/amis-editor/src/plugin/Tabs.tsx
- packages/amis-editor/src/tpl/common.tsx
- packages/amis-editor/src/tpl/style.tsx
- packages/amis-ui/scss/components/_tabs.scss
- packages/amis-ui/src/components/Tabs.tsx
- packages/amis/__tests__/renderers/Tabs.test.tsx
- packages/amis/src/renderers/Tabs.tsx
> feat: tabs支持删除动作，外观样式支持主题

- packages/amis-editor/src/plugin/Collapse.tsx
- packages/amis-editor/src/plugin/CollapseGroup.tsx
- packages/amis-editor/src/plugin/Panel.tsx
- packages/amis-editor/src/tpl/style.tsx
- packages/amis-ui/scss/components/_collapse-group.scss
- packages/amis/src/renderers/Collapse.tsx
- packages/amis/src/renderers/CollapseGroup.tsx
- packages/amis/src/renderers/Panel.tsx
> feat: panel\collapse支持新版外观

- packages/amis-ui/src/components/AnchorNav.tsx
- packages/amis/__tests__/renderers/__snapshots__/AnchorNav.test.tsx.snap
> chore: 锚点导航标识调整为data-id

- packages/amis/src/renderers/CollapseGroup.tsx
- packages/amis/src/renderers/Form/FieldSet.tsx
- packages/amis/src/renderers/Table2/index.tsx
>  折叠容器折叠异常 & table2数据更新问题

- packages/amis-editor/src/plugin/Timeline.tsx
- packages/amis-editor/src/renderer/TimelineItemControl.tsx
- packages/amis-ui/scss/components/_timeline.scss
- packages/amis-ui/src/components/WithRemoteConfig.tsx
- packages/amis/src/renderers/Timeline.tsx
> feat：修复timeline组件source变化后视图不更新，调整部分文案

- packages/amis-core/src/actions/Action.ts
- packages/amis-core/src/utils/debug.tsx
- packages/amis-core/src/utils/position.ts
- packages/amis-editor-core/src/component/Preview.tsx
- packages/amis-ui/scss/components/_debug.scss
* 编辑器预览集成 debug 功能
* 点选组件需要通过功能开关开启，开启后点击将阻断点击行为（不会出现即点选inspect，又触发了组件的行为）
* 底部添加表达式运算调试功能，可用于验证 amis 表达式
* 补充更多的日志打点
> chore: debug 面板调整

- packages/amis-editor-core/scss/control/_event-action.scss
- packages/amis-editor/src/plugin/CRUD2/BaseCRUD.tsx
- packages/amis-editor/src/plugin/Collapse.tsx
- packages/amis-editor/src/plugin/Form/Form.tsx
- packages/amis-editor/src/plugin/Form/InputTree.tsx
- packages/amis-editor/src/plugin/Form/TabsTransfer.tsx
- packages/amis-editor/src/plugin/Tabs.tsx
- packages/amis-editor/src/plugin/Wizard.tsx
- packages/amis-editor/src/renderer/event-control/action-config-dialog.tsx
- packages/amis-editor/src/renderer/event-control/actionsPanelPlugins/componentActionsPanel/clear.tsx
- packages/amis-editor/src/renderer/event-control/actionsPanelPlugins/componentActionsPanel/reload.tsx
- packages/amis-editor/src/renderer/event-control/actionsPanelPlugins/componentActionsPanel/reset.tsx
- packages/amis-editor/src/renderer/event-control/actionsPanelPlugins/componentActionsPanel/setValue.tsx
- packages/amis-editor/src/renderer/event-control/actionsPanelPlugins/componentActionsPanel/staticStatus.tsx
- packages/amis-editor/src/renderer/event-control/actionsPanelPlugins/componentActionsPanel/submit.tsx
- packages/amis-editor/src/renderer/event-control/actionsPanelPlugins/componentActionsPanel/usability.tsx
- packages/amis-editor/src/renderer/event-control/actionsPanelPlugins/componentActionsPanel/validate.tsx
- packages/amis-editor/src/renderer/event-control/actionsPanelPlugins/componentActionsPanel/validateFormItem.tsx
- packages/amis-editor/src/renderer/event-control/actionsPanelPlugins/componentActionsPanel/visibility.tsx
- packages/amis-editor/src/renderer/event-control/actionsPanelPlugins/modalActionsPanel/openDialog.tsx
- packages/amis-editor/src/renderer/event-control/actionsPanelPlugins/modalActionsPanel/toast.tsx
- packages/amis-editor/src/renderer/event-control/actionsPanelPlugins/otherActionsPanel/copy.tsx
- packages/amis-editor/src/renderer/event-control/actionsPanelPlugins/pageActionsPanel/goBack.tsx
- packages/amis-editor/src/renderer/event-control/actionsPanelPlugins/pageActionsPanel/refresh.tsx
- packages/amis-editor/src/renderer/event-control/actionsPanelPlugins/pageActionsPanel/url.tsx
- packages/amis-editor/src/renderer/event-control/actionsPanelPlugins/serverActionsPanel/ajax.tsx
- packages/amis-editor/src/renderer/event-control/comp-action-select.tsx
- packages/amis-editor/src/renderer/event-control/helper.tsx
- packages/amis-editor/src/renderer/event-control/index.tsx
> feat:事件动作面板支持查看调用链

- packages/amis/src/minimal.ts
- packages/amis/src/renderers/CRUD2.tsx
> fix: 修复table2卡片模式下 columnToggler 渲染失败的问题,完善移动端特殊case headerToolbar 的吸顶逻辑

- packages/amis-editor-core/scss/editor.scss
- packages/amis-editor/src/tpl/style.tsx
- packages/amis-ui/src/components/MobileDevTool.tsx
* fix: 修复编辑态播放动画后,高亮框错位问题
* chore: 移动端工具初始化时自适应容器大小
> fix: 修复编辑态播放动画后,高亮框错位问题 & 移动端调试工具初始化自适应

- packages/amis-ui/src/components/MobileDevTool.tsx
> chore: 移动端调试工具初始化自适应最大100%

- packages/amis-editor/src/plugin/Form/Transfer.tsx
- packages/amis-editor/src/plugin/Form/TransferPicker.tsx
- packages/amis-ui/src/components/ResultBox.tsx
- packages/amis-ui/src/components/Transfer.tsx
- packages/amis-ui/src/components/TransferPicker.tsx
- packages/amis/src/renderers/Form/Transfer.tsx
- packages/amis/src/renderers/Form/TransferPicker.tsx
> feat: 穿梭选择框增加点击选项事件，面板支持autoCheckChildren和onlyChildren属性配置

- packages/amis/src/renderers/Form/InputImage.tsx
> fix：图片裁剪时优先原格式

- packages/amis-ui/src/components/CityArea.tsx
> fix: 修复inputCity 移动端未处理disabled 的问题

- packages/amis/src/renderers/CRUD2.tsx
递归时，只需要查找 items 和 body 下的 button 个数即可，
避免查到 onEvent 或者 dialog 里面
> feat: 优化crud2组件移动端卡片模式自适应 headToolbar 时统计 button 数量的逻辑

- packages/amis-core/src/utils/helper.ts
- packages/amis-editor/src/plugin/Form/Checkbox.tsx
- packages/amis-editor/src/plugin/Form/Checkboxes.tsx
- packages/amis-editor/src/plugin/Form/Radios.tsx
- packages/amis-editor/src/renderer/style-control/helper.tsx
- packages/amis-editor/src/tpl/style.tsx
- packages/amis-ui/scss/_components.scss
- packages/amis-ui/scss/_functions.scss
- packages/amis-ui/scss/_mixins.scss
- packages/amis-ui/scss/components/form/_checks.scss
- packages/amis-ui/src/components/Checkbox.tsx
- packages/amis-ui/src/components/MobileDevTool.tsx
- packages/amis-ui/src/components/Radios.tsx
- packages/amis/__tests__/renderers/Form/__snapshots__/checkbox.test.tsx.snap
- packages/amis/__tests__/renderers/Form/__snapshots__/checkboxes.test.tsx.snap
- packages/amis/__tests__/renderers/Form/__snapshots__/options.test.tsx.snap
- packages/amis/__tests__/renderers/Form/__snapshots__/radios.test.tsx.snap
- packages/amis/__tests__/renderers/Form/__snapshots__/select.test.tsx.snap
- packages/amis/__tests__/renderers/Form/__snapshots__/tabsTransfer.test.tsx.snap
- packages/amis/__tests__/renderers/Form/__snapshots__/tabsTransferPicker.test.tsx.snap
- packages/amis/__tests__/renderers/Form/__snapshots__/transfer.test.tsx.snap
- packages/amis/__tests__/renderers/Form/checkbox.test.tsx
- packages/amis/__tests__/renderers/Form/checkboxes.test.tsx
- packages/amis/__tests__/renderers/__snapshots__/CRUD.test.tsx.snap
- packages/amis/__tests__/renderers/__snapshots__/Picker.test.tsx.snap
- packages/amis/src/renderers/Form/Checkbox.tsx
- packages/amis/src/renderers/Form/Checkboxes.tsx
- packages/amis/src/renderers/Form/Radios.tsx
> chore: 优化checkbox\radio样式

- packages/amis-core/src/RootRenderer.tsx
- packages/amis-core/src/components/Overlay.tsx
- packages/amis-core/src/factory.tsx
> fix: 修复 Overlay 定位弹出层部分懒加载导致的定位不准的问题

- packages/amis-editor-core/scss/editor.scss
- packages/amis-editor-core/src/component/RegionHLBox.tsx
> style: 调整区域展示样式避免挡住内容

- packages/amis-editor/src/renderer/FormulaControl.tsx
- packages/amis-ui/src/components/CodeMirror.tsx
> fix: 修复编辑器切换面板自动滚动到中间的问题

- packages/amis-editor/src/plugin/Form/InputDate.tsx
- packages/amis-editor/src/plugin/Form/InputDateRange.tsx
- packages/amis-editor/src/tpl/common.tsx
- packages/amis-ui/src/components/DatePicker.tsx
- packages/amis-ui/src/components/DateRangePicker.tsx
- packages/amis/src/renderers/Form/InputDate.tsx
> feat: 日期\日期范围组件可配禁止输入

- packages/amis-core/src/Scoped.tsx
- packages/amis-core/src/actions/CmptAction.ts
- packages/amis/src/renderers/CRUD.tsx
> fix: 修复 crud reload 设置 resetPage=false 无效的问题

- packages/amis-editor/src/tpl/style.tsx
> chore: 优化animations配置警告问题

- packages/amis-core/src/utils/validations.ts
- packages/amis-editor/src/plugin/Form/InputNumber.tsx
- packages/amis-editor/src/plugin/Form/Transfer.tsx
> feat:验证器手机和电话号支持国家代号,数字框新增显示上下按钮，修改自定义样式实现。

- packages/amis-core/src/components/Overlay.tsx
- packages/amis-core/src/components/PopOver.tsx
- packages/amis/__tests__/renderers/Form/__snapshots__/inputCity.test.tsx.snap
- packages/amis/__tests__/renderers/Form/__snapshots__/inputTag.test.tsx.snap
- packages/amis/__tests__/renderers/Form/__snapshots__/repeat.test.tsx.snap
- packages/amis/__tests__/renderers/Form/__snapshots__/select.test.tsx.snap
- packages/amis/__tests__/renderers/Form/__snapshots__/text.test.tsx.snap
- packages/amis/__tests__/renderers/Form/inputTag.test.tsx
- packages/amis/__tests__/renderers/PopOver.test.tsx
- packages/amis/__tests__/renderers/TooltipWrapper.test.tsx
- packages/amis/__tests__/renderers/__snapshots__/Pagination.test.tsx.snap
- packages/amis/__tests__/renderers/__snapshots__/PopOver.test.tsx.snap
- packages/amis/__tests__/renderers/__snapshots__/Tabs.test.tsx.snap
- packages/amis/__tests__/renderers/__snapshots__/TooltipWrapper.test.tsx.snap
> style: 优化 popover 避免位置闪烁

- packages/amis-core/src/index.tsx
> fix: 修复多语言切换未实时同步问题

- docs/zh-CN/components/form/input-table.md
- packages/amis-core/src/store/crud.ts
- packages/amis-core/src/utils/helper.ts
- packages/amis/src/renderers/CRUD.tsx
- packages/amis/src/renderers/Form/InputTable.tsx
> feat: inputTable 支持前端过滤与排序并优化新增节点不可见的问题

- packages/amis-editor-core/scss/control/_event-action.scss
- packages/amis-editor-core/src/component/Editor.tsx
- packages/amis-editor-core/src/plugin.ts
- packages/amis-editor/examples/Editor.tsx
- packages/amis-editor/src/renderer/event-control/helper.tsx
- packages/amis-editor/src/renderer/event-control/index.tsx
- packages/amis-formula/src/doc.ts
> feat: 全局事件动作事件配置面板

- packages/amis-formula/src/doc.ts
> fix: formula doc 文件格式format

- packages/amis-core/__tests__/jest.setup.js
- packages/amis-core/src/SchemaRenderer.tsx
- packages/amis-core/src/actions/BroadcastAction.ts
- packages/amis-core/src/utils/renderer-event.ts
> feat: 支持全局事件动作

- packages/amis-editor/src/renderer/event-control/helper.tsx
> fix: 广播事件绑定this指向

- packages/amis-editor/src/renderer/event-control/actionsPanelManager.ts
- packages/amis-editor/src/renderer/event-control/actionsPanelPlugins/componentActionsPanel/setValue.tsx
> 修复插件重复注册&输入序号支持表达式

- examples/doc.css
> style: 调整 doc 文档样式 Close: #11214

- packages/amis-editor-core/src/plugin.ts
- packages/amis-editor/examples/Editor.tsx
- packages/amis-editor/src/renderer/event-control/helper.tsx
- packages/amis-editor/src/renderer/event-control/index.tsx
> feat: 全局事件动作配置面板

- packages/amis-formula/src/evalutor.ts
> doc: 完善公式文档说明

- docs/zh-CN/components/crud.md
> doc: 补充 CRUD 共用查询条件文档

- packages/amis-core/src/store/crud.ts
- packages/amis-core/src/utils/helper.ts
- packages/amis/src/renderers/CRUD.tsx
> fix: 修复前端一次性加载前端过滤必须配置 matchFunc 的问题

- docs/zh-CN/components/crud.md
- packages/amis-editor/src/plugin/Others/TableCell.tsx
- packages/amis-ui/scss/components/_popoverable.scss
- packages/amis-ui/scss/components/_table.scss
- packages/amis/src/renderers/PopOver.tsx
- packages/amis/src/renderers/Table/TableCell.tsx
> feat: 表格列新增textOverflow属性

- packages/amis-editor/src/renderer/event-control/helper.tsx
> fix: 修复动作配置会删除 preventDefault 属性的问题

- packages/amis/src/renderers/Table/index.tsx
> fix: 修复多个 crud 并列且都开启自动撑开模式时高度计算错误问题 Close: #10981 Close: #11068

- packages/amis-editor/src/renderer/event-control/actionsPanelPlugins/otherActionsPanel/broadcast.tsx
- packages/amis-editor/src/renderer/event-control/actionsPanelPlugins/otherActionsPanel/index.ts
- packages/amis-editor/src/renderer/event-control/eventControlConfigHelper.ts
> fix: 全局广播事件配置面板

- packages/amis-editor/src/plugin/Form/InputTable.tsx
> input-table公式编辑器增加索引数据

- packages/amis-editor/src/plugin/CRUD2/BaseCRUD.tsx
- packages/amis-editor/src/plugin/Collapse.tsx
- packages/amis-editor/src/plugin/Form/InputTree.tsx
- packages/amis-editor/src/plugin/Form/TabsTransfer.tsx
- packages/amis-editor/src/plugin/Tabs.tsx
- packages/amis-editor/src/plugin/Wizard.tsx
- packages/amis-editor/src/renderer/event-control/actionsPanelPlugins/componentActionsPanel/staticStatus.tsx
- packages/amis-editor/src/renderer/event-control/helper.tsx
> fix:修复部分动作无法跳转问题

- packages/amis-editor-core/scss/control/_event-action.scss
> fix:动作调用列表样式优化

- packages/amis-editor/src/renderer/event-control/helper.tsx
> fix:优化调用链锚定提示

- packages/amis-theme-editor-helper/src/renderers/ColorPicker.tsx
> fix: 修复背景图选择参数错误问题

- packages/amis-editor/src/plugin/Form/Combo.tsx
- packages/amis-editor/src/plugin/Form/InputTable.tsx
- packages/amis-editor/src/plugin/Form/InputTree.tsx
- packages/amis-editor/src/plugin/Image.tsx
- packages/amis-editor/src/plugin/Nav.tsx
- packages/amis-editor/src/plugin/OfficeViewer.tsx
- packages/amis-editor/src/plugin/QRCode.tsx
- packages/amis-editor/src/plugin/Service.tsx
- packages/amis-editor/src/plugin/Table.tsx
> fix:补充特性动作的描述

- packages/amis/src/renderers/Action.tsx
> fix: 修复图标可能是组件的情况

- packages/amis-core/src/utils/renderer-event.ts
- packages/amis-editor/src/renderer/event-control/action-config-panel.tsx
- packages/amis-editor/src/renderer/event-control/actionsPanelPlugins/otherActionsPanel/broadcast.tsx
> fix: 全局事件动作避免死锁

- packages/amis-theme-editor-helper/package.json
- packages/amis-theme-editor-helper/rollup.config.js
- packages/amis-ui/scss/components/form/_list.scss
> fix: 修复theme-helper引用报错问题

- packages/amis-editor/src/renderer/event-control/actionsPanelPlugins/componentActionsPanel/setValue.tsx
> fix:变量赋值导致面板挂掉

- packages/amis-core/src/utils/debug.tsx
- packages/amis-core/src/utils/renderer-event.ts
> fix: 修复 debug 日志打印不全的问题

- packages/amis-editor/src/plugin/Form/InputImage.tsx
> feat：图片上传支持压缩质量配置

- packages/amis-editor-core/src/layout/flex.ts
* fix: 修复form flex模式下,往第一个元素上面拖拽添加异常问题
* fix
> fix: 修复form flex模式下,往第一个元素上面拖拽添加异常问题 (#11292)

- packages/amis-editor-core/src/component/Editor.tsx
- packages/amis-editor-core/src/component/base/SchemaForm.tsx
- packages/amis-editor-core/src/store/editor.ts
- packages/amis-editor/src/renderer/event-control/actionsPanelPlugins/otherActionsPanel/broadcast.tsx
- packages/amis-editor/src/renderer/event-control/helper.tsx
- packages/amis-editor/src/renderer/event-control/index.tsx
> fix: 全局广播事件及时更新

- packages/amis/src/renderers/Table/TableBody.tsx
- packages/amis/src/renderers/Table/TableContent.tsx
- packages/amis/src/renderers/Table/TableRow.tsx
- packages/amis/src/renderers/Table/index.tsx
> feat: table组件增加泛型

- packages/amis-core/src/utils/labelToString.ts
> chore: 调整 invalid label 展示, 无数据是展示 -

- packages/amis-core/src/utils/debug.tsx
> chore: debug 面板优化(不要触发其他 modal 的 closeOnOutside & 限制 logs 条数太多了性能不可预期)

- packages/amis-ui/scss/components/form/_list.scss
> style: 修复list选中图标异常问题

- packages/amis/src/renderers/Form/InputTable.tsx
- packages/amis/src/renderers/Table/ColumnToggler.tsx
> feat: input-table、colunmn-toggler组件增加泛型

- packages/amis-ui/src/components/icons.tsx
> fix: 修复icon组件传入部分svg字符串无法显示问题

- packages/amis-ui/scss/_components.scss
- packages/amis-ui/scss/components/form/_checks.scss
> style: 修复checkout单行垂直不对齐问题

- packages/amis-core/src/actions/BroadcastAction.ts
- packages/amis-core/src/utils/renderer-event.ts
> fix: broadcast 触发onBroadcast

- packages/amis-editor/src/renderer/event-control/actionsPanelPlugins/serverActionsPanel/download.tsx
> 修复下载文件apiControl覆盖异常

- packages/amis-editor/src/renderer/style-control/ColSize.tsx
> fix: 修复colsize在inputtable下报错问题

- packages/amis-ui/src/components/NumberInput.tsx
- packages/amis/src/renderers/Form/InputNumber.tsx
> fix: 修复数字框过早进行四舍五入，导致输入状态下自动格式化问题

- packages/amis/__tests__/renderers/__snapshots__/Picker.test.tsx.snap
- packages/amis/src/renderers/Form/Picker.tsx
> fix: 修复picker组件输入框无法foucs的交互

- docs/zh-CN/components/form/location-picker.md
- packages/amis-ui/src/components/BaiduMapPicker.tsx
- packages/amis/src/renderers/Form/LocationPicker.tsx
- packages/amis/src/renderers/Image.tsx
> feat: 地图静态展示支持设置大小

- packages/amis-ui/scss/components/form/_user-select.scss
> fix: 修复css语法错误

- packages/amis-editor/src/plugin/Form/InputTable.tsx
> [fix] inputtable配置面板确认模式关闭后二次打开状态错误的问题

- packages/amis-ui/src/components/PickerColumn.tsx
- packages/amis/src/renderers/Image.tsx
> fix: Image 组件通过css设置transform 属性不生效

- packages/amis/src/renderers/Form/InputTable.tsx
> fix: input-table确认模式下进行新增时，若只配置编辑接口，不配置新增接口，会导致新增确认时调用编辑接口

- docs/zh-CN/components/shape.md
- examples/components/Components.tsx
- packages/amis-ui/scss/components/_shape.scss
- packages/amis-ui/scss/themes/_common.scss
- packages/amis-ui/src/components/Shape.tsx
- packages/amis-ui/src/components/index.tsx
- packages/amis-ui/tsconfig.json
- packages/amis/src/Schema.ts
- packages/amis/src/minimal.ts
- packages/amis/src/renderers/Shape.tsx
> feat: 图形组件

- docs/zh-CN/components/shape.md
- packages/amis-ui/scss/components/_shape.scss
- packages/amis-ui/src/components/Shape.tsx
- packages/amis/src/renderers/Shape.tsx
> feat: 图形组件支持配置宽高、颜色

- packages/amis-editor/src/plugin/Form/InputFile.tsx
> feat: 文件上传组件新增是否开启文件上传路径拼接配置项

- packages/amis/src/renderers/Action.tsx
- packages/amis/src/renderers/Card.tsx
- packages/amis/src/renderers/Cards.tsx
> feat: crud的卡片风格支持行点击，选择表格项，行排序事件

- packages/amis-core/src/SchemaRenderer.tsx
> chore: 修复访问 props key 的 warning 报错

- packages/amis/src/renderers/Table/index.tsx
> chore: Table 调整方便外围覆盖

- docs/zh-CN/components/shape.md
- packages/amis-ui/scss/components/_shape.scss
- packages/amis-ui/src/components/Shape.tsx
- packages/amis/src/renderers/Shape.tsx
> feat: 图形组件支持边框和事件动作

- packages/amis-ui/src/components/MobileDevTool.tsx
> feat: mobileTool支持配置border

- packages/amis-core/src/utils/debug.tsx
- packages/amis-editor/src/plugin/CRUD.tsx
- packages/amis-editor/src/plugin/Table.tsx
- packages/amis/src/renderers/Table/Cell.tsx
- packages/amis/src/renderers/Table/TableRow.tsx
> chore: 补充 CRUD 配置面板

- packages/amis/src/index.tsx
> fix: overrideSupportStatic函数未导出

- packages/amis-ui/scss/components/_table.scss
- packages/amis/src/renderers/Table/index.tsx
帮忙检查一下是否可以合并 ，如果可以合并 再来完善单测和文档
> fix: 添加tableFillHeight属性控制表格高度，避免开启autoFillHeight后表格行高度异常的问题，以便向下兼容Closes #11419

- packages/amis-core/src/index.tsx
- packages/amis-core/src/utils/icon.tsx
- packages/amis-ui/src/components/icons.tsx
- packages/amis/src/index.tsx
- packages/amis/src/renderers/icons/mk.ts
> md合入master

- packages/amis/src/renderers/icons/mk.ts
> fix: 调整icon mk的判断值

- packages/amis/__tests__/renderers/Table/index.test.tsx
- packages/amis/src/renderers/Table/index.tsx
> 补充tableFillHeight文档和单测

- docs/zh-CN/components/table2.md
> 修复 文档错误 Update table2.md

- packages/amis/src/renderers/Table/index.tsx
> feat: TableRendererBase增加泛型

- packages/amis-editor-core/scss/editor.scss
- packages/amis-editor-core/src/component/Editor.tsx
- packages/amis-editor-core/src/component/HighlightBox.tsx
- packages/amis-editor-core/src/component/Preview.tsx
- packages/amis-editor-core/src/inlineEdit.ts
- packages/amis-editor-core/src/manager.ts
- packages/amis-editor-core/src/plugin.ts
- packages/amis-editor-core/src/store/editor.ts
- packages/amis-editor/src/plugin/Button.tsx
- packages/amis-editor/src/plugin/Form/Form.tsx
- packages/amis-editor/src/plugin/Form/Item.tsx
- packages/amis-editor/src/plugin/Page.tsx
- packages/amis-editor/src/plugin/Panel.tsx
- packages/amis-editor/src/plugin/Tpl.tsx
- packages/amis-ui/package.json
- packages/amis-ui/src/components/RichText.tsx
- packages/amis-ui/src/components/Tinymce.tsx
* 支持组件内文本快速编辑（通过双击进入内联编辑状态）
* 支持富文本内联编辑
> feat: amis-editor 支持内联编辑

- packages/amis-core/src/utils/renderer-event.ts
> fix: BroadcastChannel 兼容性问题

- packages/amis-ui/src/components/ContextMenu.tsx
> feat: ContextMenu menuItem 声明

- packages/amis/src/renderers/Tag.tsx
> fix: 修复 tag 渲染对象报错

- packages/amis-ui/scss/_mixins.scss
- packages/amis/__tests__/renderers/__snapshots__/Picker.test.tsx.snap
- packages/amis/src/renderers/CRUD.tsx
- packages/amis/src/renderers/Form/Picker.tsx
> fix:  修复列表选取-单选却可以选中多个，溢出隐藏样式错乱

- packages/amis-ui/scss/components/form/_select.scss
> fix: 修复select下menutpl样式错误问题

- packages/amis-ui/scss/components/form/_select.scss
- packages/amis-ui/src/components/Select.tsx
> style: 优化select下checkbox样式

- packages/amis-editor-core/src/component/HighlightBox.tsx
- packages/amis-editor-core/src/component/Preview.tsx
- packages/amis-editor-core/src/inlineEdit.ts
> fix: 修复编辑器内联编辑在自由容器里面无效的问题

- packages/amis/src/renderers/Carousel.tsx
> feat: 轮播图option 支持 itemSchema

- docs/zh-CN/components/form/input-tree.md
- docs/zh-CN/components/form/treeselect.md
- packages/amis/src/renderers/Form/InputTree.tsx
- packages/amis/src/renderers/Form/TreeSelect.tsx
> fix: tree 节点点击事件获取的值不对

- packages/amis-core/src/components/PopOver.tsx
- packages/amis-ui/scss/components/_context-menu.scss
- packages/amis-ui/scss/components/_dropdown-context-menus.scss
- packages/amis-ui/scss/themes/_common.scss
- packages/amis-ui/src/components/DropdownContextMenus.tsx
- packages/amis-ui/src/components/PopOverContainer.tsx
- packages/amis-ui/src/components/index.tsx
> feat: 新增 dropdown-contextmenus 组件

- packages/amis/src/renderers/Table/index.tsx
> feat: CRUD 的自动撑开功能支持编辑器切换及时生效

- packages/amis-core/src/utils/icon.tsx
- packages/amis-ui/src/components/icons.tsx
> feat: 优化icon组件svg link逻辑

- packages/amis-ui/scss/components/_images.scss
> 修复图片高度塌陷问题

- docs/zh-CN/components/form/input-tree.md
- docs/zh-CN/components/form/treeselect.md
- packages/amis-editor/src/util.ts
- packages/amis/src/renderers/Form/InputTree.tsx
- packages/amis/src/renderers/Form/TreeSelect.tsx
> fix：tree点击事件恢复item

- packages/amis-ui/scss/components/_images.scss
- packages/amis-ui/scss/components/form/_form.scss
- packages/amis-ui/scss/components/form/_image.scss
> style: 优化图片组件样式

- packages/amis-ui/scss/_components.scss
- packages/amis-ui/scss/_properties.scss
> style: 组件文字正常使用text-2

- packages/amis/src/renderers/Cards.tsx
- packages/amis/src/renderers/List.tsx
- packages/amis/src/renderers/Table/index.tsx
> fix: 调整 table 执行 setValue 动作，当在 crud 中时由 crud 完成 setData

- packages/amis-core/src/utils/style-helper.ts
> fix: 修复自定义样式root::after不生效问题

- packages/amis/src/renderers/CRUD.tsx
- packages/amis/src/renderers/Table/index.tsx
> fix: 修复picker双击单选不生效问题

- packages/amis-editor-core/src/component/Preview.tsx
- packages/amis-editor-core/src/store/editor.ts
> fix: 及时销毁 resizeObserver

- packages/amis/src/renderers/CRUD.tsx
> chore: crud filter 是否可使用上层数据优先用 filter 上的配置

- packages/amis/src/renderers/Form/InputTable.tsx
> fix: input-table 子项通过索引更新行数据，自身值未变化

- packages/amis-ui/src/components/icons.tsx
> fix: 修复icon组件vendor报错

- packages/amis-core/src/components/Animations.tsx
- packages/amis-core/src/utils/animations.ts
- packages/amis-editor/src/tpl/style.tsx
- packages/amis-ui/scss/base/_animate.scss
- packages/amis-ui/scss/themes/_common.scss
> feat: 增加hover动效

- packages/amis-ui/scss/components/_dropdown.scss
> fix: 修复dropdown-button浮层存在间距问题

- packages/amis-ui/scss/components/_context-menu.scss
> fix: ContextMenu多余的边框线

- packages/amis-core/src/actions/AjaxAction.ts
- packages/amis-core/src/actions/CmptAction.ts
> fix: 修复 ajax 动作不阻塞后续动作的问题 Close: #11457

- packages/amis-ui/src/components/BaiduMapPicker.tsx
- packages/amis-ui/src/components/LocationPicker.tsx
- packages/amis/src/renderers/Form/LocationPicker.tsx
location picker 增加隐藏控件的参数
地图默认增加控制组件。但是在纯展示情况不需要控件，所以增加参数隐藏
props增加参数
> feat: location picker 增加隐藏控件的参数

- packages/amis-editor-core/src/component/IFramePreview.tsx
- packages/amis-editor-core/src/component/Preview.tsx
- packages/amis-editor-core/src/inlineEdit.ts
> fix: 修复原地编辑操作对象为按钮时会触发点击行为的问题

- packages/amis-core/src/utils/api.ts
> chore: api adaptor 添加一些容错

- packages/amis-formula/__tests__/async-evalute.test.ts
- packages/amis-formula/__tests__/evalute.test.ts
- packages/amis-formula/src/evalutorForAsync.ts
> fix:修复异步表达式ARRAYFINDINDEX&ARRAYFIND单测

- packages/amis-editor/src/plugin/Carousel.tsx
- packages/amis-ui/scss/components/_carousel.scss
- packages/amis/src/renderers/Carousel.tsx
> feat: 扩展轮播图支持自定义容器

- packages/amis-editor/src/plugin/TableCell2.tsx
- packages/amis-ui/scss/components/_popoverable.scss
- packages/amis-ui/scss/components/_table.scss
- packages/amis-ui/src/components/table/Cell.tsx
- packages/amis-ui/src/components/table/Head.tsx
- packages/amis/__tests__/renderers/Form/__snapshots__/inputTable.test.tsx.snap
- packages/amis/src/renderers/PopOver.tsx
- packages/amis/src/renderers/Table/index.tsx
- packages/amis/src/renderers/Table2/index.tsx
> feat: crud、crud2支持表头单独设置样式、溢出隐藏可拖拽

- docs/zh-CN/components/form/input-image.md
- packages/amis-core/src/index.tsx
- packages/amis-core/src/locale.tsx
- packages/amis/src/renderers/Form/InputImage.tsx
> Feat input images my

- packages/amis-ui/scss/_properties.scss
- packages/amis-ui/scss/components/_context-menu.scss
- packages/amis-ui/src/components/ContextMenu.tsx
> feat: contextmenu 样式优化

- packages/amis-core/src/actions/Action.ts
- 新增 ActionIgnoreKey 和 CmptIgnoreMap 两个全局变量，用于存储动作和组件的忽略键
- 新增 registerActionMappingIgnoreKey、registerActionMappingIgnoreMap、registerComponentActionMappingIgnoreKey 和 registerComponentActionMappingIgnoreMap 四个方法，用于注册忽略键
- 重构 runAction 方法，使用新的忽略键逻辑
- 注册默认的忽略键，包括 ajax 动作和一些组件的 condition 属性
- 现在动作的参数映射忽略键是硬编码的，在增加自定义组件、自定义动作时灵活性受限
- 导出注册方法，各个模块可以自行注册忽略键
> feat(action): 导出动作参数映射忽略键注册方法

- packages/amis-core/src/locale.tsx
> Merge feat md 1

- docs/zh-CN/extend/i18n.md
> chore: 更新国际化文档

- packages/amis-ui/src/components/Signature.tsx
> feat: 签名组件全屏模式签名确认后旋转图像

- packages/amis-core/src/store/formItem.ts
> fix: 修复 inputDateRange 的 clear 动作只清除了开始时间的问题

- packages/amis-ui/scss/components/_table2.scss
- packages/amis-ui/src/components/table/Cell.tsx
- packages/amis-ui/src/components/table/Head.tsx
- packages/amis-ui/src/components/table/index.tsx
- packages/amis-ui/src/components/table/util.ts
> feat: crud2中自适应高度使用粘性定位固定表头

- docs/zh-CN/components/form/input-table.md
Correct the errors in the document
> fix: input-table.md

- packages/amis-ui/src/components/table/index.tsx
> fix: crud2设置scrolly或设置sticky+autoFillHeight时自动开启sticky

- packages/amis-editor-core/scss/editor.scss
- packages/amis-editor-core/src/component/HighlightBox.tsx
- packages/amis-editor/src/plugin/Layout/FlexPluginBase.tsx
- packages/amis-editor/src/plugin/Tpl.tsx
- packages/amis/src/renderers/Flex.tsx
> fix: flex容器内的子元素工具栏无拖拽按钮 + 工具栏样式问题

- packages/amis/__tests__/renderers/Form/static.test.tsx
- packages/amis/src/renderers/QuickEdit.tsx
> chore: 表格列即配置静态展示又配置quickEdit 时，优先静态展示

- packages/amis/src/renderers/Form/InputTable.tsx
> fix: 修复表格编辑框-设置静态展示，仍然可以进行编辑

- packages/amis-core/src/store/form.ts
- packages/amis-core/src/store/iRenderer.ts
- packages/amis-core/src/store/table.ts
> chore: 避免重复定义不可修改属性

- packages/amis-core/src/components/CustomStyle.tsx
- packages/amis-core/src/utils/style-helper.ts
> fix: 修复wrapperCustomStyle配置customStyleClassPrefix不生效问题

- packages/amis-editor/src/plugin/Tpl.tsx
- packages/amis-ui/src/components/formula/Editor.tsx
> 修复公式编辑器functions下发异常&公式编辑器扩充异常

- packages/amis-core/src/renderers/wrapControl.tsx
- packages/amis-editor/src/plugin/Form/InputText.tsx
> fix: 修复邮箱格式校验失败

- packages/amis-ui/src/components/Signature.tsx
> fix: 签名组件内嵌模式移动设备下默认全屏

- packages/amis-core/src/utils/helper.ts
- packages/amis-ui/src/components/Signature.tsx
> fix: 修改签名组件移动端全屏的逻辑条件，新增是否是移动端设备的方法

- packages/amis-core/src/renderers/Options.tsx
- packages/amis/src/renderers/Form/ButtonGroupSelect.tsx
- packages/amis/src/renderers/Form/ChainedSelect.tsx
- packages/amis/src/renderers/Form/Checkboxes.tsx
- packages/amis/src/renderers/Form/InputTag.tsx
- packages/amis/src/renderers/Form/InputText.tsx
- packages/amis/src/renderers/Form/InputTree.tsx
- packages/amis/src/renderers/Form/ListSelect.tsx
- packages/amis/src/renderers/Form/NestedSelect.tsx
- packages/amis/src/renderers/Form/Picker.tsx
- packages/amis/src/renderers/Form/Radios.tsx
- packages/amis/src/renderers/Form/Select.tsx
- packages/amis/src/renderers/Form/Transfer.tsx
- packages/amis/src/renderers/Form/TreeSelect.tsx
> feat: 选项类组件刷新支持传参

- packages/amis-editor/src/plugin/CRUD.tsx
> fix: 修复 CRUD 脚手架查询字段不更新的问题

- packages/amis-core/src/renderers/wrapControl.tsx
> chore: 避免表单项默认值关联自己导致无效修改数值的问题

- packages/amis-ui/scss/components/_table.scss
- packages/amis/src/renderers/Table/index.tsx
> style: 调整 crud 的自动高度撑开模式的样式, 去掉多余滚动条

- docs/zh-CN/components/form/input-tree.md
- packages/amis-core/src/utils/dom.tsx
- packages/amis-editor/src/plugin/Form/InputTree.tsx
- packages/amis-ui/src/components/Tree.tsx
- packages/amis/src/renderers/Form/InputTree.tsx
> feat: tree高度支持自适应

- packages/amis-ui/scss/components/_signature.scss
- packages/amis-ui/src/components/Signature.tsx
> fix: 修改签名组件close图标

- packages/amis-editor-core/src/layout/flex.ts
> fix: 修复form flex模式下外围内容拖入报错问题

- packages/amis-core/src/renderers/Form.tsx
- packages/amis-editor-core/scss/editor.scss
- packages/amis-editor-core/src/component/ContainerWrapper.tsx
- packages/amis-editor-core/src/component/Editor.tsx
- packages/amis-editor-core/src/component/HighlightBox.tsx
- packages/amis-editor-core/src/component/Panel/Outline.tsx
- packages/amis-editor-core/src/component/Panel/RenderersPanel.tsx
- packages/amis-editor-core/src/component/Preview.tsx
- packages/amis-editor-core/src/component/RegionHLBox.tsx
- packages/amis-editor-core/src/dnd/default.ts
- packages/amis-editor-core/src/dnd/index.ts
- packages/amis-editor-core/src/dnd/position-h.ts
- packages/amis-editor-core/src/plugin.ts
- packages/amis-editor-core/src/plugin/BasicToolbar.tsx
- packages/amis-editor-core/src/store/editor.ts
- packages/amis-editor/src/plugin/Container.tsx
- packages/amis-editor/src/plugin/Layout/FlexPluginBase.tsx
- packages/amis-ui/scss/components/_page.scss
- packages/amis/src/renderers/Container.tsx
- packages/amis/src/renderers/Grid.tsx
- packages/amis/src/renderers/Panel.tsx
* 调整拖拽为指示器模式
* 去掉拖拽按钮，点选框直接触发拖拽
* 优化部分组件的拖拽细节
> chore: 调整拖拽方案

- docs/zh-CN/components/cards.md
- packages/amis-editor/src/plugin/List2.tsx
- packages/amis-ui/scss/components/_cards.scss
- packages/amis/__tests__/renderers/__snapshots__/CRUD.test.tsx.snap
- packages/amis/__tests__/renderers/__snapshots__/Card.test.tsx.snap
- packages/amis/src/renderers/Cards.tsx
> feat: 扩展cards增加瀑布流展示模式

- packages/amis-editor/src/plugin/Steps.tsx
- packages/amis-editor/src/renderer/style-control/helper.tsx
- packages/amis-ui/scss/components/_steps.scss
- packages/amis-ui/src/components/Steps.tsx
- packages/amis/__tests__/renderers/__snapshots__/Steps.test.tsx.snap
- packages/amis/__tests__/renderers/__snapshots__/Wizard.test.tsx.snap
- packages/amis/src/renderers/Steps.tsx
> steps编辑器外观配置

- docs/zh-CN/components/form/input-signature.md
- packages/amis-ui/src/components/Signature.tsx
- packages/amis-ui/src/locale/de-DE.ts
- packages/amis-ui/src/locale/en-US.ts
- packages/amis-ui/src/locale/zh-CN.ts
- packages/amis/package.json
- packages/amis/src/renderers/Form/InputSignature.tsx
> feat: 签名组件新增上传图片API, 新增file64依赖包

- packages/amis/src/renderers/CRUD.tsx
> chore: 统一crud的 research 事件与 init 事件的参数

- packages/amis-editor-core/src/component/Preview.tsx
> chore: 调整 iframe 位置获取逻辑

- packages/amis-core/src/envOverwrite.ts
- packages/amis-core/src/index.tsx
- packages/amis/src/renderers/CRUD.tsx
- packages/amis/src/renderers/DropDownButton.tsx
- packages/amis/src/renderers/Form/ConditionBuilder.tsx
- packages/amis/src/renderers/Form/LocationPicker.tsx
- packages/amis/src/renderers/Form/MatrixCheckboxes.tsx
> fix: 修复编辑态组件mobile属性渲染错误问题

- docs/zh-CN/components/form/input-signature.md
- packages/amis-core/src/utils/helper.ts
- packages/amis-ui/package.json
- packages/amis-ui/scss/components/_signature.scss
- packages/amis-ui/src/components/Signature.tsx
- packages/amis-ui/src/locale/de-DE.ts
- packages/amis-ui/src/locale/en-US.ts
- packages/amis-ui/src/locale/zh-CN.ts
- packages/amis/package.json
- packages/amis/src/renderers/Form/InputSignature.tsx
> 优化签名组件，签名组件新增上传图片API

- packages/amis/src/renderers/Form/InputTable.tsx
> fix:  修复事件获取的删除元素成员错误的问题

- packages/amis/src/renderers/Form/InputTable.tsx
> fix: inputTable setValue 实现默认是 merge 的模式

- packages/amis/src/renderers/Form/InputTable.tsx
> fix: 修复表格 wizard 2.0 字段新增问题 Close: #11772

- packages/amis-ui/src/components/Tree.tsx
> fix：使用valueField时子节点全选后未勾选父节点

- packages/amis-editor/src/plugin/List2.tsx
- packages/amis/__tests__/renderers/__snapshots__/CRUD.test.tsx.snap
- packages/amis/src/renderers/Cards.tsx
> fix: 消除砖石布局未启用时对移动端的影响

- packages/amis/src/renderers/Form/InputSignature.tsx
> fix: 优化手写签名上传图片拼接字符串的问题

- packages/amis-core/src/store/table.ts
- packages/amis-core/src/store/table2.ts
- packages/amis-core/src/utils/getPageId.ts
> fix: 修复表格的列配置在 hash 路由场景冲突问题

- packages/amis-core/src/store/index.ts
> chore: 调整 store 注册调低内置 store 优先级

- .gitignore
- examples/components/Form/Full.jsx
- packages/amis-ui/src/components/Select.tsx
问题修复：Select组件点击全选按钮，会将被禁用（disabled）的选项选中
处理选中时未过滤禁用的选项
处理选中时过滤禁用的选项
> fix: selector check all filter disabled

- packages/amis-core/src/env.tsx
- packages/amis-core/src/factory.tsx
- packages/amis-core/src/store/table.ts
- packages/amis-core/src/store/table2.ts
> feat: 新增 env.getPageId 用于定义页面唯一标识用于本地存储表格列点选记录

- packages/amis/src/renderers/CRUD.tsx
> fix: 修复 picker 在弹窗模式分页选择点选丢失问题

- docs/zh-CN/components/chart.md
- packages/amis/src/renderers/Chart.tsx
新增`charts` finished 事件，以方便调用`echarts`实例方法和属性。
> feat: add chart finished

- packages/amis/src/renderers/Table/TableBody.tsx
> fix: 列过多且存在右侧固定列时总结行不生效

- packages/amis-ui/scss/components/_crud2.scss
- packages/amis/src/renderers/PopOver.tsx
> fix: 修复crud点击行会跳出个error,修复crud2多选后样式无效的问题

- packages/amis-core/src/utils/debug.tsx
> fix: 修复 debug 开启后出现 Maximum call stack size exceeded 的问题

- packages/amis-core/src/actions/Action.ts
- packages/amis-core/src/actions/CmptAction.ts
> fix: 事件动作触发失败

- packages/amis-ui/src/components/Tree.tsx
> fix: tree虚拟列表高度未重新计算

- packages/amis-ui/scss/components/_popoverable.scss
- packages/amis/src/renderers/Table/TableCell.tsx
> fix: 表格编辑框-可复制按钮、快速编辑按钮等在非确认模式下换行

- eslint.config.mjs
- packages/amis-editor/src/renderer/event-control/helper.tsx
> 修复旧版事件动作异常

- packages/amis-editor-core/src/dnd/autoScroll.ts
- packages/amis-editor-core/src/dnd/default.ts
- packages/amis-editor-core/src/dnd/flex.ts
- packages/amis-editor-core/src/dnd/position-h.ts
> feat: 编辑拖拽组件支持容器自动滚动

- packages/amis/__tests__/event-action/renderers/__snapshots__/crud.test.tsx.snap
- packages/amis/__tests__/renderers/Form/__snapshots__/inputTable.test.tsx.snap
- packages/amis/__tests__/renderers/__snapshots__/CRUD.test.tsx.snap
- packages/amis/__tests__/renderers/__snapshots__/Pagination.test.tsx.snap
- packages/amis/__tests__/renderers/__snapshots__/Table.test.tsx.snap
- packages/amis/src/renderers/Table/ColGroup.tsx
> fix: crud双table情况下网格未对齐

- packages/amis-editor-core/src/component/IFramePreview.tsx
> fix: 修复移动端可能拖入不了组件的问题

- packages/amis/__tests__/event-action/renderers/__snapshots__/crud.test.tsx.snap
- packages/amis/__tests__/renderers/Form/__snapshots__/inputTable.test.tsx.snap
- packages/amis/__tests__/renderers/__snapshots__/CRUD.test.tsx.snap
- packages/amis/__tests__/renderers/__snapshots__/Pagination.test.tsx.snap
- packages/amis/__tests__/renderers/__snapshots__/Table.test.tsx.snap
- packages/amis/src/renderers/Table/ColGroup.tsx
> revert: 回滚fix:crud双table情况下网格未对齐

- packages/amis-ui/scss/components/form/_form.scss
> fix: 修复弹窗中 form 可能内容超出弹窗的问题

- packages/amis-editor-core/src/component/IFramePreview.tsx
- packages/amis-editor-core/src/component/NodeWrapper.tsx
- packages/amis-editor-core/src/component/Preview.tsx
- packages/amis-editor-core/src/component/SchemaRenderer.tsx
> fix: 修复组件被事件动作隐藏后无法编辑的问题

- packages/amis/src/renderers/Form/InputTable.tsx
> fix: 删除元素错误优先用接口返回的错误信息

- packages/amis/src/renderers/Form/InputImage.tsx
> fix: 修复 inputImage 从字符串回显时自动填充文件名逻辑空值的问题

- packages/amis-editor/src/plugin/Form/Form.tsx
form组件的场景，在错误的feat配置时显示错误，手动切换为正确的feat会导致接口数据丢失，如数据实际配置了initApi和api，但feat是Insert，手动切换为编辑时，接口会被清空
1. 每次change把数据清空了，该逻辑在api场景下有问题
2. 初始化的时候以feat数据为准，但应该以api配置数据为准
修改以上两处内容
> [fix] form组件的默认场景选择,在初始化加载schema时纠正一次

- packages/amis-ui/scss/components/_crud2.scss
- packages/amis/src/renderers/PopOver.tsx
> fix: 修复crud点击行会跳出个error,修复crud2多选后样式无效的问题 (#11807)

- packages/amis/src/renderers/Form/InputTable.tsx
- packages/amis/src/renderers/Table/index.tsx
> fix: 修复 inputTable 合并单元格模式编辑态异常问题

- packages/amis-core/src/renderers/wrapControl.tsx
> fix: 修复编辑器模式下 CRUD 会触发列保存的问题

- packages/amis-editor/src/renderer/event-control/action-config-panel.tsx
> feat: 动作面板schema配置支持函数

- packages/amis-core/src/store/table.ts
> fix: 双table边框无法对齐

- packages/amis-core/src/store/table.ts
> fix: 修复 crud 通过事件动作新增行无法选中问题

- packages/amis-core/src/Scoped.tsx
- packages/amis-core/src/StatusScoped.tsx
- packages/amis-core/src/WithRootStore.tsx
- packages/amis-core/src/WithStore.tsx
- packages/amis-core/src/env.tsx
- packages/amis-core/src/locale.tsx
- packages/amis-core/src/renderers/Item.tsx
- packages/amis-core/src/renderers/Options.tsx
- packages/amis-core/src/theme.tsx
- packages/amis-editor-core/src/component/factory.tsx
- packages/amis-ui/src/components/Badge.tsx
- packages/amis-ui/src/components/Picker.tsx
- packages/amis-ui/src/components/PickerColumn.tsx
- packages/amis-ui/src/components/SelectMobile.tsx
- packages/amis-ui/src/components/WithRemoteConfig.tsx
- packages/amis-ui/src/components/WithStore.tsx
- packages/amis/__tests__/renderers/Form/__snapshots__/select.test.tsx.snap
- packages/amis/src/renderers/Form/Editor.tsx
> feat: 移动端单选select支持搜索

- packages/amis/src/renderers/CRUD2.tsx
> feat: crud2支持泛型，方便外围继承

- packages/amis-editor/src/renderer/event-control/helper.tsx
input-table组件特定动作setValue的配置面板 行序号指定支持表达式输入
> fix[editor]: input-table组件特定动作setValue的配置面板 行序号指定支持表达式输入

- packages/amis-editor/src/plugin/CRUD2/constants.ts
> feat: crud2的构建builder支持数据导出配置

- packages/amis-editor/src/renderer/event-control/action-config-panel.tsx
> feat: 动作面板schema配置支持函数 (#11884)

- packages/amis-editor/src/plugin/CRUD2/constants.ts
> feat: crud2的构建builder支持数据导出配置 (#11908)

- examples/components/CRUD/TableAutoFill.jsx
- packages/amis-core/src/store/table.ts
- packages/amis-ui/scss/components/_table.scss
- packages/amis/src/renderers/Table/TableBody.tsx
- packages/amis/src/renderers/Table/TableRow.tsx
- packages/amis/src/renderers/Table/VCell.tsx
- packages/amis/src/renderers/Table/VirtualTableBody.tsx
- packages/amis/src/renderers/Table/index.tsx
> feat: Table 优化大数据性能

- packages/amis-core/src/store/iRenderer.ts
> fix: form 里面的弹窗执行 form 事件动作后数据丢失的问题

- packages/amis/src/renderers/Table/TableBody.tsx
> fix: table开启选择时总结行报错

- packages/amis/src/renderers/Form/Combo.tsx
> fix: input-kv 新增多条后在添加数据 数据域的数据无变化

- packages/amis-editor/src/plugin/Carousel.tsx
- packages/amis/src/renderers/Carousel.tsx
> fix: 修改轮播图配置左右翻页图标的配置及渲染方式

- packages/amis-core/src/utils/normalizeOptions.ts
- packages/amis-editor/src/plugin/Carousel.tsx
- packages/amis/src/renderers/Carousel.tsx
- packages/amis/src/renderers/Form/Combo.tsx
> 340 6.12.0

- packages/amis/src/renderers/Table2/index.tsx
> fix: crud2的使用文字组件时td里面多了一个td

- packages/amis-editor/src/builder/ApiDSBuilder.ts
- packages/amis-editor/src/builder/DSBuilder.ts
- packages/amis-editor/src/builder/constants.ts
- packages/amis-editor/src/builder/type.ts
- packages/amis-editor/src/renderer/crud2-control/CRUDToolbarControl.tsx
> feat: CRUD2支持数据导出功能

- packages/amis-core/src/RootRenderer.tsx
- packages/amis-core/src/SchemaRenderer.tsx
- packages/amis-core/src/store/root.ts
> chore: 全局变量支持之前的 __page 和 appVariables 变量

- packages/amis-core/src/store/table.ts
- packages/amis-core/src/utils/isPureVariable.ts
- packages/amis-core/src/utils/tpl.ts
- packages/amis-ui/scss/components/_table.scss
- packages/amis/src/renderers/Table/TableBody.tsx
- packages/amis/src/renderers/Table/TableContent.tsx
- packages/amis/src/renderers/Table/TableRow.tsx
- packages/amis/src/renderers/Table/VCell.tsx
- packages/amis/src/renderers/Table/VirtualTableBody.tsx
- packages/amis/src/renderers/Table/index.tsx
> feat: table 支持虚拟滚动

- packages/amis-editor-core/src/plugin.ts
> fix: 修复渲染改异步后text组件的配置面板丢失问题

- packages/amis-editor/src/plugin/CRUD2/BaseCRUD.tsx
- packages/amis-editor/src/plugin/Table.tsx
- packages/amis-editor/src/renderer/MapSourceControl.tsx
- packages/amis-editor/src/renderer/NavSourceControl.tsx
> fix: 补充项目缺失的国际化配置项

- packages/amis-core/src/SchemaRenderer.tsx
- packages/amis-core/src/utils/style.ts
> fix: 修复组件内部下发的 style 属性丢失问题

- packages/amis-core/src/store/table.ts
- packages/amis-ui/scss/components/_table.scss
- packages/amis/src/renderers/Table/TableContent.tsx
- packages/amis/src/renderers/Table/VirtualTableBody.tsx
> chore: 虚拟滚动自动切成 fixed table layout

- packages/amis/package.json
> fix: qrcode-react-next

- packages/amis-core/src/store/root.ts
> fix: 修复历史 __page appVariables 全局变量修改视图不更新问题

- packages/amis-ui/src/components/table/util.ts
> optimize: 优化crud2固定列的渲染性能，减少不必要的回流

- packages/amis/src/renderers/CRUD.tsx
> fix: 修复 bulkActions 里面非直接用按钮场景出现多次确认按钮问题

- packages/amis/src/renderers/PopOver.tsx
> Revert "fix: 当表格列配置溢出显示 mapping等类型列显示出原始数据"

- packages/amis-core/src/store/crud.ts
- packages/amis/src/renderers/CRUD.tsx
- packages/amis/src/renderers/Table/Cell.tsx
- packages/amis/src/renderers/Table/index.tsx
> feat: CRUD 的 table index 支持传入 offset

- packages/amis-editor-core/scss/editor.scss
- packages/amis-editor-core/src/component/IFramePreview.tsx
> fix: 修复 h5 编辑器内容撑开后删除元素不能恢复的问题

- packages/amis/src/renderers/Form/Select.tsx
> fix: 修复 autoComplete 初始化可能不请求的问题

- packages/amis/src/renderers/Table/TableBody.tsx
> chore: 调整总结行不占用功能列

- packages/amis-core/src/renderers/Form.tsx
- packages/amis/__tests__/renderers/Form/__snapshots__/radios.test.tsx.snap
> fix: 修复 form 元素初始化有可能不调用接口的问题

- packages/amis/src/renderers/Table/Cell.tsx
更新crud组件 onCheck 回调函数让crud及table组件复选框以支持 shift 键+点击 实现批量选中状态
> fix: 更新crud组件 onCheck 回调函数让crud及table组件复选框以支持 shift 键+点击 实现批量选中状态

- packages/amis-ui/scss/components/form/_icon-picker.scss
- packages/amis/src/renderers/Form/IconPicker.tsx
> feat: 图标选择组件支持更多格式图标

- packages/amis/__tests__/renderers/Form/iconPicker.test.tsx
> 修改iconPicker单测

- packages/amis-editor/src/plugin/Wizard.tsx
> fix: 修复向导组件新增步骤后不支持添加新组件问题

- packages/amis/__tests__/renderers/__snapshots__/Tasks.test.tsx.snap
- packages/amis/src/renderers/Tasks.tsx
> fix: 修复 tasks 组件按钮禁用失效问题

- packages/amis-ui/src/components/table/index.tsx
>  chore: 调整只有 scroll 模式才走 renderScrollTable 模式

- packages/amis/src/renderers/List.tsx
> feat: 优化list组件索引条实现

- packages/amis-editor/src/plugin/Images.tsx
- packages/amis/src/renderers/Form/InputTree.tsx
> fix: 修复树组件静态模式报错问题

- docs/zh-CN/components/form/input-tree.md
- packages/amis-ui/scss/components/form/_tree.scss
- packages/amis-ui/src/components/AssociatedSelection.tsx
- packages/amis-ui/src/components/ResultTreeList.tsx
- packages/amis-ui/src/components/TabsTransfer.tsx
- packages/amis-ui/src/components/Transfer.tsx
- packages/amis-ui/src/components/Tree.tsx
- packages/amis/__tests__/renderers/Form/__snapshots__/tabsTransfer.test.tsx.snap
- packages/amis/__tests__/renderers/Form/__snapshots__/tabsTransferPicker.test.tsx.snap
- packages/amis/__tests__/renderers/__snapshots__/Tree.test.tsx.snap
- packages/amis/src/renderers/Form/InputTree.tsx
- packages/amis/src/renderers/Form/TreeSelect.tsx
> fix: 修复 inputTree 样式问题, 调整虚拟滚动依赖itemHeight配置问题

- packages/amis/src/renderers/Form/StaticHoc.tsx
> feat: 选项类(options) 表单项静态展示时上下文下发 selectedItems

- packages/amis-core/src/utils/date.ts
- packages/amis-ui/src/components/DateRangePicker.tsx
- packages/amis/__tests__/renderers/Form/inputMonth.test.tsx
> fix: 修复 inputQuarterRange 选择 Q2 会被转成 Q1 的问题

- packages/amis/src/renderers/Cards.tsx
- packages/amis/src/renderers/List.tsx
- packages/amis/src/renderers/Table2/index.tsx
> fix: 修复 crud2 在某种情况下编辑器模式列不可点的问题

- packages/amis-ui/scss/_components.scss
- packages/amis-ui/scss/components/_result-box.scss
- packages/amis-ui/scss/components/form/_select.scss
- packages/amis-ui/scss/components/form/_selection.scss
- packages/amis-ui/src/components/Select.tsx
> style: 微调 select 样式

- docs/zh-CN/components/form/index.md
- packages/amis-core/src/renderers/Form.tsx
- packages/amis-editor/src/plugin/Form/Form.tsx
> feat: Form 组件支持 initApiFinished 事件区分与 inited 事件 只有配置了 initApi 且接口正常请求后触发

- packages/amis/src/renderers/Table/TableBody.tsx
- packages/amis/src/renderers/Table/VirtualTableBody.tsx
修复虚拟列表在不使用默认主题时的空异常
因为代码里写死了使用cxd-
改成取当前主题的前缀
> 修复虚拟列表在不使用默认主题时的空异常

- packages/amis-core/src/store/root.ts
- packages/amis-editor-core/scss/editor.scss
- packages/amis-editor-core/src/component/HighlightBox.tsx
- packages/amis-editor-core/src/manager.ts
- packages/amis-editor/src/plugin/Collapse.tsx
- packages/amis-editor/src/plugin/CollapseGroup.tsx
> fix: 修复折叠面板样式问题 & 支持折叠面板内容面板切换

- packages/amis-editor/src/renderer/global-var-control/GlobalVarBuiltinPanel.tsx
- packages/amis-editor/src/renderer/global-var-control/GlobalVarManagerPanel.tsx
- packages/amis-editor/src/renderer/global-var-control/index.tsx
> chore: 全局变量支持外围修改内置控件

- packages/amis-ui/scss/components/_condition-builder.scss
- packages/amis-ui/src/components/condition-builder/Value.tsx
> chore: 条件组合数字输入默认改成2个小数点

- packages/amis/src/renderers/CRUD.tsx
> fix: 修复 picker 选项模式分页失效问题

- packages/amis-ui/scss/components/_cascader.scss
- packages/amis-ui/scss/components/form/_nested-select.scss
> style: 优化 nested-select 移动端样式

- packages/amis/src/renderers/Form/InputExcel.tsx
> fix: 修复 inputExcel 单选不能重复选择的问题

- packages/amis-editor/src/plugin/Image.tsx
> fix: image组件图标组件切换

- packages/amis-core/src/actions/Action.ts
- packages/amis-core/src/actions/CmptAction.ts
> chore: 容忍 cmptAction 未找到组件

- packages/amis/src/renderers/Date.tsx
> Revert "fix: 修复Date在极端情况下渲染错误的问题"

- packages/amis-core/src/utils/date.ts
- packages/amis-core/src/utils/resolveVariableAndFilter.ts
- packages/amis-ui/src/components/calendar/DaysView.tsx
> fix: 修复 maxDate minDate 格式解析错误

- packages/amis-core/src/renderers/Form.tsx
- packages/amis/src/renderers/Tabs.tsx
> chore: 稀释校验错误跳转, 多表单项校验出错时只执行一次跳转

- packages/amis-editor/src/plugin/Table.tsx
- packages/amis-editor/src/plugin/Table2.tsx
> chore: amis-editor 表格新增虚拟滚动阈值配置

- packages/amis-core/src/index.tsx
- packages/amis-core/src/utils/index.ts
- packages/amis-editor/src/plugin/Dialog.tsx
- packages/amis-editor/src/plugin/Form/InputTree.tsx
- packages/amis-editor/src/plugin/Others/TableCell.tsx
- packages/amis-editor/src/tpl/layout.tsx
- packages/amis-editor/src/tpl/style.tsx
- packages/amis-ui/examples/App.tsx
- packages/amis-ui/examples/form/MixedInput.tsx
- packages/amis-ui/scss/_properties.scss
- packages/amis-ui/scss/components/form/_input-group.scss
- packages/amis-ui/src/components/MixedInput.tsx
- packages/amis-ui/src/components/condition-builder/Value.tsx
- packages/amis-ui/src/components/condition-builder/types.ts
- packages/amis-ui/src/components/index.tsx
> feat: 编辑器外观宽高设置支持配置 css 表达式

- packages/amis-editor-core/scss/_rightPanel.scss
- packages/amis-editor-core/scss/control/_event-action.scss
- packages/amis-editor/src/plugin/Button.tsx
> style: 调整事件面板解决按钮重叠

- packages/amis-core/src/utils/tpl-builtin.ts
> fix: 修复 resolveVariableAndFilter 被 tree-shaking 的问题

- packages/amis-editor-core/src/component/factory.tsx
- packages/amis-editor-core/src/plugin.ts
- packages/amis-editor/src/plugin/CRUD.tsx
- packages/amis-editor/src/plugin/Collapse.tsx
- packages/amis-editor/src/plugin/CollapseGroup.tsx
- packages/amis-editor/src/plugin/Container.tsx
- packages/amis-editor/src/plugin/Each.tsx
- packages/amis-editor/src/plugin/Form/FieldSet.tsx
- packages/amis-editor/src/plugin/Form/Form.tsx
- packages/amis-editor/src/plugin/Grid.tsx
- packages/amis-editor/src/plugin/HBox.tsx
- packages/amis-editor/src/plugin/Layout/FlexPluginBase.tsx
- packages/amis-editor/src/plugin/List.tsx
- packages/amis-editor/src/plugin/List2.tsx
- packages/amis-editor/src/plugin/Panel.tsx
- packages/amis-editor/src/plugin/Service.tsx
- packages/amis-editor/src/plugin/Table.tsx
- packages/amis-editor/src/plugin/Table2.tsx
- packages/amis-editor/src/plugin/TableView.tsx
- packages/amis-editor/src/plugin/Tabs.tsx
- packages/amis-editor/src/plugin/Wizard.tsx
> chore: 编辑模式开始懒加载解决大页面编辑性能问题

- packages/amis-editor-core/src/component/HighlightBox.tsx
- packages/amis-ui/src/components/ContextMenu.tsx
> fix: 修复编辑器部分场景出现组件替换报错问题

- packages/amis-ui/src/components/Tree.tsx
> fix: 修复 treeSelect 卡死问题

- packages/amis/src/minimal.ts
> fix: 修复 input-table 表单项加载之前渲染可能存在表单项无法识别而渲染错误问题

- packages/amis-ui/src/components/formula/Editor.tsx
- packages/amis-ui/src/components/formula/FuncList.tsx
> fix: 修复公式函数合并与搜素问题

- mock/cfc/mock/template/getCurrentDate.js
- mock/cfc/mock/template/testResult.js
> 添加组件模版mock数据

- packages/amis-core/src/RootRenderer.tsx
> fix: 修复全局变量初始化异常

- packages/amis/src/renderers/Table/exportExcel.ts
> fix:导出excel为文件流时不做后续操作

- packages/amis-core/src/store/iRenderer.ts
- packages/amis-core/src/store/root.ts
- packages/amis-core/src/utils/helper.ts
- packages/amis/src/renderers/Table/exportExcel.ts
> fix: 修复在配置了数据映射的弹窗中使用全局变量无效的问题

- packages/amis/src/renderers/Table/Cell.tsx
> fix: 修复 table 列冻结在修改列显示与否后失效问题

- packages/amis/src/renderers/CRUD.tsx
> fix: 修复 crud 的 itemActions 不支持新版 onEvent 写法问题

- docs/zh-CN/components/form/input-table.md
- packages/amis/src/renderers/Form/InputTable.tsx
> feat: inputTable 支持控制哪行具备新增能力、编辑、删除功能等

- packages/amis-ui/src/components/table/index.tsx
> fix: 修复 table2 拖拽功能可能不初始化的问题

- packages/amis-editor/src/plugin/Card.tsx
- packages/amis-editor/src/plugin/ListItem.tsx
- packages/amis/src/renderers/Card.tsx
- packages/amis/src/renderers/Grid.tsx
- packages/amis/src/renderers/HBox.tsx
- packages/amis/src/renderers/List.tsx
- packages/amis/src/renderers/TableView.tsx
> fix: 修复 card 组合适用 grid,hbox 报错问题

- packages/amis/src/renderers/Form/InputFile.tsx
- packages/amis/src/renderers/Form/InputRichText.tsx
> feat: inputRichText 支持文件上传

- packages/amis-core/src/store/table.ts
- packages/amis/src/renderers/Table/VirtualTableBody.tsx
> fix: 修复虚拟表格行高不等导致的一直闪烁的问题, 以及优化合并单元格场景

- docs/zh-CN/components/form/condition-builder.md
- packages/amis-core/src/SchemaRenderer.tsx
- packages/amis-core/src/utils/index.ts
- packages/amis-ui/src/components/condition-builder/Group.tsx
- packages/amis-ui/src/components/condition-builder/GroupOrItem.tsx
- packages/amis-ui/src/components/condition-builder/index.tsx
- packages/amis-ui/src/components/formula/Input.tsx
- packages/amis/src/renderers/Form/ConditionBuilder.tsx
> chore: condition-builder 支持 uniqueFields 配置

- packages/amis-ui/scss/components/_table2.scss
- packages/amis-ui/src/components/table/ColGroup.tsx
- packages/amis-ui/src/components/table/index.tsx
> fix: 修复 crud2 的超级表头搭配scrollY时列框无法自动展开问题

- packages/amis-ui/src/components/Tree.tsx
> fix: 修复 tree 的展开收起在重新点选后重置的问题

- packages/amis-core/src/utils/helper.ts
- packages/amis-ui/src/components/Tree.tsx
- packages/amis/src/renderers/Form/InputTree.tsx
> fix: 修复 tree 的展开收起动作不符合预期问题

- packages/amis-ui/src/components/Tree.tsx
> fix: 修复 tree 虚拟滚动默认选中失效问题

- packages/amis-editor-core/scss/_outline.scss
- packages/amis-editor-core/scss/control/_event-action.scss
- packages/amis-editor-core/src/component/Panel/DialogList.tsx
- packages/amis-editor-core/src/store/editor.ts
- packages/amis-editor-core/src/util.ts
> feat: 编辑器展示未引用公共弹窗&修复弹窗可能会重复一份的问题

- packages/amis-formula/src/evalutor.ts
修复 https://github.com/baidu/amis/issues/12232
> fix: 修复amis表达式FLOOR计算错误 Close: #12232

- packages/amis/src/renderers/CRUD2.tsx
> fix: 修复crud2 首次切换列显示与否无效
