baidu/amis

src/components/TooltipWrapper.tsx
src/renderers/Remark.tsx

handleShow里还是去掉delay了，感觉可能没这个场景

remark补充下delay配置项

---

src/store/combo.ts
src/store/form.ts
src/store/formItem.ts
src/store/iRenderer.ts
src/store/list.ts

optimization， remove unused variable

fix: remove unused variable

---

.prettierrc
docs/getting_started.md
package.json

add formatting tool prettier, multi-person collaboration is more friendly😊

cli: add formatting tool prettier

---

docs/renderers.md
examples/components/App.jsx
examples/components/Audio.jsx
scss/components/_audio.scss
src/renderers/Audio.tsx

1. 增加`audio` 示例
2. 修复无`src`时组件也显示，所有操作不可点击
3. 增加无进度时，进度隐藏，原有布局优化

增加 audio 示例

---

docs/renderers/Number.md
docs/renderers/Service.md
src/renderers/Form/Number.tsx
src/renderers/Service.tsx

Number的min和max支持filter、service支持配置messages

---

src/renderers/CRUD.tsx
src/renderers/Form/Picker.tsx
src/renderers/Table.tsx
src/utils/validations.ts

 Picker添加embed配置项

---

__tests__/renderers/Form/__snapshots__/tabs.test.tsx.snap
scss/components/form/_nested-select.scss
src/renderers/Form/NestedSelect.tsx
src/renderers/Tabs.tsx

1. tabs修改id方式
2. nested-select 修改箭头

tabs修改id方式

---

examples/components/CRUD/Table.jsx
src/components/PopOver.tsx
src/renderers/PopOver.tsx

popOver支持offset

---

__tests__/__snapshots__/factory.test.tsx.snap
__tests__/factory.test.tsx
docs/renderers.md
docs/renderers/CRUD.md
docs/renderers/Definitions.md
docs/renderers/Table.md
examples/components/App.jsx
examples/components/Doc.jsx
examples/components/Form/Definitions.jsx
src/factory.tsx

1. 优化definitions，获取到value
3. 增加definitions的测试用例
2. 增加全局错误异常处理，修复与接口数据不一致导致的白屏，以及路径过长导致的白屏等错误抛出

优化definitions,增加全局错误异常处理

---

docs/renderers/Form/City.md
docs/renderers/Form/Input-Group.md
examples/components/Doc.jsx
scss/_variables.scss
scss/components/_audio.scss
scss/components/_drawer.scss
src/renderers/Drawer.tsx

1. 优化 `Drawer`错误提示
2. 优化 `Audio `进度条最小宽度
3. 增加 `InputGroup` 文档

优化drawer错误提示

---

scss/components/_table.scss
src/components/Radios.tsx
src/components/Select.tsx
src/renderers/Carousel.tsx
src/renderers/Form/ButtonGroup.tsx
src/renderers/Form/Checkboxes.tsx
src/renderers/Form/List.tsx
src/renderers/Form/NestedSelect.tsx
src/renderers/Form/Picker.tsx
src/renderers/Form/Radios.tsx
src/renderers/Form/Select.tsx

1. 增加autoFill功能
2. 修复 matrix 不在可视范围内的选项滑动到可视范围后点击选中导致白屏问题

增加autoFill功能

---

src/renderers/Table.tsx

filterable.source ctx问题

---

.prettierrc
examples/components/App.jsx
examples/index.html
scss/_variables.scss
scss/components/_panel.scss
scss/components/_popover.scss
scss/components/_tabs.scss
scss/components/_tooltip.scss
scss/components/_wizard.scss
scss/components/form/_checks.scss
scss/components/form/_date.scss
scss/components/form/_fieldset.scss
scss/components/form/_number.scss
scss/components/form/_rating.scss
scss/components/form/_rich-text.scss
scss/components/form/_textarea.scss
scss/components/form/_tree-select.scss
scss/layout/_aside.scss
scss/themes/dark.scss
src/components/Editor.tsx
src/index.tsx
src/renderers/Form/Editor.tsx
src/renderers/Json.tsx
src/themes/dark.ts

新增 dark 主题

---

src/components/DatePicker.tsx
src/components/Tabs.tsx

日期控件新增任意天数/周数/月数/季度数之前或之后显示时间

---

src/renderers/Form/SubForm.tsx
src/renderers/IFrame.tsx

1. iframe支持reload
2. subform支持btnLabel自定义

iframe支持reload

---

examples/components/CRUD/Table.jsx
src/renderers/Link.tsx

link支持自定义a标签的target

---

docs/renderers.md
docs/renderers/Form/Tag.md
examples/components/Doc.jsx
examples/components/Form/Full.jsx
src/components/Tree.tsx

1. tree选项disabled时不允许添加编辑和删除
2. 增加 tag 文档

tree选项disabled时不允许添加编辑和删除

---

scss/components/_tabs.scss
src/store/table.ts

1. tabs 的 links模式，最后一列的a元素的 margin 设置为 0
2. crud嵌套模式修复子数据修改后，子数据加入修改数据中

crud嵌套模式子数据修改后，子数据加入修改数据中

---

examples/components/SchemaRender.jsx

example fecher headers fix

---

scss/components/_table.scss
src/renderers/Table.tsx

相关 issues: [#386](https://github.com/baidu/amis/issues/386)

table的列标题支持tpl渲染

---

docs/renderers/CRUD.md
src/renderers/CRUD.tsx
src/store/crud.ts

在开启loadDataOnce时，filter时是否去重新请求api
看下属性名是否合理，清晰

add loadDataOnceFetchOnFilter

---

src/components/Toast.tsx

fix toast classnames

---

src/renderers/CRUD.tsx
src/store/crud.ts

修复loadDataOnceFetchOnFilter为false时无法触发reload

---

src/components/Tree.tsx
src/renderers/Form/Options.tsx
src/renderers/Form/Tree.tsx

tree中操作tip可自定义、操作限制优化

---

docs/renderers/Form/Tree.md
src/components/Tree.tsx
src/renderers/Form/Tree.tsx

就是补了个文档 + 换了个配置名
底下一大块diff是因为`formatOnSave`了

补了点文档、还有小修改

---

src/renderers/Form/Service.tsx

位于这样层级的service不应该去找form下那个service，所以优化下form下service的命中规则

form下service正则优化

---

src/utils/validations.ts

兼容下面这种用法：
```
validations: {
matchRegexp:'matchRegexp:/xxxxxx/'
}
```

正则验证添加特殊判断

---

scss/components/_drawer.scss
src/components/Drawer.tsx
src/renderers/Drawer.tsx

drawer overlay逻辑优化

---

docs/renderers/Form/Tag.md
examples/components/Form/Full.jsx
scss/components/_list-menu.scss
scss/components/form/_tag.scss
src/renderers/Form/Tag.tsx
src/renderers/Service.tsx

store 改成默认只有 form 从父级 store 自动向下同步后，Service 内部的 ajax 请求没办法更新数据了，原因是，sevice 自己没有处理 ajax 请求，而是上层比如说 page 处理的，上层处理后，store 数据变了，但是没有往下自动更新 store 了，所以改成 serivce 自己处理 ajax，这样数据就是在 service 这一层。

Service store 数据不同步问题修复

---

src/renderers/CRUD.tsx

CRUDProps export

---

src/renderers/Remark.tsx
src/utils/validations.ts

这种格式的就进不去验证了
```
validations: {
xxxxxx: 0
}
```
比较简单，看代码吧

remark classname调整下、验证问题修复

---

src/factory.tsx

哪些情况会导致渲染崩掉？
一
render(
{
...
hidden: 'anything not falsy'
},
props,
env,
pathPrefix?
)
render(
{
...
visible:  false
},
props,
env,
pathPrefix?
)
二
render(
schema,
{
...
hidden: 'anything not falsy'
},
env,
pathPrefix?
)
render(
schema,
{
...
visible:  false
},
env,
pathPrefix?
)
三
render(
schema,
{
data: {
...
visible:  false
}
},
env,
pathPrefix?
)
render(
schema,
{
data: {
...
hidden: 'anything not falsy'
}
},
env,
pathPrefix?
)
四
render(
{
...
hiddenOn: '1'
},
props,
env,
pathPrefix?
)
render(
{
...
visibleOn: '0'
},
props,
env,
pathPrefix?
)
render(
{
...
"hiddenExpr": "not falsy string",
},
props,
env,
pathPrefix?
)

某些情况下渲染空页面而非crash

---

docs/start/getting-started.md

丰富props配置的使用说明

---

docs/components/iframe.md

更新iframe宽高属性的说明文档

---

.gitignore
scss/components/form/_tinymce.scss
scss/themes/cxd.scss
scss/themes/dark.scss
scss/themes/default.scss
src/Scoped.tsx
src/renderers/Form/Image.tsx
src/renderers/Tasks.tsx
src/types.ts

主要修复以上两点问题。
附带以下小修改：
1.  纠正代码拼写 alis -> alias
2. 由于我使用的yarn, 自动产生了 `yarn.lock`文件, 由于原项目中，没有该文件，因此我将该文件加入到了 `.gitignore`

移除 window.alert 提示. 修复 tinymce 弹窗内菜单展示问题.

---

src/renderers/Json.tsx

add `hideRoot` and `source` to Json Renderer

add `hideRoot` and `source` to Json Renderer

---

docs/concepts/linkage.md

完善被动联动文档说明

---

src/components/Radios.tsx
src/components/Select.tsx
src/components/Tree.tsx
src/renderers/Action.tsx
src/renderers/Form/Checkboxes.tsx
src/renderers/Form/NestedSelect.tsx
src/renderers/Form/Picker.tsx
src/renderers/Form/Tag.tsx
src/renderers/Form/Text.tsx

Change-Id: I8f00765dfaaaeb15c130483551728a92b1e514d3

优化选项类 label 展示, 如果接口返回了对象会导致前端报错

---

scss/components/_collapse.scss
scss/components/form/_group.scss
src/renderers/Collapse.tsx
src/renderers/Form/FieldSet.tsx

Change-Id: Ic3d2f0a47338bfef82c6b3ba9a9754a99fc70319

Collapse 调整

---

src/components/SearchBox.tsx
src/components/Transfer.tsx

Change-Id: I810450dbe045c1304fb24a028ec0058178453c21

Transfer 的 Search 按 enter 提交表达关闭

---

src/renderers/Form/ButtonGroup.tsx
src/utils/api.ts

Change-Id: I220f4f6aab1e9de3a2ac03e9ad5bba47acda543d

api.adaptor 支持异步

---

scss/_variables.scss
scss/components/_table.scss
src/renderers/Table/index.tsx

1. 操作交互 itemActions z-index
2. 底部表格跟固定表格列宽度不一致
3. 固定表格 hover

fix(Table): fixed table hover

---

scss/components/_table.scss
src/renderers/Table/TableRow.tsx
src/renderers/Table/index.tsx

1. top 0 导致固定列有问题
2. ignoreFootableContent 需要空的 tr td 把高度撑起来
3. Table-fixedLeft table 会影响折叠 table 改为 Table-fixedLeft>table

fix: fixed table footable height

---

docs/components/table.md
examples/components/CRUD/PopOver.tsx
examples/components/Doc.tsx
examples/components/Example.tsx
examples/components/MdRenderer.tsx
scss/components/_popoverable.scss
src/renderers/PopOver.tsx

1. 支持 trigger 配置 'click' 或者 'hover'
2. showIcon 可配置
3. 部分定位样式补充
4. 补充文档
5. 文档中 schema 预览关闭隐藏销毁功能。

Popover 添加更多的配置

---

docs/components/table.md
examples/style.scss
scss/components/_table.scss
src/renderers/Table/TableBody.tsx
src/renderers/Table/TableContent.tsx
src/renderers/Table/index.tsx

Table支持总结行

---

scss/components/form/_picker.scss

fix picker disabled

---

src/factory.tsx
src/renderers/Action.tsx
src/renderers/Form/index.tsx
src/store/iRenderer.ts
src/types.ts

满足此需求：https://github.com/baidu/amis/issues/1268

增加 reset-and-submit 动作 

---

src/store/form.ts

form 未保存离开页面功能优化

---

examples/embed.tsx

解决 `content-disposition` 中 fileName 中有大写的情况。

jssdk  文件下载判断优化

---

scss/components/form/_nested-select.scss

修复nested-select上下闪动问题

---

src/renderers/Form/Radios.tsx

fix: 修复 radios valueField失效问题

---

src/utils/validations.ts

https://github.com/baidu/amis/issues/1313

验证规则中的参数支持变量

---

src/renderers/Form/Control.tsx
src/renderers/Form/InputGroup.tsx
src/store/formItem.ts

https://github.com/baidu/amis/issues/1323

修复 inputGroup 验证问题

---

src/renderers/Form/Picker.tsx

https://github.com/baidu/amis/issues/1308

如果 picker 的 labelField 和 valueField 一样就不要去请求选项了

---

src/renderers/Form/Combo.tsx
src/renderers/Form/Control.tsx
src/renderers/QuickEdit.tsx
src/store/formItem.ts

https://github.com/baidu/amis/issues/1332

修复 combo>table 中 text 输入可能会被重置的问题

---

src/renderers/Form/Control.tsx

修复表单项在不配置name的时候，value属性失效问题

---

fis-conf.js
src/Root.tsx
src/RootRenderer.tsx
src/SchemaRenderer.tsx
src/WithRootStore.tsx
src/WithStore.tsx
src/factory.tsx
src/renderers/Form/Control.tsx
src/renderers/Form/Item.tsx
src/renderers/Page.tsx
src/store/formItem.ts
src/store/index.ts
src/store/root.ts

1. 拆解 factory.tsx 太大了
2. 添加 RootRenderer，并能处理部分 action， 这样的好处是直接渲染个按钮也能弹窗，发ajax了。

Root renderer

---

scss/components/_quick-edit.scss
src/renderers/Table/HeadCellFilterDropdown.tsx
src/renderers/Table/index.tsx

当没有配置 options 或者 source 时，从表格数据中提取。

TableCell 的 filterable 功能优化

---

src/renderers/CRUD.tsx
src/store/crud.ts

前端一次性加载模式直接用已有数据，其他情况单独发送请求全量数据后导出。

exportCsv 改成全量导出

---

docs/zh-CN/components/form/select.md
src/components/Select.tsx
src/renderers/Form/Select.tsx

相关issue: 
* https://github.com/baidu/amis/issues/1094
* https://github.com/baidu/amis/issues/1019

select 支持配置 menuTpl 自定义菜单样式

---

docs/zh-CN/components/crud.md
src/renderers/CRUD.tsx

相关 issue: https://github.com/baidu/amis/issues/1423

crud 新增 alwaysShowPagination 属性

---

src/RootRenderer.tsx
src/components/AsideNav.tsx
src/renderers/App.tsx

相关 issue https://github.com/baidu/amis/issues/1483
需要把 App 渲染器加入到 Scoped 中，并注册 reload 方法支持被通信

App 渲染器支持被通信刷新

---

docs/zh-CN/components/action.md
src/renderers/Form/index.tsx
src/renderers/Table/HeadCellSearchDropdown.tsx
src/store/form.ts
src/store/formItem.ts
src/types.ts

关联 issue https://github.com/baidu/amis/issues/1503

添加 clear clear-and-submit 并且将 searchable 里面的重置换成 clear-and-submit 行为

---

src/renderers/Form/Control.tsx

相关issue https://github.com/baidu/amis/issues/1168

validate 改成检测值变化的时候就验证,而不是 handleChange 回调中

---

src/renderers/Form/Control.tsx

相关 issue: https://github.com/baidu/amis/issues/1568

修复 formItem 有默认值时无法删除的问题

---

src/env.tsx
src/renderers/Chart.tsx

chart 支持 env.loadChartExtends 加载 chart 扩展相关

---

docs/zh-CN/components/table.md
examples/components/CRUD/Table.jsx
src/renderers/PopOver.tsx

popover功能支持配置是否启动

---

src/renderers/CRUD.tsx
src/renderers/Table/TableBody.tsx
src/renderers/Table/TableContent.tsx
src/renderers/Table/index.tsx

因为 TableBody 已经做了，所以TableContent 不需要了，解决 placeholder 用 crud api 数据无效的问题

TableContent 不要严格控制刷新

---

docs/zh-CN/components/form/tabs.md
examples/components/Form/Tabs.jsx
src/renderers/Form/Tabs.tsx
src/renderers/Tabs.tsx

Form > Tabs 支持同步表单项

---

src/renderers/Form/Textarea.tsx

fix textarea 控制台报错

---

__tests__/renderers/Form/__snapshots__/buttonGroup.test.tsx.snap
__tests__/renderers/__snapshots__/Wizard.test.tsx.snap
scss/components/_panel.scss
src/renderers/Cards.tsx
src/renderers/List.tsx
src/renderers/Panel.tsx
src/renderers/Table/index.tsx

做了两件事：
1. 修复了Panel下，配置`affixOffsetBottom`不生效的问题
2. 优化了 CRUD 的`affixTop`的固顶体验

affixed 相关优化

---

docs/zh-CN/components/property.md
docs/zh-CN/concepts/style.md
examples/components/Components.tsx
scss/_properties.scss
scss/components/_property.scss
scss/themes/_common.scss
src/Schema.ts
src/index.tsx
src/renderers/Property.tsx
src/utils/helper.ts

feat：属性表组件

---

src/renderers/Dialog.tsx
src/renderers/Drawer.tsx
src/store/modal.ts

```
{
"label": "Open Dialog", 
"type": "button",
"actionType": "dialog",
"dialog": {
"lazySchema": () => Promise.resolve({
body: "这个内容是弹框弹出的时候加载的"
})
}
}
```

Modal 支持异步指定内容 schema

---

src/store/table.ts

优化 table 的 expand 切换

---

docs/zh-CN/components/mapping.md
mock/mapping.json
src/renderers/Mapping.tsx
src/utils/tpl-builtin.ts

mapping 添加 source 接口

---

src/renderers/CRUD.tsx
src/renderers/Form/Table.tsx
src/renderers/Table/TableRow.tsx
src/renderers/Table/index.tsx
src/store/table.ts

1. quickEdit 支持 nested 用法深层数据的修改
2. 总计行支持nested 数据的实时展示
3. 文件夹节点 tpl 展示支持实时展示

Table quickEdit 支持 nested 数据

---

__tests__/renderers/__snapshots__/Wizard.test.tsx.snap
src/renderers/Form/Checkboxes.tsx

支持控制 option 粒度 的 removable 和 editable

Checkboxes 快速编辑、删除，判断优化

---

src/renderers/Form/Grid.tsx
src/renderers/Form/HBox.tsx
src/renderers/Form/Service.tsx

还没文档估计没人用过，可能不算 breaking change？

typo：fieldSet

---

docs/zh-CN/concepts/data-mapping.md

错字修复 / corrects typos in project documentation
Scope of changes is restricted to documentation only.

fix(docs): corrects typo in project documentation - 使固定说明文件

---

scss/components/_table.scss
src/store/table.ts

记录是否收起与展开换成了普通的字符串数组，之前的引用数组可能会出现引用不存在还报错。

修复表格展开收起可能出现的报错问题

---

src/Scoped.tsx

补充 https://github.com/baidu/amis/pull/1917 相关逻辑

#1917 扩充，二选一

---

docs/zh-CN/components/form/checkboxes.md
scss/components/form/_checks.scss
src/renderers/Form/Checkboxes.tsx
src/renderers/Form/Options.tsx

Checkboxes 分组样式优化

---

docs/zh-CN/components/form/tree.md
src/renderers/Form/Options.tsx
src/renderers/Form/Tree.tsx

1. 配置了 editApi ，但是编辑后不刷新表单
2. 外层容器支持设置 className

tree 组件问题修复

---

src/utils/tpl-builtin.ts

比如：
```
"autoFill": {
"a[xxx]": 123
}
```

数据映射的 key 可以支持 . 或者 [] 来指定路径

---

src/renderers/Nav.tsx

nav 的 mapTree 需要 depthFirst

---

docs/zh-CN/components/tabs.md
src/renderers/Tabs.tsx
src/utils/tpl-builtin.ts

tabs的activeKey支持变量

---

docs/zh-CN/components/each.md
scss/components/_each.scss
src/renderers/Each.tsx

我这边开发后产品反馈的问题，一个居左一个居中确实看的有点恶心。
另外空数组的时候空白状态也不太好

each 组件空状态时文字居左，同时将空数组状态也认为是空状态

---

docs/zh-CN/components/images.md

fix: 修复文档样例错误

---

__tests__/renderers/Form/__snapshots__/index.test.tsx.snap
__tests__/renderers/__snapshots__/Action.test.tsx.snap
__tests__/renderers/__snapshots__/DropDownButton.test.tsx.snap
__tests__/renderers/__snapshots__/Wizard.test.tsx.snap
scss/components/_button.scss
scss/components/_dropdown.scss
src/components/Button.tsx
src/renderers/Action.tsx
src/renderers/Form/Checkboxes.tsx

1. dropdown 中的 tooltip 逻辑完善
2. 按钮禁用态 tooltip 实现调整

按钮 tooltip 整理 支持 disabledTip

---

docs/zh-CN/components/form/rating.md
src/components/Rating.tsx

feat: rating allow clear

---

src/renderers/Page.tsx

data-link 优化

---

src/renderers/Form/Control.tsx
src/renderers/Form/Item.tsx
src/renderers/Form/index.tsx

fix: 修复 formitem 通过 children 返回 jsx.element 的方式导致重复刷新的问题

---

scss/layout/_grid.scss
scss/layout/_hbox.scss
src/compat.ts
src/renderers/Form/index.tsx
src/renderers/Form/wrapControl.tsx
src/renderers/Grid.tsx
src/renderers/HBox.tsx
src/renderers/Tpl.tsx

1. controls 下面 tpl 展示为空的问题修复，部分静态展示没有展示 label 问题
2. Grid 展示 formitem 样式优化
3. Hbox 补充 gap 逻辑
4. Tabs 展示表单项兼容代码有问题，替换 controls 为 body 必须是在没有 body 的前提下

1.2.x 几个问题修复

---

src/components/DateRangePicker.tsx
src/components/MonthRangePicker.tsx

feat: 月份选择器增加快捷键支持

---

src/WithStore.tsx
src/compat.ts
src/renderers/Form/index.tsx
src/renderers/Table/TableRow.tsx
src/utils/tpl-builtin.ts

1. defaultData 支持配置数据映射
2. crud 下面列直接放 form 的兼容处理
3. each 在 controls 里面可能需要展示 label

1.2.x 兼容性问题处理

---

src/renderers/Table/index.tsx

根据 itemDraggableOn 控制拖拽按钮是否显示

---

src/renderers/Table/index.tsx

Revert "根据 itemDraggableOn 控制拖拽按钮是否显示"

---

docs/zh-CN/components/form/select.md

增加 select 单选模式下清空属性文档

---

docs/zh-CN/components/form/input-table.md
scss/components/_table.scss
src/compat.ts
src/locale/de-DE.ts
src/locale/en-US.ts
src/locale/zh-CN.ts
src/renderers/Form/InputTable.tsx
src/renderers/Form/index.tsx
src/renderers/Table/TableBody.tsx
src/renderers/Table/TableRow.tsx
src/renderers/Table/index.tsx
src/store/table.ts

1. 新增显示序号功能
2. 新增分页功能
3. 修复 addable 配置导致每条都直接进入编辑状态的问题
4. 改造 Table，支持不共用行 store 模式
5. Table 部分组件修改更新模式，reaction => observer

chore: InputTable 优化升级

---

__tests__/renderers/__snapshots__/Carousel.test.tsx.snap
__tests__/renderers/__snapshots__/Image.test.tsx.snap
docs/zh-CN/components/carousel.md
docs/zh-CN/components/image.md
docs/zh-CN/components/images.md
scss/components/_carousel.scss
scss/components/_images.scss
src/renderers/Carousel.tsx
src/renderers/Image.tsx

1. image 扩充原图模式。 imageMode: 'thumb' | 'original'
2. carousel 扩充图片裁剪模式 cover | contain

chore: 调整 image 和 carousel

---

src/components/condition-builder/Expression.tsx
src/components/condition-builder/Field.tsx
src/components/condition-builder/Group.tsx
src/components/condition-builder/GroupOrItem.tsx
src/components/condition-builder/Item.tsx
src/components/condition-builder/Value.tsx
src/components/condition-builder/index.tsx

优化了字段过多的场景，提供了搜索功能；
另外该组件我认为是`select`缺少的一种形式，虽然NestedSelect勉强可以代替，但是NestedSelect也不支持searchable属性，请问是否考虑单独成为一个表单项，觉得合适的话，本人可以继续跟进

condition支持字段进行搜索

---

__tests__/renderers/Form/__snapshots__/formitem.test.tsx.snap
__tests__/renderers/Form/__snapshots__/index.test.tsx.snap
__tests__/renderers/Form/__snapshots__/testarea.test.tsx.snap
__tests__/renderers/Form/checkboxes.test.tsx
__tests__/renderers/__snapshots__/Wizard.test.tsx.snap
__tests__/utils/validations.test.ts
docs/zh-CN/components/form/input-text.md
docs/zh-CN/components/form/textarea.md
package.json
scss/components/form/_text.scss
scss/components/form/_textarea.scss
src/components/Textarea.tsx
src/renderers/Form/InputText.tsx
src/renderers/Form/Item.tsx
src/renderers/Form/Textarea.tsx
src/renderers/Form/wrapControl.tsx
src/store/formItem.ts
src/utils/validations.ts

优化 minLength, maxLength ，自动验证，并能高亮错误提示

feat: 新增 inputText、textarea字数统计功能

---

src/renderers/Page.tsx

Avoid unnecessary void & anyOf in schema

---

src/renderers/Form/Formula.tsx

formula 的 init 动作改成监听事件去实现，而不是在属性变化的时候去处理，原有机制form触发出去的 onInit 方法没有包含 formula 初始设置的值

fix: 修复 formula 在 wizard 里面,初始设置的值无效的问题

---

src/utils/resize-sensor.ts

resizeSensor 的时候顺便判断一下，如果首次从隐藏状态进入显示状态，也触发 resize 回调。

fix: 修复图表在隐藏 dom 下渲染的尺寸问题

---

src/renderers/Form/InputFile.tsx

fix: 修复 InputFile 组件请求体中包含 empty 值的问题

---

src/components/calendar/DaysView.tsx

fix: 修复minDate失效的bug #2789
Fixes #2789

fix: 修复minDate失效的bug #2789

---

package.json
src/components/RichText.tsx

之前的逻辑还有问题，之前初始没有的时候，不会绑定 init 事件，导致回调钩子没有执行

fix: 修复 froalaEditor 可能数值不同步的问题

---

src/renderers/IFrame.tsx

关联卡片：https://github.com/baidu/amis/issues/2817

chore: iframe 添加 name 属性可以方便外部通信

---

docs/zh-CN/components/form/input-tree.md
src/components/Tree.tsx

#2641 修复的时候，并没有正确使用Icon组件去渲染；
同时补充了文档

inputTree的icon显示修复;并补充文档

---

build.sh

chore: IE11 下去掉动画

---

package.json
src/components/SearchBox.tsx
src/renderers/SearchBox.tsx

不过副作用是导致数据变化的时候就去搜索，可能会过于频繁，而且回车键等于没用了

fix: 修复 search box 搜索之后就不能改数据问 

---

src/components/Checkboxes.tsx

具体描述见issue：https://github.com/baidu/amis/issues/2931

fix: toogleAll

---

__tests__/renderers/Form/__snapshots__/fieldSet.test.tsx.snap
scss/components/_collapse-group.scss
scss/components/_collapse.scss
scss/themes/_cxd-variables.scss
src/components/Collapse.tsx

- [ √] 组件样式/交互改进
| 英文 |  Collapse component modifying styles and  compatible param body   |
| 中文 |  折叠面板修改样式和兼容body       |
- [ √] 文档已补充或无须补充
- [ √] 代码演示已提供或无须提供
- [ √] TypeScript 定义已补充或无须补充
- [ √] Changelog 已提供或无须提供

fix: collapse修改样式&兼容body

---

docs/zh-CN/components/progress.md
package.json
scss/_properties.scss
scss/components/_progress.scss
src/components/Progress.tsx
src/renderers/Progress.tsx

设计文档：http://ku.baidu-int.com/knowledge/HFVrC7hq1Q/pKzJfZczuc/GxsYWwEpj5/Xu8s-YFnT_cfaU
| 中文 |         1.新增圆形进度条<br />2.新增进度条状态<br />3.新增内容格式化函数<br />4.对齐4.0规范 |

feat: progress 组件功能对齐4.0规范

---

src/components/Collapse.tsx

- [ √] 组件样式/交互改进
| 英文 |   Style fixed when collapsable is set by collapse component       |
| 中文 |  collapse组件设置collapsable时样式修复        |
- [ √] 文档已补充或无须补充
- [ √] 代码演示已提供或无须提供
- [ √] TypeScript 定义已补充或无须补充
- [ √] Changelog 已提供或无须提供

fix: collapse组件设置collapsable时样式修复

---

docs/zh-CN/components/form/switch.md
scss/components/form/_switch.scss
src/components/Switch.tsx

http://wiki.baidu.com/pages/viewpage.action?pageId=1679794435
| 中文 |       1.trueValue/falseValue 类型 any---->boolean / string / number 2.onText/offText 类型string---->ReactNode 3.规范开关icon为svg时的样式    |

feat: Switch 组件功能对齐4.0规范

---

__tests__/renderers/Timeline.test.tsx
docs/zh-CN/components/timeline.md
examples/components/Components.tsx
mock/cfc/mock/timeline/timelineItems.json
package.json
scss/components/_timeline.scss
scss/themes/_antd-variables.scss
scss/themes/_common.scss
scss/themes/_cxd-variables.scss
src/Schema.ts
src/components/Timeline.tsx
src/components/TimelineItem.tsx
src/components/icons.tsx
src/icons/tree-down.svg
src/index.tsx
src/locale/de-DE.ts
src/locale/en-US.ts
src/locale/zh-CN.ts
src/renderers/Timeline.tsx

<h3 dir="auto" style="box-sizing: border-box; margin-top: 0px !important; margin-bottom: 16px; font-size: 1.25em; font-weight: 600; line-height: 1.25; color: rgb(36, 41, 47); font-family: -apple-system, system-ui, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">这个变动的性质是？</h3><ul class="contains-task-list" style="box-sizing: border-box; …

feat: timeline3.0

---

docs/zh-CN/start/getting-started.md

fix: 修改文档切换主题重复问题

---

docs/zh-CN/components/app.md

fix: 修复文档App 多页应用内链接404

---

src/renderers/Card.tsx

crud 如果没有 bulkActions 按理是不应该有点选能力的

fix: 修复 Card 点选不可关闭问题

---

docs/zh-CN/components/action.md

fix:修复文档链接错误

---

src/renderers/CRUD.tsx
src/renderers/Table/index.tsx
src/store/table.ts

同时修复 searchable 设置 true 没作用的问题

fix: 修复开启 autoGenerateFilter 后同时有没有可搜索项时, 接口不初始化的问题

---

examples/components/EventAction/UploadEvent.jsx
examples/components/Example.jsx
src/renderers/Form/InputFile.tsx

[设计文档](https://ku.baidu-int.com/knowledge/HFVrC7hq1Q/pKzJfZczuc/GxsYWwEpj5/RVKj6kWo5m4epf)

feat: input-file 事件动作补充

---

examples/components/EventAction/SelectEvent.jsx
examples/components/Example.jsx
src/renderers/Form/Select.tsx
src/renderers/Form/Transfer.tsx

设计文档：https://ku.baidu-int.com/knowledge/HFVrC7hq1Q/pKzJfZczuc/GxsYWwEpj5/PkWzOn5SM8-sM_
| 中文 |     1、select组件添加clear动作    |

Feat select action event

---

__tests__/renderers/Form/number.test.tsx
examples/components/EventAction/InputNumberEvent.jsx
examples/components/Example.jsx
src/components/NumberInput.tsx
src/renderers/Form/InputNumber.tsx

https://ku.baidu-int.com/knowledge/HFVrC7hq1Q/pKzJfZczuc/GxsYWwEpj5/6QvTayeh8nu9jT
| 中文 |    1. inputNumber组件添加'change', 'focus', 'blur'事件 <br> 2. inputNumber组件添加'clear'动作      |

feat: 数字输入组件事件 & 动作扩充

---

__tests__/renderers/Form/list.test.tsx
__tests__/renderers/Form/radios.test.tsx
examples/components/EventAction/SelectEvent.jsx
examples/components/Example.jsx
src/renderers/Form/InputTag.tsx
src/renderers/Form/MatrixCheckboxes.tsx
src/renderers/Form/Options.tsx
src/renderers/Form/Radios.tsx
src/renderers/Form/Select.tsx

设计文档：https://ku.baidu-int.com/knowledge/HFVrC7hq1Q/pKzJfZczuc/GxsYWwEpj5/PkWzOn5SM8-sM_
| 中文 |     1、下拉选择类事件动作补充     |

下拉选择类组件新增事件动作&demo

---

docs/zh-CN/components/drawer.md
src/components/Drawer.tsx
src/renderers/Drawer.tsx

设计文档 （https://ku.baidu-int.com/knowledge/HFVrC7hq1Q/pKzJfZczuc/GxsYWwEpj5/6-E3FuAcPNJx9N）
| 中文 |     1. 新增宽度、高度属性 <br> 2. 新增是否展示关闭按钮属性 <br>3. 可自定义设置多种类名     |

feat: Drawer 组件功能丰富

---

scss/components/form/_checks.scss
src/components/Radios.tsx
src/renderers/Form/Radios.tsx

feat: Radios 功能补齐

---

examples/components/EventAction/UploadEvent.jsx
src/renderers/Form/InputFile.tsx
src/renderers/Form/InputImage.tsx

[设计文档](https://ku.baidu-int.com/knowledge/HFVrC7hq1Q/pKzJfZczuc/GxsYWwEpj5/RVKj6kWo5m4epf)

feat: input-image 事件动作补充

---

scss/_properties.scss
scss/components/_result-box.scss
scss/components/form/_nested-select.scss
scss/components/form/_select.scss
scss/themes/_cxd-variables.scss
src/components/ResultBox.tsx
src/renderers/Form/NestedSelect.tsx

新特性提交
其- [ ] 他改动（inputImage 事件&动作）
[设计文档](https://ku.baidu-int.com/knowledge/HFVrC7hq1Q/pKzJfZczuc/GxsYWwEpj5/_MEo0JKmVlYEo5)
⚠️ 请自检并全部勾选全部选项。⚠️

feat: cascader-select 组件升级

---

examples/components/EventAction/InputRatingEvent.jsx
examples/components/Example.jsx
src/components/Rating.tsx
src/renderers/Form/InputRating.tsx

设计文档 [https://ku.baidu-int.com/knowledge/HFVrC7hq1Q/pKzJfZczuc/GxsYWwEpj5/E9n3ikMASe_njh](https://ku.baidu-int.com/knowledge/HFVrC7hq1Q/pKzJfZczuc/GxsYWwEpj5/E9n3ikMASe_njh)
| 中文 |     1. 组件增加 `change` 事件派发<br>2. 组件增加 `clear`、`reset` 动作 |

feat: InputRating 评分组件事件&动作补充

---

examples/components/EventAction/InputEvent.jsx
examples/components/EventAction/SelectEvent.jsx
examples/components/Example.jsx
src/renderers/Form/ChainedSelect.tsx
src/renderers/Form/Checkbox.tsx
src/renderers/Form/InputTag.tsx
src/renderers/Form/MatrixCheckboxes.tsx
src/renderers/Form/NestedSelect.tsx
src/renderers/Form/Options.tsx
src/renderers/Form/Radios.tsx
src/renderers/Form/Select.tsx

设计文档：https://ku.baidu-int.com/knowledge/HFVrC7hq1Q/pKzJfZczuc/GxsYWwEpj5/PkWzOn5SM8-sM_
| 中文 |     1、select相关选择类、单选框等事件动作补充     |

feat: NestedSelect&Checkbox&ChainedSelect事件&动作扩充

---

docs/zh-CN/components/form/switch.md
examples/components/Form/Full.jsx
scss/components/form/_switch.scss
src/renderers/Form/Switch.tsx

这个变动的性质是？
需求背景和解决方案
之前开发的是组件用法，现补充可视化配置所需组件json用法
请求合并前的自查清单
⚠️ 请自检并全部勾选全部选项。⚠️

feat: Switch支持开关状态下的内容为icon

---

src/components/Range.tsx
src/renderers/Form/InputRange.tsx

| 中文 | inputRange schema类型定义&事件&动作扩充 |

feat: inputRange schema类型定义&事件&动作扩充

---

examples/components/EventAction/ExcelEvent.jsx
examples/components/Example.jsx
src/renderers/Form/InputExcel.tsx
src/renderers/Form/InputFile.tsx
src/renderers/Form/InputImage.tsx

feat: input-excel 事件动作补充

---

scss/components/_city-area.scss
scss/components/_popup.scss
src/components/PopUp.tsx
src/renderers/Form/InputColor.tsx
src/renderers/Form/InputDate.tsx
src/renderers/Form/InputDateRange.tsx
src/renderers/Form/Select.tsx

修复select移动端popup出现位置、增加popup关闭按钮点击区域

fix： 解决弹框容器内容多时popup遮挡问题

---

__tests__/renderers/Form/__snapshots__/tabs.test.tsx.snap
__tests__/renderers/Form/__snapshots__/tabsTransfer.test.tsx.snap
__tests__/renderers/__snapshots__/Portlet.test.tsx.snap
__tests__/renderers/__snapshots__/Tabs.test.tsx.snap
docs/zh-CN/components/tabs.md
scss/_properties.scss
scss/components/_tabs.scss
scss/themes/_cxd-variables.scss
src/components/Tabs.tsx
src/renderers/Tabs.tsx

| 中文 |     1. 修复Tabs宽度 resize 问题<br>2. 样式问题优化<br>3. 新增一种模式 |

Tabs 宽度问题修改，与样式优化

---

src/factory.tsx

文本替换的时候替换不全
顺便问下，为啥我之前关于 combo 的 pr 和 issue 都没人管（手动狗头）：
https://github.com/baidu/amis/pull/3658
https://github.com/baidu/amis/issues/3511

fix: replaceText 替换文本不全

---

docs/zh-CN/components/wizard.md
examples/components/EventAction/WizardEvent.jsx
examples/components/Example.jsx
src/renderers/Wizard.tsx
src/types.ts

设计文档 [https://ku.baidu-int.com/knowledge/HFVrC7hq1Q/pKzJfZczuc/GxsYWwEpj5/V60q7R721SMQ83](https://ku.baidu-int.com/knowledge/HFVrC7hq1Q/pKzJfZczuc/GxsYWwEpj5/V60q7R721SMQ83)
| 中文 |     1. 组件增加 `inited`、`finished`、`stepChange`、`change`、`submitSucc`、`submitFail`、`stepSubmitSucc`、`stepSubmitFail` 事件派发<br>2. 组件增加  `submit`、`stepSubmit`、`next`、`prev`、`gotoStep` 动作 |

feat: 向导组件 事件&动作 配置

---

examples/components/EventAction/SelectEvent.jsx
src/renderers/Form/InputCity.tsx

设计文档：https://ku.baidu-int.com/knowledge/HFVrC7hq1Q/pKzJfZczuc/GxsYWwEpj5/PkWzOn5SM8-sM_
| 中文 |     1、input-city事件动作补充     |

feat:input-city事件&动作扩充

---

src/components/Range.tsx

fix: range组件去除循环引用

---

package.json

如：
* ```ARRAYMAP(arr, item => item.x)```
* ```ARRAYMAP(arr, item => item.x * 2)```
* ```ARRAYMAP(arr, item =>`${item.x}-${item.y}`)```
* ```ARRAYMAP(arr, (item, index) => {x: item.a, index: index})```

feat: 公式支持单表达式箭头函数

---

scss/components/form/_checks.scss
src/components/Checkbox.tsx

fix:修复半选状态

---

docs/zh-CN/components/tooltip-wrapper.md
scss/_properties.scss
scss/components/_tooltip.scss
src/components/Overlay.tsx
src/components/Tooltip.tsx
src/components/TooltipWrapper.tsx
src/renderers/TooltipWrapper.tsx
src/utils/dom.tsx

feat: TooltipWrapper 的component组件完善
feat: TooltipWrapper 文字提示容器 render组件 & 文档完善

Feat tooltip wrapper

---

scss/_properties.scss
scss/components/form/_checks.scss
scss/themes/_cxd-variables.scss

fix: checkbox对齐云舍样式

---

docs/zh-CN/components/tooltip-wrapper.md
src/components/TooltipWrapper.tsx
src/renderers/TooltipWrapper.tsx

tooltipwrapper浮层 原绑定事件会导致浮层出现bug

fix: 为tooltipwrapper浮层绑定指定事件，并丰富enterable属性

---

src/renderers/Markdown.tsx

fix: 修复 Markdown 组件的 componentDidUpdate hook 反复被触发导致无限循环

---

scss/components/_context-menu.scss

style: 调整菜单面板样式

---

scss/components/_context-menu.scss

docs: 剔除多余注释

---

docs/zh-CN/concepts/event-action.md
src/actions/ToastAction.ts

调整toast触发时传入的参数，去除options层
| 中文 |    ToastAction去除options层结构      |

feat: 调整ToastAction 参数结构

---

src/renderers/Form/TreeSelect.tsx

treeSelect支持selfDisabledAffectChildren

Feat tree select opt

---

src/renderers/Tabs.tsx

| 中文 |      tabs 触发change事件调整     |

fix: tabs 触发change事件调整

---

__tests__/renderers/Carousel.test.tsx
__tests__/renderers/Page.test.tsx
__tests__/renderers/Wizard.test.tsx
__tests__/renderers/__snapshots__/Carousel.test.tsx.snap
docs/zh-CN/components/carousel.md
src/renderers/Carousel.tsx
src/types.ts

设计文档：https://ku.baidu-int.com/knowledge/HFVrC7hq1Q/pKzJfZczuc/GxsYWwEpj5/VXawHCQkTj2-uw
| 中文 |     1、轮播图组件事件&动作补充     |

feat: Carousel轮播图组件事件&动作补充

---

scss/_properties.scss

css 计算属性没有空格，在 umi 中报错: postcss-loader Syntax Error

fix: umi 集成报错,样式库编译报错

---

scss/components/form/_select.scss
src/renderers/Form/Options.tsx

| 中文 |    fix: 修复Select默认全选失效     |

fix: 修复Select默认全选失效

---

scss/components/form/_nested-select.scss
src/renderers/Form/NestedSelect.tsx

| 中文 |      调整默认placeholder、无搜索结果文案   |

Feat nestedselect

---

src/components/Select.tsx
src/renderers/Form/InputCity.tsx

1. 默认不应该显示 clear 的 icon
2. 点击clear 的 icon 后不应该所有的地址都清理了，而是只清理当前选项

fix: 修复 inputCity 选项清理问题

---

src/renderers/Form/InputText.tsx

InputText 选择器模式下 仅返回首字BUG

---

docs/zh-CN/components/form/input-file.md
docs/zh-CN/components/form/input-image.md
scss/components/form/_file.scss
src/renderers/Form/InputFile.tsx
src/renderers/Form/InputImage.tsx

调整change事件派发时机
修复上传进度条与实际比例不匹配

fix: 调整上传change的派发时机，修复上传进度条与实际比例不匹配

---

docs/zh-CN/components/form/input-tree.md
scss/_properties.scss
scss/components/form/_tree.scss
scss/themes/_cxd-variables.scss
src/components/Tree.tsx
src/renderers/Form/InputTree.tsx

https://ku.baidu-int.com/knowledge/HFVrC7hq1Q/pKzJfZczuc/GxsYWwEpj5/ZDu3eBNnP9MeEr
兼容已有业务场景用法
| 中文 |     1. 对齐4.0规范 <br/> 2. 选中级联拆分为UI级联与数据级联   |

Feat/tree cxd 4.0

---

src/components/Select.tsx

| 中文 |    fix: Select仅全选不多选不应展示选框,且无法选中值修复   |

fix:Select仅全选无法选中值修复

---

scss/components/form/_text.scss
scss/themes/cxd.scss

fix: 修复inputText下拉框样式对齐问题

---

__tests__/renderers/Form/inputMonthRange.test.tsx
src/components/DateRangePicker.tsx
src/components/calendar/Calendar.tsx
src/components/calendar/MonthsView.tsx
src/renderers/Form/InputDateRange.tsx
src/renderers/Form/InputMonthRange.tsx
src/renderers/Form/InputQuarterRange.tsx
src/renderers/Form/InputYearRange.tsx

fix: 更改月份范围选择器 Render

---

src/components/calendar/TimeView.tsx

fix #4089: 时间选择器timeConstraints属性不生效问题

---

scss/helper/background/_background-color.scss

 添加background参考颜色，更方便选取颜色

---

__tests__/renderers/CRUD.test.tsx
__tests__/renderers/Form/__snapshots__/chainedSelect.test.tsx.snap
__tests__/renderers/Form/__snapshots__/city.test.tsx.snap
__tests__/renderers/Form/__snapshots__/conditionBuilder.test.tsx.snap
__tests__/renderers/Form/__snapshots__/repeat.test.tsx.snap
__tests__/renderers/Form/__snapshots__/select.test.tsx.snap
__tests__/renderers/Form/__snapshots__/service.test.tsx.snap
__tests__/renderers/Form/combo.test.tsx
__tests__/renderers/Form/formula.test.tsx
__tests__/renderers/Form/inputArray.test.tsx
__tests__/renderers/Page.test.tsx
scss/components/_button-group.scss
scss/components/_result-box.scss
scss/components/form/_checks.scss
scss/components/form/_nested-select.scss
scss/components/form/_select.scss
scss/components/form/_selection.scss
scss/components/form/_transfer.scss
scss/themes/_cxd-variables.scss
scss/themes/cxd.scss
src/components/ResultBox.tsx
src/components/Select.tsx
src/components/TransferDropDown.tsx
src/renderers/Form/NestedSelect.tsx

| 中文 |   Select Options等组件样式对齐4.0   |

Select Options等组件样式对齐4.0

---

scss/components/_result-box.scss
scss/components/form/_checks.scss

feat: checkboxes内边距&nestedSelect箭头修改

feat: checkboxes内边距&nestedSelect箭头修改

---

src/components/calendar/DaysView.tsx
src/components/calendar/TimeView.tsx

fix: 修复datetime移动端报错

---

examples/components/EventAction/FormEvent.jsx
src/components/Toast.tsx
src/utils/renderer-event.ts

同步的toast会因为setState的默认合并导致只有最后一个生效

feat:toast支持取消合并state

---

scss/components/_table.scss

fix: curd 图标垂直居中

---

scss/components/form/_nested-select.scss

fix:修复nestedSelect无法动态调整位置及溢出问题

fix:修复nestedSelect无法动态调整位置及溢出问题

---

__tests__/renderers/Form/__snapshots__/dateRange.test.tsx.snap
src/components/DateRangePicker.tsx

fix: 去掉日期返回不打开的时候底部的线

---

src/renderers/Form/Options.tsx

perf:添加选项必填

---

docs/zh-CN/components/table.md
src/renderers/CRUD.tsx
src/renderers/Service.tsx
src/renderers/Table/TableContent.tsx
src/renderers/Table/index.tsx

Fix table loading

---

__tests__/renderers/Form/__snapshots__/repeat.test.tsx.snap
__tests__/renderers/Form/__snapshots__/select.test.tsx.snap
scss/components/form/_select.scss
src/components/Select.tsx
src/locale/zh-CN.ts

fix: 修复 select 样式问题

---

fis-conf.js

修改前：如果修改 packages 下面的 src 源码需要执行 npm run build --workspace xxx 才能及时看到预览效果
修改后：无需执行 npm run build

chore: monorepo 开发模式直接将包引用重定向到 src 目录

---

packages/amis/src/renderers/Form/Textarea.tsx

feat：多行文本框支持change事件

---

packages/amis-ui/src/components/Range.tsx
packages/amis/__tests__/event-action/renderers/form/__snapshots__/range.test.tsx.snap
packages/amis/__tests__/event-action/renderers/form/range.test.tsx

fix: inputRange值没改变不触发change事件
test: inputRange事件动作单测

test: inputRange事件动作单测

---

docs/zh-CN/components/action.md
docs/zh-CN/components/form/input-table.md

doc:补充完善inputTable按钮触发新增行文档

---

packages/amis/src/renderers/Form/InputFile.tsx

| 中文 |     上传文件组件，当通过自动填充为其他组件赋值时，初始化赋值存在问题，会覆盖掉原来应该显示的值     |

fix: 解决上传文件组件自动填充值为空的情况

---

docs/zh-CN/components/form/input-file.md
packages/amis/src/renderers/Form/InputFile.tsx
packages/amis/src/renderers/Form/InputImage.tsx

fix: 文件上传自动填充问题修复

---

lerna.json
packages/amis-core/package.json
packages/amis-formula/package.json
packages/amis-ui/package.json
packages/amis/package.json
packages/amis/src/renderers/Form/InputFile.tsx
packages/amis/src/renderers/Form/InputImage.tsx

Fix input file

---

packages/amis-core/src/actions/AjaxAction.ts

fix: 事件动作修复文件下载问题

---

docs/zh-CN/components/log.md
packages/amis-ui/scss/components/_log.scss
packages/amis-ui/src/components/icons.tsx
packages/amis/src/renderers/Log.tsx

支持了下检索功能，同时调整了下操作按钮的样式，目前样子如下：

feat: Log 组件支持日志检索功能;重构 Log 组件操作按钮样式和位置

---

packages/amis-ui/src/components/DateRangePicker.tsx

dateRange相关的组件minDuration 和 maxDuration 属性失效
| 中文 |  修复时间范围相关组件minDuration和maxDuration失效的问题  |

fix: 修复dateRange组件minDuration和maxDuration失效的问题

---

packages/amis-ui/scss/components/_result-box.scss

| 中文 |         清除和下拉角标重叠问题修复 |

fix:清除和下拉角标重叠问题

---

packages/amis/src/renderers/DropDownButton.tsx

| 中文 |         下拉按钮组件 icon支持扩展amis组件中扩展的Icon组件 |

feat: DropdownButton支持内置的svg icon

---

docs/zh-CN/components/table.md
packages/amis/__tests__/renderers/Table.test.tsx
packages/amis/__tests__/renderers/__snapshots__/Table.test.tsx.snap
packages/amis/src/renderers/Table/index.tsx

fix: 修复table无法勾选的问题
chore： 补充select的文档

fix: 修复table无法勾选的问题

---

docs/zh-CN/components/iframe.md
src/renderers/IFrame.tsx

feat: iframe 组件补充 sandbox、allow、referrerpolicy

---

__tests__/renderers/__snapshots__/Table.test.tsx.snap
src/renderers/Table/index.tsx

* fix:table无数据时固定列宽失效问题
* update:更新测试用例

fix:table无数据时固定列宽失效问题 (#4847)

---

packages/amis-ui/scss/components/form/_date-range.scss
packages/amis-ui/scss/components/form/_date.scss
packages/amis-ui/src/components/DatePicker.tsx
packages/amis-ui/src/components/DateRangePicker.tsx
packages/amis-ui/src/components/calendar/CalendarContainer.tsx
packages/amis-ui/src/components/calendar/DaysView.tsx

- 修复 DateRangePicker取消按钮无法点击的问题
- 修复DateTime组件，时间选择器高度与日期对齐
- 修复 DateRangeTimePicker选中开始时间后，结束时间跳转到23：59
- 优化 对无法选择的日期上增加disabled样式

fix: 修复DateRangePicker交互问题

---

docs/zh-CN/components/form/input-tag.md
packages/amis-ui/src/components/ResultBox.tsx
packages/amis-ui/src/locale/zh-CN.ts
packages/amis/__tests__/renderers/Form/__snapshots__/inputTag.test.tsx.snap
packages/amis/__tests__/renderers/Form/inputTag.test.tsx
packages/amis/src/renderers/Form/InputTable.tsx
packages/amis/src/renderers/Form/InputTag.tsx
packages/amis/src/renderers/Form/NestedSelect.tsx
packages/amis/src/renderers/Form/TreeSelect.tsx

- InputTag组件的placeholder不生效问题修复
- InputTag组件的placeholder默认值改为'请输入/选择标签'
- InputTag / TreeSelect的placeholder允许传empty string覆盖
- 修复inputTable的TS报错

fix: InputTag组件placeholder属性不生效问题

---

docs/zh-CN/concepts/event-action.md
packages/amis-core/src/actions/AjaxAction.ts
packages/amis/__tests__/event-action/ajax.test.tsx
packages/amis/__tests__/event-action/custom.test.tsx

ajax动作返回数据格式调整：
- outputVar中存放请求返回结果
- 去掉原有responseStatus、responseMsg

feat:ajax动作返回数据格式调整

---

packages/amis-ui/scss/components/_input-box.scss
packages/amis-ui/scss/components/form/_checks.scss
packages/amis-ui/scss/components/form/_nested-select.scss
packages/amis-ui/scss/components/form/_number.scss
packages/amis-ui/scss/components/form/_select.scss
packages/amis-ui/scss/components/form/_selection.scss
packages/amis-ui/scss/themes/cxd.scss

fix：inputnumber&checkbox&select&nestedSelect 4.0样式对齐

fix:amis 4.0样式对齐 checkbox&select等组件

---

packages/amis-ui/scss/components/_table.scss
packages/amis/src/renderers/Table/index.tsx

This reverts commit f81d18c7c844add3ad7ff18f68613312db6afe92.

Revert "fix: 兼容低版本浏览器配置table:autoFillHeight（不支持sticky） (#5020)"

---

packages/amis-ui/src/components/Cascader.tsx

joinValues、extractValue 逻辑应该交付给更上层处理，这里不需要处理

fix: 修复 nestedSelect 移动端下选中数据异常问题

---

packages/amis-ui/scss/_properties.scss
packages/amis-ui/scss/themes/_cxd-variables.scss

Theme: 全局变量替换

---

docs/zh-CN/components/tabs.md
packages/amis-ui/scss/components/_dropdown.scss
packages/amis-ui/scss/components/_tabs.scss
packages/amis-ui/src/components/PopOverContainer.tsx
packages/amis-ui/src/components/Tabs.tsx
packages/amis-ui/src/locale/de-DE.ts
packages/amis-ui/src/locale/en-US.ts
packages/amis-ui/src/locale/zh-CN.ts
packages/amis/__tests__/renderers/__snapshots__/calendar.test.tsx.snap
packages/amis/src/renderers/Tabs.tsx

feat: tabs 支持collapseOnExceed 菜单超出多少个时剩余的开始折叠

---

packages/amis-core/src/utils/helper.ts

fix: Form开启trimValues时会将File字段错误转换问题

---

packages/amis-ui/scss/_properties.scss
packages/amis-ui/scss/themes/_cxd-variables.scss

style:amis4.0样式走查

---

packages/amis-ui/scss/_properties.scss

feat: 主题变量修改

---

examples/components/Example.jsx
examples/components/Loading.jsx
packages/amis-ui/src/components/Spinner.tsx
packages/amis/src/renderers/Nav.tsx

feat: 只有最外层组件的loading可以生效 

---

packages/amis-ui/scss/components/_button.scss
packages/amis-ui/scss/themes/_antd-variables.scss

feat: AntD主题对齐

---

packages/amis/src/renderers/Drawer.tsx

fix: 修复drawer组件设置closeOnOutside为false后，点击外部仍能关闭的问题

---

docs/zh-CN/components/form/condition-builder.md
packages/amis-ui/scss/components/form/_selection.scss
packages/amis-ui/src/components/condition-builder/Expression.tsx
packages/amis-ui/src/components/condition-builder/Field.tsx
packages/amis-ui/src/components/condition-builder/Group.tsx
packages/amis-ui/src/components/condition-builder/GroupOrItem.tsx
packages/amis-ui/src/components/condition-builder/Item.tsx
packages/amis-ui/src/components/condition-builder/index.tsx

* feat: ConditionBuilder组件左侧选项支持树形结构
* patch: version for condition-builder.md selectMode
Co-authored-by: wutong25 <wutong25@baidu.com>
Co-authored-by: RUNZE LU <36724300+lurunze1226@users.noreply.github.com>

feat: ConditionBuilder组件左侧选项支持树形结构 (#5342)

---

docs/zh-CN/components/log.md
fis-conf.js
packages/amis-formula/package.json
packages/amis-ui/package.json
packages/amis/package.json
packages/amis/src/renderers/Log.tsx

1. 这个模块性能差
2. 这个模块不支持 react 18

chore: 去除 ansi-to-react 依赖，日志模块不再提供高亮功能

---

examples/components/Example.jsx
examples/components/Loading.jsx
packages/amis-ui/src/components/Button.tsx
packages/amis-ui/src/components/Spinner.tsx
packages/amis/__tests__/renderers/__snapshots__/Page.test.tsx.snap
packages/amis/src/renderers/Nav.tsx

feat: 多个 Spinner 处于 loading 状态时, 只有最外层元素处在 loading 状态 (#5096)

---

packages/amis-ui/src/components/condition-builder/Field.tsx

fix: conditionBuilder ts类型报错修改

---

packages/amis-formula/src/evalutor.ts

fix：https://github.com/baidu/amis/pull/5410

fix: 修复金额组件转换问题

---

packages/amis/src/renderers/Form/InputImage.tsx

修复问题：https://github.com/baidu/amis/issues/5097

input-image 图片上传回显问题修复

---

docs/zh-CN/components/form/picker.md
examples/components/Form/Picker.jsx
packages/amis/src/renderers/Form/Picker.tsx

New item click event handler for items the picker. This solves issue #1616 
选择器的项目的新项目单击事件处理程序。这解决了问题 #1616

feat: Added item click event to picker 

---

docs/zh-CN/components/form/index.md

docs: Form组件debug区域配置项说明

---

docs/zh-CN/components/date.md

docs: 修复Date日期组件文档错误

---

docs/zh-CN/components/form/formitem.md
packages/amis-core/src/renderers/Form.tsx

- docs: 增加静态展示态相关文档
- fix: 修改表单项静态展示配置优先级

chore: 修改表单项静态展示配置优先级; docs: 增加静态展示态相关文档

---

packages/amis-core/src/index.tsx

chore: 调整useMobileUI参数判断

---

fis-conf.js

react-hook-form
qrcode.react 
<https://github.com/baidu/amis/issues/4644>

chore: 修正 react-hook-form 及 qrcode 未 ES5 编译问题

---

docs/zh-CN/start/getting-started.md

docs: 文档-快速开始-切换主题，不必要的文字

---

docs/zh-CN/components/log.md

fix: log文档

---

packages/amis-core/src/utils/filter.ts

feat: bytes 过滤器 支持指定 step

---

packages/amis-core/src/types.ts
packages/amis-core/src/utils/renderer-event.ts

feat: debounce event

---

packages/amis-core/src/factory.tsx
packages/amis-core/src/index.tsx
packages/amis-core/src/renderers/register.ts

feat: 增加动态注册渲染器机制

---

docs/zh-CN/components/mapping.md
packages/amis/__tests__/renderers/Mapping.test.tsx
packages/amis/__tests__/renderers/__snapshots__/Mapping.test.tsx.snap
packages/amis/src/renderers/Mapping.tsx

[设计文档](https://ku.baidu-int.com/knowledge/HFVrC7hq1Q/tQvrZcAEPS/GxsYWwEpj5/TADM065whtCNDX)

feat: mapping组件支持数组数据源,自定义渲染模板itemSchema

---

packages/amis-ui/src/components/Tinymce.tsx

Add autoresize plugin for tinymce component

---

docs/zh-CN/components/form/treeselect.md

doc: TreeSelect文档调整

---

packages/amis-ui/src/components/Tree.tsx
packages/amis/__tests__/renderers/Tree.test.tsx

- 点开第一个defer节点后，收起第一个defer节点
- 点开第二个defer节点后，第一个节点会跟着展开

fix: 修复 tree 配置了 defer 属性时，展开错误

---

packages/amis-ui/src/components/GroupedSelection.tsx
packages/amis/src/renderers/Form/Select.tsx

问题详细描述如下：https://github.com/baidu/amis/issues/5979

fix: 修复 select 级联模式和分组模式下 labelField 丢失问题

---

packages/amis-ui/src/components/DateRangePicker.tsx

fix: dateRangePicker 取消问题修复

---

docs/zh-CN/components/status.md
packages/amis/__tests__/renderers/Status.test.tsx
packages/amis/src/renderers/Status.tsx

1. 新增source属性，用类似mapping 映射的方式配置状态的label、icon以及新增的颜色。
2. source属性支持表达式。
3. value属性支持表达式。
4. 优化Icon渲染方式，以支持Editor中新版Icon配置。
5. 兼容旧版配置方式。
```json
// 旧版
{
"type": "status",
"labelMap": {
"normal": "正常",
"unusual": "异常",
},
"map": {
"normal": "fa fa-times-circle",
"unusual": "fa fa-times-circle",
}
"value": "normal"
}
// 新版
{
"type": "status",
"source": {
"normal": {
"label": "正常",
"icon": "fa fa-times-circle",
"color": "#000"
},
"unusual": {
"label": "异常",
"icon": "fa fa-times-circle",
"color": "#f00"
}
},
"value": "normal"
}
```

Status组件新增source属性，优化Icon渲染逻辑

---

packages/amis/src/renderers/Form/Combo.tsx
packages/amis/src/renderers/Form/InputGroup.tsx

fix: 单独使用input-group&Combo静态展示不生效

---

packages/amis-ui/src/components/condition-builder/Value.tsx

问题描述：https://github.com/baidu/amis/issues/5699#issue-1435790156

fix: 修复条件组合组件，自定义类型 value 不回显问题

---

packages/amis-core/src/actions/Action.ts
packages/amis-core/src/actions/DialogAction.ts

feat:config动作优化

---

packages/amis-ui/scss/_components.scss
packages/amis-ui/scss/_properties.scss
packages/amis-ui/scss/components/_tag.scss

[amis-saas-10190]主题组件TAG开发，修改样式文件

faeture:[amis-saas-10190]主题组件TAG开发

---

packages/amis-ui/src/components/Alert.tsx

chore: alert 支持多个实例

---

packages/amis/src/renderers/Icon.tsx

1. icon 支持自定义样式
2. 修复 svg图标不展示的问题。

feat: icon支持自定义样式

---

packages/amis-core/src/utils/dom.tsx

空间足够，正常显示
当四个方向都无法完全可见时，overlay当前是默认放到右下角，
然而 demo中 这种情况，overlay放到左下角比较好，
配合父级的overflow：auto，可以保持功能正常
因此，不得已使用兜底时，通过收集可见位置，动态设置兜底方向比较好
修复后：

fix:完善Overlay弹层自动计算位置的兜底逻辑

---

packages/amis/src/renderers/DropDownButton.tsx
packages/amis/src/renderers/Table/index.tsx

fix: 「组件」「Bug」Dropdown组件hover触发时移开不消失

fix: 「组件」「Bug」Dropdown组件hover触发时移开不消失

---

docs/zh-CN/components/form/location-picker.md
packages/amis-core/src/utils/helper.ts
packages/amis-ui/src/components/GaodeMapPicker.tsx
packages/amis-ui/src/components/LocationPicker.tsx

为 LocationPicker 添加 AMap 支持
LocationPicker 组件缺少对高德地图的支持
* 添加了对高德地图的支持
* 添加了一个工具方法以动态加载样式
* 更新了相应部分的文档

feat: LocationPicker 添加 AMap 支持

---

packages/amis-editor/src/renderer/event-control/helper.tsx

issue地址：https://github.com/baidu/amis/issues/6581

fix: 解决editor 报错 'getVariableOptions' of undefined

---

packages/amis/src/renderers/Form/InputImage.tsx

fix: 修复input-image单选情况报错

---

packages/amis/src/renderers/Form/Group.tsx

crud组件在开启autoGenerateFilter后，会出现组件值被联动覆盖的问题
```
{
"body": {
"type": "crud",
"api": "/amis/api/mock2/sample",
"syncLocation": false,
"autoGenerateFilter": true,
"headerToolbar": [
{
"type": "columns-toggler",
"align": "right",
"draggable": true,
"icon": "fas fa-cog",
"overlay": true,
"footerBtnSize": "sm"
}
],
"columns": [
{
"name": "id",
"label": "ID",
"searchable": {
"name": "id",
"label": "主键",
"placeholder": "输入id"
}
},
{
"name": "engine",
"label": "Rendering engine",
"searchable": {
"name": "engine",
"label": "engine",
"placeholder": "输入engine",
"mode": "horizontal"
}
},
{
"name": "browser",
"label": "Browser",
"searchable": {
"type": "select",
"name": "browser",
"label": "浏览器",
"placeholder": "选择浏览器",
"options": [
{
"label": …
```

fix: 修复table组件自动生成筛选条件渲染错误问题

---

packages/amis-core/src/utils/tokenize.ts
packages/amis-core/src/utils/tpl-builtin.ts
packages/amis-core/src/utils/tpl-lodash.ts
packages/amis-core/src/utils/tpl.ts
packages/amis/__tests__/renderers/Form/inputSubForm.test.tsx
packages/amis/__tests__/renderers/Page.test.tsx
packages/amis/__tests__/renderers/Progress.test.tsx
packages/amis/src/renderers/Tpl.tsx

feat: tpl支持异步表达式

---

packages/amis/src/renderers/Table/HeadCellFilterDropdown.tsx

feat(amis)：CRUD组件列表头过滤时重置页码

---

docs/zh-CN/concepts/event-action.md

增加自定义函数签名示例
方便开发者理解 自定义JS 函数调用

增加自定义函数签名示例

---

docs/zh-CN/extend/contribute.md

docs: 更新 React 官网链接

---

docs/zh-CN/components/drawer.md

docs: 添加 position 默认值示意

---

packages/amis/src/renderers/Form/InputNumber.tsx

- 修改 `showSteps` 注释
- 修正 Docs 链接
- 增加字段上下间的空白行
原注释毫无意义

docs: 调整 showSteps 注释

---

docs/zh-CN/components/form/input-number.md

整体更新 input-number 文档。
缺少必要的描述与示意。
- 优化排版
- 增入属性默认值与版本示意
- 消除 `"big": "true"` 歧义使用

docs: 更新 input-number 文档

---

packages/amis-editor/src/renderer/TimelineItemControl.tsx

feat(amis-editor): timeline组件配置面板增加关联上下文配置

---

packages/amis/src/renderers/Timeline.tsx

fix: 编译时ts报错 timelineitem.d.ts has not been built from soure file 'amis-ui/src/components/TimelineItem.tsx'

chore: 删去timelineitem引入的声明

---

packages/amis-core/src/utils/helper.ts
packages/amis-editor-core/src/util.ts

chore: 优化编辑器工具函数逻辑

---

docs/zh-CN/concepts/event-action.md

update 'for' replace  with 'loop' in event-action.md
update 'for' replace  with 'loop' in event-action.md
update 'for' replace  with 'loop' in event-action.md

update 'for' replace  with 'loop' in event-action.md

---

packages/amis-core/src/RootRenderer.tsx

之前在 constructor 里面绑定了不需要绑定的函数，这次去掉了

refactor: 重构了 RootRenderer.tsx 的 render 方法， 已自测

---

packages/amis-core/src/store/table.ts

Reverts baidu/amis#5236
Close: #8096

Revert "fix: table 添加 toggled: false 的列不参与持久化" Close: #8096

---

packages/amis-editor/src/plugin/Cards.tsx
packages/amis-editor/src/plugin/Each.tsx
packages/amis-editor/src/plugin/List2.tsx

- 去除循环组件冗余外观配置
- 优化左侧面板列表类型组件预览样式，通过缩放来确保展示完全

fix(amis-editor): 修复列表类型组件预览及配置

---

packages/amis-core/src/components/CustomStyle.tsx
packages/amis-editor-core/src/manager.ts
packages/amis-editor-core/src/util.ts

fix: 修复组件拖入时未递归生成id导致样式丢失问题

---

packages/amis-core/src/actions/DrawerAction.ts
packages/amis-editor-core/src/component/factory.tsx
packages/amis-editor-core/src/store/editor.ts
packages/amis-editor-core/src/util.ts
packages/amis-editor/src/renderer/event-control/helper.tsx
packages/amis-editor/src/renderer/event-control/index.tsx

修复历史数据dialog schema没有type兼容
修复编辑态聚焦事件等触发抽屉
新建弹窗切换到打开弹窗过滤自身

fix:修复历史数据dialog没有type的兼容

---

packages/amis-editor-core/src/component/Preview.tsx
packages/amis-editor-core/src/component/factory.tsx
packages/amis-editor-core/src/util.ts
packages/amis-editor/src/renderer/event-control/helper.tsx
packages/amis-editor/src/renderer/event-control/index.tsx

修复选择现有弹窗出现报错
修复新建弹窗后异步导致弹窗没有进入编辑的问题

fix: 修复选择现有弹窗的报错以及弹窗ref替换不全的问题

---

packages/amis/src/renderers/Json.tsx

fix: JSON 组件缺失的属性说明

---

packages/amis-editor-core/src/component/factory.tsx
packages/amis-editor/src/plugin/Drawer.tsx
packages/amis-editor/src/tpl/options.tsx
packages/amis-ui/scss/components/_modal.scss
packages/amis-ui/src/components/Modal.tsx
packages/amis/src/renderers/Form/Combo.tsx

修复弹窗尺寸自定义时媒体查询限制的最大宽度显示
修复弹窗数据映射下的key\value输入配置栏自动清空数据
修复抽屉位置和宽高设置的关系

fix:修复弹窗自定义宽度时媒体查询max-width限制宽度显示

---

packages/amis-editor-core/src/util.ts
packages/amis-editor/src/renderer/event-control/action-config-panel.tsx
packages/amis-editor/src/renderer/event-control/comp-action-select.tsx
packages/amis-editor/src/renderer/event-control/helper.tsx

修复弹窗不再打开子编辑器在组件动作里选不到弹窗之外的组件问题的临时兼容，增加一个输入框让用户可以自己输入组件id，
修复弹窗大纲隐藏属性携带弹框schema出现重复的问题

fix:修复组件特性动作无法选中弹窗之外组件的兼容

---

packages/amis-editor/src/plugin/Form/InputDate.tsx

fix：
日期组件编辑器初始默认值（input-date / input-time）

fix(amis-editor): 日期组件配置面板格式初始值不正确

---

docs/zh-CN/components/image.md
packages/amis-editor/src/plugin/Image.tsx
packages/amis-editor/src/renderer/event-control/helper.tsx
packages/amis/__tests__/renderers/Image.test.tsx
packages/amis/__tests__/renderers/__snapshots__/Image.test.tsx.snap
packages/amis/__tests__/renderers/__snapshots__/Table.test.tsx.snap
packages/amis/src/renderers/Image.tsx
packages/amis/src/types.ts

https://ku.baidu-int.com/knowledge/HFVrC7hq1Q/tQvrZcAEPS/GxsYWwEpj5/puZv4Q7O4IVnAm
| 中文 |  支持图片点击/鼠标移入移出事件 & 支持图片预览放大缩小动作  |

feat: 支持图片点击/鼠标移入移出事件 & 支持图片预览放大缩小动作

---

packages/amis-editor/src/plugin/Form/LocationPicker.tsx

2. 检查PR提交信息
⚠️dev分支已弃用，这里选择master分支
3. 提交成功后，你就可以在[AMIS](https://github.com/baidu/amis/pulls)仓库的Pull requests下看到自己提交的PR了
3. 在PR中附上本次提交的相关信息
相关模版如下：

feat: location-picker-editor 取消输入框样式

---

packages/amis-editor/src/plugin/Form/LocationPicker.tsx

feat: location-picker-editor 地图ak支持变量映射

---

packages/amis-editor/src/plugin/Form/InputTree.tsx
packages/amis-editor/src/plugin/Form/TreeSelect.tsx

fix: 树组件默认使用内嵌模式

---

pull_request_template.md

https://githubnext.com/copilot-for-prs-sunset

chore: Copilot for Pull Request 功能下线了, 删除相关配置

---

packages/amis-core/src/renderers/Form.tsx

fix: Form 数据同步改为lazyEmitChange

---

packages/amis/src/renderers/Form/InputTable.tsx

pick: fix: 修复 inputTable 在列中表单项有默认值的情况下无法新增的问题

---

packages/amis/src/renderers/Form/InputTable.tsx

fix: 修复 inputTable 在列中表单项有默认值的情况下无法新增的问题

---

packages/amis-ui/src/locale/zh-CN.ts
packages/amis/__tests__/renderers/__snapshots__/CRUD.test.tsx.snap
packages/amis/__tests__/renderers/__snapshots__/Pagination.test.tsx.snap

chore: 分页组件 go 字符翻译

---

packages/amis-editor/src/plugin/Form/Static.tsx
packages/amis-editor/src/plugin/Others/TableCell.tsx
packages/amis-editor/src/plugin/TableCell2.tsx
packages/amis/src/compat.ts

fix:快读编辑弹窗多层嵌套、立即保存失效

---

packages/amis-ui/scss/_components.scss
packages/amis-ui/scss/components/form/_checks.scss

style: 优化checkbox组件样式

---

packages/amis/src/renderers/Table/TableCell.tsx
packages/amis/src/renderers/Table2/index.tsx

https://github.com/baidu/amis/pull/8392 已经让所有组件都支持 classNameExpr 了，原先的逻辑要删掉避免出现两个相同的 className

chore: classNameExpr 已经所有组件都支持,不需要单独处理了 Closes #3869

---

packages/amis/src/renderers/Table2/index.tsx

fix: 修复由#8905引入的row.index丢失问题

---

packages/amis-ui/scss/components/_table.scss

style: 优化table中label字体大小 Close:#8879

---

packages/amis-core/src/components/Overlay.tsx
packages/amis-core/src/components/PopOver.tsx
packages/amis/__tests__/renderers/Form/__snapshots__/inputCity.test.tsx.snap
packages/amis/__tests__/renderers/Form/__snapshots__/inputTag.test.tsx.snap
packages/amis/__tests__/renderers/Form/__snapshots__/repeat.test.tsx.snap
packages/amis/__tests__/renderers/Form/__snapshots__/select.test.tsx.snap
packages/amis/__tests__/renderers/Form/__snapshots__/text.test.tsx.snap
packages/amis/__tests__/renderers/__snapshots__/Pagination.test.tsx.snap
packages/amis/__tests__/renderers/__snapshots__/PopOver.test.tsx.snap
packages/amis/__tests__/renderers/__snapshots__/Tabs.test.tsx.snap

fix: PopOver嵌套场景下错误触发hidden事件问题 Close: #9015

---

packages/amis/src/renderers/Form/Combo.tsx

fix: Combo配置flat且成员配置必填后校验无法通过问题

---

packages/amis-core/src/components/Overlay.tsx
packages/amis-core/src/components/PopOver.tsx
packages/amis/__tests__/renderers/Form/__snapshots__/inputCity.test.tsx.snap
packages/amis/__tests__/renderers/Form/__snapshots__/inputTag.test.tsx.snap
packages/amis/__tests__/renderers/Form/__snapshots__/repeat.test.tsx.snap
packages/amis/__tests__/renderers/Form/__snapshots__/select.test.tsx.snap
packages/amis/__tests__/renderers/Form/__snapshots__/text.test.tsx.snap
packages/amis/__tests__/renderers/__snapshots__/Pagination.test.tsx.snap
packages/amis/__tests__/renderers/__snapshots__/PopOver.test.tsx.snap
packages/amis/__tests__/renderers/__snapshots__/Tabs.test.tsx.snap
packages/amis/src/renderers/Form/Combo.tsx

cherry-pick: #9022 #9027

---

packages/amis-theme-editor-helper/package.json
packages/amis-theme-editor-helper/src/index.ts

fix: 修复外观样式选择器未国际化问题

---

docs/zh-CN/components/log.md
mock/cfc/mock/log/app.js
mock/cfc/mock/log/date.js
packages/amis-core/src/store/crud.ts
packages/amis-core/src/store/form.ts
packages/amis-core/src/store/iRenderer.ts
packages/amis-core/src/store/service.ts
packages/amis-core/src/store/table2.ts
packages/amis-core/src/types.ts
packages/amis-core/src/utils/concatData.ts
packages/amis-core/src/utils/index.ts
packages/amis/__tests__/renderers/Form/service.test.tsx
packages/amis/src/renderers/Log.tsx
packages/amis/src/renderers/Service.tsx

feat: api 添加 concatDataFields 配置支持多次请求将数据字段自动合并功能

---

packages/amis-core/src/utils/renderer-event.ts

fix:修复api query包含event变量报错的问题

---

packages/amis-core/src/utils/style-helper.ts
packages/amis-editor/src/plugin/Button.tsx
packages/amis-editor/src/plugin/Form/InputImage.tsx
packages/amis-editor/src/plugin/Form/Picker.tsx
packages/amis-editor/src/renderer/style-control/helper.tsx
packages/amis-editor/src/tpl/style.tsx
packages/amis-theme-editor-helper/src/renderers/Border.tsx
packages/amis-theme-editor-helper/src/renderers/ColorPicker.tsx
packages/amis-theme-editor-helper/src/renderers/Font.tsx
packages/amis-theme-editor-helper/src/renderers/PaddingAndMargin.tsx
packages/amis-theme-editor-helper/src/renderers/Radius.tsx
packages/amis-theme-editor-helper/src/renderers/Shadow.tsx

fix: 外观值继承修复

---

packages/amis-editor/src/plugin/Form/InputTree.tsx
packages/amis-editor/src/plugin/Form/TreeSelect.tsx

fix(editor): tree组件配置面板去除只读配置

---

packages/amis-editor/src/plugin/Mapping.tsx

fix: editor中mapping组件配置的itemSchema无法预览隐藏态无法选中

---

packages/amis/src/renderers/QuickEdit.tsx

chore: inputTable 中单元格数据没有差异时不触发变更

---

packages/amis-ui/scss/_components.scss
packages/amis-ui/scss/components/form/_tag.scss

styles: InputTag下拉浮层添加最大高度避免超出屏幕

---

packages/amis-ui/src/components/SelectMobile.tsx

fix: Select移动端组件多选且设置menuTpl时无法选择 Close: #9005

---

packages/amis-editor-core/src/component/NodeWrapper.tsx
packages/amis-editor/src/plugin/CRUD2/BaseCRUD.tsx
packages/amis-editor/src/plugin/CRUD2/constants.ts
packages/amis-editor/src/plugin/Table2.tsx
packages/amis-ui/src/components/table/SummaryRow.tsx
packages/amis-ui/src/components/table/index.tsx
packages/amis/src/renderers/Table2/index.tsx

feat(amis-editor): CRUD2组件支持Mock配置&最大展示条数

---

packages/amis-ui/src/components/RichText.tsx
packages/amis-ui/src/components/Tinymce.tsx
packages/amis/src/renderers/Form/InputRichText.tsx

fix: 修复rich-text更新挂载异常问题

---

packages/amis-editor/src/renderer/event-control/index.tsx

fix:解决事件动作面板卡顿问题

---

packages/amis-editor/src/renderer/event-control/index.tsx

fix:解决事件动作面板卡死问题

---

packages/amis-ui/src/components/Collapse.tsx
packages/amis-ui/src/components/CollapseGroup.tsx
packages/amis/src/renderers/Collapse.tsx

fix(amis-ui): 修复collapse-group组件特性动作/收起 执行异常问题

---

docs/zh-CN/components/form/formitem.md

doc: 添加 strictMode 的说明

---

packages/amis-core/src/actions/Action.ts

fix:列表类组件更新指定行记录condition失效问题

---

docs/zh-CN/components/form/index.md
docs/zh-CN/concepts/event-action.md
packages/amis-core/src/actions/CmptAction.ts
packages/amis-editor/src/renderer/event-control/helper.tsx

fix: 修复表单项校验动作类型判断及editor中outputVar问题

---

packages/amis-editor-core/scss/editor.scss
packages/amis-editor-core/src/component/Preview.tsx

fix(amis-editor): 修复设计器切换预览按钮后选中组件变更的问题

---

packages/amis-editor/src/plugin/Chart.tsx
packages/amis/src/renderers/Chart.tsx

1. fix(amis): 修复chart配置定时刷新后出现死循环问题；
2. feat(amis): chart mapURL支持联动。

chart组件功能优化

---

docs/zh-CN/components/table.md
docs/zh-CN/components/table2.md
packages/amis-core/src/store/table2.ts
packages/amis-ui/package.json
packages/amis-ui/scss/components/_table2.scss
packages/amis-ui/src/components/table/HeadCellFilter.tsx
packages/amis-ui/src/components/table/Row.tsx
packages/amis-ui/src/components/table/index.tsx
packages/amis/src/renderers/Table2/ColumnToggler.tsx
packages/amis/src/renderers/Table2/HeadCellSearchDropdown.tsx
packages/amis/src/renderers/Table2/index.tsx

fix: crud2搜索表单和列搜索参数同步问题修复、table2渲染性能优化、table2完善事件动作以及相关文档

---

packages/amis-editor-core/src/component/factory.tsx
packages/amis-editor-core/src/plugin.ts
packages/amis-editor/src/plugin/CRUD2/BaseCRUD.tsx
packages/amis-editor/src/plugin/Form/Form.tsx
packages/amis-editor/src/plugin/Service.tsx

perf(amis-editor): 配置面板中外部注册数据源变化时按需构建

---

packages/amis-ui/src/components/DateRangePicker.tsx
packages/amis-ui/src/components/calendar/Calendar.tsx

fix: InputDateRange开启内嵌模式选择日期错误问题

---

packages/amis-ui/src/components/formula/Input.tsx

fix: InputFormula组件allowInput属性未透传问题

---

package.json
packages/amis-theme-editor-helper/i18nConfig.js
packages/amis-theme-editor-helper/package.json

chore: 更新theme-editor依赖

---

packages/amis/src/renderers/QRCode.tsx

fix: 修复 qrcode 下载不支持 codeSize 配置

---

docs/zh-CN/components/crud.md
packages/amis/src/renderers/Table/exportExcel.ts

chore: CRUD组件导出Excel时默认隐藏操作列  Close #8067

---

docs/zh-CN/components/form/input-file.md
docs/zh-CN/components/form/input-image.md

docs: InputFile & InputImage补充autoUpload、hideUploadButton属性Demo

---

docs/zh-CN/components/form/input-text.md
package.json
packages/amis-core/__tests__/jest.setup.js
packages/amis-core/package.json
packages/amis-ui/examples/App.tsx
packages/amis-ui/examples/basic/OverflowTpl.tsx
packages/amis-ui/scss/components/_overflow-tpl.scss
packages/amis-ui/scss/themes/_common.scss
packages/amis-ui/src/components/DateRangePicker.tsx
packages/amis-ui/src/components/OverflowTpl.tsx
packages/amis-ui/src/components/index.tsx
packages/amis/__tests__/renderers/Form/__snapshots__/text.test.tsx.snap
packages/amis/__tests__/renderers/Form/text.test.tsx
packages/amis/src/renderers/Form/InputText.tsx

feat: InputText多选模式下的tag自适应展示tooltip(OverflowTpl)

---

packages/amis-ui/scss/components/_dropdown.scss

style: 修复DropDownButton下拉选项禁用样式

---

packages/amis-editor/src/plugin/Icon.tsx
packages/amis-ui/src/components/icons.tsx
packages/amis/__tests__/event-action/renderers/icon.test.tsx
packages/amis/__tests__/renderers/__snapshots__/Action.test.tsx.snap
packages/amis/__tests__/renderers/__snapshots__/Breadcrumb.test.tsx.snap
packages/amis/__tests__/renderers/__snapshots__/Page.test.tsx.snap

cherry-pick feat: icon支持配置事件动作

---

packages/amis-ui/src/components/DateRangePicker.tsx

fix: 修复最大时间约束不了时间范围选择器的结束时间问题

---

packages/amis-ui/src/components/DateRangePicker.tsx

fix: 修复最大时间约束不了时间范围选择器的结束时间问题 (#9154)

---

packages/amis-ui/scss/components/form/_fieldset.scss

fix: 修复fieldset设置边框样式后，再设置大小，边框样式不生效问题

---

docs/zh-CN/extend/ui-library.md

docs: fix example code in ui-library.md

---

packages/amis/__tests__/renderers/Dialog.test.tsx
packages/amis/src/renderers/Dialog.tsx
packages/amis/src/renderers/Drawer.tsx

修复弹窗中做 url 调整动作异常问题。并补充两个 issue 用例
Close: #9149、#9142

fix: 修复 dialog 内部做常规动作没反应的问题 Close: #9149

---

packages/amis-ui/scss/_properties.scss
packages/amis-ui/scss/components/_menu.scss
packages/amis-ui/scss/components/form/_date-range.scss
packages/amis-ui/scss/components/form/_textarea.scss

style:深色模式 变量替换

---

packages/amis-core/src/utils/style-helper.ts

fix: 修复主题配置icon失败问题

---

packages/amis-core/src/store/table.ts
packages/amis-ui/scss/_components.scss
packages/amis-ui/src/components/PopOverContainer.tsx
packages/amis-ui/src/components/condition-builder/Item.tsx
packages/amis-ui/src/components/formula/VariableList.tsx

fix: 修复 table 的 column 的 id 属性可能重复导致样式错误的问题

---

packages/amis-core/src/store/list.ts
packages/amis-core/src/store/table.ts

fix: 修复 picker 点选时无法区分 false 和 数字 0 的问题

---

packages/amis-editor/src/builder/ApiDSBuilder.ts

chore(amis-editor): 数据源构造器基于接口生成字段逻辑对齐CRUD的fetch逻辑

---

packages/amis-editor/src/plugin/CRUD.tsx

fix(amis-editor): CRUD组件工具栏配置内容被遮挡问题

---

docs/zh-CN/components/table.md
docs/zh-CN/components/table2.md
packages/amis-ui/scss/components/_table.scss
packages/amis-ui/scss/components/_table2.scss
packages/amis-ui/src/components/table/Head.tsx
packages/amis/__tests__/renderers/Form/__snapshots__/inputTable.test.tsx.snap
packages/amis/src/renderers/Table/index.tsx

fix: Table、Table2组件列固定宽度时禁止拖拽伸缩

---

packages/amis-ui/src/components/condition-builder/Item.tsx
packages/amis-ui/src/components/formula/Editor.tsx
packages/amis-ui/src/components/formula/Input.tsx
packages/amis/__tests__/renderers/Form/conditionBuilder.test.tsx

fix: ConditionBuilder使用公式编辑器切换类型异常问题

---

docs/zh-CN/components/crud.md
packages/amis-core/src/store/crud.ts
packages/amis/__tests__/renderers/CRUD.test.tsx
packages/amis/__tests__/renderers/Form/conditionBuilder.test.tsx
packages/amis/src/renderers/CRUD.tsx

fix: CRUD组件触发reload后已选项未清空问题

---

packages/amis-core/src/actions/Action.ts

fix:兼容dispatchEvent数据未定义的情况

---

packages/amis-editor/src/plugin/Form/Static.tsx
packages/amis-editor/src/plugin/Others/TableCell.tsx
packages/amis-editor/src/plugin/TableCell2.tsx

fix(amis-editor)：模型列表配置快速编辑，默认生成【包裹】容器，点击绑定字段组件，默认选中【包裹】

---

packages/amis-editor/src/plugin/Form/Static.tsx
packages/amis-editor/src/plugin/Others/TableCell.tsx
packages/amis-editor/src/plugin/TableCell2.tsx

amis-saas-15645 [Bug]：[模型列表]配置快速编辑，默认生成【包裹】容器，点击绑定字段组件，默认选中【包裹】

---

packages/amis-core/src/types.ts
packages/amis-core/src/utils/renderer-event.ts
packages/amis-editor/src/renderer/event-control/index.tsx
packages/amis-editor/src/renderer/event-control/types.ts

feat: 事件动作支持上报埋点

---

packages/amis/__tests__/renderers/CRUD.test.tsx
packages/amis/src/renderers/Table/Cell.tsx

fix: 表格数据源更新由嵌套切换为非嵌套单元格未更新问题修复

---

packages/amis/__tests__/renderers/Form/nestedSelect.test.tsx
packages/amis/src/renderers/Form/NestedSelect.tsx

fix: NestedSelect级联下拉开启onlyChildren&onlyleaf后，导致下拉最后一项默认选中问题

---

packages/amis-ui/src/components/NumberInput.tsx
packages/amis/__tests__/renderers/Form/number.test.tsx
packages/amis/src/renderers/Form/InputNumber.tsx

fix: 修复有单位时默认值不对,点击事件阻止冒泡

---

package.json
packages/amis-editor-core/package.json
packages/amis-editor/package.json

cherry-pick: #8838

---

packages/amis/src/renderers/Table/exportExcel.ts

fix: 修复 export-excel 中 mapping 不支持 array 格式 map 问题 Closes #9136

---

packages/amis/src/renderers/Form/InputNumber.tsx

fix: input-number 在大数输入下不处理精度 Closes #6334

---

packages/amis/src/renderers/Form/InputNumber.tsx

fix: InputNumber更新逻辑变更

---

packages/amis/src/renderers/Form/InputNumber.tsx

fix: InputNumber更新逻辑变更，修复setValue时单位丢失问题

---

packages/amis-editor-core/scss/editor.scss

feat: editor 设计器 page 撑开画布区

---

docs/zh-CN/components/progress.md
packages/amis-editor/src/plugin/Progress.tsx
packages/amis-ui/src/components/Progress.tsx
packages/amis/__tests__/renderers/Progress.test.tsx
packages/amis/__tests__/renderers/__snapshots__/Progress.test.tsx.snap
packages/amis/src/renderers/Progress.tsx

feat: Progress组件支持事件动作

---

packages/amis-core/__tests__/utils/math.test.ts
packages/amis-core/src/utils/math.ts
packages/amis/src/renderers/Form/InputNumber.tsx

小数光标漂移问题
git cherry-pick cccca16e258ac616c11b7d697b9416b3975aca07
git cherry-pick 9f1941f4332c52ecc7aa05d88f1e09c448bf8656

cherry-pick  fix(amis) input-number 小数光标漂移问题

---

docs/zh-CN/components/crud.md
docs/zh-CN/components/table.md
packages/amis-ui/scss/components/_cards.scss
packages/amis-ui/scss/components/_list.scss
packages/amis-ui/scss/components/_table.scss
packages/amis/src/renderers/Cards.tsx
packages/amis/src/renderers/List.tsx
packages/amis/src/renderers/Table/index.tsx

feat: CRUD & 与其搭配的 table,cards,list三种模式支持配置 affixFooter

---

docs/zh-CN/components/tabs.md
packages/amis/src/renderers/Tabs.tsx

fix:修复tabs激活卡片动作失效问题

---

packages/amis/src/renderers/Table2/index.tsx

fix: 修复table2行内无法获取全局参数Close:#9177

---

packages/amis-ui/scss/components/form/_result-list.scss
packages/amis-ui/scss/components/form/_selection.scss

style: transfer结果选择添加hover样式&字体居中

---

packages/amis-editor-core/src/util.ts

fix(amis-editor): reGenerateID细节优化，避免多余的二次遍历

---

packages/amis-editor/src/plugin/Dialog.tsx

fix: 兼容字段类型不同导致的报错

---

packages/amis-ui/src/components/DateRangePicker.tsx
packages/amis/__tests__/renderers/Form/datetimeRange.test.tsx

fix: InputDateTimeRanege组件首次选择后无法选择0点问题

---

packages/amis-editor/src/renderer/event-control/action-config-dialog.tsx

fix:可见性、可用性动作配置字段校验失效

---

packages/amis-core/src/utils/style-helper.ts
packages/amis-ui/src/components/calendar/Calendar.tsx
packages/amis/__tests__/renderers/calendar.test.tsx

fix: 修复移动端日期选择完年月无法关闭浮窗的问题

---

packages/amis-editor-core/src/manager.ts
packages/amis-editor/src/plugin/CRUD.tsx
packages/amis-editor/src/plugin/CRUD2/BaseCRUD.tsx
packages/amis-editor/src/plugin/Form/Combo.tsx
packages/amis-editor/src/plugin/Form/Form.tsx
packages/amis-editor/src/plugin/Form/InputTable.tsx
packages/amis-editor/src/plugin/Page.tsx
packages/amis-editor/src/plugin/Service.tsx
packages/amis-editor/src/plugin/Table.tsx
packages/amis-editor/src/plugin/Table2.tsx

fix:修复上下文重复问题

---

packages/amis-editor-core/src/plugin.ts
packages/amis-editor/src/plugin/Form/InputTree.tsx
packages/amis-editor/src/plugin/Form/Select.tsx
packages/amis-editor/src/plugin/Form/TreeSelect.tsx
packages/amis-editor/src/renderer/event-control/index.tsx
packages/amis-editor/src/util.ts

chore:组件事件列表支持动态构建

---

packages/amis-core/src/store/crud.ts
packages/amis/__tests__/renderers/__snapshots__/CRUD.test.tsx.snap

fix:修复crud unSelectedItems无法在公式内解析问题

---

packages/amis-editor/src/renderer/event-control/helper.tsx

fix: 重新请求数据动作数据是否追加参数&合并数据方式处理

---

packages/amis-ui/scss/components/_menu.scss
packages/amis-ui/scss/components/_nav.scss

fix: nav深色模式颜色优先级调整

---

packages/amis-editor/src/plugin/Nav.tsx
packages/amis/__tests__/renderers/__snapshots__/Action.test.tsx.snap
packages/amis/__tests__/renderers/__snapshots__/Breadcrumb.test.tsx.snap
packages/amis/__tests__/renderers/__snapshots__/Page.test.tsx.snap

fix: nav增加文字外观

---

packages/amis-editor-core/package.json
packages/amis-editor/package.json

fix: 开发态固定主题编辑器版本

---

packages/amis/__tests__/renderers/Form/__snapshots__/transfer.test.tsx.snap
packages/amis/__tests__/renderers/Form/datetimeRange.test.tsx
packages/amis/__tests__/renderers/Form/nestedSelect.test.tsx
packages/amis/__tests__/renderers/Form/transfer.test.tsx

chore: 去掉单测中多余的only

---

packages/amis-editor/src/plugin/Form/Combo.tsx

fix:字段集中有combo组件就打不开动作面板

---

packages/amis-theme-editor-helper/src/renderers/PaddingAndMargin.tsx
packages/amis-theme-editor-helper/src/style/_padding-and-margin.scss

pref: 内外边距外观组件优化

---

docs/zh-CN/components/crud.md
examples/components/CRUD/ExportCSVExcel.jsx
packages/amis-ui/src/locale/de-DE.ts
packages/amis-ui/src/locale/en-US.ts
packages/amis-ui/src/locale/zh-CN.ts
packages/amis/package.json
packages/amis/src/renderers/Table/exportExcel.ts
packages/amis/src/renderers/Table/index.tsx

feat: CRUD 支持导出 Excel 模板 Closes #9157

---

packages/amis-ui/scss/components/form/_number.scss

style: 修复number组件单位换行问题 Close#9251

---

packages/amis-core/src/store/crud.ts

revert:crud unSelectedItems无法被表达式解析问题

---

packages/amis-editor/src/plugin/Dialog.tsx
packages/amis-editor/src/renderer/event-control/action-config-dialog.tsx

fix: 弹窗配置字段兼容性问题 && 可见性、可用性动作配置字段校验

---

packages/amis/__tests__/renderers/Nav.test.tsx
packages/amis/__tests__/renderers/__snapshots__/Nav.test.tsx.snap
packages/amis/src/renderers/Nav.tsx

fix: nav updateItems动作支持valueField属性

---

packages/amis-editor/src/renderer/event-control/helper.tsx

cherry-pick(amis-editor): 重新请求数据动作数据是否追加参数&合并数据方式处理

---

packages/amis/src/renderers/CRUD2.tsx

fix: crud2自定义列无法关闭问题修复Close:#9283

---

packages/amis/__tests__/renderers/__snapshots__/CRUD.test.tsx.snap

revert:crud test

---

packages/amis-editor-core/src/store/editor.ts

fix: Editor中setSchema DiffArray处理增加$$id时判断数组成员的类型

---

packages/amis-editor/src/plugin/CRUD.tsx

fix(amis-editor): CRUD脚手架接口返回示例修正

---

packages/amis-editor/src/util.ts

fix:(amis-editor)修复添加动作 (#9355)

---

packages/amis-ui/scss/layout/_layout.scss

fix: layout aside滚动条兼容性问题

---

packages/amis/src/renderers/OfficeViewer.tsx

fix: 修复 office-viewer 变量替换里公式不生效问题 Closes #9276

---

docs/zh-CN/components/crud.md
packages/amis-core/src/store/table.ts
packages/amis/__tests__/renderers/__snapshots__/CRUD.test.tsx.snap
packages/amis/src/renderers/CRUD.tsx
packages/amis/src/renderers/Table/index.tsx

feat: 新增maxItemSelectionLength支持单独配置当前页最大勾选数

---

docs/zh-CN/components/crud.md
packages/amis-ui/scss/components/_table.scss
packages/amis/__tests__/renderers/CRUDFilterable.test.tsx
packages/amis/src/renderers/Table/HeadCellFilterDropdown.tsx

feat: crud 的 filterable 支持 searchable

---

packages/amis/src/renderers/Table/ColumnToggler.tsx

fix: 修复使用列切换功能引发的 mst 报错问题

---

packages/amis-ui/src/components/InputBox.tsx

fix(amis-ui): 修复inputBox默认值0或者false不回现问题

---

packages/amis-core/src/RootRenderer.tsx
packages/amis-editor/src/renderer/event-control/helper.tsx

1. fix(editor): 通过nav切换页面时，CRUD2组件修改url参数导致页面参数默认值异常的问题
2. fix(editor): 事件动作 - 变量赋值页面变量名称统一

fix(editor): 通过nav切换页面时，CRUD2组件修改url参数导致页面参数默认值异常的问题

---

packages/amis-editor/src/renderer/textarea-formula/plugin.tsx

fix: 调整tpl输入框表达式匹配规则

---

packages/amis-core/src/utils/highlight.tsx
packages/amis-core/src/utils/index.ts
packages/amis-core/src/utils/labelToString.ts
packages/amis-core/src/utils/string2regExp.ts
packages/amis-ui/src/components/Select.tsx

select 的 label 为对象时 react 会报错，需要提取一段字符串

fix: select 的 label 为对象时渲染异常

---

packages/amis-core/src/index.tsx
packages/amis-core/src/utils/replaceText.ts

chore: 修改 replaceText 的实现,减少没必要的 deepClone

---

packages/amis-editor/src/plugin/Table.tsx

showHeader & showFooter 不配置默认应该为 true

fix: Table 编辑器面板初始顶部&底部是否初始选中问题修复

---

packages/amis-core/src/renderers/wrapControl.tsx
packages/amis/__tests__/renderers/Form/formitem.test.tsx

fix: 修复单元格中直接放表单项可能取不到值的问题

---

README.md
package.json

chore: 升级发版脚本版本

---

packages/amis/src/renderers/Form/Checkboxes.tsx

chore: checkboxes 显示 loading 当选项在加载过程中

---

packages/amis/src/renderers/Form/Combo.tsx

fix: 修复 combo nullable 清空失败的问题

---

packages/amis-editor-core/src/store/node.ts

fix: 修复 #9418 调整带来的编辑器预览错误问题

---

packages/amis-editor-core/src/store/node.ts

fix: 修复 #9418 调整带来的编辑器预览错误问题 (#9427)

---

packages/amis-editor-core/src/component/ContainerWrapper.tsx
packages/amis-editor-core/src/store/node.ts

perf: 优化编辑器性能

---

packages/amis-editor-core/src/store/editor.ts

fix: 修复 #9418 调整带来的点选双重身份的组件时选中的是孩子的问题

---

packages/amis-editor-core/src/component/ContainerWrapper.tsx
packages/amis-editor-core/src/store/editor.ts
packages/amis-editor-core/src/store/node.ts

Pick: 2112f75d0321485e2583eba474f145653bcd9b79 f45cb590729d48e1b89a5765c5317c4563ed7138

---

packages/amis-editor-core/src/util.ts
packages/amis-editor/src/tpl/layout.tsx

fix(amis-editor): 布局容器相关配置细节优化

---

packages/amis-editor-core/src/util.ts

fix: 清除css错误转成key的属性

---

mock/cfc/mock/crud/table2.js
packages/amis-core/src/store/table.ts

fix: 修复 crud nested 模式深层次点选异常

---

packages/amis-editor-core/src/tpl.tsx
packages/amis-editor/src/index.tsx
packages/amis-editor/src/plugin/Form/Checkbox.tsx
packages/amis-editor/src/plugin/Form/Checkboxes.tsx
packages/amis-editor/src/plugin/Form/MatrixCheckboxes.tsx
packages/amis-editor/src/plugin/Form/Select.tsx
packages/amis-editor/src/renderer/OptionControl.tsx
packages/amis-editor/src/renderer/ValueFormatControl.tsx

fix(editor)：修复部分选择类组件设置选项和默认值方面的问题

---

packages/amis-core/src/utils/helper.ts
packages/amis-ui/src/components/Switch.tsx
packages/amis-ui/src/components/table/Row.tsx
packages/amis/__tests__/renderers/Form/__snapshots__/switch.test.tsx.snap
packages/amis/__tests__/renderers/Form/__snapshots__/valueFormula.test.tsx.snap
packages/amis/__tests__/renderers/__snapshots__/Table.test.tsx.snap

fix:crud2中行记录内switch无法change问题

---

docs/zh-CN/components/form/select.md
packages/amis-ui/src/components/Select.tsx

Select组件加载autoComplete数据时展示loading态
- 现状是缺少loading过渡，导致用户可以在数据加载前选择旧数据
- 加一个过渡态更流畅

feat: Select组件自动补全增加loading中间状态

---

packages/amis/src/renderers/Form/InputText.tsx

fix:input clear时补充change事件 Close  #9436

---

packages/amis-editor/src/plugin/Form/ButtonGroupSelect.tsx
packages/amis-ui/scss/components/_button-group.scss

fix: 取消buttongroupselect默认值展示条件限制 & 配置badge情况下按钮平铺无法自适应

---

packages/amis-editor/src/renderer/TplFormulaControl.tsx

fix(editor): 文本表达式通过${}唤起表达书输入时缺少变量内容

---

packages/amis-editor/src/renderer/event-control/helper.tsx

style(editor): 优化编辑器事件动作表单label样式

---

packages/amis-ui/scss/components/_card.scss

style: 优化 card 卡片样式

---

packages/amis-core/src/utils/helper.ts
packages/amis-core/src/utils/labelToString.ts
packages/amis-core/src/utils/tokenize.ts
packages/amis-core/src/utils/tpl.ts
packages/amis-editor-core/src/plugin/BasicToolbar.tsx
packages/amis-editor-core/src/store/editor.ts
packages/amis-editor-core/src/store/node.ts
packages/amis-formula/src/evalutor.ts
packages/amis-ui/src/components/ContextMenu.tsx
packages/amis/src/compat.ts
packages/amis/src/renderers/Table/Cell.tsx

chore: 优化编辑器选中顶部菜单栏三个点呼出的功能菜单位置,防止被挡住

---

mock/cfc/mock/crud/table2.js
packages/amis-core/src/store/table.ts
packages/amis-core/src/utils/helper.ts
packages/amis-core/src/utils/labelToString.ts
packages/amis-core/src/utils/tokenize.ts
packages/amis-core/src/utils/tpl.ts
packages/amis-editor-core/src/plugin/BasicToolbar.tsx
packages/amis-editor-core/src/store/editor.ts
packages/amis-editor-core/src/store/node.ts
packages/amis-formula/src/evalutor.ts
packages/amis-ui/src/components/ContextMenu.tsx
packages/amis-ui/src/components/condition-builder/Item.tsx
packages/amis/src/compat.ts
packages/amis/src/renderers/Table/Cell.tsx

Pick: #9446、#9440、#9439

---

packages/amis-core/src/renderers/Form.tsx
packages/amis-core/src/renderers/wrapControl.tsx
packages/amis-core/src/store/iRenderer.ts
packages/amis-editor/src/renderer/APIControl.tsx
packages/amis/__tests__/event-action/ajax.test.tsx
packages/amis/src/renderers/Form/Combo.tsx
packages/amis/src/renderers/Form/ConditionBuilder.tsx

fix: 修复 api 编辑输入太快立马弹出详情时出现弹窗空白问题

---

packages/amis-editor-core/src/store/editor.ts

feat: editor增加获取当前SubEditor的方法

---

packages/amis-core/src/store/table.ts
packages/amis/src/renderers/Table/Cell.tsx
packages/amis/src/renderers/Table/TableRow.tsx

fix: 修复CRUD nested 模式展示异常

---

packages/amis-core/src/SchemaRenderer.tsx
packages/amis-core/src/env.tsx
packages/amis-core/src/renderers/Item.tsx
packages/amis-core/src/utils/helper.ts
packages/amis-ui/src/components/InputBox.tsx
packages/amis-ui/src/components/Switch.tsx
packages/amis-ui/src/components/Textarea.tsx
packages/amis/src/renderers/Form/Select.tsx
packages/amis/src/renderers/Form/Switch.tsx
packages/amis/src/renderers/Form/Textarea.tsx

feat: id 默认转testid && editor部分组件配置面板补充testid

---

packages/amis-editor-core/scss/_renderers.scss
packages/amis-theme-editor-helper/src/systemTheme/component.ts
packages/amis-ui/scss/_components.scss
packages/amis-ui/scss/_properties.scss
packages/amis-ui/scss/components/_search-box.scss
packages/amis-ui/scss/components/form/_date.scss
packages/amis-ui/scss/components/form/_list.scss
packages/amis-ui/scss/components/form/_select.scss
packages/amis-ui/scss/components/form/_tag.scss
packages/amis-ui/scss/components/form/_transfer.scss
packages/amis-ui/src/components/DateRangePicker.tsx
packages/amis/__tests__/renderers/Form/__snapshots__/inputMonthRange.test.tsx.snap
packages/amis/__tests__/renderers/Form/__snapshots__/inputQuarterRange.test.tsx.snap
packages/amis/__tests__/renderers/Form/__snapshots__/inputYearRange.test.tsx.snap
packages/amis/__tests__/renderers/Form/dateRange.test.tsx

style: 优化input-tag、input-year-range、list-select等组件样式

---

packages/amis-core/src/components/CustomStyle.tsx
packages/amis-core/src/renderers/Item.tsx
packages/amis-core/src/utils/style-helper.ts
packages/amis-ui/src/components/SparkLine.tsx
packages/amis/src/renderers/Action.tsx
packages/amis/src/renderers/Cards.tsx
packages/amis/src/renderers/Carousel.tsx
packages/amis/src/renderers/Chart.tsx
packages/amis/src/renderers/Container.tsx
packages/amis/src/renderers/Date.tsx
packages/amis/src/renderers/Dialog.tsx
packages/amis/src/renderers/Divider.tsx
packages/amis/src/renderers/Drawer.tsx
packages/amis/src/renderers/Each.tsx
packages/amis/src/renderers/Flex.tsx
packages/amis/src/renderers/Form/InputImage.tsx
packages/amis/src/renderers/Form/InputNumber.tsx
packages/amis/src/renderers/Form/InputText.tsx
packages/amis/src/renderers/Form/Picker.tsx
packages/amis/src/renderers/Grid.tsx
packages/amis/src/renderers/IFrame.tsx
packages/amis/src/renderers/Icon.tsx
packages/amis/src/renderers/Image.tsx
packages/amis/src/renderers/Images.tsx
packages/amis/src/renderers/Page.tsx
packages/amis/src/renderers/SparkLine.tsx
packages/amis/src/renderers/SwitchContainer.tsx
packages/amis/src/renderers/TableView.tsx
packages/amis/src/renderers/TooltipWrapper.tsx
packages/amis/src/renderers/Tpl.tsx

feat: themeCss支持数据域变量,循环数据支持单独样式

---

packages/amis-ui/src/components/icons.tsx

fix: 修复icon组件缺少事件问题

---

packages/amis/src/renderers/Tabs.tsx

fix: issue: 8308 Tabs active 激活问题

---

packages/amis/src/renderers/Table/TableCell.tsx

fix(amis): 表格组件/渲染列级元素前，剔除style中的定位相关样式，避免表格样式异常

---

packages/amis-editor/src/plugin/CRUD2/BaseCRUD.tsx
packages/amis-editor/src/plugin/Table2.tsx
packages/amis-editor/src/renderer/crud2-control/CRUDFiltersControl.tsx
packages/amis-ui/src/components/table/Head.tsx

fix: 修复crud2搜索关闭时搜索面板依旧存在问题
feat: table2支持当前行上下文数据
fix: 修复crud2 列选中问题

修复crud2 若干bug

---

packages/amis-editor/src/plugin/Form/InputSubForm.tsx

fix:子表单上下文类型错误

---

packages/amis-ui/src/components/Input.tsx
packages/amis-ui/src/components/Pagination.tsx
packages/amis-ui/src/components/SearchBox.tsx
packages/amis-ui/src/components/Select.tsx
packages/amis-ui/src/components/Tree.tsx
packages/amis/src/renderers/CRUD.tsx
packages/amis/src/renderers/Card.tsx
packages/amis/src/renderers/Form/InputTree.tsx
packages/amis/src/renderers/Form/TreeSelect.tsx

feat(amis): 增加搜索框、树组件、下拉选择中的部分testid

---

packages/amis-ui/scss/components/form/_excel.scss
packages/amis-ui/src/components/NumberInput.tsx
packages/amis-ui/src/components/Select.tsx
packages/amis/src/renderers/Form/InputExcel.tsx
packages/amis/src/renderers/Form/InputNumber.tsx
packages/amis/src/renderers/Form/Select.tsx
packages/amis/src/renderers/Service.tsx
packages/amis/src/renderers/Tpl.tsx

feat: 增加input-number inputExcel service tpl 的部分testid

---

packages/amis-ui/src/components/formula/Input.tsx
packages/amis-ui/src/components/formula/Picker.tsx

fix: 修复condition-builder 中公式值默认不高亮的问题

---

packages/amis-editor/src/plugin/Form/Item.tsx

chore: 优化设计器表单项修改默认值同步展示问题

---

packages/amis/src/renderers/Log.tsx

fix: 修复 log 的 source 是 api object 时不自动加载的问题

---

packages/amis/src/renderers/Card.tsx
packages/amis/src/renderers/Cards.tsx
packages/amis/src/renderers/List.tsx
packages/amis/src/renderers/QuickEdit.tsx
packages/amis/src/renderers/Table/Cell.tsx
packages/amis/src/renderers/Table/index.tsx
packages/amis/src/renderers/Table2/index.tsx

fix: 修复 extraName 在单元格中无效的问题 Close: #8525

---

packages/amis-editor/src/renderer/DateShortCutControl.tsx
packages/amis-editor/src/renderer/FeatureControl.tsx
packages/amis-editor/src/renderer/ListItemControl.tsx
packages/amis-editor/src/renderer/OptionControl.tsx
packages/amis-editor/src/renderer/TimelineItemControl.tsx
packages/amis-editor/src/renderer/crud2-control/CRUDColumnControl.tsx
packages/amis-editor/src/renderer/event-control/index.tsx
packages/amis-ui/src/components/ArrayInput.tsx
packages/amis-ui/src/components/ResultList.tsx
packages/amis-ui/src/components/UserSelect.tsx
packages/amis/src/renderers/Cards.tsx
packages/amis/src/renderers/Form/Combo.tsx
packages/amis/src/renderers/Form/InputImage.tsx
packages/amis/src/renderers/Form/InputSubForm.tsx
packages/amis/src/renderers/List.tsx
packages/amis/src/renderers/Table/ColumnToggler.tsx
packages/amis/src/renderers/Table/index.tsx

fix: 修复 inputSubForm 拖拽排序值位置与视图位置不一致问题 Close: #3269

---

packages/amis-core/src/store/table.ts

fix: 修复 table 切换列显隐后设计器重新调整列顺序不生效问题

---

packages/amis-editor/src/plugin/Form/Switch.tsx

fix: 修复编辑器中switch组件默认值回显不对问题

---

packages/amis-core/src/utils/helper.ts
packages/amis-ui/src/components/Tabs.tsx
packages/amis/src/renderers/Table/Cell.tsx
packages/amis/src/renderers/Table/TableBody.tsx
packages/amis/src/renderers/Table/TableRow.tsx
packages/amis/src/renderers/Table/index.tsx
packages/amis/src/renderers/Tabs.tsx

feat(amis): 增加tabs、table cell的testid

---

packages/amis-ui/scss/_components.scss
packages/amis-ui/scss/components/_spinner.scss
packages/amis-ui/scss/themes/dark.scss
packages/amis-ui/src/components/Spinner.tsx

feat: loading根据父级背景颜色自动适配颜色 Close#9489

---

packages/amis-editor-core/src/manager.ts

fix(editor): editor 数据域查询问题

---

packages/amis-editor-core/src/manager.ts

feat(editor): editor addElem 支持 doc-entiry

---

packages/amis/src/renderers/Form/InputText.tsx

fix(amis): InputText 清空操作支持clearValueOnEmpty配置

---

packages/amis-editor-core/src/manager.ts

fix:可视化编辑器弹窗中多选了组件，面板异常

---

packages/amis-editor-core/scss/control/_event-action.scss
packages/amis-editor/src/renderer/event-control/action-config-panel.tsx
packages/amis-editor/src/renderer/event-control/helper.tsx

fix:事件动作-变量赋值交互问题

---

packages/amis-ui/src/components/icons.tsx
packages/amis/__tests__/renderers/__snapshots__/Action.test.tsx.snap
packages/amis/__tests__/renderers/__snapshots__/Breadcrumb.test.tsx.snap
packages/amis/__tests__/renderers/__snapshots__/Page.test.tsx.snap

chore: 固定icon组件支持的事件,避免警告

---

packages/amis/src/renderers/DropDownButton.tsx

fix: dropdown-button 下载无效问题

---

packages/amis-ui/scss/components/_button-group.scss
packages/amis-ui/scss/components/form/_select.scss

style: select 下拉框最小宽度设置成 120px

---

packages/amis-editor/src/plugin/Layout/FlexPluginBase.tsx
packages/amis-editor/src/tpl/layout.tsx

chore: flex切换纵向时清除子容器为0的flexBasis

---

packages/amis-core/__tests__/scoped.test.ts
packages/amis-core/src/Scoped.tsx
packages/amis-core/src/index.tsx

fix: 刷新多个目标逗号与表达式逗号冲突问题修复 Close: #9499

---

packages/amis-editor/src/plugin/CRUD.tsx

fix: editor: 修复增删改查快速编辑在卡片和列表模式没有生成对应schema的问题

---

packages/amis-editor-core/src/component/factory.tsx
packages/amis-ui/scss/components/form/_select.scss

fix: 修复编辑器中渲染 list 时提示 key 重复 warning

---

packages/amis/src/renderers/CRUD2.tsx
packages/amis/src/renderers/Table2/ColumnToggler.tsx

fix: 修复crud2自定义显示列不生效问题

---

packages/amis-core/src/store/list.ts
packages/amis-core/src/store/table.ts
packages/amis/src/renderers/Table/index.tsx

fix: 修复 Table 中调用 setData 报错问题

---

packages/amis-editor/src/plugin/CRUD.tsx

fix: 修复crud快速构建内容失效

---

packages/amis-core/src/components/CustomStyle.tsx
packages/amis-core/src/utils/style-helper.ts

fix:修复使用amis sdk时自定义样式不生效问题

---

packages/amis-theme-editor-helper/src/helper/ParseThemeData.ts

fix: 兼容主题配置中的脏数据

---

packages/amis-editor/src/plugin/TableView.tsx
packages/amis/__tests__/renderers/Form/inputDate.test.tsx

fix: 修复表格视图显示边框默认没选中问题

---

packages/amis-editor/src/plugin/CRUD.tsx

fix: 修复 crud 脚手架新增表单中出现错误渲染器的问题

---

packages/amis-core/src/WithStore.tsx
packages/amis/__tests__/event-action/renderers/paginationWrapper.test.tsx

fix: 修复数据下发同步问题

---

packages/amis-core/src/utils/dom.tsx

style: 当为 auto 定位时如果兜底的定位方式都显示不全的话直接平移到可视区域

---

packages/amis-editor-core/src/component/MiniEditor.tsx
packages/amis/src/renderers/Table/AutoFilterForm.tsx

fix: 修复miniEditor应用国际化不生效问题

---

packages/amis-core/__tests__/scoped.test.ts
packages/amis-core/src/Scoped.tsx

fix:scope命中多目标兼容空格情况

---

scripts/bot/.gitignore
scripts/bot/gen_embedding.py
scripts/bot/gui.py

chore: 去掉 bot 示例中的 pickle 依赖

---

packages/amis-core/src/store/table.ts
packages/amis/src/renderers/Table/index.tsx

fix: 修复表格调整排序信息未保存问题 Close: #8585, #9590

---

packages/amis-core/src/utils/api.ts
packages/amis-core/src/utils/attachmentAdpator.ts

fix: 修复 mockResponse 没有 headers 时的报错 Close: #9565

---

packages/amis-core/src/renderers/wrapControl.tsx
packages/amis/__tests__/renderers/Table.test.tsx

因为表单项类组件没有读取 props 里面的 canAccessSuperData 属性 
Close: #9556

fix: 修复 static-xxx 在列中始终是能获取上层数据的问题 Close: #9556

---

examples/loader.ts

fix: jssdk导出npm扩展包缺失依赖

---

docs/zh-CN/concepts/event-action.md
packages/amis-core/src/actions/PrintAction.ts
packages/amis-core/src/actions/index.ts
packages/amis-core/src/renderers/Form.tsx
packages/amis-core/src/utils/printElement.ts
packages/amis-ui/scss/components/_print.scss
packages/amis-ui/scss/themes/_common.scss
packages/amis/src/renderers/CRUD.tsx
packages/amis/src/renderers/CRUD2.tsx
packages/amis/src/renderers/Container.tsx
packages/amis/src/renderers/Flex.tsx
packages/amis/src/renderers/Grid.tsx
packages/amis/src/renderers/Grid2D.tsx
packages/amis/src/renderers/Table/index.tsx
packages/amis/src/renderers/TableView.tsx
packages/amis/src/renderers/Wrapper.tsx

feat: 增加打印事件, 支持打印容器组件 Closes #9475

---

packages/amis/__tests__/renderers/Mapping.test.tsx
packages/amis/src/renderers/Mapping.tsx

Close: #9613 
https://github.com/baidu/amis/pull/9479  的修改没有给子组件下发 value 了，所以需要下发 name 让子组件自己去取值

fix: 修复 mapping 结合其他组件兜底显示时取值错误 Close: #9613

---

packages/amis/__tests__/renderers/Form/inputTable.test.tsx
packages/amis/src/renderers/QuickEdit.tsx

fix: 修复 select 的 autoFill 在 inputTable 中赋值不正确的问题 Close: #9494

---

packages/amis-core/src/store/table.ts
packages/amis-core/src/utils/browser.ts
packages/amis/__tests__/renderers/Form/__snapshots__/inputTable.test.tsx.snap
packages/amis/src/renderers/Table/ColGroup.tsx
packages/amis/src/renderers/Table/index.tsx

style: 修复 table 在 safari 里面设置 width 无效问题 Close: #9486

---

packages/amis-core/src/index.tsx
packages/amis-core/src/store/service.ts
packages/amis-ui/scss/components/_app.scss
packages/amis/__tests__/renderers/App.test.tsx
packages/amis/src/renderers/App.tsx

Close: #9564
https://aisuda.bce.baidu.com/amis/zh-CN/docs/extend/i18n 规则应用在动态 schema 上

feat: 组件中动态加载的组件 schema 也支持多语言规则 Close: #9564

---

packages/amis-core/src/renderers/wrapControl.tsx
packages/amis/__tests__/renderers/Form/inputTable.test.tsx

fix: 修复 inputTable 单元中容器内表单项是否可获取父级数据逻辑异常问题 Close: #9520

---

docs/zh-CN/components/form/input-tree.md
docs/zh-CN/components/form/treeselect.md
packages/amis-editor/src/plugin/Form/TreeSelect.tsx
packages/amis-editor/src/util.ts
packages/amis/src/renderers/Form/InputTree.tsx
packages/amis/src/renderers/Form/TreeSelect.tsx

feat:树组件事件支持选中项获取

---

packages/amis/src/renderers/CRUD.tsx

fix: 修复 crud 重置失效的问题 Close: #9686

---

packages/amis/src/renderers/Form/InputMonthRange.tsx
packages/amis/src/renderers/Form/InputQuarterRange.tsx
packages/amis/src/renderers/Form/InputYearRange.tsx

fix:根据broadcast广播配置input-month-range组件清空操作无效 Close #9505

---

packages/amis/src/renderers/CRUD2.tsx

fix: crud2条件查询表单重置失效 issue: #9701

---

packages/amis-core/package.json
packages/amis-editor-core/src/plugin.ts
packages/amis-editor/src/renderer/event-control/helper.tsx
packages/amis-editor/src/renderer/event-control/index.tsx

fix: 修复弹窗交互调整引发动作添加报错 Close: #9720

---

packages/amis-core/src/renderers/Form.tsx
packages/amis-core/src/renderers/Item.tsx
packages/amis-core/src/renderers/Options.tsx
packages/amis-ui/scss/components/_table.scss
packages/amis-ui/scss/components/form/_form.scss
packages/amis/src/renderers/Form/Picker.tsx

feat: autoFill api 模式也支持 initAutoFill 配置 Close: #9631 #9716 #9721

---

docs/zh-CN/components/form/input-signature.md
examples/components/Components.tsx
package.json
packages/amis-ui/scss/components/_signature.scss
packages/amis-ui/scss/themes/_common.scss
packages/amis-ui/src/components/Signature.tsx
packages/amis-ui/src/components/index.tsx
packages/amis-ui/src/locale/de-DE.ts
packages/amis-ui/src/locale/en-US.ts
packages/amis-ui/src/locale/zh-CN.ts
packages/amis/src/Schema.ts
packages/amis/src/index.tsx
packages/amis/src/renderers/Form/InputSignature.tsx

feat：amis支持手写签名面板

---

packages/amis/src/renderers/Table/index.tsx

fix: table的select动作判断falttenedRows进行选中，以便选中子节点 close: #9714

---

packages/amis-core/src/renderers/Form.tsx
packages/amis-core/src/renderers/Item.tsx
packages/amis-editor-core/src/component/Panel/DialogList.tsx
packages/amis-editor-core/src/component/base/SchemaForm.tsx
packages/amis-editor-core/src/store/editor.ts
packages/amis-editor/src/plugin/Dialog.tsx
packages/amis-editor/src/plugin/Drawer.tsx
packages/amis-editor/src/renderer/event-control/DialogActionPanel.tsx
packages/amis-editor/src/renderer/event-control/helper.tsx
packages/amis-ui/src/components/json-schema/Item.tsx
packages/amis-ui/src/components/json-schema/Object.tsx

chore: 优化弹窗参数映射逻辑

---

packages/amis-editor-core/src/component/Panel/DialogList.tsx
packages/amis-editor-core/src/store/editor.ts
packages/amis-editor-core/src/util.ts
packages/amis-editor/src/renderer/event-control/DialogActionPanel.tsx
packages/amis-editor/src/renderer/event-control/helper.tsx

chore: 调整弹窗编辑逻辑支持子弹窗中可以选择打开父级其他弹窗

---

packages/amis-core/src/renderers/Item.tsx
packages/amis-core/src/renderers/Options.tsx
packages/amis-core/src/renderers/wrapControl.tsx
packages/amis-core/src/store/formItem.ts
packages/amis/__tests__/renderers/Form/formitem.test.tsx
packages/amis/src/renderers/Form/InputFile.tsx
packages/amis/src/renderers/Form/InputImage.tsx
packages/amis/src/renderers/Form/MatrixCheckboxes.tsx
packages/amis/src/renderers/Form/Picker.tsx

chore: 调整表单项初始化过程 解决表单项非初始渲染时 initAutoFill 配置无效的问题 Close: #9733, #9742

---

packages/amis-editor/src/plugin/Form/Switch.tsx

fix: editor-修复switch组件值格式数字和字符串会被自动转为布尔值的问题

---

packages/amis-editor-core/scss/editor.scss
packages/amis-editor-core/scss/style-control/_flex-layout.scss
packages/amis-editor-core/src/manager.ts
packages/amis-editor/src/index.tsx
packages/amis-editor/src/plugin/Container.tsx
packages/amis-editor/src/plugin/Image.tsx
packages/amis-editor/src/plugin/Layout/FlexPluginBase.tsx
packages/amis-editor/src/renderer/FlexSettingControl.tsx
packages/amis-editor/src/renderer/style-control/FlexLayout.tsx
packages/amis-editor/src/tpl/layout.tsx
packages/amis-editor/src/tpl/style.tsx

chore: 布局容器优化

---

packages/amis/src/renderers/CRUD.tsx

fix: 修复 crud setData 动作处理报错

---

packages/amis-core/src/renderers/Form.tsx
packages/amis-core/src/renderers/wrapControl.tsx
packages/amis-core/src/store/iRenderer.ts
packages/amis-editor/src/renderer/APIControl.tsx
packages/amis/__tests__/event-action/ajax.test.tsx
packages/amis/src/renderers/Form/Combo.tsx
packages/amis/src/renderers/Form/ConditionBuilder.tsx

pick: fix: 修复 api 编辑输入太快立马弹出详情时出现弹窗空白问题

---

packages/amis-core/src/utils/validateId.ts
packages/amis/__tests__/utils/validations.test.ts

feat: 增加验证身份证号码的范围合理性(1850-今天)

---

packages/amis/__tests__/renderers/Form/__snapshots__/select.test.tsx.snap
packages/amis/src/renderers/Form/Select.tsx

feat: select tree模式支持menuTpl

---

packages/amis-core/src/utils/dom.tsx

fix: 修复popover定位问题

---

docs/zh-CN/components/crud.md
packages/amis-core/src/types.ts
packages/amis/src/renderers/CRUD.tsx
packages/amis/src/renderers/Cards.tsx
packages/amis/src/renderers/List.tsx
packages/amis/src/renderers/Table/index.tsx

fix: 修复 table 更新指定行数数据多次调用报错问题 Close: #9659

---

packages/amis-core/src/renderers/wrapControl.tsx
packages/amis/src/renderers/QuickEdit.tsx

chore: input-table 支持单元格为容器时内部放表单项也参与校验 Close: #9756

---

packages/amis-editor/src/renderer/ExpressionFormulaControl.tsx
packages/amis-editor/src/renderer/FormulaControl.tsx
packages/amis-editor/src/renderer/StatusControl.tsx
packages/amis-editor/src/renderer/TplFormulaControl.tsx
packages/amis-editor/src/renderer/textarea-formula/TextareaFormulaControl.tsx
packages/amis-ui/src/components/formula/Picker.tsx

chore: 优化公式编辑器支持表达式中换行

---

packages/amis-editor/src/plugin/CRUD.tsx

fix: 修复 crud 其他模式构建脚手架初始化态状态错误

---

packages/amis-ui/scss/components/form/_text.scss

fix: issue:9755:inputGroup下inputText icon 不显示

---

packages/amis-editor-core/src/component/Panel/DialogList.tsx
packages/amis-editor/src/renderer/event-control/DialogActionPanel.tsx
packages/amis-editor/src/renderer/event-control/helper.tsx

fix: 修复弹窗修改可能的报错

---

packages/amis-core/src/SchemaRenderer.tsx

chore: 默认不要透传 loading

---

packages/amis/src/renderers/Form/Combo.tsx

fix: 修复 combo 可能无限触发 onChange 的问题

---

fis-conf.js
packages/office-viewer/__tests__/happydom.ts
packages/office-viewer/__tests__/snapShotTest.ts
packages/office-viewer/bunfig.toml
packages/office-viewer/package.json
packages/office-viewer/src/common/autoParse.ts
packages/office-viewer/src/excel/edit/ui/CellEditor.ts
packages/office-viewer/src/excel/io/excel/parseWorksheet.ts
packages/office-viewer/src/excel/render/__test__/autoWrapText.test.ts
packages/office-viewer/src/excel/render/autoFilter/AutoFilterIconUI.ts
packages/office-viewer/src/excel/render/autoFilter/filterColumn/CustomFiltersUI.ts
packages/office-viewer/src/excel/render/formulaBar/FormulaBar.ts
packages/office-viewer/src/excel/render/header/drawRowColHeaders.ts
packages/office-viewer/src/excel/render/ui/CheckBoxList.ts
packages/office-viewer/src/excel/render/ui/Input.ts
packages/office-viewer/src/excel/types/worksheet/CellData.ts
packages/office-viewer/src/util/__tests__/replaceVar.test.ts
packages/office-viewer/src/util/__tests__/xmlToNode.test.ts
packages/office-viewer/src/util/onClickOutsideOnce.ts
packages/office-viewer/src/util/xmlToNode.ts

chore: 修复 gh-pages 没有 xlsx 文件问题

---

packages/amis-ui/src/components/ContextMenu.tsx

ContextMenu组件
- 支持渲染自定义菜单
- 支持监听菜单大小变化并重新计算位置

feat: ContextMenu组件支持渲染自定义菜单\支持监听菜单大小变化并重新计算位置

---

packages/amis-ui/src/components/ContextMenu.tsx

feat: contextMenu组件willUnmount时cancel debounce

---

packages/amis-formula/src/parser.ts
packages/amis-ui/scss/components/_condition-builder.scss
packages/amis-ui/src/components/CodeMirror.tsx
packages/amis-ui/src/components/formula/CodeEditor.tsx
packages/amis-ui/src/components/formula/Input.tsx
packages/amis-ui/src/components/formula/Picker.tsx
packages/amis-ui/src/components/formula/plugin.ts
packages/amis/__tests__/renderers/Form/__snapshots__/inputFormula.test.tsx.snap

style: 调整公式部分样式

---

packages/amis/src/renderers/QRCode.tsx

fix: 二维码组件下载展示不全 #9859

---

packages/amis-ui/scss/components/_formula.scss
packages/amis-ui/src/components/condition-builder/Value.tsx
packages/amis-ui/src/components/formula/Input.tsx
packages/amis-ui/src/components/formula/Picker.tsx
packages/amis/src/renderers/Form/InputFormula.tsx

feat: 条件组合与公式结合时支持自定义输入框类型

---

packages/amis-core/src/store/table2.ts
packages/amis-ui/src/components/table/index.tsx
packages/amis/src/renderers/Table2/index.tsx

fix: 修复 table2 树形数据展示对应错误问题

---

packages/amis-core/src/SchemaRenderer.tsx
packages/amis-core/src/WithStore.tsx
packages/amis-core/src/renderers/Form.tsx
packages/amis-core/src/store/combo.ts
packages/amis-core/src/store/table2.ts
packages/amis-ui/scss/_components.scss
packages/amis-ui/scss/components/_tabs.scss
packages/amis-ui/scss/components/form/_combo.scss
packages/amis-ui/src/components/Tabs.tsx
packages/amis-ui/src/components/table/index.tsx
packages/amis/__tests__/event-action/renderers/paginationWrapper.test.tsx
packages/amis/__tests__/renderers/Form/combo.test.tsx
packages/amis/__tests__/renderers/Form/inputArray.test.tsx
packages/amis/src/renderers/CRUD.tsx
packages/amis/src/renderers/CRUD2.tsx
packages/amis/src/renderers/Form/Combo.tsx
packages/amis/src/renderers/Table/TableRow.tsx
packages/amis/src/renderers/Table2/index.tsx

Pick combo 修改相关

---

packages/amis-core/src/utils/stripNumber.ts
packages/amis/src/renderers/Form/InputRange.tsx

fix: 修复滑块组件有精度配置时精度不准确的问题

---

docs/zh-CN/components/crud.md
packages/amis-core/src/Scoped.tsx
packages/amis-core/src/actions/CmptAction.ts
packages/amis-core/src/types.ts
packages/amis/src/renderers/CRUD.tsx
packages/amis/src/renderers/Carousel.tsx
packages/amis/src/renderers/Collapse.tsx
packages/amis/src/renderers/Form/Combo.tsx
packages/amis/src/renderers/Form/DiffEditor.tsx
packages/amis/src/renderers/Form/Editor.tsx
packages/amis/src/renderers/Form/InputNumber.tsx
packages/amis/src/renderers/Form/InputTable.tsx
packages/amis/src/renderers/Form/InputText.tsx
packages/amis/src/renderers/Form/TabsTransfer.tsx
packages/amis/src/renderers/Form/Textarea.tsx
packages/amis/src/renderers/Nav.tsx
packages/amis/src/renderers/OfficeViewer.tsx
packages/amis/src/renderers/Progress.tsx
packages/amis/src/renderers/QRCode.tsx
packages/amis/src/renderers/SearchBox.tsx
packages/amis/src/renderers/Service.tsx
packages/amis/src/renderers/Table/index.tsx
packages/amis/src/renderers/Table2/index.tsx
packages/amis/src/renderers/Tabs.tsx

feat: crud 支持刷新行数据

---

.github/workflows/gh-pages.yml

chore: gh-pages 只有 master 分支才更新

---

docs/zh-CN/components/form/input-formula.md
packages/amis-ui/src/components/formula/Picker.tsx

fix: 修复 inputFormula evalMode false 时提交报错问题

---

packages/amis-core/src/actions/DialogAction.ts
packages/amis-ui/src/components/Alert.tsx

feat: 事件动作confirmDialog和alert支持自定义className Close #9869

---

examples/polyfills/index.ts

fix: 增加 Object.hasOwn polyfill 避免 Chrome 92 以下报错 Closes #9816

---

packages/amis/src/renderers/IFrame.tsx

feat: iframe 支持打开 blob 地址 Close: #8971

---

packages/amis/src/renderers/Table/TableContent.tsx
packages/amis/src/renderers/Table/index.tsx

fix: 修复 crud 的 autoFillHeight 模式与 itemActions 结合使用时位置不正确的问题 Close: #9231

---

packages/amis-core/src/utils/dom.tsx
packages/amis/__tests__/renderers/Form/__snapshots__/inputCity.test.tsx.snap
packages/amis/__tests__/renderers/Form/__snapshots__/inputTag.test.tsx.snap
packages/amis/__tests__/renderers/Form/__snapshots__/repeat.test.tsx.snap
packages/amis/__tests__/renderers/Form/__snapshots__/select.test.tsx.snap
packages/amis/__tests__/renderers/Form/__snapshots__/text.test.tsx.snap
packages/amis/__tests__/renderers/__snapshots__/Pagination.test.tsx.snap

fix: 修复 popOver 在滚动容器内的位置不正确的问题 Close: #9855

---

fis-conf.js

fix: 修复 gh-pages 访问 app 多页面应用报错 Close: #9001

---

packages/amis-core/src/SchemaRenderer.tsx
packages/amis-core/src/WithStore.tsx
packages/amis/src/renderers/GridNav.tsx

fix: 修复 defaultData 中配置 schema, 存在数据映射冲突问题 Close: #8972

---

docs/zh-CN/components/crud.md
docs/zh-CN/components/form/input-table.md
docs/zh-CN/components/table.md
packages/amis-core/src/store/formItem.ts
packages/amis-editor/src/plugin/CRUD.tsx
packages/amis-editor/src/plugin/Form/InputTable.tsx
packages/amis-editor/src/plugin/Table.tsx
packages/amis/src/renderers/Form/InputTable.tsx
packages/amis/src/renderers/Table/TableRow.tsx
packages/amis/src/renderers/Table/index.tsx

fix: 修复 inputTable 事件动作上下文信息不全 Close: #8853

---

packages/amis/src/renderers/CRUD.tsx

fix:修复crud赋值时没传行数据的报错

---

packages/amis-ui/scss/components/_image-gallery.scss
packages/amis-ui/src/components/ImageGallery.tsx
packages/amis/src/renderers/Image.tsx

fix: 修复Image图片组件enlargeWithGallary和enlargeCaption两个属性不生效的问题 Close: #9769

---

packages/amis-ui/scss/components/_input-box.scss
packages/amis-ui/src/components/InputBox.tsx
packages/amis-ui/src/components/InputBoxWithSuggestion.tsx
packages/amis-ui/src/components/PopOverContainer.tsx

* clear 按钮，在激活态才显示
* 没有可选项时不显示 popOver 和 箭头

style: 优化 inputBoxWithSuggestion 的样式

---

packages/amis-editor-core/scss/control/_expression-formula-control.scss
packages/amis-editor/src/renderer/ExpressionFormulaControl.tsx
packages/amis-editor/src/renderer/FormulaControl.tsx
packages/amis-editor/src/renderer/TplFormulaControl.tsx

style: 优化 tooltip 中的代码块展示

---

packages/amis-core/src/renderers/Form.tsx

chore: 避免 form 无限触发 onChange

---

packages/amis-theme-editor-helper/src/renderers/ColorPicker.tsx

fix(amis-editor): 背景选择器图片缩放类型选择无效问题

---

packages/amis-editor/src/plugin/Form/InputKV.tsx

fix: 修复编辑器中选择inputKv组件异常问题

---

packages/amis-ui/src/components/Tinymce.tsx

feat: InputRichText组件TinyMCE默认支持图片尺寸调整

---

packages/amis-ui/src/components/CalendarMobile.tsx
packages/amis-ui/src/components/DateRangePicker.tsx
packages/amis-ui/src/components/Picker.tsx
packages/amis-ui/src/components/PickerColumn.tsx
packages/amis-ui/src/components/SelectMobile.tsx

移动select 搜索支持 & 移动日期年份快速切换支持

---

docs/zh-CN/components/crud.md

chore: crud即时保存文档更新

---

packages/amis-editor/src/renderer/TimelineItemControl.tsx

fix: 修复timeline组件属性面板数据回显不正确问题

---

packages/amis-core/src/store/modal.ts
packages/amis/src/renderers/Dialog.tsx
packages/amis/src/renderers/Drawer.tsx

store.form 是多余的，不如直接修改到 store.data 上
Close: #9884

fix: 调整弹窗数据变更逻辑 Close: #9884

---

packages/amis-formula/__tests__/__snapshots__/parser.test.ts.snap
packages/amis-formula/__tests__/parser.test.ts
packages/amis-formula/src/lexer.ts

fix: 修复公式字符串中转义反斜杠处理不正确的问题 Close: #9933

---

packages/amis-core/src/actions/DialogAction.ts
packages/amis-core/src/actions/DrawerAction.ts
packages/amis-core/src/utils/renderer-event.ts
packages/amis-editor/src/renderer/event-control/DialogActionPanel.tsx
packages/amis/src/renderers/Action.tsx
packages/amis/src/renderers/Dialog.tsx
packages/amis/src/renderers/Drawer.tsx

fix: 修复弹窗确认按钮中添加打开弹窗动作运行时失效的问题

---

packages/amis-core/src/utils/dom.tsx
packages/amis/__tests__/renderers/Form/__snapshots__/inputCity.test.tsx.snap
packages/amis/__tests__/renderers/Form/__snapshots__/inputTag.test.tsx.snap
packages/amis/__tests__/renderers/Form/__snapshots__/repeat.test.tsx.snap
packages/amis/__tests__/renderers/Form/__snapshots__/select.test.tsx.snap
packages/amis/__tests__/renderers/Form/__snapshots__/text.test.tsx.snap
packages/amis/__tests__/renderers/__snapshots__/Pagination.test.tsx.snap
packages/amis/__tests__/renderers/__snapshots__/Tabs.test.tsx.snap

fix: 修复可视化区域检测问题 x 和 y 数值为 0 时不一定不在可视区域

---

docs/zh-CN/components/form/input-tree.md
packages/amis-editor/src/util.ts
packages/amis-ui/src/components/index.tsx
packages/amis/src/renderers/Form/InputTree.tsx
packages/amis/src/renderers/Form/TreeSelect.tsx

Resolves: #9942, Resolves: #9946

fix: 修复 tree-select autoComplete 合并选项逻辑错误  Close: #9942 #9946

---

docs/zh-CN/components/form/json-schema.md
packages/amis-editor/src/renderer/event-control/DialogActionPanel.tsx
packages/amis-ui/src/components/WithRemoteConfig.tsx
packages/amis-ui/src/components/json-schema/Array.tsx
packages/amis-ui/src/components/json-schema/Item.tsx
packages/amis-ui/src/components/json-schema/Object.tsx
packages/amis-ui/src/components/json-schema/index.tsx
packages/amis-ui/src/locale/de-DE.ts
packages/amis-ui/src/locale/en-US.ts
packages/amis-ui/src/locale/zh-CN.ts
packages/amis/src/renderers/Form/ConditionBuilder.tsx
packages/amis/src/renderers/Form/JSONSchema.tsx

feat: 弹窗参数映射支持公式

---

packages/amis-editor-core/src/component/factory.tsx

chore: 调整右侧面板构建优化对象属性下发减少re-render

---

packages/amis-core/src/store/iRenderer.ts

fix: 修复crud 弹窗表单提交后不刷新 crud 的问题

---

packages/amis-core/src/renderers/Form.tsx

fix:form getData无法获取最新数据问题

---

packages/amis-core/src/actions/CmptAction.ts

fix(amis-core): 事件动作/组件动作/未找到组件提示增加组件ID信息，方便知晓哪个组件未找到。

---

packages/amis-core/src/utils/helper.ts

fix: 修复 form 计算差值可能死循环的问题

---

packages/amis/src/renderers/Page.tsx

fix: 修复 toolbar 中放表单项无效的问题  Close: #9931

---

docs/zh-CN/components/cards.md
docs/zh-CN/components/crud.md
docs/zh-CN/components/form/input-table.md
docs/zh-CN/components/list.md
docs/zh-CN/components/table.md
packages/amis-core/src/actions/Action.ts
packages/amis-core/src/store/list.ts
packages/amis-core/src/store/table.ts
packages/amis-core/src/types.ts
packages/amis-editor/src/plugin/Form/InputTable.tsx
packages/amis-editor/src/plugin/Table.tsx
packages/amis/src/renderers/CRUD.tsx
packages/amis/src/renderers/Cards.tsx
packages/amis/src/renderers/Form/InputTable.tsx
packages/amis/src/renderers/List.tsx
packages/amis/src/renderers/Table/index.tsx

feat: 补充 crud, table, list, cards 组件动作表 Close: #9597

---

packages/amis-core/src/Scoped.tsx

优先从当前层级开始超找，找不到才向上查找
历史导航模式，一次性会渲染多个页面，如果这两个页面里面存在组件 id 相同的情况，内部通行就可能找错对象。
将原来的回到顶点开始找，改成从当前层开始找，找不到才一步一步回到顶点

fix: 修复多页面同时渲染场景查找组件优先级问题

---

packages/amis-ui/src/components/DatePicker.tsx

fix: 修复inputDate组件输入无效问题

---

packages/amis/package.json
packages/office-viewer/package.json
packages/office-viewer/src/excel/sheet/getViewPointData.ts

fix: office-viewer excel 修复存在多个合并单元格时渲染丢失问题

---

packages/amis-ui/src/components/NumberInput.tsx
packages/amis/src/renderers/Form/InputNumber.tsx

fix(amis-ui): numberInput change时不进行额外多余的数值处理

---

packages/amis-ui/scss/components/form/_icon-select.scss
packages/amis-ui/src/components/icons.tsx
packages/amis/src/renderers/Form/IconSelect.tsx

chore: 优化图标选择器

---

packages/amis-editor-core/src/component/Editor.tsx
packages/amis-editor-core/src/component/IFramePreview.tsx
packages/amis-editor-core/src/component/Preview.tsx
packages/amis-editor-core/src/store/editor.ts

fix: 修复编辑器预览模式弹窗的上下文信息会丢失的问题

---

packages/amis-editor-core/src/component/base/SchemaForm.tsx

fix: 优化schemaForm onChange 解决弹窗中弹窗编辑报错问题

---

packages/amis-ui/scss/components/_menu.scss
packages/amis-ui/src/components/Tree.tsx
packages/amis/src/renderers/Nav.tsx

feat: tree\nav支持svg icon

---

packages/amis-ui/scss/components/_tabs.scss

style: 优化tabs文字样式 Close: #10006

---

packages/amis-ui/src/components/json-schema/Object.tsx

chore: jsonschema 输入字符串默认值设置为空字符解决默认为 undefined 时设置无效的问题

---

docs/zh-CN/components/form/index.md
packages/amis-core/src/renderers/Form.tsx
packages/amis-core/src/renderers/wrapControl.tsx

fix:修复input-table表单初始化数据渲染失败问题

---

packages/amis-editor/src/renderer/TransferTableControl.tsx

fix: 修复transfer 表格模式时设置表格行时无法渲染最新值的bug

---

packages/amis/src/renderers/Form/Combo.tsx

原来的逻辑会出现 subForm 成员被覆盖的情况，导致丢失了部分成员

fix: 修复拖拽后出现表单项校验失败的问题

---

packages/amis-core/src/actions/DialogAction.ts
packages/amis-core/src/actions/DrawerAction.ts
packages/amis-editor-core/src/store/editor.ts
packages/amis/src/renderers/Dialog.tsx
packages/amis/src/renderers/Drawer.tsx

问题 schema
```
{
"title": "套娃验证",
"regions": [
"body",
"toolbar",
"header"
],
"body": [
{
"type": "button",
"label": "套娃按钮",
"onEvent": {
"click": {
"actions": [
{
"ignoreError": false,
"actionType": "dialog",
"dialog": {
"type": "dialog",
"title": "弹窗1",
"body": [
{
"type": "tpl",
"tpl": "弹窗内容",
"id": "u:0e7389261eba"
}
],
"id": "u:81fe5be7c218",
"actions": [
{
"type": "button",
"actionType": "cancel",
"label": "取消",
"id": "u:29b92565b8dc"
},
{
"type": "button",
"actionType": "confirm",
"label": "确定",
"primary": true,
"id": "u:30e70cef6513"
}
],
"showCloseButton": true,
"closeOnOutside": false,
"closeOnEsc": false,
"showErrorMsg": true,
"showLoading": true,
"draggable": false,
"editorSetting": {
"displayName": "弹窗1"
},
"onEvent": {
"confirm": {
"weight": 0,
"actions": [
{ …
```

fix: 修复弹窗中关闭动作中打开弹窗后续事件动作不执行的问题

---

packages/amis-editor-core/src/store/editor.ts

fix: 修复新建弹窗中弹窗列表出现重复的问题

---

packages/amis/src/renderers/Card.tsx

feat: card subTitle支持更多渲染方式

---

packages/amis-core/src/factory.tsx
packages/amis-core/src/renderers/Form.tsx
packages/amis/src/renderers/Form/InputDate.tsx
packages/amis/src/renderers/Form/InputDateRange.tsx
packages/amis/src/renderers/Table2/index.tsx

fix: 修复 form 的 flush 逻辑可能会出现一直等待自己的问题

---

packages/amis-editor-core/src/component/Panel/DialogList.tsx
packages/amis-editor/src/renderer/event-control/helper.tsx

fix: 修复动作面板中弹窗信息显示不全的问题

---

packages/amis-ui/scss/_components.scss
packages/amis-ui/scss/components/_collapse.scss

style: 优化collapse移动端样式

---

packages/amis-core/src/components/CustomStyle.tsx
packages/amis-ui/scss/components/form/_picker.scss

style: 优化picker组件在inline模式下的宽度
