baidu/amis

scss/components/_button-group.scss
在button-group active时不填充背景色的theme中，acitve但不:active的状态：
修复前：
修复后：
=> 修复button-group is-acitve时不显示重叠的border的问题

src/renderers/Drawer.tsx
`Drawer`内当有`Select`组件时，当显示`Select`下拉列表后，点击任意地方会自动关闭`Drawer`
主要由于#501 ，默认下发的是Drawer顶层dom，Drawer中的Popover（例如Select）会成为`Drawer-content`的**兄弟节点**
```
<div class="amis-dialog-widget a-Drawer a-Drawer--right a-Drawer--md a-Modal--1th">
<div class="a-Drawer-content in"></div>
<div class="a-Popover"></div>
</div>
```
这样当`Drawer`开启`closeOnOutside`时，下面逻辑会导致onHide方法触发。
```
handleWidgetClick(e: React.MouseEvent) {
const {classPrefix: ns, closeOnOutside, onHide} = this.props;
if ((e.target as HTMLElement).closest(`.${ns}Drawer-content`)) {
return;
}
closeOnOutside && onHide && onHide();
}
```
下发`Drawer-content`这一层，让Popover成为`Drawer-content`子节点，保持原逻辑可用。
=> 调整一下Drawer下发的popoverContainer

src/components/Select.tsx
在Select 配置`multiple`+`autoComplete` 时，输入搜索内容触发`autoComplete`后，勾选任意项，会再次触发`autoComplete`并清空`term`参数值，导致当前`options`变化。
`handleStateChange`中判断勾选项后，拉取
- 单选时清空`term`是有意义的
- 所以只判断：在多选的时候，保持当前`options`，不重新拉取
=> 修复 Select 多选+autoComplete 时，重新拉取的问题

src/components/Select.tsx, src/renderers/Form/Select.tsx
之前当配置`multiple`+`autoComplete`，选中部分项之后，输入新的关键字搜索`新的options`时，也显示`已选择的options`
重新拉取`autoComplete`后，会把`已选项`和`新拉取的项`进行`merge`
保持`merge`，因为需要映射input中的label值，只在已选项中添加`hidden:true`，并在`select`输出显示时做次过滤
=> Select 在有已选项时，autoComplete 不显示已选项

docs/renderers/Tabs.md, scss/components/_drawer.scss, src/renderers/Wizard.tsx
`drawer`中，`wizard`的`popover`被覆盖
`Wizard`中未将`drawer`的`popoverContainer`下传
下传`drawer`的`popoverContainer`
一些样式和文档
=> drawer的wizard中popoverContainer问题

src/utils/validations.ts
在配置如下形式的验证格式时，验证会失效
```
{
validations: 'matchRegexp: /。$/',
validationErrors: {
matchRegexp: '必须以中文。结尾'
}
}
```
解析正则部分，未将`matchRegexp: `部分去掉
而[这次提交](https://github.com/baidu/amis/pull/533/files#diff-92d10af68ec8cbb847370aa5cb07f057R7  )，加上了开始和结束匹配，得以发现该问题
看代码
=> 修复字符串形式配置正则时异常

docs/renderers/Action.md, src/renderers/Form/index.tsx, src/store/formItem.ts, src/utils/helper.ts
当feedback 配置在弹框的确认按钮中，预期是，当达到某个条件，这个 feedback 弹框出现，需要用户做二次确认，确认了再发送一个请求完成操作，接下来继续原来确认按钮的逻辑，即关闭弹框。如果用户点了取消，只关闭feedback 弹框而不关闭外面的弹框。为了不影响原有规则，这个时候就需要一个 feedback.skipRestOnCancel 的配置来实现。
=> feedback 添加 skipRestOnCancel 配置

src/renderers/Form/index.tsx
`dialog`的`confirm`按钮中，配置`feedback`，然后`feedback`配置`skipRestOnCancel:true`,`feedback`点击`confirm`后，不会关掉上层的`dialog`
漏写部分逻辑判断
see code
=> 修复弹框中feedback，confirm关闭弹框逻辑

src/renderers/Drawer.tsx, src/renderers/Form/Options.tsx
输入 `xxx(xxx)`形式的字符串会报错
```js
input.replace(/([\$\^\*\+\-\?\.\(\)\|\[\]\\])/, '\\$1')
// 这里没加 g 标识，所以只会replace第一个，如下：
// aaa(bbb) --> aaa\(bbb)
```
`aaa\(bbb)` 在 `new RegExp` 时会报错
补充标识符
=> 修复Options正则

src/renderers/Form/Service.tsx
`form`中，配置`service`，并设置`interval`，但是form并没有设置`initApi`，则轮训失效
由于`form/service`会在`form`之前调用`componentDidMount`，因此下面代码会走到`else`
然而，initFetch -> initInterval，后续，this.mount始终是undefined,因此无法初始化轮训
在`form/service`的`componentDidMount`中，设置一下`this.mount = true`
=> 修复form中的service轮训问题

src/utils/helper.ts
`form`中配置`crud`，该`crud`中有弹框，弹框中有另外一个`crud`，这时，弹出层显示列为上层`crud`配置的`columns`列，导致有可能无限循环弹框。
`SchemaRenderer.render`中，给`Component`传props时，通过`chainEvents`，当前节点层属性会被上层属性覆盖：
当前节点已有属性不做覆盖处理，如果没有当前属性，则取用上层属性。
=> 修复form中crud弹框crud无限循环问题

src/renderers/Form/Container.tsx, src/renderers/Form/Grid.tsx, src/renderers/Form/HBox.tsx, src/renderers/Form/Panel.tsx, src/renderers/Form/Service.tsx, src/renderers/Form/Tabs.tsx
`form`中配置`tabs`等容器组件，该容器组件内部配置`另一个form`，修改`内部form`的表单项值
会自动提交`外部form`
```
{
type: 'page',
body: {
type: 'form',
api: '/api/mock2/form/saveForm?pushCode',
controls: [
{
type: 'tabs',
tabs: [
{
title: 'json编辑器',
body: {
type: 'form',
controls: [
{
name: 'json',
type: 'editor',
language: 'json'
}
]
}
}
]
}
]
}
}
```
`内部form`在`handleChange`时，会调用`上层form`的`OnChange`，导致逻辑异常
`propList`中添加`onChange`从而`omit`掉
=> form中容器组件中配置form时，修改内层的form会自动触发上层form的提交操作

src/components/Select.tsx
当`select`中配置了`value`为`0`的`options`时，回显异常
`value`为`0`，这里逻辑会有问题
`||` 判断符号更换为 `??`
=> option value为0时，回显问题

src/store/table.ts
合并单元格里，对象类型的比较时会有问题
对象类型时`==`不相等
`lodash.isEqual`
=> 合并单元格，对象类型的对比优化

src/components/Drawer.tsx
有`overlay`时，配置`closeOnOutside`失效
过滤掉来自弹框里面的点击可能漏掉了`overlay:true`的场景
加个match `.${ns}Drawer-overlay.in`判断
=> Drawer 有 overlay 时，配置 closeOnOutside 失效

src/utils/tpl-builtin.ts
像下面这种形式，`"user"`和`"id"`应该list为["user"]和["id"]，而不是`[]`
```
'${fields|filter:type:notIn:"user"|filter:key:notIn:"id"|pick:value~key,label~name}'
```
=> filter notIn优化

src/utils/api.ts
fix #726
1. 支持自定义请求协议进行变量替换，如 ws://, wss://, taf://，去掉 `isValidApi` 的校验（自定义协议会在 fetcher 函数做处理，没有必要校验 URL 的准确性，遵循浏览器自己的协议）
2. 增加 fis3 编译依赖的包
=> fix-726 支持自定义请求协议

scss/_variables.scss
优化样式，设置variables的$Modal-content-minHeight为unset
=> 优化Modal的minHeight

src/components/Editor.tsx
使用monaco-editor编辑json文件，且开启json验证时，有可能因为加载不到json worker,
monaco.languages对象下会没有json属性，会报undefined错误，进而导致整个编辑器无法使用
=> fix(components): 修复monaco-editor加载json worker报错问题

src/renderers/Form/Control.tsx
当配置**validateOnChange=false**时，如果该项**填写正确**，**点击提交**。这时候**修改该项目的内容，让其不符合校验规则**，**再次点击提交**，表单不会校验该项内容。
我认为this.model.valid保存的是发生变化前该项目的状态，当发生变化时，该项model也应该重置。
复现demo:  
gif:   https://github.com/DuLinRain/pictures/blob/master/amis-bug1.gif?raw=true  
mp4:   https://github.com/DuLinRain/pictures/blob/master/amis-bug1.mp4?raw=true
复现代码如下：
```
{
"$schema": "https://houtai.baidu.com/v2/schemas/page.json#",
"title": "表单验证示例",
"toolbar": "<a target='_blank' href='/docs/renderers/Form/FormItem'>文档</a>",
"body": [
{
"autoFocus": false,
"messages": {
"validateFailed": "请仔细检查表单规则，部分表单项没通过验证"
},
"title": "表单",
"actions": [
{
"type": "submit",
"label": "提交"
}
],
"api": "/api/mock2/form/saveFormFailed?waitSeconds=2",
"mode": "horizontal",
"controls": [
{
"name": "minLength",
"type": …
```
=> fix: validateOnChange=false时，提交后修改内容，表单不校验

src/renderers/Form/Image.tsx
```json
{
"label": "作者头像",
"name": "portrait",
"type": "image",
"multiple": false,
"reciever": "/api/mock2/form/saveForm",
"autoUpload": true,
"compress": false,
"autoFill": {
"portrait": "$url"
}
}
```
上传完图片，再点击提交，表单会一直显示loading，无法操作
如上配置，如果成功上传了图片之后，再次提交表单时，验证触发`image`的`validate`，
`this.state.uploading`这里仍然是`true`
会因为没有`resolve`所以`form`一直显示`loading`
调整autofill的位置，放在`tick`后的`setState`的回调中，防止`onBulkChange`触发`componentWillReceiveProps`导致`state`混乱
=> 修复 image 添加 autoFill，导致表单提交一直 loading 的问题

src/renderers/Form/NestedSelect.tsx
在使用NestedSelect组件的时候如果设置`searchAble: true`后，在搜索框中输入内容，然后当鼠标经过全选的时候就会触发mouseenter事件导致所有选项全部展示，从而使得搜索无效，产生交互上的bug。
所以为NestedSelect添加和select类似的checkAll和checkAllLabel选项，使得我们可以为NestedSelect设置是否展示全选框，同时可以设置全选的label。
前面场景见issues#851
=> 为NestedSelect添加checkAll和checkAllLabel选项

src/renderers/IFrame.tsx
fix: 解决通过style设置height, width不生效的bug && 并且style优先级高于标签height和width属性。
现在的实现是，即使不在外层设置height, width，他两也被设置成100%了，height !== void 0 成立了，在style里设置height 和 width就不生效了。
=> fix: 解决iframe通过style设置height, width不生效的bug && style优先级

src/renderers/Form/File.tsx, src/renderers/Form/Image.tsx, src/utils/helper.ts
用于支持第三方云存储（百度云、腾讯云、阿里云、AWS 等厂商）的 `PostObject` 接口
比如百度云文档：https://cloud.baidu.com/doc/BOS/s/akc5orrn5#%E8%AF%B7%E6%B1%82%E5%8F%82%E6%95%B0
=> 支持第三方云存储 API 鉴权

src/renderers/CRUD.tsx, src/renderers/Cards.tsx, src/renderers/List.tsx, src/renderers/Table/index.tsx
这边 因为要调整 `Layout` 组件整体布局，需要动态修改 render时传入的 `affixOffsetTop`。但是发现在 `Table` 分页切换时，被悬浮固定的Toolbar并没有消失掉。是因为切换页面后，滚动条回滚的位置，是写死的默认值 50，这边简单修复了下。我这边应用场景是没有问题了。
另外将其他的几个吸顶Header的 `affixOffsetTop`,参照 `renderers/Table` 代码，统一了下，支持动态修改。
=> 修复动态修改 affixOffsetTop 时的异常情况

examples/components/Form/Full.jsx, src/components/DatePicker.tsx, src/components/calendar/Calendar.tsx, src/components/calendar/MonthsView.tsx
添加通过inputFormat控制是否可以显示年份，以及年份是否可以点击出现年份选择列表，
同时区分是单独选择月（没有年份），
选择年月（年份可点，出现年份列表），
以及日期中的月份选择页面的年份（年份不可点），3种情况
=> 针对月份选择器，添加年份可点列表功能

src/renderers/Table/index.tsx
=> fix(Table): handleOutterScroll trailing

scss/components/_table.scss
固定表头列样式优化，固定表头列一直在顶部显示，只改变 box-shadow 显隐，这样滚动体验好一点
=> style(table): fixed table box-shadow

src/Scoped.tsx
当联动目标为 window 时，应该用 replace 模式同步地址栏。
=> window 通信逻辑优化

src/renderers/Table/TableRow.tsx, src/renderers/Table/index.tsx
当有批量操作按钮时，根据 index 读取原始数据列信息没对上。
=> 修复图片放大功能读取图片地址错误问题

examples/embed.tsx, examples/loadMonacoEditor.ts
1. alert confirm 弹框 getModalContainer 设置无效问题
2. monaco-editor/min/vs/base/browser/ui/codicons/codicon/codicon.ttf 文件缺失问题
=> 修复两个 jssdk 用法问题

src/renderers/Form/ButtonGroup.tsx, src/renderers/Form/Control.tsx, src/renderers/Form/File.tsx, src/renderers/Form/Image.tsx, src/renderers/Form/List.tsx, src/renderers/Form/NestedSelect.tsx, src/renderers/Form/Picker.tsx, src/renderers/Form/Radios.tsx, src/renderers/Form/Select.tsx, src/store/formItem.ts
将表单项的 autoFill 修改成 store 层实现，不是只有点击才会同步出去，而是只要有值变动就会同步，包括初始选中。
image & file 相关autoFill 逻辑保留在原处，不过应该是有问题，先记录了 todo。
=> 整理 autoFill

docs/zh-CN/components/form/options.md
修复options.md文档中label字段指代错误, 这里应该为label而不是value
=> docs(options.md): 修复options.md文档中label字段指代错误

src/components/Tree.tsx, src/renderers/Form/TreeSelect.tsx
Tree-Select 里使用 `labelField` 和 `valueField` 时，`label` 显示不全问题
=> Tree-Select label 修复

examples/embed.tsx, src/components/Modal.tsx
相关 issue https://github.com/baidu/amis/issues/1245
原来是复用 Portal 的，所以 env.getModalContainer 是复用的，有可能不是最新的。现在改成弹出的时候才创建。保证及时性
=> 优化 Modal 弹出, 只有在弹出的那一下才创建 Portal 组件事例

docs/zh-CN/components/list.md, scss/components/_list.scss, src/renderers/Card.tsx, src/renderers/List.tsx
相关issue： https://github.com/baidu/amis/issues/1481
解决两个问题
1. crud 的 list 模式， quickEdit 中的表单项无法设置 multiple 问题
2. list 新增 actionsPosition 配置项。
=> list 模式支持按钮在左侧 & 修复 multiple 透传问题

src/components/Tree.tsx, src/renderers/Form/TreeSelect.tsx, src/utils/helper.ts
1. treeSelect 显示值复用 `getTreeAncestors` 方法。
2. 非 onChildren 模式，当所有孩子节点都选中时，父级自动选中，并且所有子节点选中不可勾选状态。
3. onlyChildren 模式时，所有子节点都选中，父级节点自动选中，并且所有子节点保持选中，但是可取消勾选状态。取消后父级自动变成不勾选状态。
4. cascade 模式不受影响。
5. 添加了半选展示，即当有其中某个孩子点选了，父级就处于半选状态。
=> 优化 Tree 父子选中逻辑

src/utils/tpl-builtin.ts
最开始如果为 null 或 undefined dataMapping 后变成了空字符.
后来改动后变成原始值,也就是说如果是 undefined 就还会是 undefined. 这样的话发送 api 就不会发送这个 key 了.导致了大量已有业务可能不兼容报错.
所以...
还原原来的逻辑, dataMapping 如果目标值是 undefined 或者 null 就继续是空字符.除非这么配置就不发送了. ${xxx|default:undefined}
=> 调整 data-mapping 对 null undefined 值的处理.

package.json
用户反馈 monaco-editor 0.21.2 会导致safari 崩溃
=> 升级 monaco-editor

src/utils/tpl-builtin.ts
目前 api.data 支持对象形式的数据映射，如果想配置成发送数组格式，同时支持数据映射则不支持
=> api data 支持对象外的其他格式,比如数组

src/components/Select.tsx
loadOption method with empty term is not regarded as whole option fetch, so we need to cancel the method excute with empty string in clickItem case period. and support fetch agin when clear the value.
hope you adopt it : )
=> fix: change autoCompelete performance

src/components/Select.tsx
1. 点选不清空选项
2. 点选不清空搜索值
3. 搜索框添加清空按钮,点击清空选项
4. 只有搜索框值变化才触发选项拉取
=> 优化 select 交互

src/renderers/Table/HeadCellFilterDropdown.tsx
如果接口返回的是数字,点选后同步地址栏后变成字符串后当前选中的判断就不对了
=> filterable 判断是否选中不要那么严格

__tests__/renderers/Audio.test.tsx, __tests__/renderers/__snapshots__/Audio.test.tsx.snap, src/renderers/Audio.tsx
当音频文件加载所需时间大于 500 ms 时，会发生调用 load 方法，导致 canceled 当前请求，重新发起请求的循序，无法正确加载音频文件。
=> fix(Audio): should not call load method at first render

src/renderers/Form/ButtonToolbar.tsx
buttonToolbar 是个容器，本来不关联表单项，所以应该是 strictMode：false 。如果不是容器的话，默认关联 name，只有表单项的值变化才会更新。
=> fix: buttonToolbar 中数据同步不及时

src/SchemaRenderer.tsx, src/renderers/Audio.tsx, src/renderers/Carousel.tsx, src/renderers/Color.tsx, src/renderers/Date.tsx, src/renderers/Each.tsx, src/renderers/Form/wrapControl.tsx, src/renderers/Image.tsx, src/renderers/Images.tsx, src/renderers/Json.tsx, src/renderers/Link.tsx, src/renderers/Mapping.tsx, src/renderers/Markdown.tsx, src/renderers/Plain.tsx, src/renderers/Progress.tsx, src/renderers/QRCode.tsx, src/renderers/SearchBox.tsx, src/renderers/SparkLine.tsx, src/renderers/Status.tsx, src/renderers/Steps.tsx, src/renderers/Tpl.tsx, src/renderers/Video.tsx, src/utils/helper.ts
配置默认值和组件控制下发的值都是属性 `value` 区分不了，表单项如果想自己控制值，应该忽略其他途径同步值。所以在schemaRenderer 中把 schema 中的 value 变成了 defaultValue，原本非表单项下获取值的方式也有所调整。
=> 组件 value 逻辑优化

src/components/Select.tsx
=> fix: 修复 Select 多选时，高亮会自动选中第一项的问题

src/components/DateRangePicker.tsx
季度范围选择器禁用方法比对精确到季就够用了。
修复在使用unix时间戳作为值时，禁用范围显示不正确的bug。
=> fix: 修复季度范围选择器禁用bug

src/components/DateRangePicker.tsx, src/components/MonthRangePicker.tsx
年份选择切换是根据/yy/i.test(this.props.inputFormat || '')判断的，给它传一下inputFormat让它支持切换
=> feat: 月度选择器支持年份选择切换

src/store/form.ts
原先行为：
也就是 `item.name` 可能是 `data.appId` 这样的多级属性
关联 [mr](https://github.com/baidu/amis/pull/1549)
=> 修复搜索框 clear-and-submit 时有多级属性时的错误行为

__tests__/renderers/Form/__snapshots__/fieldSet.test.tsx.snap, src/SchemaRenderer.tsx, src/compat.ts, src/renderers/Form/Item.tsx, src/utils/helper.ts
1. 原有 controls 下非表单项的 visibleOn 逻辑表现不一致
2. form 下面的 service 如果有字段跟 form 下字段同名，form 数据便跟不会下发到 service
3. 部分没有走 formItem 的表单项设置 mode 展示模式无效
=> 1.2.x 兼容性问题修复

src/renderers/Card.tsx, src/renderers/Form/Static.tsx, src/renderers/List.tsx, src/renderers/Table/TableCell.tsx
在 schema 的配置会作为 props 下发,导致优先级提高
比如: 某个表格配置了个 service 如果 service 成员包含有配置 api 的在成员中读取的 api 始终是最外层这个表格的 service api
=> fix: 表格单元格下发属性逻辑优化

src/SchemaRenderer.tsx, src/renderers/Form/index.tsx, src/renderers/Form/wrapControl.tsx
原来  {component: ReactComponent} 用法只能在 form 的 boy（或者 controls）下生效，如果层级较多，比如在 fieldset 中则无效。此次调整后多少层级都能支持。
=> feat: 自定义组件不在 form 当前层级也需要支持自动包裹 formItem 功能

docs/zh-CN/components/action.md
docs(action): added `info` level in action.md
文档缺少对`level=info`的展示效果，这里补充了info级别展示
官网文档描述如下：
```
level: 按钮样式，支持：link、primary、secondary、info、success、warning、danger、light、dark、default。
```
原始展示：
=> docs(action): added `info` level in action.md

src/utils/tpl-builtin.ts
以下模板实际上是 lodash 模板语法，但是被检测成了内置模板。因为 $XXX 用法是加了转义的，不应该生效
`"abc \\${{ varname }}，<%- data.a ? '1' : '2' %>" `
=> fix: bultin 语法检测,不检测带转义了的用法

src/renderers/Form/InputImage.tsx
qsstringify 空对象会出来一个空字符串，然后 split 会得到一个 [""]，然后被添加到 formData 里面了
=> fix: InputImage 上传时 formdata 不添加空元素

src/WithStore.tsx
主要解决以下场景
crud 中有一栏为 service, service 通过接口拉取接口数据, 当切换页面的时候,如果没有构成接口重新加载的条件, service 的接口不会重新拉取, 但是因为行数据变化,导致了 service 的数据丢失.
解决办法是, 当有远程数据时, 只做 merge ,而不是完全替换
=> fix: 数据同步导致接口数据丢失问题

src/renderers/Images.tsx
之前的改动引入的 bug ，变成无法支持 "images": "https://internal-amis-res.cdn.bcebos.com/images/2020-1/1578395692722/4f3cb4202335.jpeg,https://internal-amis-res.cdn.bcebos.com/images/2020-1/1578395692722/4f3cb4202335.jpeg" 这样子逗号分隔的字符串了
=> fix：图片集支持 string 类型

src/SchemaRenderer.tsx
下层消费的是 $schema，这里怎么没有放在 $schema 里面。我记得之前 requiredOn 是好的，应该是哪次重构 form 这边弄坏了。。
=> fix: requiredOn 不生效问题

docs/zh-CN/components/form/list-select.md
根据smis-1.2.1\src\renders\Form\ListSelect.tsx135-142行代码和语义，labelField & valueField应该为string类型。
=> labelField & labelField类型

__tests__/renderers/Form/__snapshots__/range.test.tsx.snap, scss/_properties.scss, scss/components/form/_range.scss, src/renderers/Form/InputRange.tsx
=> chore: 优化 inputRange 中间值位置

src/renderers/Dialog.tsx, src/renderers/Drawer.tsx
原来是有且只有一个 page 或者 service 才向下找,
现在是不管怎么组合,找不到就一直往里面找,直到找到第一个 crud 或者 form 或者 wizard 为止
=> chore: 调整弹框中查找子节点渲染器处理动作逻辑

__tests__/utils/validations.test.ts, src/utils/validations.ts
单纯的依赖 `JSON.parse` 判断是否是 `json` 并不准确。
```
JSON.parse('true'); // true
JSON.parse('false'); // false
JSON.parse('123'); // 123
```
https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse
=> fix: 修复 isJson 校验

docs/zh-CN/components/form/input-rich-text.md, src/renderers/Form/InputRichText.tsx
之前不支持 amis 标准的 api 返回格式，response.data 是返回内容
```
{
"status": 0,
"data": {
"link": "https://xxx.png"
}
}
```
=> fix: tinymce 图片上传结果解析不正确

docs/zh-CN/components/date.md
docs(date.md): 修复date在Form表单中文档与代码不一致的问题
`static-color`应该为`static-date`
参考：
https://aisuda.github.io/amis-1.1.7/zh-CN/components/date#form-%E4%B8%AD%E9%9D%99%E6%80%81%E5%B1%95%E7%A4%BA
=> docs(date.md): 修复date在Form表单中文档与代码不一致的问题

scss/components/_table.scss, src/renderers/Form/InputTable.tsx, src/renderers/Table/TableContent.tsx, src/renderers/Table/index.tsx, src/store/table.ts
1. 修复固定列和超级表头结合导致的样式问题
2. 超级表头如果 label 值一样，自动合并单元格
3. inputTable 共用 operation 栏
4. th td 可以通过配置 text-center 或者text-right 来实现居中和居右
=> fix: 修复固定列和超级表头结合导致的样式问题

src/renderers/CRUD.tsx
{
type: 'crud',
api: '/api/sample',
mode: 'cards',
primaryField: 'id',
pickerMode: true,
value:[{id:2}]
}
src/renderers/CRUD.tsx
componentDidMount, componentDidUpdate
中无法获取到this.props.value，导致无法选中value默认的值
需要getPropValue(this.props)来取defaultValue
=> fix: crud无法获取value的修复

examples/components/Form/Full.jsx, src/components/Tree.tsx, src/renderers/Form/InputTree.tsx
{
type: 'input-tree',
name: 'tree',
label: '树',
showIcon: true
iconField: 'icon',
option:[
{
label: 'Folder A',
value: 1,
icon: 'fa fa-bookmark',
children:[
{
label: 'file A',
value: 2,
icon: 'fa fa-star'
}]}]
}
显示 iconField 对应的 icon；
之前的会出现 iconFied 的 icon 和 内部的 folder/file icon 同时显示的情况
=> fix: inputTree的icon显示修复

docs/zh-CN/components/form/input-tree.md, src/components/Tree.tsx
之前为了使用组件内提供的svg所以这么修复了。
但是这样子就不支持iconfont等，所以重新进行了容错
=> inputTree的icon显示修复

src/renderers/Form/Picker.tsx
如果配置 source 打开后通过接口拉取显示选项,没必要下发当前表单项的选项, 减少dom 更新开销
=> chore: 优化 picker 弹出窗, 不会出现先渲染整个 options 然后接口返回后改成渲染当前第一页数据

src/renderers/Form/index.tsx, src/store/form.ts
原因是表单初始化过程中也会触发 form 的handleChange，而这个时候拿到的数据是不全的，而且会写入本地，导致原来写入的数据被删除。
=> fix: 修复表单本地持久数据获取失效问题

scss/_properties.scss, scss/themes/_cxd-variables.scss
现在AntD，Ang主题下的背景色和ICON颜色交叠，有点不太和谐。
看了下AntD官方的消息组件都采用白色背景了，所以这里统一升级一下
=> fix: 非CxD主题下Toast背景颜色和ICON颜色相近问题

src/components/Drawer.tsx
`Drawer`
当该组件消失时，动画结束后，图标按钮(`Close`)并没有消失，`dark`主题下可浮现
根据组件`props.show`动态渲染图标按钮(`Close`)，来避免延时问题
=> style: fix close button hide delay

scss/_properties.scss, src/components/calendar/DaysView.tsx
- [ √] 组件样式/交互改进
| 英文 |   Calendar schedule component style fixed under other themes & Schedule click event Click area modification      |
| 中文 |    日历日程在其他主题下样式修复&日程点击事件点击区域修改      |
- [ √] 文档已补充或无须补充
- [ √] 代码演示已提供或无须提供
- [ √] TypeScript 定义已补充或无须补充
- [ √] Changelog 已提供或无须提供
=> fix: 日历日程在其他主题下样式修复 & 日程点击事件点击区域修改

src/utils/helper.ts
如果判断 `children.length !== item.children.length`，这样如果当前层级长度没变，那么下一层级的children过滤结果就不会正确返回。
如下：
```
const nav = [
{
label: '1',
readable: true,
children: [
{
label: '2',
readable: true,
children: [
{
label: '3',
readable: false
}
]
}
]
}
];
```
正常过滤后，应该结果是
```
[
{
label: '1',
readable: true,
children: [
{
label: '2',
readable: true,
children: []
}
]
}
]
```
但因为第二层长度没变，又会返回原来的item，导致第三层还是原始值
=> fix: 修复 filterTree 深层级过滤失效的问题

scss/components/_modal.scss, scss/components/_panel.scss, scss/components/form/_form.scss, src/renderers/Form/Item.tsx, src/renderers/Remark.tsx
输入框样式优化: 横向展示，去除多余边距
提示: 改成弹框
底部按钮：横向铺满
=> refactor: 移动端输入框样式优化

scss/components/_table.scss, src/renderers/Form/Select.tsx
感觉可能是之前改 popOverContainer 导致的，但没看出是哪里，而这个 overflow-x 似乎用处不大，就先这样修复了
=> fix: 修复 input-table 里的 popover 被遮挡问题 Closes #3377

src/renderers/CRUD.tsx
测试例子是
```javascript
export default {
type: 'page',
title: '列表',
body: [
{
type: 'crud',
name: 'datalist',
autoGenerateFilter: true,
api: '/api/mock2/sample',
columns: [
{
type: 'text',
name: 'id',
label: 'ID',
searchable: {
type: 'input-text',
name: 'id',
label: 'ID',
placeholder: '请输入ID',
mode: 'horizontal'
}
}
]
}
]
};
```
=> fix: 修复 autoGenerateFilter 导致 crud 加载两次问题

docs/zh-CN/start/getting-started.md
Hi,
"skd" should be “sdk”.
Thanks.
=> doc: 修正快速开始部分的文档错误.

examples/components/EventAction/SwitchEvent.jsx, examples/components/EventAction/TabsEvent.jsx, examples/components/Example.jsx, src/renderers/Form/Switch.tsx, src/renderers/Tabs.tsx
https://ku.baidu-int.com/knowledge/HFVrC7hq1Q/pKzJfZczuc/GxsYWwEpj5/FqxJ7_8Hkof-ed
https://ku.baidu-int.com/knowledge/HFVrC7hq1Q/pKzJfZczuc/GxsYWwEpj5/8riCsF-a-98HYl
| 中文 |    1. Switch，Tabs组件添加'change'事件 <br> 2. Tabs组件添加'ChangeActiveKey'动作      |
=> 开关/选项卡组件事件 & 动作扩充

src/utils/attachmentAdpator.ts
当http code不为200的时候，response.data为null，执行`response.data.toString()`会抛错
导致无法正确执行后续的`responseAdaptor`
=> fixup: 容错请求错误的情况

docs/zh-CN/components/service.md
虽然只是一个单词错误, 但在使用的时候会误导用户, 导致只能看源码才能确认
=> docs: service组件文档示例里将dataProvider错写成func

src/renderers/Tabs.tsx
改动一行代码, 对preProps.location做了空值保护
=> fix: 修复在使用App路由时, Tabs组件页面跳转其他路由出现白屏 #3636

scss/components/form/_number.scss
input-number圆角显示可能不完整，云舍主题下比较明显；
dark主题下数字颜色是黑色，改成跟随主题。
=> fix: input-number圆角显示可能不完整，数字颜色跟随主题

src/renderers/Page.tsx
问题 case
一个 crud 和 form 并列，crud 的操作栏中按钮  actionType: reload, target: theForm?xx=xxx 
如果直接放在 page 下面可以将数据传递下去。
如果中间夹杂一个 service，就不成功。
原因 是 reload 动作是在 page 层处理的，找组件的时候之前是在page那层找的，所以找不到对应的组件
=> fix: 修复 action 为 reload 时获取目标逻辑问题

src/renderers/Form/Combo.tsx
在 Tabs 模式下, `makeFormRef`函数 要在选中对应的 Tab 之后才会执行。
如果新增了多个，先选中之后的 Tab，则 `this.subForms` 会类似  `[FormRenderer, empty, FormRenderer]`。
导致 `this.subFormDefaultValues.length !== this.subForms.length` 为true，之后的 init 没有执行。
而在最后一次初始化的时候，就会有很多 subFormDefaultValue 的 setted 为 `false`，值被重置
相关问题请看 issue 中的视频：https://github.com/baidu/amis/issues/3511
=> fix: combo 组件 Tabs 模式下值丢失的 bug

scss/components/form/_editor.scss
=> fix: 多层Form嵌套情况下Editor无法完整显示问题

examples/components/CRUD/LoadOnce.jsx, mock/cfc/mock/sample.js, src/renderers/CRUD.tsx, src/store/crud.ts
前端一次性加载之前配置列搜索功能还需要对应配置 source 结合过滤器处理。现在改成自动就支持无需配置 source 里面的过滤器语法。只要列开启了搜索功能就自动过滤。
=> feat: crud loadDataOnce 前端自动支持过滤器

docs/zh-CN/components/progress.md, scss/components/_progress.scss, src/components/Progress.tsx, src/renderers/Progress.tsx
1. map新增自定义颜色控制 支持 "#ffff" | "bg-success" | ["#ffff","bg-success"] |  [{color: '#f1f', value: 60}...]
2. 样式优化
=> feat: 添加进度条自定义颜色配置

docs/zh-CN/components/form/nestedselect.md, src/renderers/Form/NestedSelect.tsx
| 中文 |       增加级联多选仅允许选择子节点及文档说明   |
=> feat: 级联多选支持仅子节点

docs/zh-CN/components/icon.md, src/renderers/Icon.tsx
由于升级fontawesome到v5/v6等版本后, 无法正常展示, 排查发现是由于字符串拼接的问题，修复后效果如下
示例amis代码：
```schema
{
"type":"page",
"body":[
{
"type":"icon",
"icon":"far fa-address-book",
"vendor":""
},
]
}
```
=> feat: 支持fontawesome v5/v6 等版本 & 添加icon示例

src/actions/EmailAction.ts
修复前：
`mailto:amis@baidu.com?to=amis%40baidu.com&cc=&bcc=&subject=&body=`
修复后：
`mailto:amis@baidu.com?cc=&bcc=&subject=&body=`
=> 修复邮箱地址重复填写的问题

src/renderers/Form/wrapControl.tsx
unRegisterComponent 无效，从而导致getComponentById返回错误的引用 #4004
=> unRegisterComponent 无法被调用到

examples/embed.tsx
#4010 也提到了该问题
大概原因，应该是升级了react的版本引起的加载顺序的问题
=> 修复jssdk下，丢失scoped的问题

src/components/Rating.tsx
=> feat: 评分组件 texts、colors 过滤非数字key， 如：$$id

docs/zh-CN/components/form/json-schema-editor.md, examples/components/Components.tsx, package.json, scss/components/_json-schema-editor.scss, scss/components/_result-box.scss, scss/components/form/_selection.scss, scss/themes/_common.scss, src/Schema.ts, src/components/InputBox.tsx, src/components/PickerContainer.tsx, src/components/TooltipWrapper.tsx, src/components/formula/VariableList.tsx, src/components/schema-editor/Array.tsx, src/components/schema-editor/Common.tsx, src/components/schema-editor/Item.tsx, src/components/schema-editor/Object.tsx, src/components/schema-editor/SchemaVariableList.tsx, src/components/schema-editor/SchemaVariableListPicker.tsx, src/components/schema-editor/index.tsx, src/index.tsx, src/locale/de-DE.ts, src/locale/en-US.ts, src/locale/zh-CN.ts, src/renderers/Form/JSONSchemaEditor.tsx, src/utils/DataSchema.ts, src/utils/DataScope.ts
* 添加 json-schema-editor 渲染器
* 添加 SchemaVariableList 和 SchemaVariableListPicker  组件
* 添加数据类型帮助类
=> feta: 添加 json-schema-editor 渲染器

src/renderers/CRUD.tsx
=> fix #3967: CRUD导出csv按钮文字size不统一问题

scss/helper/typography/_text-color.scss
=> docs: 增加Text Color示例支持，方便选取颜色

docs/zh-CN/components/form/input-tree.md, examples/components/EventAction/CarouselEvent.jsx, examples/components/EventAction/InputTreeEvent.jsx, examples/components/EventAction/TabsEvent.jsx, src/components/Tree.tsx, src/renderers/Carousel.tsx, src/renderers/Form/InputTree.tsx, src/renderers/Tabs.tsx
https://console.cloud.baidu-int.com/devops/icafe/issue/amis-saas-4174/show?source=drawer-header
| 中文 |      标签组件："changeActiveKey'"动作，标签项索引默认值从1开始，自定义tab hash不受影响 <br> 轮播图组件："goto-image"动作，索引默认从1开始 <br>树组件框，"expand"动作，展开层级默认从1开始    |
=> feat: 调整Tabs、Carousel、InputTree组件触发动作索引值，从1开始递增

src/renderers/Form/Select.tsx
| 中文 |  fix: 修复select onEdit/onDelete外部无法获取option   |
=> fix #4085: 修复select onEdit/onDelete外部无法获取option

src/renderers/PopOver.tsx
类似下面这种结构，mode应该覆盖掉type属性才是正常弹框
```json
{
"name": "engine",
"label": "渲染引擎",
"type": "text",
"popOver": {
"mode": "dialog",
"title": "查看详情",
"body": [
{
"type": "tpl",
"tpl": "内容详情",
"inline": false
}
]
}
}
```
=> fix: 修复Popover弹框显示异常问题

scss/components/form/_date-range.scss
input框未设置宽度，所以第一次渲染的的时候，宽度是合适的。
但拖动浏览器宽度后，就会发现input小了或者过长了。加上flex:1的属性后可以自动伸缩
=> chore: 优化日期范围input宽度

__tests__/renderers/Table.test.tsx, __tests__/renderers/__snapshots__/Table.test.tsx.snap, src/store/table.ts
```js
{
type: 'table',
source: '$rows',
className: 'm-b-none',
columns: [
{
name: 'engine',
label: 'Engine'
},
{
name: 'grade',
label: 'Grade'
},
{
name: 'version',
label: 'Version',
groupName: '分组2' // 这里没配置groupName
},
{
name: 'browser',
label: 'Browser',
groupName: '分组2'
},
{
name: 'id',
label: 'ID',
groupName: '分组3'
},
{
name: 'platform',
label: 'Platform',
groupName: '分组3'
}
]
}
```
=> fix: 修复超级表头合并问题

src/components/Range.tsx
=> fix(Range): 完善滑块刻度标记展示，避免显示多余元素

packages/amis-ui/scss/components/_page.scss
bug复现的 json配置如下
```json
{
"pullRefresh": {
"disabled": false
},
"aside": [
{
"type": "tpl",
"tpl": "这是侧边栏部分"
}
],
"body": [
{
"label": "66666666"
}
]
}
```
导致内容区的外层元素宽度没有设置 flex-flow:1 而没有撑开
=> fix:修复存在侧边栏的情况下，设置pullRefresh.disabled为 false情况下，内容区展示异常问题

docs/zh-CN/style/index.md
=> docs: 修复文档中示例code多余空格导致的报错

packages/amis-core/src/store/form.ts, packages/amis/src/renderers/Form/Combo.tsx
1. 描述： combo 组件在值打平模式下（配置如下）,提交时校验出错
```javascript
{
type: "combo",
flat: true,
joinValues: true
// ...
}
```
2. 问题出现原因：
值打平模式下，value 为字符串`str1,str2`，会在下方代码的`!Array.isArray(value)`中被捕获，导致校验报错
```javascript
if (minLength && (!Array.isArray(value) || value.length < minLength)) {
return __(
(messages && messages.minLengthValidateFailed) || 'Combo.minLength',
{minLength}
);
}
```
3. 解决方案
在校验前，使用`this.getValueAsArray()`方法对`value`先进行转换
1. 描述：当表单中有combo组件submit时，combo中的表单项会被重复校验，如果是多层combo嵌套会重复更多次，尤其是表单项中包含 远程api校验的情况，会让校验时间成倍增长，表单反应特别慢。
2. 问题出现原因：当前逻辑是校验时，会先收集包含深层子元素在内的所有formItem，循环校验结束后，再调用子表单hook校验，子表单校验时，其中的表单项被再次校验，导致了重复校验。
3. 解决方案：在收集formItem阶段，只收集验证直接子表单项就可以。
| 英文 | Fix some verification issues of the Combo component.  |
| 中文 | 修复combo组件的一些校验问题。 | …
=> Fix comb repeat remote verification

packages/amis/src/renderers/Flex.tsx
以下代码存在bug，因为flex布局向下传递的 disabled 会一直覆盖 items中每项的 disabled属性
```javascript
{
"body": [
{
"type": "flex",
"justify": "space-around",
"alignItems": "center",
"direction": "row",
"style": {
"width": 350,
"height": 30
},
"items": [
{
"type": "tooltip-wrapper",
"content": "提示文字",
"body": "hover 激活文字提示",
"className": "mb-1",
"disabled": true  // 此属性设置不生效
}
]
}
]
}
```
=> fix:修复flex布局传递给 flexItem的disabled属性bug问题

src/components/Select.tsx, src/renderers/Form/Select.tsx
当在value值未匹配到当前options中的选项时，是否value值对应文本飘红显示
=> feat:新增 select组件 showInvalidMatch属性

packages/amis-core/src/renderers/Form.tsx, packages/amis-ui/scss/components/form/_form.scss, packages/amis/__tests__/event-action/renderers/form/__snapshots__/range.test.tsx.snap, packages/amis/__tests__/renderers/Form/__snapshots__/chainedSelect.test.tsx.snap, packages/amis/__tests__/renderers/Form/__snapshots__/conditionBuilder.test.tsx.snap, packages/amis/__tests__/renderers/Form/__snapshots__/inputArray.test.tsx.snap, packages/amis/__tests__/renderers/Form/__snapshots__/inputFormula.test.tsx.snap, packages/amis/__tests__/renderers/Form/__snapshots__/inputTable.test.tsx.snap, packages/amis/__tests__/renderers/Form/__snapshots__/text.test.tsx.snap, packages/amis/__tests__/renderers/Form/inputTag.test.tsx
amis文档中即可复现，bug复现代码如下：
```javascript
{
"body": {
"debug": true,
"body": [
{
"name": "name",
"label": "姓名：",
"value": "这是一个很长的文本，导致了开启debug后，表单数据显示的样式出现了问题，超出的内容显示在容器外了，超出的内容显示在容器外了，超出的内容显示在容器外了，超出的内容显示在容器外了"
}
]
}
}
```
=> fix:表单开启debug后，表单项字段内容过长导致数据显示样式问题

packages/amis-ui/src/components/Select.tsx, packages/amis/__tests__/renderers/Form/__snapshots__/repeat.test.tsx.snap, packages/amis/__tests__/renderers/Form/__snapshots__/select.test.tsx.snap
.hidden 样式是 `display: none`，所以这个区块的 offsetHeight 肯定为 0，导致其实这个区块实际上即不显示，对应的 ref 也没有效果，其实是无用代码
=> fix: 去掉 select 中的无用代码

packages/amis-core/src/actions/DialogAction.ts
dialogAction 是新版事件动作，要刷新什么由用户配置决定，不需要自动刷新机制，所以复用原来的弹窗逻辑时指定不刷新任何目标
=> chore: 事件动作中 dialog 动作关闭自动个刷新, 由配置决定是否刷新目标

docs/zh-CN/components/form/chain-select.md, packages/amis/src/renderers/Form/ChainedSelect.tsx
在后端接口不符合规范的情况下，导致页面报错，例如下面接口返回：
```javascript
{
"status": 0,
"data": {
"items": [ // 这里应该使用 options ， 或者整个data字段是个 Array
{
"engine": "aute nulla incididunt mollit",
"id": "sunt"
},
{
"engine": "deserunt",
"id": "nulla ullamco fugiat labore"
},
{
"engine": "ullamco laboris reprehenderit",
"id": "sunt do id"
}
]
}
}
```
在 amis 中可复现此bug，代码如下：
```javascript
{
"body": {
"debug": true,
"api": "/api/mock2/form/saveForm",
"body": [
{
"name": "select3",
"type": "chained-select",
"label": "链式下拉",
"source": "https://yapi.baidu-int.com/mock/29236/selectabc/test/a",
"labelField": "engine",
"valueField": "id"
}
]
}
}
```
=> fix:ChainedSelect针对后端接口返回内容不规范导致报错处理

packages/amis-core/src/store/crud.ts, packages/amis/src/renderers/CRUD2.tsx
为了不影响 table-v2 ，我在CRUD里面传参过去的时候调整一下, 这样 store中的 crud.ts文件会运行下面
```javascript
if (Array.isArray(columns)) {
self.columns = columns.concat(); // 设置 store.columns 为 接口获取的值
} else {
self.columns = options.columns; // 设置传递进来的 columns 值， 这时候传递进来的就是  undefined
}
```
=> fix:修复 CRUD组件更改columns字段不立刻生效问题

packages/amis-formula/src/evalutor.ts
示例中使用了 `~` 符号，和 markdown 的语法产生冲突，造成文档解析异常
修正示例符号，解决 markdown 的语法冲突。
=> fix: fix doc parse error caused by vulnerable example.

packages/amis-core/src/store/form.ts
下面代码可在 amis 中复现bug
```javascript
{
"title": "test-tree",
"body": [{
"title": "表单",
"body": [{
"label": "文本",
"name": "text",
},
{
"type": "input-password",
"label": "密码",
"name": "pas",
"showCounter": false,
"validations": {
"equals": "${text}"
},
"validationErrors": {
"equals": "密码nononno"
},
"validateOnChange": false
}],
"apiFromAPICenter": false,
"id": "u:7cff08516ae7",
"initApiFromAPICenter": false,
"debug": true,
"api": "111"
}]
}
```
bug复现逻辑为：
1、先在 文本中输入 12
2、在在 密码中输入 12
3、然后 点击提交可正常触发提交逻辑
4、更改文本内容为 123时
5、再次点击提交可正常触发提交逻辑，不符合预期
=> fix:配置指定某个字段的值校验情况，导致校验可能出错

packages/amis-core/src/renderers/Form.tsx, packages/amis/src/renderers/Action.tsx, packages/amis/src/renderers/Dialog.tsx, packages/amis/src/renderers/Drawer.tsx
1. 正常通过点击弹窗的确认按钮可以提交表单并关闭，但是如果不是通过点击弹窗的按钮触发的表单提交目前无法自动关闭，比如按 enter，或者 form 内的提交按钮
2. dialog 中表单提交如果不是dialog 里面的按钮触发的，目前 dialog 不会出现 loading 态，导致可以重复提交，目前的解法是，onAction 的基础上加了 onActionSensor ， 通过这个来监控内部动作的结果，过程中让整个 dialog 不可点。
=> fix: 修复弹窗中的表单提交不自动关闭弹窗的问题

packages/amis/__tests__/renderers/__snapshots__/Page.test.tsx.snap, packages/amis/src/renderers/Tpl.tsx
解决某些组件中由于 tpl 中不存在 diff，导致的重渲染 bug
=> fix: 用 dangerouslyHTML 代替 innerHTML 以使 tpl 中的标签有 diff 优化

packages/amis/src/renderers/Table/index.tsx
之前 revert 遗留的问题，因为 `Modal` 在展开后已经不具备 `transform` 属性，之前去判断 `height` 和 `scrollHeight` 的方法已经没有必要了
=> fix: 修复 table 获取滚动的父元素不准确的问题

docs/zh-CN/components/form/input-formula.md, packages/amis-ui/src/components/formula/Picker.tsx, packages/amis/src/renderers/Form/InputFormula.tsx
混合模式的意思是支持输入文本和输入公式两种格式的值，当输入公式时值会自动用 `${` 和 `}` 包裹，如果不是这种格式则认为是输入普通的字符串。通过 `mixedMode` 为 true 启用这种模式
=> feat: input-formula 支持 mixedMode 支持字符串和表达式混合输入

examples/components/Example.jsx, examples/components/Form/SwitchDisplay.jsx, packages/amis-core/src/SchemaRenderer.tsx, packages/amis-core/src/actions/CmptAction.ts, packages/amis-core/src/renderers/Form.tsx, packages/amis-core/src/renderers/Item.tsx, packages/amis-core/src/store/root.ts, packages/amis-core/src/types.ts, packages/amis-ui/scss/components/form/_checks.scss, packages/amis-ui/scss/components/form/_form.scss, packages/amis-ui/scss/components/form/_input-group.scss, packages/amis-ui/scss/components/form/_list.scss, packages/amis/src/renderers/Color.tsx, packages/amis/src/renderers/Form/InputColor.tsx, packages/amis/src/renderers/Form/InputText.tsx, packages/amis/src/renderers/Form/StaticHoc.tsx, packages/amis/src/renderers/Form/Switch.tsx, packages/amis/src/renderers/QuickEdit.tsx
[Form支持编辑态、展示态切换](https://ku.baidu-int.com/knowledge/HFVrC7hq1Q/tQvrZcAEPS/GxsYWwEpj5/CB1YWGgjJB3DYZ)
1. `Form` 新增`static、staticOn、staticClassName`属性，支持通过`static`切换编辑态展示态；
2. `FormItem` 新增`static、staticOn、staticSchema、staticPlaceholder、staticClassName`属性，支持通过`static`切换编辑态展示态；
3. 新增`static`、`nonstatic`动作，用以切换`Form`和`FormItem` 的编辑态展示态；
=> feat: 表单展示态编辑态切换

docs/zh-CN/components/form/condition-builder.md, packages/amis-ui/scss/components/form/_selection.scss, packages/amis-ui/src/components/condition-builder/Expression.tsx, packages/amis-ui/src/components/condition-builder/Field.tsx, packages/amis-ui/src/components/condition-builder/Group.tsx, packages/amis-ui/src/components/condition-builder/GroupOrItem.tsx, packages/amis-ui/src/components/condition-builder/Item.tsx, packages/amis-ui/src/components/condition-builder/index.tsx
ConditionBuilder组件，左侧选择框对于多层嵌套的属性结构支持不友好，增加属性配置，支持树形结构
| 中文 |    ConditionBuilder组件左侧选项支持树形结构      |
=> feat: ConditionBuilder组件左侧选项支持树形结构

packages/amis/src/renderers/Form/InputRichText.tsx
点击[官方示例](https://baidu.github.io/amis/zh-CN/components/form/input-rich-text)进行上传图片出现报错, 如下图：
升级到tinymce 6 后images_upload_handler 有变化。
The [version 6.X ](https://www.tiny.cloud/docs/tinymce/6/upload-images/#example-using-images_upload_handler)return a Promise and the [version 5.X](https://www.tiny.cloud/docs/configure/file-image-upload/#images_upload_handler) use callback function.
=> fix: 2.1.0 及以上版本升级到tinymce 6上传图片不兼容的问题

packages/amis/src/renderers/Json.tsx
当使用JSON组件时，不能支持boolean类型的值展示，因此对boolean类型进行兼容
同时对于空对象和值为0时，不能够进行适配，因此去除data的判断
| 中文 |      json组件支持boolean基础类型     |
=> fix: json组件支持boolean基础类型

packages/amis/src/renderers/Form/InputText.tsx
通过 JSON.stringify 后变成了带引号的格式比如 `"2022-09-26T14:55:17.301Z"` 实际上应该显示 `2022-09-26T14:55:17.301Z`
=> fix: 修复 inputText 对日期对象显示问题

packages/amis-ui/scss/components/_images.scss, packages/amis/src/renderers/Image.tsx
比如 crud 中，翻页后，图片地址变化，但是在新图片加载完成之前依旧显示旧图片。导致用户困扰
=> fix: Image 修改图片地址,图片显示问题修复

packages/amis-ui/scss/components/form/_form.scss, packages/amis-ui/scss/components/form/_select.scss
复现schema
```javascript
{
"body": {
"body": [
{
"label": "选项",
"type": "select",
"name": "select",
"options": [
{
"label": "Adsafasfdsadasdasdasdasdasdfsacsacewdwadawdasdasdasfasfasfasdfasdasdasdasdsadfasfasfascsaxewfhtrjytkuyikuynfdvascfasdasd",
"value": "a"
},
{
"label": "B",
"value": "b"
},
{
"label": "C",
"value": "c"
}
]
}
]
}
}
```
=> fix:select组件选中项很长的情况下，输入框内容的label显示问题 & 同样移动端也是存在显示问题

packages/amis-ui/scss/components/form/_form.scss
=> style: quickEdit 列去掉 min-width 设置,因为如果是个开关用不了那么宽

packages/amis-ui/scss/components/form/_number.scss
- [✓] 日常 bug 修复
1. 改变`amis_ui `中的`_number.scss` 文件 input border颜色 为`--Form-input-borderColor`
2. 向`amis_ui` 中的`_number.scss `文件 中的相应input类加入placeholder伪元素 控制颜色
自测case文档：https://ku.baidu-int.com/knowledge/HFVrC7hq1Q/pKzJfZczuc/CHrzXx4sGW/pRAcc5vDQDbrtP
总共两项变化：
1. input-number组件边框与其余form-input组件（例如input-text）边框颜色统一
2. input-number组件 placeholder颜色置灰 与input-text组件颜色统一
- [✓] 文档已补充或无须补充
- [✓] 代码演示已提供或无须提供
- [✓] TypeScript 定义已补充或无须补充
- [✓] Changelog 已提供或无须提供
=> fix: 数字输入框-属性配置-placeholder置灰+边框与form-input统一

docs/zh-CN/components/form/condition-builder.md, packages/amis-ui/src/components/condition-builder/Value.tsx
复现步骤，官方网站示例即可复现：
https://baidu.github.io/amis/zh-CN/components/form/condition-builder#%E4%B8%8B%E6%8B%89%E9%80%89%E6%8B%A9
修复完成的效果图
=> fix: 修复condition-builder组件select类型placeholder属性不生效的bug

packages/amis-core/src/renderers/Item.tsx
修复static-xxx组件配置inputClassName时，会重复设置的问题，如图
bug原因：
在开发表单静态展示的时候，删除了两行代码导致
解决：
还原代码，在解构赋值时，加入inputClassName，让 rest 不包含inputClassName
=> fix: 修复旧版static-xxx组件inputClassName重复的问题

packages/amis-core/src/RootRenderer.tsx, packages/amis-core/src/env.tsx, packages/amis-core/src/store/root.ts
SaaS中需要对页面入参进行结构化定义，意味着需要将url中的页面参数转化成对象、布尔等结构的值，因此添加自定义解析URL的方法来解析URL参数
| 中文 |    添加自定义解析页面URL方法      |
=> feat: 添加自定义解析页面URL方法

packages/amis/src/renderers/Table/index.tsx
否则 table 内嵌 table，会导致里面的 autoGenerateFilter 配置无效
=> chore: table 不应该透传 autoGenerateFilter

docs/zh-CN/concepts/data-mapping.md
以前 https://github.com/baidu/amis/pull/1996 就有的cookie數據映射
文檔沒寫到 順手添加
=> docs: 補充namespace缺少的cookie

packages/amis/src/renderers/Form/InputTable.tsx
问题：inputTable组件，存在多行内容，当某行被编辑后，无论确认还是取消，操作列按钮显示Bug
[官方文档位置](https://aisuda.bce.baidu.com/amis/zh-CN/components/form/input-table#%E9%85%8D%E7%BD%AE%E6%8C%89%E9%92%AE%E4%B8%BA%E6%96%87%E5%AD%97)
解决：操作后，重新渲染列
问题截图：
_编辑后：_
第2行编辑后，1/3行的操作列没有被渲染
=> fix: inputTable编辑按钮Bug

packages/amis-ui/src/components/DatePicker.tsx
bug原因： onInputBlur 时候会把inputValue 设置为 缓存值，当有默认值，componentDidMount 中未对 inputValueCache 进行初始化
```
onInputBlur() {
this.setState({
inputValue: this.inputValueCache
});
}
```
=> fix: 修复inputDate组件有默认值时首次触发blur值会被清空的问题

docs/zh-CN/components/form/condition-builder.md
问题描述： 修复ConditionBuilder文档中tree模式格式代码示例错误导致的下拉框无法被选中问题，如下，点击file A后，仍然未
**选中前：**
**选中后：**
复现步骤：
官方网站示例即可复现
示例地址：https://baidu.github.io/amis/zh-CN/components/form/condition-builder#%E5%AD%97%E6%AE%B5%E9%80%89%E9%A1%B9%E7%B1%BB%E5%9E%8B
修复效果如下：
=> docs: 修复ConditionBuilder文档中tree模式格式代码示例错误导致的下拉框无法被选中问题

packages/amis/src/renderers/Action.tsx, packages/amis/src/renderers/Dialog.tsx, packages/amis/src/renderers/Drawer.tsx
当dialog/drawer的body中同时存在`"actionType": "ajax"` 类型的按钮和CRUD/Service等组件时(平级关系), 触发Action的请求, 会联动触发CURD/Service组件的api请求, 此时设置`isolateScope`可以避免联动触发, 让Action单纯发出一个请求.
=> feat: Action组件支持isolateScope

packages/amis-core/src/renderers/Form.tsx
复现schema
```
{
"body": [
{
"type": "tabs",
"tabs": [
{
"title": "基本信息",
"body": [
{
"name": "status",
"label": "状态",
"static": true
}
]
}
]
}
]
}
```
bug原因：
Form中包含容器类组件时，
这些组件会将此处的disbaled、static 等属性继续下发至子组件，
导致SchemaRenderer中 `props.static` 覆盖 `schema.static`
以上schema 渲染tabs时，`static: (control as Schema).static || props.static` 的结果为 `false`, 
下发后覆盖了表单项的 static ，从而导致了bug
=> fix: 修复tabs 内的表单项无法设置 static 属性的问题

index.html, packages/amis-ui/src/components/Editor.tsx
使用了vite-plugin-monaco-editor 会自动注入 MonacoEnvironment 这个全局变量，不用ui库改写了， 要不然代码还需要复写，现在我是这样处理的 😂
=> fix: 解决monaco环境变量和monaco插件的冲突

examples/components/CRUD/Nested.jsx, packages/amis-core/src/store/table.ts
```
{
expandConfig: {
expand: 'all'
},
}
```
不能展开所有子节点，如果考虑性能展开第一个层级是否应该增加配置，保留原来模式
但 `expand: 'all'` 意在展开所有子节点更容易被用户记住和接受
=> fix(Table): #2978 嵌套表格如何设置默认全部展开

packages/amis-ui/src/components/formula/VariableList.tsx
=> fix: 解决公式编辑器 搜索变量失效bug

packages/amis-core/src/RootRenderer.tsx, packages/amis-core/src/store/iRenderer.ts, packages/amis/src/renderers/Page.tsx
因为 drawer 会委托上层来处理，reload 的时候查找目标也变成上层了，所以会存在某些组件找不到的问题
=> fix: 修复 drawer reload 目标可能找不到的问题

packages/amis-editor-core/package.json, packages/amis/package.json
https://webpack.js.org/guides/package-exports/#reference-syntax
webpack5 引入css的时候会报错
=> fix: webpack5 import css error

packages/amis-core/src/utils/optionValueCompare.ts, packages/amis-ui/src/components/Transfer.tsx, packages/amis/src/renderers/Form/Transfer.tsx
* fix:transfer tree 支持 onlyChildren;两个值为undefined的Option不相等
* 修改
* 修改
=> fix: Transfer tree mode 支持 onlyChildren;两个值为undefined的Option不相等 (#6342)

docs/zh-CN/components/form/editor.md
之前文档链接打不开了，新的链接为：https://microsoft.github.io/monaco-editor/docs.html#interfaces/editor.IEditorOptions.html
=> docs: 修复editor组件的options参数说明url失效问题

examples/components/Form/SwitchDisplay.jsx, packages/amis/src/renderers/Form/InputNumber.tsx, packages/amis/src/renderers/Number.tsx
1. `InputNumber.tsx`中的后缀属性是 suffix，`Number.tsx`的后缀属性是 affix，静态展示时，需要兼容一下
2. `InputNumber.tsx` renderStatic 函数的优先级高于 `StaticHoc.tsx`中的逻辑，但是这里已经多余了，可以去掉
=> fix: 修复number render对于suffix的兼容

docs/zh-CN/components/form/formitem.md, docs/zh-CN/extend/addon.md, packages/amis-core/src/utils/validations.ts, packages/amis/__tests__/renderers/Form/inputGroup.test.tsx, packages/amis/__tests__/utils/validations.test.ts
- 多数用户反馈，表单项校验不希望一次把所有校验消息都展示出来，
- 目前是把所有校验规则走一遍，然后收集错误
1. 改成顺序校验模式，不再每次都校验所有规则，遇到错误直接break 并展示当前错误
2. 自定义校验 addRule 支持自定义错误消息
=> feat: 表单项校验变更为顺序校验模式

packages/amis-ui/src/components/index.tsx
由于editor中存在很多不规范的引入路径，如：import type {VariableItem} from 'amis-ui/lib/components/formula/Editor';
现将一些模块通过amis-ui直接暴露出来
=> feat: amis-ui添加导入模块

packages/amis-editor/src/plugin/Property.tsx
属性列表组件配置面板，点击新增属性，页面报错，预览状态正常。
原因：点击新增属性时，combo组件会新增个空对象，属性表组件渲染时拿不到content（属性值）、label（属性名）。
解决方法：editor点击新增属性时，给个默认值。
=> amis-saas-10292 fix: 属性表组件，新增属性页面渲染报错

packages/amis-ui/scss/components/_tag.scss, packages/amis-ui/src/components/Tag.tsx
- 修复图标颜色不跟随自定义color变化的问题，bug如下：
```json
{
"type": "tag",
"label": "状态标签",
"displayMode": "status",
"color": "#4096ff",
"closable": true
}
```
- 修复自定义图标过小问题
- 支持新版svg图标
=> fix: 修复Tag组件status模式下的图标问题

packages/amis-editor/src/plugin/Form/ButtonGroupSelect.tsx, packages/amis-editor/src/renderer/BadgeControl.tsx, packages/amis-editor/src/renderer/OptionControl.tsx, packages/amis/src/renderers/Form/ButtonGroupSelect.tsx
1、支持button-group-select统一配置角标
2、支持option中配置角标，可覆盖统一配置
3、支持外层配置角标后，option中仅配置角标文案
=> feat: Button-group-select支持统一配置所有选项角标

packages/amis-ui/src/components/DatePicker.tsx, packages/amis/src/renderers/Form/InputDate.tsx, packages/amis/src/renderers/Form/InputDateRange.tsx
Added include for German moments language file to calendar files.
To use the locale "de-DE" wtih amis requires the German momentjs language file to be included in the SDK.
Otherwise the calendar will show year, month etc. in  Chinese.
=> feat: Added support for German to momentjs calendars

packages/amis/src/renderers/Form/Editor.tsx
editor组件设置的string 类型的 editorDidMount不生效.
=> fix bug: editor 的 editorDidMount 支持 string格式

packages/amis/src/renderers/List.tsx
List单行点击操作时，在item.data里得不到对的行index信息，但在list按钮操作时是对的；
参考list按钮操作里的对象赋值，通过this.props.data替换item.data，this.props.data中含有对的index信息。
=> fix:LIst单行点击事件上下文补全更多信息

packages/amis/src/renderers/Form/InputImage.tsx
fix: 修复inputImage的receiver等参数如果使用变量无法及时获取变量最新值的问题。
参照原来inputFile问题的修复代码做了处理，相关issues [#4438](https://github.com/baidu/amis/issues/4438)
=> fix: 修复inputImage的receiver等参数如果使用变量无法及时获取变量最新值的问题。

docs/zh-CN/components/wizard.md, examples/components/Example.jsx, examples/components/WizardPage.jsx, packages/amis-ui/scss/components/_steps.scss, packages/amis-ui/scss/components/_wizard.scss, packages/amis-ui/src/components/Steps.tsx, packages/amis-ui/src/locale/de-DE.ts, packages/amis-ui/src/locale/en-US.ts, packages/amis-ui/src/locale/zh-CN.ts, packages/amis/__tests__/renderers/Wizard.test.tsx, packages/amis/__tests__/renderers/__snapshots__/Steps.test.tsx.snap, packages/amis/__tests__/renderers/__snapshots__/Wizard.test.tsx.snap, packages/amis/src/renderers/Wizard.tsx
1. wizard组件步骤条换成amis-ui的steps组件
2. amis-ui的steps组件支持onClickStep事件，支持wizard组件点击步骤后跳转
3. wizard支持withWrapPanel属性（是否包含panel边框，同form组件的withWrapPanel）
4. amis-ui支持不同区域的样式配置：stepsClassName（步骤条区域样式）、stepClassName（除去底部操作栏区域样式）、bodyClassName（表单区域样式）、footerClassName（底部操作栏样式）
5. wizard组件支持动态步骤
=> feat: wizard组件样式交互改造

packages/amis-ui/src/components/AssociatedSelection.tsx, packages/amis-ui/src/components/UserSelect.tsx, packages/amis-ui/src/components/UserTabSelect.tsx, packages/amis-ui/src/components/index.tsx
这个PR对功能没有任何影响
我们在使用`amis`来搭建自己的低代码平台，最近在`amis`代码基础上二次开发一个组件分包的功能。使用`vite`的库模式来将组件分开打包以便可以按需引用来减少包的体积。在开发过程中这些"不太合群"的导入方式对我造成了一些困扰，当然可以在插件中特殊处理咯，但是修改这些"不太合群"的导入方式会更简单些，并且同一个组件被引入多次或者出现循环引入也会降低可维护性
=> chore: 修改组件导入方式

packages/amis-editor/src/renderer/APIAdaptorControl.tsx
- 用户配置请求发送适配器时，api.data与api.body界限不清晰，不知道要从body中写数据还是在data中写数据
- 实测 在api的请求适配器里，将数据放在 api.body 里并不会生效
-  去掉api.body 的说明，统一都使用 api.data 作为标准
=> fix:去掉editor里api请求适配器里关于api.body的说明,统一使用api.data

packages/amis-ui/scss/components/_condition-builder.scss, packages/amis-ui/src/components/condition-builder/GroupOrItem.tsx
修复问题1：Amis组件ConditionBuilder添加《条件组》选项触发弹出框（如日期组件）后会显示底层其他条件组中select组件的删除图标
原因：
- select组件删除图标样式设为 z-index:2
- 条件组件的条件组鼠标悬浮时，原css样式设置为z-index：1
修复问题2：Amis组件ConditionBuilder开启formula后添加条件组《fx》不生效
原因：
未向ConditionGroup传递formula属性
=> fix: 条件组选项触发弹出框后会显示底层其他条件组中select组件的删除按钮

docs/zh-CN/components/drawer.md
- 优化
- 简化使用示例，能使用默认值配置，则忽略不写。
- 调整部分配置描述的先后位置，便于后面示例使用不突兀。
- 为示例使用添加小段描述。
- 修正
- 抽屉组件文档示例中使用弹窗组件。
=> docs: 重写 drawer 组件文档

docs/zh-CN/components/timeline.md, packages/amis-editor/src/plugin/Timeline.tsx, packages/amis-ui/scss/components/_timeline.scss, packages/amis-ui/src/components/Timeline.tsx, packages/amis-ui/src/components/TimelineItem.tsx, packages/amis/__tests__/renderers/Timeline.test.tsx, packages/amis/src/renderers/Timeline.tsx
1、fix： 配置面板配置Timeline组件className不生效 
（原因：render/Timeline组件中未将props中的className传入Timeline UI组件）
2、feat:
- Timeline组件支持统一/单独配置节点detailClassName / timeClassName / titleClassName
- 配置面板支持统一配置detailClassName / timeClassName / titleClassName
- Timeline组件支持关联上下文
3、perf： 
- Timeline组件detail样式优化为自适应
- 补充Timeline组件文档
=> feat: timeline组件支持detailClaaName/titleClassName/timeClassName & 可视化配置

packages/amis-editor/src/plugin/Form/Item.tsx, packages/amis-ui/src/locale/de-DE.ts, packages/amis-ui/src/locale/en-US.ts, packages/amis-ui/src/locale/zh-CN.ts, packages/amis/src/renderers/Form/ConditionBuilder.tsx
修改内容：
1、perf：
条件组件作为表单项使用时禁止配置面板配置《控件宽度》为极小
2、feat：
条件组件作为表单项进行《必选》校验时支持 拦截**无完整条件的配置**
=> feat: 条件组件作为表单项配置面板隐藏极小宽度 & 增加必选校验

docs/zh-CN/components/form/transfer.md, examples/components/EventAction/cmpt-event-action/TransferEvent.jsx, packages/amis-core/src/types.ts, packages/amis-ui/src/components/ResultList.tsx, packages/amis-ui/src/components/ResultTableList.tsx, packages/amis-ui/src/components/ResultTreeList.tsx, packages/amis-ui/src/components/Transfer.tsx, packages/amis-ui/src/components/TransferSearch.tsx, packages/amis-ui/src/components/Tree.tsx, packages/amis/__tests__/renderers/Form/__snapshots__/transfer.test.tsx.snap, packages/amis/__tests__/renderers/Form/transfer.test.tsx, packages/amis/src/renderers/Form/Transfer.tsx
feat: transfer 树形搜索的时候支持高亮
feat: transfer 提供清空搜索的事件动作 
fix: transfer 穿梭器左上角的全选勾选时，没有处理 onlyChildren:true 的逻辑
=> feat: transfer 树形搜索的时候支持高亮& feat: transfer 提供清空搜索的事件动作 & fix: transfer 穿梭器左上角的全选勾选时，没有处理 onlyChildren:true 的逻辑

packages/amis-core/src/utils/autobind.ts
- 消除 `getBoundSuper()` `undefined` 返回值的二义性。
- 显式声明 `mapStore` `value` 类型
=> refactor: 优化 autobind TS 类型

docs/zh-CN/components/tpl.md
- 删除了文档中tpl组件说明里的快速编辑部分，因为这部分的示例代码里没有使用tpl类型组件，和页面主题无关
=> docs: 去掉tpl组件快速编辑部分的说明

packages/amis-ui/scss/components/form/_form.scss
修改完成后，仍然遗留一个问题：
编辑器状态下，最后一个元素是编辑器预留的 placeholder，因此选择器会有错位，导致仍然有期望外的 margin bottom。
在正常渲染时没有这个问题，如果改成 last-type-of 的话，表单中加入其他非 form-item 的元素，会导致选择器选择的 dom 不符合预期。
=> fix: 修复指定列数 > 1 的情况下 form 最后一行 margin-bottom 不为 0 的问题

packages/amis-core/src/renderers/Form.tsx
如题，form 组件在配置了 columnCount 时，如果 item 个数刚好是其整数倍，placeholder 的个数非 0，导致多出一行空白。
=> fix: 修复 form item 个数刚好为 columnCount 的整数倍时, 多一行 placeholder dom 的问题

packages/amis-core/src/theme.tsx
- 去除不必要的 `interface`
- 根据 `type` 值，调整字段的先后顺序
- 使用 `Partial` 与 `Record` 简化部分类型实现
=> refactor: 简化 Theme 类型

packages/amis-core/src/components/PopOver.tsx, packages/amis-core/src/locale.tsx, packages/amis-core/src/theme.tsx
- `loacle` => `locale`
- `ThemeOutterProps` => `ThemeOuterProps`
- `PopOverPorps` => `PopOverProps`
=> fix: 命名拼写错误

packages/amis-core/src/actions/AjaxAction.ts, packages/amis-core/src/renderers/Options.tsx, packages/amis-core/src/store/crud.ts, packages/amis-core/src/store/form.ts, packages/amis-core/src/store/formItem.ts, packages/amis-core/src/store/service.ts, packages/amis-core/src/store/table2.ts, packages/amis-editor/src/plugin/Form/InputTree.tsx, packages/amis-editor/src/renderer/APIControl.tsx, packages/amis-editor/src/tpl/api.tsx, packages/amis/__tests__/renderers/CRUD.test.tsx, packages/amis/src/renderers/Chart.tsx, packages/amis/src/renderers/Form/ChainedSelect.tsx, packages/amis/src/renderers/Form/Combo.tsx, packages/amis/src/renderers/Form/InputTable.tsx, packages/amis/src/renderers/Form/TabsTransfer.tsx, packages/amis/src/renderers/Form/Transfer.tsx, packages/amis/src/renderers/Log.tsx, packages/amis/src/renderers/Wizard.tsx
https://ku.baidu-int.com/knowledge/HFVrC7hq1Q/tQvrZcAEPS/GxsYWwEpj5/J2M4hcB_753S2J
部分接口希望屏蔽所有报错弹窗，静默发起请求，需要api请求支持屏蔽报错能力
1. api高级设置添加静默请求选项
2. ApiControl、ServiceStore内的屏蔽报错处理
3. 事件动作=>发送请求的屏蔽报错处理
4. 各组件内部的屏蔽报错处理
| 英文 | Supports silent requests to mask error messages |
| 中文 | 支持静默请求屏蔽报错提示 |
=> feat: 支持静默请求屏蔽报错

examples/loader.ts
解决通过jssdk导出页面时自定义组件及npm自定义组件模块缺失不可用问题
=> fix: jssdk自定义组件缺失依赖

packages/amis/src/renderers/CRUD.tsx
目前editor的老版crud组件配置 `perPageAvailable` 是在 crud 层；
当crud是以下配置时，`perPageAvailable` 无法下发到分页组件中，导致失效；
（新版crud支持直接配置分页的perPageAvailable属性）
例如 [issue](https://github.com/baidu/amis/issues/1677)，直接复制wiki里的 picker 代码，然后配置此属性会失效
```
{
"type": "crud",
"perPageAvailable": [
5
],
"footerToolbar": [
"statistics",
{
"type": "pagination",
"showPageInput": true,
"layout": "perPage,pager,go"
}
]
}
```
因此需要下发属性
=> fix: crud的perPageAvailable下发到分页工具中

packages/amis-editor-core/src/component/factory.tsx, packages/amis-editor/src/renderer/event-control/helper.tsx
修复：
1.选择弹窗后弹窗类型不正确
2.选择已有的现有弹窗$$id不存在导致的报错
3.弹窗动作path不正确导致页面初始化等事件打开弹窗预览出错
=> fix(amis-editor): 修复选择弹窗类型错误,弹窗path不正确导致页面初始化失败的问题

packages/amis-editor-core/src/mocker.ts, packages/amis-editor/src/plugin/Form/InputTable.tsx
当editor中使用以下case时，会导致死循环
原因是：
- editor 实时预览时，input-table plugin 会在filterProps mock 假数据
- 初始化时， input-number假数据值是 【随机数】，input-text等一般组件的值是 【假数据】
- 当后者根据表达式渲染时，触发inputTable 的emitValue，props.onChange....然后重新渲染
- 重新渲染时 filterProps 会mock的新的数据（因为是随机数）
- 从而导致死循环
```
{
"type": "input-table",
"name": "work",
"columns": [
{
"type": "input-number",
"name": "column1"
},
{
"name": "column2",
"value": "${column1}"
}
]
}
```
解决办法：
- 在 editor plugin 中 props 传入 onChange: ()=> true, 来阻断change
- 预览态也根本不需要 onChange
另一个mocker的改动是因为关于 input-number 的 mocker逻辑写重复了
=> fix(amis-editor): 阻止inputTable的在editor中预览时的change事件,避免特殊case时死循环

packages/amis-editor-core/scss/control/_formItem-control.scss, packages/amis-editor-core/src/component/SubEditor.tsx, packages/amis-editor-core/src/util.ts, packages/amis-editor/src/plugin/Form/ListSelect.tsx, packages/amis-editor/src/renderer/ExpressionFormulaControl.tsx, packages/amis-editor/src/tpl/common.tsx
对于picker、list等组件，配置项需要打开子编辑器弹窗，但子编辑器弹窗中fx没有携带当前组件的上下文变量
在打开子编辑器时收集组件的上下文变量，在打开fx弹窗时对变量进行注入来获取宿主组件的上下文变量
=> feat: 子编辑器公式输入框变量中加入宿主组件上下文变量的声明

packages/amis-editor-core/scss/control/_event-action.scss, packages/amis-editor/src/renderer/event-control/action-config-dialog.tsx, packages/amis-editor/src/renderer/event-control/helper.tsx, packages/amis-editor/src/renderer/event-control/index.tsx
背景：事件动作中的组件特性动作很常见但是在很底下。
方案：新增常用动作，记录用户最近使用的5个动作
| 中文 | 新增常用动作 |
=> feat(amis-editor): 动作弹窗中记录常用动作

packages/amis-core/src/utils/browser.ts, packages/amis-core/src/utils/index.ts, packages/amis/src/renderers/Table/ColGroup.tsx
The problem is min-width CSS property.
Before Chrome 91, min-width was ignored on COL elements. 91 no longer ignores it.
=> fix: 修复 chrome 低版本列设置宽度无效的问题

packages/amis-core/src/store/form.ts, packages/amis-editor/src/renderer/event-control/index.tsx, packages/amis/__tests__/event-action/renderers/form/__snapshots__/form.test.tsx.snap, packages/amis/__tests__/event-action/renderers/form/form.test.tsx
表单提交前进行强制校验
之前提交前虽然会校验，但会使用缓存，即已经校验过的不再校验，不能覆盖某些特殊场景（如自定义的双向联合校验后报错无法清除），所以需要进行强制校验
=> feat: 表单提交前进行强制校验

packages/amis-editor/src/plugin/TableCell2.tsx
=> fix(amis-editor): CRUD2列配置使用快速保存时配置不生效问题

packages/amis/src/renderers/Pagination.tsx
=> fix: 分页组件activePage为非number类型时导致设计器卡死

examples/loadMonacoEditor.ts, packages/amis-ui/src/components/Editor.tsx
=> chore: jssdk 中使用代码编辑器在不同的 locale 下加载编辑器对应的语言文件 Close: #8880

packages/amis-ui/scss/components/_condition-builder.scss
table fixed header的z-index: $zindex-sticky 900
=> styles: 修复ConditionBuilder下拉浮层被Table表头遮挡问题

packages/amis-ui/src/components/NumberInput.tsx, packages/amis/__tests__/renderers/Form/number.test.tsx, packages/amis/src/renderers/Form/InputNumber.tsx
1. 有单位时，默认值没有添加上单位
2. 点击事件阻止冒泡
默认值未处理单位
阻止冒泡事件
=> fix: 默认值没有添加上单位, 点击事件阻止冒泡

packages/amis-editor-core/src/component/Editor.tsx, packages/amis-editor-core/src/manager.ts, packages/amis-editor-core/src/plugin.ts, packages/amis-editor-core/src/util.ts
1. addChild新增reGenerateId参数控制，可用于控制不重置组件id；
2. 优化reGenerateID逻辑：遍历到某个节点时还需考虑未遍历到的节点，避免事件动作（onEvent中的componentId没有正常替换）失效。
=> fix(amis-editor): addChild新增reGenerateId参数控制，并优化reGenerateID逻辑

packages/amis-ui/scss/components/_alert.scss
alert继承了RegionWrapper的min-height
=> style: 修复Alert在编辑时样式和预览时样式不一致问题

packages/amis/src/renderers/Form/InputText.tsx
input-text，如果配置了options，那么“可清除”（clearable）这个属性也会失效，即，input框里不会显示清除图标
历史版本主题升级时，input-text多选模式的清除按钮类名配置错误
更正input-text多选模式的清除按钮类名
=> fix : input-text选择器模式下，clearable无效问题

packages/amis-editor/src/plugin/Form/Static.tsx
在 Editor 中，默认值的字段是 tpl、历史上是 value
当清除默认值（tpl）时，value 无法被清除，导致渲染时仍然有值可展示
应该是以往改动的时候，没有考虑到这种情况
=> fix: Editor:当删除静态展示框的默认值时清除历史残余的value值

examples/loader.ts
解决通过jssdk导出页面时自定义组件及npm自定义组件模块缺失不可用问题
=> fix: jssdk导出npm扩展包缺失依赖

packages/amis-editor/src/plugin/Form/Switch.tsx
switch配置truevalue/falsevalue后，修改默认值还是true和false
falsevalue设置为0时，返回值为false
采用解构的方式取值，不使用 falsevalue || false的形式
=> fix : 修复switch配置truevalue/falsevalue后,默认值不更新问题

packages/amis-editor-core/src/component/RegionHLBox.tsx
修复的问题现象：通过大纲或者面包屑选中容器组件的时候，没有显示清空功能icon。
=> fix(amis-editor): 修复容器清空功能icon偶发不显示问题

packages/amis-editor-core/src/manager.ts, packages/amis-ui/src/components/ContextMenu.tsx
打开右键按钮时，这里调用了一个异步操作（试了一下，不方便改成同步）
这里偶尔会导致 contextId 为空，然后速搭创建公共组件的时候 store.context 为空，取不到正确的 schema
=> fix: 修复Editor 打开右键菜单时contextId可能会为空的问题

packages/amis-editor/src/plugin/Tabs.tsx
=> feat(editor): tabs组件去掉默认创建时的文本，直接显示内容区供用户拖拽内容

packages/amis-core/src/index.tsx, packages/amis-core/src/renderers/wrapControl.tsx, packages/amis-editor-core/src/store/editor.ts, packages/amis-editor-core/src/store/node.ts, packages/amis-editor/src/plugin/Table.tsx, publish.sh
=> perf: 提高编辑器性能 (#9413)

packages/amis-ui/src/components/condition-builder/Item.tsx
=> fix: 修复 condition-builder 操作符只有一个时不可以点选的问题

packages/amis-editor/src/plugin/Form/InputImage.tsx, packages/amis-editor/src/plugin/Image.tsx, packages/amis-ui/scss/components/_image-gallery.scss, packages/amis/src/renderers/Form/InputImage.tsx
1.图片预览标题与关闭icon，保持在同一行
2. 图片设置大小上限，上传oversize文件时提示异常，修改为不走rc的提示，走自定义提示
修改后
3. 修复编辑器中设置maxSize后，关闭图片限制后仍然会校验maxSize的问题
1. 修复 编辑器 拖动图片大小后修改宽高失效 的问题
=> fix: 图片组件优化:调整预览标题位置;优化上传组件文件提及限制提示;修复编辑器拖拽后修改宽高无效的问题

packages/amis-editor-core/src/component/factory.tsx, packages/amis-ui/src/components/DateRangePicker.tsx, packages/amis-ui/src/components/MonthRangePicker.tsx
1. 在crud中日期范围组件显示错误
{
"type": "crud",
"syncLocation": false,
"columns": [
{
"name": "id",
"label": "ID",
"type": "text",
"id": "u:f980a646c8fc"
}
],
"headerToolbar": [
{
"type": "input-datetime-range",
"label": "日期范围",
"name": "date-range",
"value": "-6days, +1days",
"id": "u:6b0f8b9bb91b"
}
]
}
2. 日期范围组件左侧点击两次，右侧再点击一次，左侧会出现3个高亮的时间
1. moment函数处理+60days类似的时间是错误的，所以改为filterDate处理
2. 如果同时存在开始和结束时间了，就剔除选中时间的高亮
=> fix: 修复日期时间范围选择组件bug

packages/amis-core/src/components/Overlay.tsx, packages/amis-core/src/components/PopOver.tsx, packages/amis-theme-editor-helper/src/style/_padding-and-margin.scss, packages/amis-ui/src/components/Tooltip.tsx
=> fix: 修复popover存在多个子popover时,错误关闭父级问题

packages/amis-ui/scss/components/_wrapper.scss
=> fix(amis-ui): 容器组件增加默认的min-width和min-height

packages/amis/src/renderers/Table/TableRow.tsx
=> fix: 修复单元格中直接放表单项 name 为带路径的变量时值修改不符合预期的问题

packages/amis-editor-core/src/component/Panel/Outline.tsx
=> fix: 修复弹框大纲中未国际化问题

packages/amis-editor-core/scss/control/_status.scss
=> style: 优化编辑器中 icon 样式

packages/amis-ui/src/components/Tabs.tsx
tabs组件，tabs属性内容使用了visibleOn属性，切换到visibloeOn属性的后一个标签页，会报错
tabs属性中的内容使用了visibleOn，会导致children内生成null元素，访问null元素的属性会报错
判断如果是null元素，直接返回false
=> fix: 修正tabs特定场景下，切换标签页报错问题；对应issue#9544

packages/amis/src/renderers/Form/InputTag.tsx
inputtag在带有提交地址的Form中，内容为空，回车，出现假死问题。对应issue#9468
inputtag组件内容为空时，回车提交，触发Form的提交。input-tag失焦，但是内部的handlerBlur回调没有执行【查询资料发现，由于某些原因，浏览器并不保证所有的blur事件都会被执行】，导致inputtag组件的下拉未收起，其浮层遮挡了所有的可是元素，用户操作没有反应，给人一种假死的感觉
在inputtag组件的handleKeyDown中，增加分支条件。判断value为空且输入回车时，调用handleBlur，关闭弹窗，再触发Form的表单提交，可以解决当前问题
=> fix: issue#9468,inputtag在输入内容为空，回车触发表单提交，假死问题

packages/amis-ui/src/components/TabsTransfer.tsx, packages/amis-ui/src/components/TabsTransferPicker.tsx, packages/amis-ui/src/components/Transfer.tsx, packages/amis-ui/src/components/TransferPicker.tsx, packages/amis/src/renderers/CRUD.tsx, packages/amis/src/renderers/Form/TabsTransfer.tsx, packages/amis/src/renderers/Form/TabsTransferPicker.tsx, packages/amis/src/renderers/Form/Transfer.tsx, packages/amis/src/renderers/Form/TransferPicker.tsx
1. 新增TransferPicker的分页支持
2. 修复Transfer组件开发分页时，搜索不支持分页的问题
3. 新增TransferPicker和TabsTransferPicker支持placeholder配置项
4. 修复TabsTransfer在多tab状态下搜索问题
5. Transfer组件及相关的Tabs和Picker，增加tree模式下的initiallyOpen支持
6. 修复CRUD组件在loading状态下按钮仍然可以触发操作
7. 修复Transfer组件autoCheckChildren的传参问题
本次提交是 #9195 的rebase，并增加了第7点内容
1. 在3.6.1版本Transfer新增了分页功能，但是TransferPicker以及TabsTransferPicker并不支持
2. Transfer组件在开启分页和搜索时，用户进行搜索操作；请求接口搜索到结果时页码组件并未刷新，仍然使用默认数据的分页而不是使用搜索结果的分页
3. TransferPicker和TabsTransferPicker目前并不支持配置placeholder，作为表单的组件应该统一支持这个配置项
4. 在TabsTransfer组件下，如果数据是静态的、多个tabs并且开启了搜索，当用户停留在某个tab下时，搜索出来的内容时全部tab的，而且内容显示错乱
5. Transfer组件在tree模式下，当前默认是展开所有选项的，而用户可能会出现数据量过多默认需要收起的情况，所以希望新增tree组件的initiallyOpen配置项来支持
6. CRUD组件在加载中状态时所有按钮本应该被遮罩住的，但是发现代码有关于遮罩会导致弹层被影响所以去掉了按钮的遮罩，导致用户可以加载中时操作按钮重复触发行为
7. …
=> fix: transfer、transferPicker分页和搜索相关的问题修复和优化

examples/components/CRUD/Table.jsx, packages/amis-core/src/store/service.ts
messages 没有解析数据，直接读取的字符串
packages/amis-core/src/store/service.ts
需要从数据中解析msg
=> feat: messages 支持数据渲染

packages/amis-editor/src/renderer/TransferTableControl.tsx
添加表格列时，没有填写 字段名，导致取不到值字段
设置表格列时，将标题和字段名设置为必填
=> fix: editor-修复穿梭器表格形式设置表格列不填写字段名时valueTpl为undefined的问题

packages/amis-theme-editor-helper/src/renderers/Border.tsx, packages/amis-theme-editor-helper/src/renderers/Font.tsx, packages/amis-theme-editor-helper/src/renderers/PaddingAndMargin.tsx, packages/amis-theme-editor-helper/src/renderers/Radius.tsx
用于解决以下问题：
1、很多内置组件相关配置项没有配置主题路径值（editorThemePath），导致placeholder为空，没有任何提示；
2、报表组件和自定义组件也存在以上问题。
=> fix(amis-theme-editor-helper): 字体、边框、内外边距等外观配置增加默认placeholder

packages/amis-editor-core/src/component/NodeWrapper.tsx, packages/amis-editor/src/plugin/Cards.tsx, packages/amis-editor/src/plugin/Each.tsx, packages/amis-editor/src/plugin/List2.tsx
crud里面文本设置假数据时报错，另外crud里面添加列表、each组件时内部对象不可修改导致报错
=> fix: 修复crud里面使用文本假数据/列表组件渲染报错

packages/amis-ui/scss/components/_crud2.scss
=> style(amis): 修复crud2/部分场景/列级元素内部tooltip提示位置异常问题

packages/amis-core/src/components/Overlay.tsx, packages/amis-ui/src/components/TooltipWrapper.tsx, packages/amis/src/renderers/Form/InputTree.tsx
=> fix: 修复 jssdk 模式下 inputTree 的按钮提示不可见 Close: #9834

packages/amis/src/renderers/Nav.tsx
=> fix: 修复数据域改变，nav没有动态修改的问题

packages/amis/package.json, packages/office-viewer/package.json, packages/office-viewer/src/excel/render/cell/drawMultiLineText.ts
=> fix: office-viewer excel 去掉字母间距导致显示不正确问题

packages/amis-core/src/utils/dom.tsx, packages/amis-ui/src/components/ContextMenu.tsx
如果是作为菜单浮层，不再基于四个方向对齐，而是模拟原生右键菜单定位：
1. 计算放右边，还是左边
2. 计算能否放在下面，如果不能则贴底
3. 由于是基于一个点此时不考虑 arrow
=> feat: ContextMenu-更高效\好用地计算右键菜单的位置

packages/amis-editor-core/src/component/Editor.tsx
由于 `closeContextMenus` 是异步操作，偶尔会有出现后立刻消失的问题
=> fix: 修复editor中的右键菜单偶尔出现后立刻消失的问题

packages/amis/src/renderers/App.tsx
=> fix: 修复 app 模式页面定义 definitions 无效的问题 Close: #4679

packages/amis-core/src/utils/style-helper.ts, packages/amis/src/renderers/Nav.tsx
固定样式（基本样式、内容区样式等）和自定义样式渲染时机混乱，导致编辑态和预览态效果不一致
=> fix(editor): 修复编辑器自定义样式和固定样式渲染混乱问题

packages/amis-ui/scss/components/_tabs.scss, packages/amis-ui/scss/components/form/_combo.scss, packages/amis-ui/src/components/Tabs.tsx, packages/amis/__tests__/renderers/Form/__snapshots__/combo.test.tsx.snap, packages/amis/__tests__/renderers/Form/__snapshots__/tabs.test.tsx.snap, packages/amis/__tests__/renderers/Form/__snapshots__/tabsTransfer.test.tsx.snap, packages/amis/__tests__/renderers/Form/__snapshots__/tabsTransferPicker.test.tsx.snap, packages/amis/__tests__/renderers/__snapshots__/Portlet.test.tsx.snap, packages/amis/__tests__/renderers/__snapshots__/Tabs.test.tsx.snap
移动了一下按钮的位置，和文字同级
p.s. 
- 按钮的data-tooltip没有用，因为外层有overflow: hidden, 之前也一直没显示
=> fix: combo中超长字符串导致group的tab删除按钮消失

packages/amis-core/src/store/table.ts
=> fix: 修复crud 拖拽上下文信息中 insertBefore 和 insertAfter 为空的问题 Close: #1533

packages/amis-ui/src/components/PopOverContainer.tsx
popoverContainer 写死了，sdk模式下，没有渲染到 container 里，导致虽然dom渲染了，但是样式覆盖不到就看不见了
=> fix: SDK模式下，select使用自定义过滤，采用移动模式，下拉点不开 Close: #9725

packages/amis-editor/src/plugin/Form/Transfer.tsx, packages/amis-editor/src/plugin/Form/TransferPicker.tsx, packages/amis-editor/src/plugin/index.ts
新增TransferPicker组件的编辑器插件
TransferPicker组件功能强大，但目前缺少对编辑器的支持，新增编辑器插件后更方便用户Transfer的基础配置、事件等操作
TransferPicker组件继承于Transfer组件，在其基础上扩展了borderMode和pickerSize两个属性，所以编辑器插件基本复用了Transfer插件。
新增部分：
发现了个问题：组件中pickerSize提供了xs选项，但modal样式并不支持xs尺寸，所以在编辑器中并未提供xs的选择
该问题未在组件中解决
=> feat: 新增TransferPicker的编辑器插件

packages/amis/package.json, packages/office-viewer/package.json, packages/office-viewer/src/excel/sheet/getViewPointData.ts
=> fix: 修复 excel 渲染时合并单元格垂直方向不正确问题 Closes #9936

packages/amis-core/src/SchemaRenderer.tsx, packages/amis-core/src/utils/helper.ts, packages/amis-editor/src/plugin/Form/InputNumber.tsx, packages/amis/src/renderers/Breadcrumb.tsx
=> fix(amis-editor): input-number步长配置功能优化，实时同步当前小数位数配置

packages/amis-core/src/renderers/wrapControl.tsx
问题 schema
```json
{
"title": "表单页面",
"body": [
{
"mode": "horizontal",
"initApi": {
"method": "get",
"url": "/api/sample/show?id=${id}",
"mockResponse": {
"status": 200,
"data": {
"id": 1,
"varc": "123",
"vard": "124xxx",
"combo": [
{
"vara": "123",
"varb": "123xxx"
}
],
"vare": "xxx"
}
}
},
"body": [
{
"label": "Combo",
"type": "combo",
"name": "combo",
"multiple": true,
"items": [
{
"name": "vara"
},
{
"name": "varb",
"value": "${vara}yyy"
}
]
},
{
"name": "varc",
"value": "234"
},
{
"name": "vard",
"value": "${varc}yyy"
},
{
"name": "vare",
"value": "yyyy"
}
]
}
]
}
```
公式默认值在 form 与在 combo 内部表现不统一，预期初始值高于表达式，除非表达式关联变量发生变化，才更新公式结果
=> fix: 修复表单项公式默认值优先级高于实际返回值的问题

docs/zh-CN/components/dialog.md, packages/amis-editor-core/src/store/editor.ts, packages/amis-editor-core/src/util.ts, packages/amis-editor/src/plugin/Button.tsx, packages/amis-editor/src/plugin/Form/InputImage.tsx, packages/amis-editor/src/plugin/Form/Picker.tsx, packages/amis-editor/src/renderer/style-control/helper.tsx, packages/amis-editor/src/tpl/style.tsx
editorState是在编辑外观的过程中出现的只有编辑器才需要一个标识变量，不应该存储到schema中
=> fix: schema中删除editorState

packages/amis-editor-core/src/component/SubEditor.tsx
子编辑器【撤回】按钮的 tooltip 会遮挡【重做】按钮
视觉优化
Before：
After：
=> fix: 修复子编辑器弹窗撤回按钮遮挡

packages/amis-editor-core/scss/editor.scss
close #9406
使用 amis-editor 时，会重复引用 amis-ui/scss/_components.scss 
第一份来自于 amis-ui/scss/themes/cxd.scss 引入的 components.scss
第二份来自于 amis-editor-core/scss/editor.scss 引入的 components.scss
因为 amis-editor 依赖 amis-ui。amis-ui 会引用相应的主题样式。
如：`amis-ui/scss/themes/cxd.scss`
因此第二份引入的样式是冗余的。
收益：
1. 移除后页面样式无影响
2. 能够降低 amis-editor-core/lib/style.css 体积 200+kb
**复现案例来自于 amis 仓库中的 examples。**
复现路径： `npm start`，访问 localhost:8080/packages/amis-editor；查看 network
开发环境：
优化前：
优化后：
生产环境：
amis-editor-core/lib/style.css 从 437kb 降低至 182 kb
删除 amis-editor-core 中的样式变量引用。
=> fix: 解决使用编辑器时 amis-ui 样式变量重复引入

package.json
支持根据分支的最新版本号来自动升级版本号
如：
290-6.4.0分支：
280-6.3.0分支：
=> chore: 升级amis-publish版本,支持根据分支的最新版本号来自动升级版本号

packages/amis-ui/scss/components/_collapse.scss, packages/amis-ui/scss/components/form/_input-group.scss
=> style: 修复设计态弹窗中放 fieldset 渲染器宽度过宽的问题

packages/amis-editor/src/plugin/TableView.tsx
fix: https://github.com/baidu/amis/issues/10080
=> fix: amis-editor table-view 新增行和列

packages/amis/src/renderers/Form/Select.tsx
=> fix: select 不在 form 下面报 addHook 不是函数的错误

packages/amis/src/renderers/Form/InputExcel.tsx, packages/amis/src/renderers/Table/index.tsx
=> chore: 兼容 exceljs 在部分打包配置下引入错误问题 Closes #9598

packages/amis/src/renderers/Dialog.tsx, packages/amis/src/renderers/Drawer.tsx
=> fix: 修复弹窗嵌套弹窗观察动作执行逻辑错误 Close: #10200

docs/zh-CN/components/table-view.md, packages/amis/__tests__/renderers/TableView.test.tsx, packages/amis/__tests__/renderers/__snapshots__/TableView.test.tsx.snap, packages/amis/src/renderers/TableView.tsx
=> feat: Table View 的行和列支持配置 visibleOn Closes #9621

packages/amis-ui/src/components/AnchorNav.tsx
原始逻辑是在组件mount和dom tree改变后去计算每个section的高度并记录到数组中，但是会出现section中有图片一类在计算后才改变高度的情况，导致锚点定位不准。
现优化为收集每一个section的真实dom，在每次点击菜单或滚动时去实时计算高度
=> fix: 修复anchorNav组件定位不准问题

packages/amis-editor/src/renderer/event-control/helper.tsx
=> fix(editor): 解决getRootManager死循环问题

packages/amis-core/src/utils/api.ts
=> fix: api query开启过滤空值时, 若参数值是表达式且其执行结果为date类型导致该参数被删除

packages/amis-core/src/utils/api.ts
=> fix: 查询条件过滤空条件时, api query参数值的表达式执行结果为date类型时导致参数不生效

docs/zh-CN/components/form/input-datetime.md, packages/amis-core/src/utils/date.ts, packages/amis-ui/src/components/DatePicker.tsx, packages/amis-ui/src/components/DateRangePicker.tsx
解决issue https://github.com/baidu/amis/issues/10122
当时间日期组件配置utc后，会将时间变成utc时间，不符合预期
仅value为utc时间，展示时间仍为本地时间
以北京时间为例
=> fix: 修复时间选择组件配置utc后交互异常问题 Close:#10122

.github/workflows/codeql-analysis.yml
v1 已经不用了，改成 v2 https://github.blog/changelog/2023-01-18-code-scanning-codeql-action-v1-is-now-deprecated/
=> chore: Update codeql-analysis to v2

packages/amis/src/renderers/Tabs.tsx
=> fix: 修复 tabs 的 title 渲染上下文信息错误问题 Close: #10259

packages/amis-core/src/WithStore.tsx, packages/amis-core/src/store/iRenderer.ts, packages/amis/__tests__/renderers/CRUD.test.tsx, packages/amis/__tests__/stores/__snapshots__/service.test.ts.snap, packages/amis/src/renderers/Cards.tsx, packages/amis/src/renderers/List.tsx, packages/amis/src/renderers/Table/index.tsx
CRUD 列中存在一列 List 组件，List 是带 store 的，crud 的行数据发生切换时，如果 list 关联的数组，从有有成员变成 undefined 时，会出现 List 的数据不更新的问题。原因是 withStore 里面同步逻辑有问题，保留了原来的 store.data
=> fix: 修复 store 数据上下层同步问题

packages/amis/src/renderers/Form/InputNumber.tsx, packages/amis/src/renderers/Table/TableRow.tsx
=> fix: 修复 table 中有表单项带路径时会把对应对象其他属性弄丢的问题

packages/amis-ui/src/components/NumberInput.tsx, packages/amis/src/renderers/Form/InputNumber.tsx
- input-number用修改formatter的方式替换移动光标的方式 解决光标漂浮问题
- 还原输入过程中进行normalizeValue数值处理的逻辑
光标漂浮相关issue
https://github.com/baidu/amis/issues/8405
https://github.com/baidu/amis/issues/7558
https://github.com/baidu/amis/issues/8795
输入过程需要实时 normalizeValue数值处理，否则change事件等逻辑会不符合预期
=> fix: input-number用修改formatter的方式替换移动光标的方式 解决光标漂浮问题

packages/amis-ui/src/components/condition-builder/Value.tsx
=> chore: condition-builder 非预设类型渲染时也转成走自定义类型渲染逻辑

packages/amis-core/src/utils/renderer-event.ts
之前的实现会导致 SchemaRenderer 执行解绑时无法解绑当前组件的任何 eventListener
逻辑改为：如果 eventName 为 undefined时解绑当前组件的所有事件，否则只解绑指定事件
=> bugfix: 修复 unbindEvent 无法完全解绑 eventListener 的问题

packages/amis-core/src/Scoped.tsx
从 scope 中注销组件时，自动从父级 scope 中移除当前 scope，不然的话在反复打开弹窗等场景下会导致父级 scope 的 children 一直增长
=> bugfix:从 scope 中注销组件时，自动从父级 scope 中移除当前 scope

packages/amis/src/renderers/Code.tsx
issue#10515 修复code组件值为空控制台报错
code组件值为undefined时，会导致monaco-editor内部出现报错
如果值为undefined时将值设置为空字符串
=> fix: issue#10515 修复code组件值为空控制台报错

packages/amis-core/src/renderers/Options.tsx, packages/amis-ui/scss/components/_condition-builder.scss
=> fix: 修复 select 值格式是对象时初始化值不正确的问题

packages/amis-ui/scss/components/form/_tree.scss
=> fix: input-tree图标为url时，未限制img图片宽高

packages/amis-core/src/components/CustomStyle.tsx
在crud的card模式下（可能还有其他场景），会有 id 为数字的 Tpl 组件的情况，导致 removeCustomStyle 函数报错。 这个跟 #10396 解决的问题是同一个，只是我觉的既然所有的工具函数都是预设了 id 为 string，何不从源头上解决？免得以后更新工具方法的时候还要再写很多防御性代码。
=> 修复 CustomStyle 在某些情况下 id 的类型可能是 number 而导致异常报错

packages/amis-core/src/utils/validateId.ts
=> fix: 修复身份证号码验证时缺少直辖县级市的校验

packages/amis/src/renderers/Table/ColumnToggler.tsx, packages/amis/src/renderers/Table/index.tsx
目前自定义列全选在配置dragged时不支持全选，在列数较多时有全选的需求
效果如下：
=> feat: crud自定义列在drag模式下支持全选

packages/amis-core/src/actions/CustomAction.ts
在自定义js脚本中，经常需要对其他组件进行一些操作，比如提交按钮点击的时候，让某个组件获取焦点之类的。
使用时从简单方便的角度出发，希望可以通过
```javascript
this.name.focus()
```
就可以让**name**这个组件获取焦点。
=> 自定义脚本中，通过组件的名称来获取组件引用，方便使用

packages/amis/src/renderers/Number.tsx
修复 #10566 
带精度的 `Number` 组件，value 应该是 string 格式，否则像 `1.20` 之类的数字，展示时末尾的零会丢失
直接移除了 `getMiniDecimal` 的调用
=> fix: number with precision should be string format

packages/amis-ui/scss/components/_cards.scss, packages/amis-ui/scss/components/_list.scss, packages/amis-ui/scss/components/_table.scss, packages/amis/src/renderers/CRUD.tsx, packages/amis/src/renderers/Table/index.tsx
=> fix: 修复 crud 分页点击页面位置跳转问题 Close: #9667

packages/amis-core/src/actions/Action.ts, packages/amis-core/src/renderers/Item.tsx, packages/amis-core/src/utils/renderer-event.ts
通过下发方法，让 formItem 节流渲染的的控件也有办法拿到最新的数据，同时调整时间派发的数据获取方式
=> fix: 调整 formItem 下面的事件触发参数让其拿到最新的 Close: #10376

examples/style.scss
####Error
```css
.markdown-body {
color: #fff;
}
```
####fix
```css
.markdown-body {
color: rgb(100 116 139 / 1);
background-color: var(--colors-neutral-fill-11) !important;
}
```
=> fix-darkModeCss

packages/amis-core/src/utils/api.ts
First, `!nextApi` is always `boolean`, so I expect it should be `nextApi !== undefined` at first place.
Secondly, `nextApi` has already been guaranteed to be truthy at https://github.com/baidu/amis/blob/d43922db81798c3fd16072aa873bf8390653319f/packages/amis-core/src/utils/api.ts#L740-L742, so the check here is just redundant.
N/A
N/A
=> refactor: nextApi check can be simplified

docs/zh-CN/components/form/input-color.md, packages/amis-editor/src/plugin/Form/InputColor.tsx, packages/amis-ui/src/components/ColorPicker.tsx, packages/amis/src/renderers/Form/InputColor.tsx
`format` 支持 8位 HEX，参考 `https://drafts.csswg.org/css-color/`。
目前的移动端，及css 都支持8位 Hex，用于标识透明度，方便多端统一。
```schema: scope="body"
{
"api": "/api/mock2/form/saveForm",
"body": [
{
"type": "input-color",
"name": "color",
"label": "带透明度调节的色盘, 8 digits HEX",
"value": "#73E3EC88",
"format": "hexa"
}
]
}
```
=> feat: 颜色选择器 Hex 支持 8-digits 透明度，增加 hexa format

packages/amis-core/src/renderers/Form.tsx
Combo渲染form时配置了formLazyChange，在此处不生效。
Combo渲染form时配置了formLazyChange，在此处不生效。
增加使用formLazyChange的逻辑，保持和Form中其他调用lazyEmitChange的地方行为一致。
=> fix: Form组件的formLazyChange针对监听生效

packages/amis-core/src/store/table.ts
原来的本地存储的 key 跟列有关，以至于列做调整（新增列，或者删除列），这个 key 就会失效，所以记录的列显隐状态就会失效。
修改后将与列无关，后续调整表格的列，原本的列状态信息记录将依然有效
=> chore: 调整 table 的本地存储策略以支持表格列发生变化本次存储依然有效

packages/amis/src/renderers/Form/InputTable.tsx
=> chore: fix inputTable 的行按钮新增与删除不受 minLength maxLength 控制 Close: #10793

packages/amis/src/renderers/Table/ColGroup.tsx
可以拖动的前提是列设置了 realWidth， 而那个 case，的单选列是有数据后出来的，这个 case 新出来的列没有设置宽度，所以不能拖动。所以列发生变化的时候，之前的监控逻辑需要重新加载
=> fix: 修复 picker 组件数据由接口返回时列不可拖动调整宽度问题 Close: #10791

packages/amis-ui/src/components/NumberInput.tsx
=> fix: 修复百分号情况下，最大值最小值失效

packages/amis/src/renderers/Form/NestedSelect.tsx
当数据源为api返回是以下内容时
```
{
"status": 0,
"msg": "",
"data": {
"links":
[{ "label": "Nav 1", "to": "?cat=1", "value": "1", "icon": "fa fa-user" }, { "label": "Nav 2", "unfolded": true, "children": [{ "label": "Nav 2-1", "children": [{ "label": "Nav 2-1-1", "to": "?cat=2-1", "value": "2-1" }] }, { "label": "Nav 2-2", "to": "?cat=2-2", "value": "2-2" }] }, { "label": "Nav 3", "to": "?cat=3", "value": "3", "defer": true }],
"value": "?cat=1"
}
}
```
会引发页面崩溃
需要对labelji进行兼容处理
=> fix: 修复级联选择器数据源异常label为数组时页面崩溃的问题

packages/amis-editor-core/scss/editor.scss, packages/amis-editor-core/src/component/Editor.tsx, packages/amis-editor-core/src/component/HighlightBox.tsx, packages/amis-editor-core/src/component/Panel/LeftPanels.tsx, packages/amis-editor-core/src/component/Panel/RightPanels.tsx, packages/amis-editor-core/src/component/Preview.tsx, packages/amis-editor-core/src/component/SubEditor.tsx, packages/amis-editor-core/src/component/base/SchemaForm.tsx, packages/amis-editor-core/src/plugin.ts, packages/amis-editor-core/src/store/editor.ts, packages/amis-editor-core/src/store/node.ts, packages/amis-editor-core/src/util.ts
支持于diff编辑器联动
1. 隐藏左侧边栏
2. 不可编辑
3. 暴露元素active事件
4. 暴露所有插件的key和name
=> feat: 扩展编辑器功能

packages/amis-core/src/renderers/Options.tsx, packages/amis-ui/src/components/Select.tsx, packages/amis/src/renderers/Form/Select.tsx
=> fix: 修复 autoComplete 和 addApi 搭配时新增选项不刷新的问题

packages/amis-ui/src/components/Tree.tsx
=> fix: inputTree defer模式下悬浮不展示操作按钮 #10873

packages/amis/src/renderers/Table/index.tsx
#10877 
draggable不应该是render('table'）的第三个参数，会透传覆盖别的render渲染元素
=> fix: inputTable开启拖拽后会导致表头文字可拖拽

packages/amis/src/renderers/Words.tsx
=> fix: 设置inTag时，label 为对象时渲染异常

packages/amis-ui/scss/components/_column-toggler.scss
=> 解决bug:https://github.com/baidu/amis/issues/9146

packages/amis-core/src/store/formItem.ts
```
{
"body": {
"type": "combo",
"name": "combo2",
"label": "Combo 多选展示",
"multiple": true,
"items": [
{
"name": "text",
"label": "文本",
"type": "input-text"
},
{
"name": "select",
"label": "选项",
"type": "select",
"unique": true,
"labelField": "name",
"valueField": "id",
"options": [
{
"name": "选项1",
"id": 1
},
{
"name": "选项2",
"id": 2
},
{
"name": "选项3",
"id": 3
},
]
}
]
}
}
```
以上schema选择一项后，其他select的options会被全部禁用
syncOptions中，使用 valueField 时，item.value 取不到值，导致了异常
```
item.value -> item[valueField]
```
=> fix: 修复combo内select的options使用valueField时options会被全部禁用的问题

packages/amis-core/src/SchemaRenderer.tsx
修复 #10939 广播事件无效。
6.8 版本，在 `SchemaRenderer` 中，改动了调用 `bindEvent` 时机。
在 每次调用渲染器组件的 `props.dispatchEvent` 实际调用的是 `SchemaRenderer.dispatchEvent` 方法。第二个参数默认传的 `this.cRef`。因此在，"bindEvent" 的时候，也要默认传入 `cRef`
改了下 `bindEvent` 传入的参数为 `cRef`，从而支持 广播事件。
=> fix: #10939 修复 broadcast 事件无效

packages/amis-ui/src/components/Drawer.tsx, packages/amis-ui/src/components/Modal.tsx
移动端场景： 弹窗或者抽屉配置了closeOnOutside：true，其中的表单有popup弹出层的选项选择后整个表单即可关闭了，正常应该不关闭。
移动端popup弹窗直接弹在body下，脱离了dialog
判断如果是移动端不执行dialog 中查找元素逻辑
=> fix: 移动端弹窗、抽屉配置了closeOnOutside， 移动端下拉类型的表单选择后整个弹窗关闭

packages/amis/src/renderers/Form/InputTable.tsx
修复 #10951 , `InputTable` 在配置 `perPage` 开启分页时，新增按钮展示异常问题。
1. 配置 `perPage`, `maxLength` 时 ，且数量超出限制时，新增按钮未正常隐藏。
2. 配置 `perPage`, `addable`  时，在 static 静态模式下，新增按钮仍然展示。 
问题1:  `maxLength` 只取了当页的 `items` 数量对比， 应该使用全量数据对比。
问题2: 底部新增按钮限制条件，在有分页器时，就只有 `addable && showFooterAddBtn !== false`, 与不存在 分页器的时候，表现不一样。按理说，无论分页不分页，底部新增按钮，展示逻辑应该一样。
调整下底部按钮展示逻辑，保持与是否分页无关。
=> fix: #10951 修复 InputTable 在 配置 perPage 开启分页场景时，底部新增按钮展示异常

examples/style.scss
由于下边距是0，当鼠标移动到左侧导航菜单上时，浏览器会默认在左下角预览显示当前菜单的链接，从而遮挡住了最下面的那一个菜单项
使用和右侧.Doc-footer同样的下边距，解决该问题，并保持两边间距一样
=> docs: 将文档左侧导航栏下边距设置成和右侧文档主体下边距一致，以避免底部菜单被浏览器链接遮挡

packages/amis/src/renderers/Form/InputNumber.tsx
=> fix: 修复数字输入框存在后缀时，清空数据，光标位置定位不准确

.husky/pre-commit, package.json
项目中并无lintstaged配置文件，所以huksy中的npx lint-staged命令并未实际执行任何操作，而npm run stylelint会在每次commit时对packages下的所有scss进行检验，效率较低
=> build: 通过lintstaged对scss文件进行增量校验，避免npm run stylelint全量校验的时间浪费

packages/amis-ui/src/components/Editor.tsx
在文档中编辑代码后，组件会崩溃
fix: 修复 DiffEditor 可能显示最新值的问题
1513c5402a343146e562378880795917d0e1e55c 引起的异常
=> fix: 直接调用dispose函数清空编辑器插件，避免类型异常引起组件崩溃

packages/amis-ui/scss/components/_crud2.scss, packages/amis-ui/scss/components/_panel.scss, packages/amis/src/renderers/CRUD2.tsx
=> feat: 修正crud2移动端简单查询折叠器箭头方向,没数据时不显示[没有更多了]文案

packages/amis-core/package.json
amis-core中引用了react-overlays, 但是package.json中不存在。 详细信息可见原issue
=> chore: 补充react-overlays至dep(#11117)

packages/amis-editor/src/renderer/NavSourceControl.tsx
getSchemaTpl错误引用诱发amis editor side effect， 导致引入amis editor全部内容， 详见issue
引入NavSourceControl renderer后amis editor引入全量的plugin, 影响使用
修改getSchemaTpl方法引入方法
=> fix: 修复getSchemaTpl方法错误的引入方式(#11133)

packages/amis-editor/src/renderer/DataBindingControl.tsx
数据绑定成功后， 重新打开数据绑定组件后， 回传的值不正确， 详见issue
需要定开一个数据绑定组件， 阻塞在此bug
参考内部实现， 调整代码
=> fix: 修复数据绑定组件选中值回传不正确的问题(#11126)

packages/amis-editor-core/scss/editor.scss, packages/amis-editor/src/tpl/style.tsx, packages/amis-ui/src/components/MobileDevTool.tsx
=> fix: 修复编辑态播放动画后,高亮框错位问题

packages/amis/src/renderers/Form/InputFile.tsx, packages/amis/src/renderers/Form/InputImage.tsx
文件上传成功后通过 success 事件把当前文件框的值改了，然后这个控件会一直处于上传中的状态。
上层表单提交的时候会一直等待这个控件上传完成。
=> fix: 修复文件上传中事件修改表单项本身的值后, 表单校验卡住的问题

packages/amis/src/renderers/CRUD.tsx
=> fix:修复crud批量操作上下文event导致的ajax请求报错问题

packages/amis/src/renderers/Form/InputText.tsx
resetValue和clearValue应该只做reset和clear的事情，不应该管理焦点。
=> 解决在B事件里操作A文本框的resetValue或者clearValue导致失焦的问题，可能引发多次失去焦点事件

packages/amis-formula/src/evalutor.ts
在表达式里计算文本长度的时候，如果文本框不输入值，fnLEN会计算undefined的长度，返回是9，与预期不符。
=> 解决在组件不输入内容的情况下，LEN函数返回9的错误（undefined字符串的长度）

packages/amis-editor/src/plugin/Button.tsx, packages/amis-editor/src/plugin/Steps.tsx, packages/amis-ui/scss/components/_steps.scss, packages/amis-ui/src/components/Steps.tsx, packages/amis/src/renderers/Steps.tsx
=> feat: 步骤条新增iconPositon属性，修复简单模式下箭头布局错乱

packages/amis/src/renderers/Table/TableRow.tsx, packages/amis/src/renderers/Table/index.tsx
表格行的编辑按钮，弹出对话框时，无法获取返回值
handleAction没有把promise给返回回去，导致别人waitForAction的时候获取了个undefine报错
=> fit： 解决表格行编辑的时候的弹窗，无法获取返回值的问题

packages/amis-editor/src/plugin/Form/Combo.tsx
在combo组件的配置项中增加一个unique开关，能下拉选择所需要的combo中的列字段进行增加unique：true属性
经常需要combo进行一个唯一性的判断输入
遍历items属性，并将选中的item增加一个unique：true字段
=> feat: 增加combo组件unique配置项

packages/amis-core/src/RootRenderer.tsx
=> fix: 修复只更新 context rootStore 无法监听变化的问题

packages/amis-editor/src/plugin/Form/Combo.tsx, packages/amis-editor/src/plugin/Form/InputTable.tsx, packages/amis-editor/src/plugin/Form/InputTree.tsx, packages/amis-editor/src/plugin/Image.tsx, packages/amis-editor/src/plugin/Nav.tsx, packages/amis-editor/src/plugin/OfficeViewer.tsx, packages/amis-editor/src/plugin/QRCode.tsx, packages/amis-editor/src/plugin/Service.tsx, packages/amis-editor/src/plugin/Table.tsx
=> fix:补充特性动作的描述

packages/amis-ui/src/components/PickerColumn.tsx
=> fix: 移动端picker label为对象时页面白屏

packages/amis-ui/src/components/Tinymce.tsx
=> fix: 修复 tinymce 被移动后不可用问题

packages/amis/src/renderers/Form/ChainedSelect.tsx
=> fix: 链式下拉组件不支持 valueField

packages/amis-editor-core/src/component/Editor.tsx, packages/amis-editor-core/src/component/base/SchemaForm.tsx, packages/amis-editor-core/src/store/editor.ts, packages/amis-editor/src/renderer/event-control/actionsPanelPlugins/otherActionsPanel/broadcast.tsx, packages/amis-editor/src/renderer/event-control/helper.tsx, packages/amis-editor/src/renderer/event-control/index.tsx
=> fix: 全局广播事件及时更新

packages/amis-ui/src/components/UserSelect.tsx, packages/amis-ui/src/components/UserTabSelect.tsx, packages/amis/src/renderers/Form/UserSelect.tsx
=> fix: 人员组件移动端支持禁用

docs/zh-CN/components/form/picker.md, packages/amis-editor/src/plugin/Form/Picker.tsx, packages/amis-editor/src/plugin/Steps.tsx, packages/amis-editor/src/tpl/api.tsx, packages/amis-ui/scss/components/form/_picker.scss, packages/amis/__tests__/renderers/__snapshots__/Picker.test.tsx.snap, packages/amis/src/renderers/Form/ChainedSelect.tsx, packages/amis/src/renderers/Form/Picker.tsx, packages/amis/src/renderers/Form/StaticHoc.tsx, packages/amis/src/renderers/PopOver.tsx
=> feat:调整静态样式,更新步骤条配置面板。列表选取新增选项可删除图标控制，配置面板调整

packages/amis-core/src/renderers/Form.tsx, packages/amis-editor/src/plugin/Form/Checkbox.tsx, packages/amis-editor/src/plugin/Form/Checkboxes.tsx, packages/amis-editor/src/plugin/Form/Radios.tsx, packages/amis-editor/src/renderer/style-control/ColSize.tsx, packages/amis/__tests__/renderers/Form/__snapshots__/combo.test.tsx.snap, packages/amis/__tests__/renderers/Form/__snapshots__/inputArray.test.tsx.snap, packages/amis/__tests__/renderers/Form/__snapshots__/inputTable.test.tsx.snap
=> feat: combo row模式组件支持选择宽度

docs/zh-CN/components/form/picker.md, packages/amis-editor/src/plugin/Form/Picker.tsx, packages/amis-ui/scss/components/_crud.scss, packages/amis-ui/scss/components/form/_picker.scss, packages/amis/__tests__/renderers/__snapshots__/Picker.test.tsx.snap, packages/amis/src/renderers/Form/Picker.tsx
=> fix: 修复变量命名冲突导致功能失效，修复弹出层内容堆叠在一起。新增标签内文本溢出后,hover展示全部信息

packages/amis-editor/src/plugin/Form/NestedSelect.tsx, packages/amis/src/renderers/Form/NestedSelect.tsx
=> feat: 级联选择器增加选中项标题事件动作变量

packages/amis/src/renderers/Form/StaticHoc.tsx
=> fix: 表单项静态展示不应该自动获取展示父级value

packages/amis-editor/src/plugin/Form/InputText.tsx, packages/amis/src/renderers/Form/InputText.tsx
=> feat: 输入框增加查看密码和隐藏密码事件和动作，调整自定义样式配置

packages/amis-editor/src/component/BaseControl.ts, packages/amis-editor/src/plugin/Carousel.tsx, packages/amis-editor/src/plugin/CollapseGroup.tsx, packages/amis-editor/src/plugin/Form/InputRating.tsx, packages/amis-editor/src/plugin/Form/InputTable.tsx, packages/amis-editor/src/plugin/Form/InputTree.tsx, packages/amis-editor/src/plugin/Form/ListSelect.tsx, packages/amis-editor/src/plugin/Form/Picker.tsx, packages/amis-editor/src/plugin/Form/Static.tsx, packages/amis-editor/src/plugin/Form/Switch.tsx, packages/amis-editor/src/plugin/Form/TreeSelect.tsx, packages/amis-editor/src/plugin/Image.tsx, packages/amis-editor/src/plugin/List.tsx, packages/amis-editor/src/plugin/Mapping.tsx, packages/amis-editor/src/plugin/Table.tsx, packages/amis-editor/src/plugin/Table2.tsx, packages/amis-editor/src/plugin/TableCell2.tsx, packages/amis-editor/src/plugin/Timeline.tsx, packages/amis-editor/src/renderer/SwitchMoreControl.tsx, packages/amis-editor/src/tpl/options.tsx
table 列配置的快速编辑部分打开后会把schema中的配置重置
switch more的属性没有正确使用，switchmore中 的表单数据读取不正确
重新梳理了switchmore控件的属性，并检查了各使用部分的属性配置和功能正确性
=> [fix] editor 配置面板中的开关打开更多配置的组件配置整理

packages/amis-ui/src/components/Tabs.tsx
=> fix: 修复tab组件透传className未赋值

packages/amis-core/src/SchemaRenderer.tsx, packages/amis-core/src/components/Animations.tsx, packages/amis-core/src/utils/animations.ts, packages/amis-core/src/utils/helper.ts, packages/amis-editor-core/scss/control/_event-action.scss, packages/amis-editor/src/tpl/style.tsx, packages/amis-ui/scss/base/_typography.scss
=> feat: 进入视图才执行动画

docs/zh-CN/components/form/location-picker.md, packages/amis-ui/src/components/BaiduMapPicker.tsx, packages/amis/src/renderers/Form/LocationPicker.tsx
=> feat: 地理位置静态展示支持内嵌地图方式展示

docs/zh-CN/components/form/location-picker.md, packages/amis-ui/src/components/BaiduMapPicker.tsx, packages/amis/src/renderers/Form/LocationPicker.tsx, packages/amis/src/renderers/Image.tsx
=> feat: 地图静态展示支持设置大小

README-en.md
=> docs: add english readme

packages/amis-ui/scss/components/form/_picker.scss
=> fix: 修复picker禁用状态下点击折叠标签仍可打开弹窗

packages/amis/src/renderers/Form/InputTable.tsx
=> fix: 修复 inputTable 非最后一页点击上传并且列中有图片上传时出现新行有初始值的问题

packages/amis-theme-editor-helper/src/helper/declares.ts, packages/amis-theme-editor-helper/src/helper/getGlobalData.ts, packages/amis-theme-editor-helper/src/renderers/Font.tsx, packages/amis-theme-editor-helper/src/renderers/ThemeSelect.tsx
=> feat: 编辑器选择字体时支持预览,字体配置支持 previewUrl

packages/amis/src/renderers/Table2/index.tsx
=> feat: crud2列标题支持表达式

docs/zh-CN/components/crud.md, docs/zh-CN/components/table.md, packages/amis-core/src/RootRenderer.tsx, packages/amis-core/src/store/crud.ts, packages/amis-core/src/store/list.ts, packages/amis-core/src/store/table.ts, packages/amis-editor/src/plugin/CRUD.tsx, packages/amis-ui/scss/_mixins.scss, packages/amis-ui/scss/_properties.scss, packages/amis-ui/scss/components/_crud.scss, packages/amis-ui/scss/components/form/_picker.scss, packages/amis-ui/src/locale/de-DE.ts, packages/amis-ui/src/locale/en-US.ts, packages/amis-ui/src/locale/zh-CN.ts, packages/amis/__tests__/renderers/Picker.test.tsx, packages/amis/__tests__/renderers/__snapshots__/Picker.test.tsx.snap, packages/amis/src/renderers/CRUD.tsx, packages/amis/src/renderers/Cards.tsx, packages/amis/src/renderers/Form/InputTable.tsx, packages/amis/src/renderers/Form/Picker.tsx, packages/amis/src/renderers/List.tsx, packages/amis/src/renderers/Table/Cell.tsx, packages/amis/src/renderers/Table/index.tsx
* CRUD 渲染器支持泛型方便外围扩充
* 解决 itemCheckableOn 在顶部已选清单中依然可以删除的问题
* 调整 picker 部分样式 
* CRUD 支持直接开启可点选
* 补充 CRUD 文档，补充更多的使用场景示例
* 修复 Toast 动作弹出内容不支持模版的问题
* 修复前端分页模式事件上下文中 unSelectedItems 数据不全问题
* 事件上下文中添加 selectedIndexes 记录点选的索引位置
* 修复嵌套模式且为单选时，无法选中父级节点（因为为了照顾多选会自动选中上下级，而实际上单选不需要这么处理）
* table 新增 showIndex 属性，调整 input-table 复用 table 中的 showIndex 能力，crud 适配 showIndex
* 编辑器增加双击事件面板
=> chore: CRUD 调整方便外围覆盖

packages/amis/src/renderers/Table/HeadCellSearchDropdown.tsx
=> fix: 修复 inputTable 列检索同级别存在同名表单项值时搜索框查询条件自动被赋值问题

packages/amis-core/src/utils/api.ts, packages/amis/__tests__/utils/api.test.ts
=> fix: 修复 api 配置 query 参数值中存在变量语法经过两次运算的问题

packages/amis/src/renderers/Form/InputNumber.tsx
=> fix: 修复数字框在iframe中，输入状态下自动格式化了

packages/amis/rollup.config.js
=> chore(amis): rollup配置文件中删除未使用的变量引入，避免编译时警告

packages/amis-ui/package.json
```shell
vite v4.4.4 building for production...
✓ 53 modules transformed.
✓ built in 3.36s
[vite:css] [sass] Can't find stylesheet to import.
╷
7 │ @import '../../../node_modules/video-react/dist/video-react';
│         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
╵
node_modules/amis-ui/scss/_thirds.scss 7:9         @import
node_modules/amis-ui/scss/themes/_common.scss 1:9  @import
node_modules/amis-ui/scss/themes/cxd.scss 5:9      @import
node_modules/amis-ui/scss/themes/default.scss 2:9  root stylesheet
file: /Users/macbookpro/Documents/zmn/zmn-plat-menu-frontend/node_modules/amis-ui/scss/themes/default.scss
```
```shell
bash-5.1$ npm list video-react
zmn-plat-menu-frontend@1.0.0 /Users/macbookpro/Documents/zmn/zmn-plat-menu-frontend
└─┬ zmn@12.14.2-next.2
└─┬ amis@6.10.0
└── …
```
=> fix(amis-ui): dependencies中引入video-react@0.15.0依赖，避免_thirds.scss中引入依赖报错的问题

packages/amis-editor-core/src/component/Editor.tsx, packages/amis-editor-core/src/component/HighlightBox.tsx, packages/amis-editor-core/src/manager.ts, packages/amis-editor-core/src/plugin/BasicToolbar.tsx, packages/amis-editor-core/src/store/editor.ts, packages/amis-ui/src/components/MobileDevTool.tsx
=> 自由容器组件支持层级调整及重叠时点击选中

docs/zh-CN/components/tooltip-wrapper.md, packages/amis-ui/src/components/Tooltip.tsx, packages/amis-ui/src/components/TooltipWrapper.tsx, packages/amis/src/renderers/TooltipWrapper.tsx
=> tooltip箭头增加可配置class

.gitignore
schema.json只会被构建到packages/amis目录中，根目录中不会有该文件，且amis/.gitignore中已经忽略了schema.json
=> chore: 删除多余的git配置，提升代码可维护性

packages/amis-ui/src/components/CalendarMobile.tsx
`InputDateRange` 和 `InputDatetimeRange` 在移动端模式下按年份加载月份。
`InputDateRange` 和 `InputDatetimeRange` 在移动端模式下，设置`minDate`和`maxDate`之间的间距过大，乘以12月。数据量大，`InputDateRange` 和 `InputDatetimeRange` 无法打开`PopUp`, 并且滚动卡顿， 无法使用。
=> fix: date-range 按年份加载月份数据

packages/amis-core/src/renderers/Form.tsx, packages/amis-core/src/utils/uncontrollable.tsx, packages/amis-ui/scss/components/_quick-edit.scss, packages/amis-ui/src/components/Button.tsx, packages/amis-ui/src/components/Select.tsx, packages/amis/__tests__/renderers/Form/__snapshots__/inputTable.test.tsx.snap, packages/amis/__tests__/renderers/Form/__snapshots__/static.test.tsx.snap, packages/amis/__tests__/renderers/__snapshots__/CRUD.test.tsx.snap, packages/amis/src/renderers/Action.tsx, packages/amis/src/renderers/QuickEdit.tsx
=> fix: 修复 quickEdit focus 高亮与列冻结样式冲突问题并优化快速编辑键盘操作交互

packages/amis-ui/scss/components/_images.scss
=> fix: 图片展示的标题和描述居中样式设置效果不符合预期

packages/amis-ui/src/components/NumberInput.tsx
=> fix: 解决js浮点数计算有精度丢失问题

packages/amis-core/src/store/formItem.ts
=> fix: 开启extraName后，范围组件清空后必填校验无法生效

packages/amis-ui/scss/components/_carousel.scss, packages/amis/src/renderers/Carousel.tsx
What
为carousel增加纵向模式和鼠标滑动模式。增加了如下配置：
/**
轮播图方向，默认为水平方向
*/
direction?: 'horizontal' | 'vertical';
/**
是否循环播放, 默认为 true。
*/
loop?: boolean;
/**
是否支持鼠标事件
默认为 true。
*/
mouseEvent?: boolean;
Why
carousel目前只支持横向模式，而且翻页只能通过点击和自动翻页。增加滑动模式后，支持页面在移动端的滑动来操作翻页
How
在componentDidMount后通过监听mousedown/mouseup/mouseleave/touchstart/touchend事件，在鼠标/手势移动超过20px后，认为滑动。并且禁用了image的交互来防止对图片的拖拽
=> feat: 为carousel增加纵向模式和鼠标滑动模式

packages/amis/src/renderers/Carousel.tsx
增加height允许传入字符串类型，修复touchEnd使用事件中changedTouches属性获取鼠标坐标
1. 高度和宽度有时需要传入100%字符串类型
2. 修复touchEnd使用事件中changedTouches属性获取鼠标坐标
=> fix: 增加height允许传入字符串类型，兼容滑动过程中元素被其他元素获取焦点时事件缺少touchlist

packages/amis-ui/scss/components/_images.scss
=> fix: 图片展示的标题和描述居中样式设置效果不符合预期 (#11454)

packages/amis-core/rollup.config.js, packages/amis/rollup.config.js
=> chore: Disable tree shake for modules under

packages/amis/src/renderers/Form/InputTable.tsx
=> feat: input-table change事件data增加index

packages/amis-editor-core/src/inlineEdit.ts
=> fix: 修复移动端编辑模式双击光标位置不正确的问题

packages/amis-ui/src/components/Tree.tsx, packages/amis/src/renderers/Form/Select.tsx
设置valueField 或者 children为空数组时，select树模式中全选、多选不生效
=> fix: 部分情况下，select树模式中全选、多选不生效

packages/amis/src/renderers/Carousel.tsx
=> fix: 修复轮播图有 style 且设置了 width\height 时会导致 js 报错渲染失败

packages/amis-core/src/factory.tsx
优化异步渲染器注册逻辑
- 当已存在占位渲染器时，在注册异步渲染器时删除占位渲染器
- 解决了在某些情况下（如设置了 visibleOn/hiddenOn 条件）无法渲染的问题
=> fix: 注册异步渲染器时删除占位渲染器，修复设置了显隐条件时无法正确渲染的问题

packages/amis-ui/scss/_properties.scss, packages/amis-ui/scss/components/_pagination.scss, packages/amis-ui/src/components/Pagination.tsx, packages/amis/src/renderers/Pagination.tsx
=> feat: 分页组件移动端适配

docs/zh-CN/components/nav.md, packages/amis-ui/scss/components/_menu.scss, packages/amis-ui/src/components/menu/MenuContext.tsx, packages/amis-ui/src/components/menu/PanelMenu.tsx, packages/amis-ui/src/components/menu/index.tsx, packages/amis/__tests__/renderers/Nav.test.tsx, packages/amis/src/renderers/Nav.tsx
扩展了Nav组件的mode参数，设置mode为panel后，用悬浮面板展示Nav的二级、三级菜单。最大支持到三级。
实现效果
调整amis renders中的Nav、 amis ui 中的Menu，增加mode参数。在amis ui的Menu中控制渲染，当mode:panel时，使用PanelMenu组件渲染导航的二级、三级菜单。
=> feat: Nav组件增加悬浮面板模式

packages/amis-ui/src/components/BaiduMapPicker.tsx
在地图的值修改后，需要刷新地图展示
做为受控组件的地图组件，在外部value变化后，地图位置不变。因为没有监听value变化
用componentDidUpdate监听value变化，初始化地图
=> fix: 在地图的值修改后，需要刷新地图展示

packages/amis-ui/scss/components/_context-menu.scss
=> fix: 去掉contextmenu多余的边框

packages/amis/src/renderers/Table/index.tsx
修复 #11535 
crud使用本地数据源时需要分页，source改变后，crud会自动计算好分页后的数据，这里不应该走进下面代码，只有单独使用table时才会进。
=> fix: #11535 crud的source切换后分页失效问题修复

packages/amis/src/renderers/Form/InputFile.tsx, packages/amis/src/renderers/Form/InputImage.tsx
- 在 FileControl 和 ImageControl 组件中添加对静态属性 (static) 的处理
- 确保在静态模式下禁用文件选择、上传和清除等操作
- 优化了静态模式下的界面显示，防止用户进行交互操作
- `input-file` 和 `input-image` 在 static=true 的 form 中仍会显示上传等按钮
- 在 FileControl 和 ImageControl 组件中添加对静态属性 (static) 的处理
=> fix(InputFile, InputImage): 修复静态模式下文件选择器仍然可操作的问题

packages/amis-ui/scss/components/_table.scss, packages/amis/src/renderers/Table/index.tsx
火狐浏览器，Crud设置autoFillHeight后，如果无数据，表头被拉伸
**正常情况**
autoFillHeight:true （暂无数据 居中）
autoFillHeight:false
**产生原因**
火狐浏览器下，table外层设置固定高度、table设置min-height:100%后，会被拉伸
**相关pr**
https://github.com/baidu/amis/issues/11419
**为什么文档中demo正常？**
计算得到的高度为负值，高度未生效，等同于autoFillHeight:false
项目中已计算thead大小，利用tableContentHeight获得tbody大小
=> fix: Firefox浏览器Crud设置autoFillHeight，无数据时表头被拉伸

packages/amis-ui/src/components/table/index.tsx
=> fix：配置scrolly时使用粘性定位固定表头

packages/amis/src/renderers/Card.tsx
- 渲染 toolbar 和 actions 时，在传入 subProps 中指定 onClick 为 undefined
- 避免 Cards 中为 Cards 功能特性增加的点击处理函数意外传给 Card 的 toolbar 和 actions
- 修复 renderField 拼写错误
- Cards 渲染 Card 的时候会传入 onClick
- Card 渲染 actions、toolbar 区域的时候会把这个属性带入到相关组件的渲染中
- 导致 dropdown-button 这样的组件，在点击下拉菜单项的时候触发了 rowClick 事件，而不是 button 的 click 事件
- Card 渲染可能会包含下拉菜单的部件的时候把 onClick 置为 undefined
=> fix(card): 修复 Card 组件中 actions 和 toolbar 中的 dropdown-button 组件失效的问题

docs/zh-CN/components/dialog.md
- 在 size 属性中添加了 custom 选项
- 新增 width、height 和 draggable 属性说明
_(无)_
_(无)_
=> doc: 为 Dialog 属性表增加自定义尺寸、拖拽功能和高度属性说明

packages/amis-ui/src/components/formula/Picker.tsx
修复 InputFormula 组件 variables 配置表达式时无法获取 api 中数据
当 variables 为字符串的时候，在 amis 层的 InputFormula 组件中，已经转成了具体的数据。所以到 amis-ui 层的时候已经是具体值了。
https://github.com/baidu/amis/blob/b594a93ef897b1fb52f416b07ab04b7eab9f001d/packages/amis/src/renderers/Form/InputFormula.tsx#L213-L216 
但是在 amis-ui 层 的 formula/Picker 组件里面，只处理了 variables 为 function/string 的时候，变更情况。没有处理 variables 为具体数据时候的情况。
在 amis-ui 层的 formula/Picker 的 componentDidUpdate 添加一下，props.variables 如果已经是具体数据的情况下变更后， 同步设置state状态。
=> fix: #11630 修复 InputFormula 组件 variables 配置表达式时无法获取 api 中数据

packages/amis-ui/src/components/table/Head.tsx
修复表格设置sticky:true后，开启选择或拖拽功能，其头部未被应用sticky样式
设置sticky:true、autoFillHeight:{maxHeight:360}
组件补全selfSticky属性，[相关pr](https://github.com/baidu/amis/pull/11637)
=> fix: 表格设置sticky后，如果开启选择或拖拽功能，其头部sticky未生效

packages/amis-ui/scss/components/_table2.scss
=> fix: table2 sticky时border未跟随导致底部文字透出

packages/amis-ui/src/components/index.tsx
修复horizontalScroll组件没有从amis ui导出导致被摇树优化的问题
=> fix: 修复horizontalScroll组件没有从amis ui导出导致被摇树优化的问题

packages/amis-ui/src/components/BaiduMapPicker.tsx
=> fix: 修复两个百度地图同时加载，同一个路径只触发一次初始化导致有一个地图空白的问题

packages/amis-editor-core/scss/_variables.scss, packages/amis-editor-core/scss/editor.scss
flex内，子容器默认是block情况下，编辑器的最小高度占位必须父子一致
block 父min-height，子height 100%不生效
设定min-height一致
=> [fix amis-editor]修复block容器的最小高度问题

packages/amis/src/renderers/Cards.tsx, packages/amis/src/renderers/List.tsx, packages/amis/src/renderers/Service.tsx, packages/amis/src/renderers/Table2/index.tsx, packages/amis/src/renderers/Wizard.tsx
为 Service 等组件的 handleAction 方法补上返回值。
事件动作中某些时候会因为 handleAction 没有返回值破坏逻辑引发异常，导致动作序列无法继续。
举个例子：
在 Service 中有个 button，button 的 click event 中有一个 action 是 openDialog，该 action 配置了 waitForAction。
正常情况下 DialogAction 会检查动作的返回值，提取返回值中的 confirmed 和 value。
在这个场景下这个 action 会通过 Service 的 handleAction 执行动作，而 Service 的 handleAction 没有把 onAction 的结果 return 出来，就会导致 DialogAction 会尝试 await undefined 并从中提取 confirmed 和 value；从而导致 runActions 被中断。
补充 Service 中返回值逻辑，并检查其他组件中类似的情况，尝试一起修复。
=> fix(Actions): 为 Service 等组件的 handleAction 方法增加返回值，修复事件动作序列异常中断问题

packages/amis-editor/src/plugin/CRUD.tsx
=> fix(plugin/CRUD):  使用数组值前增加是否为空的判断

packages/amis-core/src/store/crud.ts, packages/amis/src/renderers/CRUD.tsx
1. #11684  配置filterTogglable 配置为 true 时， 点击“切换按钮”，筛选框无法正常切换
2. #11573 filterDefaultVisible:false 属性失效
看了下之前，v6.11.0 之前，渲染CRUD filter的条件是: `filter && (!store.filterTogggable || store.filterVisible)`
v6.11.0 进行了改动，改为了 ：`!filter && (!store.filterTogggable || store.filterVisible)`
此处进行了取反逻辑，但是判断有误。
**改动1:**
看了下，配置传入的  `filterTogglable `, store存储的为：`filterTogggable`, 单词拼写不一致。 顺便，对crud/Crud 两个文件中使用, `filterTogggable` 的地方，都改为了 `filterTogglable`
**改动2:**
这块修复了下 filter 渲染条件，改为：`!filter || (store.filterTogglable && !store.filterVisible)`
=> fix: #11684 修复 CRUD filterTogglable 配置为 true 时，点击切换无效问题

packages/amis-ui/src/locale/de-DE.ts, packages/amis-ui/src/locale/en-US.ts, packages/amis-ui/src/locale/zh-CN.ts, packages/amis/src/renderers/Table/ColumnToggler.tsx
- 拖拽列的时候把交换列修复为移动列，与拖动时的视觉指示相匹配
- 简化并修复 dragEnd 事件处理逻辑，删除直接修改 DOM 的代码（因为无效）
- 删除 swapColumnPosition 方法
- 增加 moveColumn 方法
- 增加拖拽列时的文字提示
在 columns-toggler 中启用 draggable 后，拖拽列的时候，视觉指示的效果是把拖拽的列移动到目标位置，而实际上是与目标位置的列交换，存在严重矛盾，应视为BUG。
- 删除交换列方法，替换为移动列
=> fix: 修复 Table 的 columns-toggler 中列拖拽排序逻辑错误

docs/zh-CN/components/tabs.md, packages/amis-core/src/utils/renderer-event.ts
点击批量发布按钮1时，执行的确是按钮2的事件。原因是：事件列表里面只判断了render和当前点击的元素是否相等。可是由于浅拷贝的原因。render其实已经发生变化，但是判断条件还是为true。 但是无法通过深拷贝来实现，深拷贝以后render永远不等于当前点击的元素的render。只能增加判断条件。
=> fix: 修复crud2中批量操作按钮事件混乱问题

packages/amis-core/src/RootRenderer.tsx, packages/amis-core/src/SchemaRenderer.tsx, packages/amis-core/src/factory.tsx, packages/amis/__tests__/renderers/CRUD.test.tsx, packages/amis/src/renderers/CRUD.tsx, packages/amis/src/renderers/CRUD2.tsx, packages/amis/src/renderers/Form/InputDate.tsx, packages/amis/src/renderers/List.tsx, packages/amis/src/renderers/Table/index.tsx, packages/amis/src/renderers/Table2/index.tsx
* Table 组件本身需要发送 `selectedChange` 事件，同时如果在 CRUD 中也要发送，目前的逻辑在 table 中，但是当 crud 中开启分页保留选择项时，派送事件的上下文不正确，只有当前页的。所以这段逻辑需要在 CRUD 中处理。之前的逻辑 dispatchEvent 无法在组件树中干预，故：调整 dispatchEvent 执行顺序，走一遍组件树，最后在 rootRenderer 中执行事件逻辑，而不是每层渲染器层直接处理了。
=> fix: 调整 dispatchEvent 流程解决 CRUD 中派送选中事件的上下文信息错误问题

packages/amis-editor-core/src/manager.ts
修改插入组件时的逻辑判断
在 combo 组件插入组件时，新增的组件会追加到 combo 后面，而不是 combo 内部。
在插入组件时，新增对 combo 类型的判断
=> fix: 修复编辑器 combo 插入组件后不在子节点的情况

packages/amis-editor/src/plugin/Form/InputNumber.tsx
保持与只读态和最终渲染态里的千分符渲染结果一致
修改 input-number 组件在编辑器右侧面板的千分符配置，改成默认打开
数字输入框的千分符配置在最终渲染时默认会设置为 true
而编辑器里配置 input-number 组件时默认不会带上千分符配置属性，导致在编辑态的预览时看到的数据是不带千分符的，这与最终的渲染结果不一致
input-number 组件里的默认属性中新增 kilobitSeparator: true
=> fix(inputNumber): 编辑器右侧面板默认打开千分符配置

packages/amis/src/renderers/Wizard.tsx
#11270 Wizard 向导组件，如果配置 自定义actions 执行 onEvent 的时候，会异常1次触发多余事件，
这个好像是 事件机制 引起的，在 SchemaRenderer 里，给每一个组件 进行了一次 bindEvent。在 Wizard 向导组件 Step 的 actions 里，比较特殊。actions渲染的 button 的时候 key 设置的是 action 的 index。切换 step 的时候，index 不会变，key也没有变，就导致这个问题了。
简单改的话，就是改了下 渲染 button 时的 key, 用 step的索引和 action 的 index 组合一下。每次切换 step 每一个 action 的 key 都变了。
=> fix: #11270 修复 Wizard 向导组件 单步Step 自定义actions 执行 onEvent  事件异常

packages/amis-ui/src/components/json-schema/Object.tsx
#11612 JSONSchema 反显时， schema 的 `object`类型存在`"additionalProperties": false`时， 表单项的value值里面存在一个，`object` 中未定义的 属性时，会出现一个 无法选属性的框，并且出现“添加属性”按钮。
amis ui 层，JSONSchema 组件，props.value 变化的时候，同步更新 members 数组的时候，将不存在的在 member 中的 key 进行更新了。当 key 不在 member 存在的时候，进行更新应该从代码逻辑上就有问题，导致数据不对了。
key 在 member 存在的时候再更新。
=> fix: #11612 修复 JSONSchema 反显的时候出现异常

docs/zh-CN/extend/editor.md
可拖拽基类 `LayoutBasePlugin` 已实现，但并未在文档说明中体现。
原本的文档说明会导致开发自定义插件时产生冗余代码。
开发插件时直接继承 `LayoutBasePlugin` 即可，无需插入实现代码。
=> ref(docs): 优化如何让渲染器可通过拖拽调整宽高文档说明

packages/amis/src/renderers/CRUD.tsx
增加enableBulkActions属性
批量操作在一定场景下时候可以动态的隐藏多选框和批量操作按钮区
现在只能打开或者关闭，
=> feat: 增加enableBulkActions属性，批量操作在一定场景下时候可以动态的隐藏多选框和批量操作按钮区

packages/amis/src/renderers/Form/Transfer.tsx
解决 https://github.com/baidu/amis/issues/11431 ，当设置了 selectMode 后触发的 change 事件未能正确包含 selectedItems
使用了 BaseTransferRenderer 进行渲染，但是未实现 change 事件中透传 selectedItems
BaseTransferRenderer 的 chang 事件处理器中透传选中的值
=> fix: 修复select组件change事件的选中数据问题

docs/zh-CN/components/table2.md, packages/amis-ui/src/components/table/Row.tsx, packages/amis-ui/src/components/table/index.tsx
修复表格开启整行选择(rowSelection.rowClick)后，点击单选或复选框无响应
当前效果：
修改后的效果：
Row.tsx组件中的onClick事件做了限制（修复是 在这里扩展了一个配置，不影响之前逻辑）
```javascript
// packages/amis-ui/src/components/table/Row.tsx
onClick(
e: React.MouseEvent<HTMLTableRowElement>,
record?: any,
rowIndex?: number
) {
if (isClickOnInput(e)) {
return;
}
const {onClick} = this.props;
onClick && onClick(e, record, rowIndex);
}
```
另一个原因是：
checkbox的onChange到table的onRowChange中被拦截
```javascript
// packages/amis-ui/src/components/table/index.tsx
onRowChange(value: boolean, record: any) {
const {rowSelection} = this.props;
if (!(rowSelection && rowSelection.rowClick)) {
this.selectedSingleRow(value, record);
}
}
```
同时isClickOnInput也影响onEvent. rowClick
=> fix: 修复表格开启整行选择后，点击单选或复选框无响应

packages/amis-core/src/utils/resize-sensor.ts
在特定的浏览器宽度下，弹出层的位置会一直循环计算
resizeSensor所监听的弹出层元素宽度会有0.几的变化，这个变化不应该重新去计算位置
=> fix: 修复popOver组件内容字符过长时，弹窗中的内容闪烁

packages/amis-core/src/utils/dom.tsx, packages/amis-ui/src/components/Tree.tsx, packages/amis/src/renderers/Form/InputTree.tsx
=> fix: tree虚拟列表加载接口时误将loading高度计算进来

packages/amis-editor/src/plugin/Form/Combo.tsx
combo 组件关闭可多选按钮时，增加对最多条数和最少条数属性的清空操作
每次 combo 组件可多选按钮被点击后，将 maxLength 和 minLength 属性清除
=> fix: 修复 combo 组件可多选按钮关闭时最多条数&最少条数未被清空

packages/amis-ui/scss/_components.scss, packages/amis-ui/scss/components/form/_picker.scss
Picker组件禁用态样式与其他组件的边框、底色不同
picker加了一个透明度属性
去掉picker的透明度，暂时不对value的透明度做特殊处理
=> [fix] picker组件禁用态样式

packages/amis-editor-core/src/store/editor.ts
=> fix: 修复子编辑器修改丢失问题

packages/amis-core/src/SchemaRenderer.tsx, packages/amis-core/src/WithStore.tsx, packages/amis-core/src/globalVar.ts, packages/amis-core/src/renderers/Item.tsx, packages/amis-core/src/store/iRenderer.ts, packages/amis-core/src/store/root.ts, packages/amis-editor-core/src/variable.ts, packages/amis/src/renderers/Tabs.tsx
=> chore: 调整全局变量更新机制使得组件层无须额外编写检测代码

packages/amis-core/src/store/form.ts
如题，表单还原的时候，会导致父级数据被还原。如果表单项中有数据请求等依赖父级数据，会导致数据错误
=> fix: form reset的时候父级数据也被还原

packages/amis/src/renderers/PopOver.tsx
=> fix: 当表格列配置溢出显示 mapping等类型列显示出原始数据

docs/zh-CN/components/table.md, packages/amis-core/src/store/table.ts, packages/amis-core/src/store/table2.ts, packages/amis/src/renderers/Table/index.tsx, packages/amis/src/renderers/Table2/index.tsx
=> feat: table 的列信息本地缓存支持配置 Close: #11850

packages/amis-core/src/utils/api.ts
同为json请求，还有扩展的Content-Type，如`application/vnd.api+json`，当遇到严格的校验的服务接口，使用`application/json`无法通过校验，所以不应遇到json请求就统一指定`Content-Type`为`application/json`
=> fix: 修复json请求时无法指定自定义的Content-Type

packages/amis-core/src/utils/dom.tsx
当嵌套在无界当中时，弹出层会把非iframe的顶层区域也当成自己的可视区域，计算出来的位置，并不是正确的。超出了iframe的区域，于是不可见。
判断当前页面是否是在iframe内部，是的话减去非iframe可视区域的高度。
=> fix: 修复在无界框架中，弹出层计算了非iframe区域的高度，导致弹层被遮挡

packages/amis-core/src/store/crud.ts, packages/amis-core/src/store/table2.ts, packages/amis-core/src/utils/errors.ts
result.msg 是有值的
最后 toast 的时候拿到的 e.message 并没有生效
本质原因如下
解决办法参考 https://github.com/Microsoft/TypeScript-wiki/blob/main/Breaking-Changes.md#extending-built-ins-like-error-array-and-map-may-no-longer-work
=> fix: 修复接口报错时无法弹出预期的 msg 内容

packages/amis-ui/scss/components/_tooltip.scss
=> feat: TooltipWrapper暗色模式下border去除

packages/amis-editor/src/renderer/FormulaControl.tsx
=> fix: range类开启双字段保存时,影响默认值配置中结束字段的值回显

packages/amis-core/src/utils/normalizeOptions.ts
=> fix: 修复级联选择器组件不同的分类下子类的label不应该因为value一致就展示了一样label的问题

packages/amis-ui/scss/components/_popoverable.scss, packages/amis/src/renderers/Form/NestedSelect.tsx
=> fix: 修复级联选择器拿不到最新选中值+修复开启溢出隐藏后中文的第二行会露出一点

packages/amis-ui/src/components/table/index.tsx
=> fix: 使用最后一行的单元格来计算列宽，提高性能

packages/amis-editor/src/renderer/ValidationControl.tsx
=> fix: 校验规则滚动条会与属性配置栏滚动条冲突，撑开空白底部

packages/amis-ui/scss/_components.scss
=> fix:修复checkbox的标签对齐

packages/amis/src/renderers/PopOver.tsx
=> fix: 表格列配置溢出显示时，mapping类型列显示出原始数据

packages/amis-core/src/components/PopOver.tsx
=> fix: 解决 PopOver 中打开新页签后第一次点击无效的问题

packages/amis-core/src/actions/AjaxAction.ts
=> chore: ajaxAction api 配置 sendOn 空字符串 api 执行会被拦截问题调整

packages/amis-editor/src/renderer/event-control/actionsPanelPlugins/componentActionsPanel/setValue.tsx
=> fix: 修复动作赋值先选自定义后id后选组件不出现赋值控件问题

packages/amis/src/renderers/Date.tsx
当table配置了
`{
"quickEdit": {
"type": "date-range"
},
"name": "time",
"label": "日期",
"type": "date"
}`
快捷编辑时间范围
这时候Date组件便会收到如1744041600,1749139199
点击确认会显示
1744-04-16
这很神奇?
因为Date组件调用normalizeDate->moment('1744041600,1749139199','YYYY-MM-DD HH:mm:ss')
神奇的事情发生了
moment尝试把17440416..转换为YYYY-MM-DD HH:mm:ss 是成功的isValid验证通过
为什么呢因为1744-04 -6 是合法的
虽然这种概率很小就是某天0点的时间戳1744041600 恰好是一个时间格式时, 时间就显示错误了
如:20240507,202550408 ... 
Date组件名字已经确定他是一个日期显示器不是日期范围显示器
所以修改Date组件兼容1744041600,1749139199 值,解析value取第一个有效的时间显示
不应该错误的吧1744041600,1749139199传给moment
=> fix: 修复Date在极端情况下渲染错误的问题

packages/amis/src/renderers/Form/StaticHoc.tsx
picker设定静态展示使用其他组件，如each时，会读取picker的value，而不是解析name数据
=> [fix] 删除多余的props,只传递必要的,避免static定制情况下读到非预期的数据

packages/amis-core/src/store/app.ts
修复App 组件切换带参数的相同路由下的不同路径，路由参数不会更新的问题 #12149
同一路由下切换路径，原代码判断相同路由后跳过了 `params` 更新。
相同路由时，额外简易添加更新`params`逻辑。
=> fix: App 组件切换带参数的相同路由下的不同路径，路由参数不会更新的问题

packages/amis-editor/src/util.ts
null值的typeof结果是object, 有特殊情况会导致无法添加事件
复现代码:
{
"id": "u:053682f3f0e8",
"title": "表单",
"mode": "flex",
"labelAlign": "top",
"dsType": "api",
"feat": "View",
"body": [
{
"name": "select",
"label": "选择器",
"type": "select",
"id": "u:ad9b3d796e12",
"multiple": false,
"required": true,
"options": [
{
"label": "test1",
"value": "test1"
}
],
"valueField": "name",
"row": null,
"colSize": "1",
"onEvent": {
"change": {
"weight": 0,
"actions": []
}
}
}
],
"actions": [
{
"type": "button",
"label": "提交",
"onEvent": {
"click": {
"actions": [
{
"actionType": "submit",
"componentId": "u:053682f3f0e8"
}
]
}
},
"level": "primary",
"id": "u:4b933b4338bd"
}
],
"resetAfterSubmit": true,
"initApi": {
"method": "get",
"url": "http://localhost:8888/",
"requestAdaptor": "",
"messages": {}, …
=> fix: 修复resolveOptionType未处理null值的问题

packages/amis-core/src/utils/date.ts
`normalizeDate` 函数不够健壮，utc 情况下无法处理 valueFormat 和 value 的不匹配。
=> fix(date): normalizeDate 在 utc 情况下没有处理 valueFormat 和 value 不匹配情况

packages/amis-ui/src/components/formula/VariableList.tsx, packages/amis-ui/src/components/formula/plugin.ts
类似表达式data[0]['username']==bizName，data是数组，username是数字对象的属性，之前不支持username高亮。
=> feat: 优化代码支持表达式data[0]['username']==bizName, 支持'username'高亮

packages/amis-core/src/index.tsx
amis-editor中使用render的地方没有传theme, 导致render渲染出来是cxd的类名, 在AMISRenderer使用defaultTheme, 可以通过设置defaultTheme固定主题
=> fix(theme): 修复默认主题设置问题, 使用defaultTheme作为默认值而不是硬编码的'cxd'

packages/amis-ui/src/components/condition-builder/Item.tsx
修复bug: conditions组合条件组件，defaultValue 设置默认值"bb"，但是查询时，没有携带默认值，发送的是空
没有在初始化时带入defaultValue
初始化时，带入defaultValue
具体bug见 #12218
=> fix: #12218
